### DISCUSSION TITLE
Nextcloud <=> photoprism

### DISCUSSION THREAD

**Discussion by giterest** [photoprism/photoprism#1462] [Q&A] [answered]
Hi there,
I just wanted to know if there's actually any possibility that photoprism is just indexing/showing images from my Nextcloud-server? Both photoprism (docker) and Nextcloud run on the same server.

Nextcloud-path: /usr/share/nginx/html/nextcloud/data/#USER#/files/#ALBUM#/#YEAR#/#MONTH#/

I've seen that there's a volumes-section in the docker-compose file, but I'm afraid I'm not sure how to use it properly, so many thanks in advance for your time.

**Comment by lastzero** [comment, marked as answer]
Yes, simply mount the Nextcloud file storage folder and restart the container. You may also want to enable read-only mode so that only Nextcloud can add, remove and rename files:

```yaml
environment:
      PHOTOPRISM_READONLY: "true" 
volumes:
      # Your photo and video files ([local path]:[container path]):
      - "/usr/share/nginx/html/nextcloud/data/admin/files:/photoprism/originals:ro"
```

You may also mount one or multiple folders as sub-folders to have more flexibility:

```yaml
volumes:
      # Your photo and video files ([local path]:[container path]):
      - "/usr/share/nginx/html/nextcloud/data/ada/files:/photoprism/originals/Nextcloud/Ada:ro"
      - "/usr/share/nginx/html/nextcloud/data/bill/files:/photoprism/originals/Nextcloud/Bill:ro"
```

**Reply by giterest** [reply]
hi there. many thanks for your feedback - as you're the maintainer of that repo, let me send a "großes dankeschön" for that awesome piece of software.

i have three follow-up questions;
1) would like to donate :) - any preferred way?
2) is there any way to automatically index the mounted volume (e.g. cronjob,...)?
3) is there a possibility to use an existing non-docker pgsql-db (the one that serves nextcloud in my case)?

**Reply by hoggatt** [reply]
I have a cronjob that runs this: `docker-compose exec -T photoprism photoprism index` in the correct folder. 
Not sure if photoprism auto-indexes when nextcloud adds new things, but if you're running this once a night it will only take a few seconds each time.

**Reply by lastzero** [reply]
Postgres is not supposed yet, for background jobs see this example config: https://dl.photoprism.org/docker/scheduler/

**Reply by giterest** [reply]
many thanks both for coming back to me, added a cronjob therefore!

**Reply by ruffson** [reply]
@lastzero Is this also possible if my nextcloud instance is running inside a docker on the same server with a named volume like this?
```yaml
# From my nextcloud docker-compose.yaml:
# ...
NCFrontend:
image: "nextcloud:22"
    volumes: 
        - "NCData:/var/www/html"
# ...
```

**Reply by ruffson** [reply]
One way seems to be to be to define a volume in the global volumes as external like this:
```yaml
volumes:                                                                                                                                                                                        
  nextcloud:                                                                                                                                                                                  
    external: true                                                                                                                                                                            
    name: nextcloud_NCData
```
And then in the volume for photoprism to refer to this volume as `nextcloud` in my case and map that to `originals`.
Unfortunately it seems that it is not possible to refer to a specifc directory under the volume like `nextcloud/data/user/files/my_photos`. For testing I mapped this volume to some other directory inside the docker and then entered the docker via `exec` and symlinked it to the `originals` folder. Not very nice and certainly not sustaining a re-up...
Any recommendations are welcome! One other way would be to copy that volume to a easily accesible directory on the host via `docker cp` OR to directly refer to that volume in the `/usr/var/.../_data/...` directory which is quite nasty.
