### DISCUSSION TITLE
Mariadb gets in a loop

### DISCUSSION THREAD

**Discussion by Dikakus** [photoprism/photoprism#1711] [Q&A] [answered]
Hi. I downloaded the docker-compose.yml for raspberry-pi 4 and started the service. Nevertheless, mariadb gets in a loop and photoprims gives an excepcion becasue it can't connect.

I have a mapped volume for the bd:

```
  mariadb:
    restart: unless-stopped
    image: lscr.io/linuxserver/mariadb:latest
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    command: mysqld --transaction-isolation=READ-COMMITTED --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-connections=512 --innodb-rollback-on-timeout=OFF --innodb-lock-wait-timeout=120
    volumes:
      ##  - "./mariadb:/config" # Never remove
      - "/media/MediaBk/.photoprism/database:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: insecure
      MYSQL_DATABASE: photoprism
      MYSQL_USER: photoprism
      MYSQL_PASSWORD: insecure

```

This is the log:

> mariadb_1     | [services.d] starting services
> mariadb_1     | [services.d] done.
> mariadb_1     | 2021-11-09 13:04:15 0 [Note] mysqld (mysqld 10.5.12-MariaDB-log) starting as process 307 ...
> mariadb_1     | mysqld: Please consult the Knowledge Base to find out how to run mysqld as root!
> mariadb_1     | 2021-11-09 13:04:15 0 [ERROR] Aborting
> mariadb_1     | [cmd] mysqld exited 1
> mariadb_1     | Caught SIGTERM signal!
> mariadb_1     | cat: /var/run/mysqld/mysqld.pid: No such file or directory
> mariadb_1     | [cont-finish.d] executing container finish scripts...
> mariadb_1     | [cont-finish.d] done.
> mariadb_1     | [s6-finish] waiting for services.
> mariadb_1     | 211109 13:04:15 mysqld_safe Logging to '/config/databases/5670030d31a9.err'.
> mariadb_1     | 211109 13:04:15 mysqld_safe Starting mariadbd daemon with databases from /config/databases
> mariadb_1     | [s6-finish] sending all processes the TERM signal.
> mariadb_1     | [s6-finish] sending all processes the KILL signal and exiting.

Any suggestions or help, please?

**Comment by Dikakus** [comment, marked as answer]
I answer my self if anyone needs it: changed mariadb image to use amd64 arch:

```
  mariadb:
    restart: unless-stopped
    image: arm64v8/mariadb:10.6
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    command: mysqld --transaction-isolation=READ-COMMITTED --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-connections=512 --innodb-rollback-on-timeout=OFF --innodb-lock-wait-timeout=120
    volumes:
      ....
```
