### DISCUSSION TITLE
Bug: Invalid credentials - docker installation

### DISCUSSION THREAD

**Discussion by dynamicat** [photoprism/photoprism#1783] [Q&A] [answered]
I am using the latest release docker version of photoprism.

I have the login page displayed and in the console I see no errors.  In the docker-compose file I have specified the admin password as suggested in the documentation.  Here is a copy of my docker-compose file:

```
services:
  ## App Server (required)
  photoprism:
    ## Use photoprism/photoprism:preview for testing preview builds:
    image: photoprism/photoprism:latest
    depends_on:
      - maria
    networks:
      - t2_proxy
    ## Only enable automatic restarts once your installation is properly
    ## configured as it otherwise may get stuck in a restart loop,
    ## see https://docs.photoprism.org/getting-started/faq/#why-is-photoprism-getting-stuck-in-a-restart-loop
    # restart: unless-stopped
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    ## Run as a specific, non-root user (see https://docs.docker.com/engine/reference/run/#user):
    user: "1000:1000"
#    ports:
#      - "2342:2342" # HTTP port (host:container)
    environment:
      PUID: 1000
      PGID: 1000
      PHOTOPRISM_ADMIN_PASSWORD: "MYSECRET"          # PLEASE CHANGE: Your initial admin password (min 4 characters)
      PHOTOPRISM_SITE_URL: "https://photoprism.domain.tld"  # Public server URL incl http:// or https:// and /path, :port is optional
      PHOTOPRISM_ORIGINALS_LIMIT: 5000               # File size limit for originals in MB (increase for high-res video)
      PHOTOPRISM_HTTP_COMPRESSION: "gzip"            # Improves transfer speed and bandwidth utilization (none or gzip)
      PHOTOPRISM_DEBUG: "true"                      # Run in debug mode (shows additional log messages)
      PHOTOPRISM_PUBLIC: "false"                     # No authentication required (disables password protection)
      PHOTOPRISM_READONLY: "false"                   # Don't modify originals directory (reduced functionality)
      PHOTOPRISM_EXPERIMENTAL: "false"               # Enables experimental features
      PHOTOPRISM_DISABLE_CHOWN: "false"              # Disables storage permission updates on startup
      PHOTOPRISM_DISABLE_WEBDAV: "false"             # Disables built-in WebDAV server
      PHOTOPRISM_DISABLE_SETTINGS: "false"           # Disables Settings in Web UI
      PHOTOPRISM_DISABLE_TENSORFLOW: "false"         # Disables all features depending on TensorFlow
      PHOTOPRISM_DISABLE_FACES: "false"              # Disables facial recognition
      PHOTOPRISM_DISABLE_CLASSIFICATION: "false"     # Disables image classification
      PHOTOPRISM_DARKTABLE_PRESETS: "false"          # Enables Darktable presets and disables concurrent RAW conversion
      PHOTOPRISM_DETECT_NSFW: "false"                # Flag photos as private that MAY be offensive (requires TensorFlow)
      PHOTOPRISM_UPLOAD_NSFW: "true"                 # Allow uploads that MAY be offensive
      # PHOTOPRISM_DATABASE_DRIVER: "sqlite"         # SQLite is an embedded database that doesn't require a server
      PHOTOPRISM_DATABASE_DRIVER: "mysql"            # Use MariaDB 10.5+ or MySQL 8+ instead of SQLite for improved performance
      PHOTOPRISM_DATABASE_SERVER: "mariadb:3306"     # MariaDB or MySQL database server (hostname:port)
      PHOTOPRISM_DATABASE_NAME: "photoprism"         # MariaDB or MySQL database schema name
      PHOTOPRISM_DATABASE_USER: "photoprism"         # MariaDB or MySQL database user name
      PHOTOPRISM_DATABASE_PASSWORD: "MYSECRET"       # MariaDB or MySQL database user password
      PHOTOPRISM_SITE_TITLE: "PhotoPrism"
      PHOTOPRISM_SITE_CAPTION: "Browse Your Life"
      PHOTOPRISM_SITE_DESCRIPTION: "The Golden Collection"
      PHOTOPRISM_SITE_AUTHOR: ""
      ## Set a non-root user, group, or custom umask if your Docker environment doesn't support this natively:
      PHOTOPRISM_UID: 1000
      PHOTOPRISM_GID: 1000
      # PHOTOPRISM_UMASK: 0000
      ## Enable TensorFlow AVX2 support for modern Intel CPUs (requires starting the container as root):
      # PHOTOPRISM_INIT: "tensorflow-amd64-avx2"
      ## Hardware video transcoding config (optional):
      # PHOTOPRISM_FFMPEG_BUFFERS: "64"              # FFmpeg capture buffers (default: 32)
      # PHOTOPRISM_FFMPEG_BITRATE: "32"              # FFmpeg encoding bitrate limit in Mbit/s (default: 50)
      # PHOTOPRISM_FFMPEG_ENCODER: "h264_v4l2m2m"    # Use Video4Linux for AVC transcoding (default: libx264)
      # PHOTOPRISM_FFMPEG_ENCODER: "h264_qsv"        # Use Intel Quick Sync Video for AVC transcoding (default: libx264)
      # PHOTOPRISM_INIT: "intel-graphics tensorflow-amd64-avx2" # Enable TensorFlow AVX2 & Intel Graphics support
      HOME: "/photoprism"
    ## Hardware devices for video transcoding and machine learning (optional):
    #devices:
    # - "/dev/video11:/dev/video11" # Video4Linux (h264_v4l2m2m)
    #  - "/dev/dri/renderD128:/dev/dri/renderD128" # Intel GPU
    # - "/dev/dri/card0:/dev/dri/card0"
    working_dir: "/photoprism"
    volumes:
      - /share/Photos/Wedding:/photoprism/originals/Wedding
      ## The *originals* folder contains your original photo and video files (- "[host folder]:/photoprism/originals"):
      - "~/Pictures:/photoprism/originals"
      ## Multiple folders can be made accessible by mounting them as subfolders of /photoprism/originals:
      # - "/mnt/Family:/photoprism/originals/Family"    # [folder 1]:/photoprism/originals/[folder 1]
      # - "/mnt/Friends:/photoprism/originals/Friends"  # [folder 2]:/photoprism/originals/[folder 2]
      ## You may mount an *import* folder from which files can be transferred to *originals* (optional):
      # - "~/Import:/photoprism/import"
      ## Cache, session, thumbnail, and sidecar files will be created in the *storage* folder (never remove):
      - photoprism-storage:/photoprism/storage"
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.fampics-rtr.entrypoints=https"
      - "traefik.http.routers.fampics-rtr.rule=Host(`photoprism.domain.tld`)"
      - "traefik.http.routers.fampics-rtr.tls=true"
      ## HTTP Services
      - "traefik.http.routers.fampics-rtr.service=fampics-svc"
      - "traefik.http.services.fampics-svc.loadbalancer.server.port=2342"
      - "traefik.http.routers.fampics-rtr.middlewares=chain-no-auth@file"
      - "traefik.http.routers.fampics-rtr.middlewares=chain-authelia@file"  
      - 'traefik.http.routers.fampics.middlewares=authelia@docker'            


  maria:
    restart: unless-stopped
    image: mariadb:10.6
    networks:
      - t2_proxy
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    command: mysqld --transaction-isolation=READ-COMMITTED --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-connections=512 --innodb-rollback-on-timeout=OFF --innodb-lock-wait-timeout=120
    volumes:
      - "./database:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: z4VfgreGGb57mC
      MYSQL_DATABASE: photoprism
      MYSQL_USER: photoprism
      MYSQL_PASSWORD: MYSECRET
      
volumes:
 photoprism-storage:
      
networks:
  t2_proxy:
    external: true
```

The issue I am having is that when I use the user: admin and the password I specified in the docker-compose file it states my credentials are invalid.  I have also tried the default password: photoprism

Here is a copy of my logs:

`
[GIN-debug] POST   /api/v1/batch/labels/delete --> github.com/photoprism/photoprism/internal/api.BatchLabelsDelete.func1 (5 handlers),
[GIN-debug] GET    /api/v1/svg/photo         --> github.com/photoprism/photoprism/internal/api.GetSvg.func1 (5 handlers),
[GIN-debug] GET    /api/v1/svg/raw           --> github.com/photoprism/photoprism/internal/api.GetSvg.func2 (5 handlers),
[GIN-debug] GET    /api/v1/svg/file          --> github.com/photoprism/photoprism/internal/api.GetSvg.func3 (5 handlers),
[GIN-debug] GET    /api/v1/svg/video         --> github.com/photoprism/photoprism/internal/api.GetSvg.func4 (5 handlers),
[GIN-debug] GET    /api/v1/svg/label         --> github.com/photoprism/photoprism/internal/api.GetSvg.func5 (5 handlers),
[GIN-debug] GET    /api/v1/svg/portrait      --> github.com/photoprism/photoprism/internal/api.GetSvg.func6 (5 handlers),
[GIN-debug] GET    /api/v1/svg/folder        --> github.com/photoprism/photoprism/internal/api.GetSvg.func7 (5 handlers),
[GIN-debug] GET    /api/v1/svg/album         --> github.com/photoprism/photoprism/internal/api.GetSvg.func8 (5 handlers),
[GIN-debug] GET    /api/v1/svg/broken        --> github.com/photoprism/photoprism/internal/api.GetSvg.func9 (5 handlers),
[GIN-debug] GET    /api/v1/svg/uncached      --> github.com/photoprism/photoprism/internal/api.GetSvg.func10 (5 handlers),
[GIN-debug] GET    /api/v1/status            --> github.com/photoprism/photoprism/internal/api.GetStatus.func1 (5 handlers),
[GIN-debug] GET    /api/v1/errors            --> github.com/photoprism/photoprism/internal/api.GetErrors.func1 (5 handlers),
[GIN-debug] POST   /api/v1/feedback          --> github.com/photoprism/photoprism/internal/api.SendFeedback.func1 (5 handlers),
[GIN-debug] GET    /api/v1/ws                --> github.com/photoprism/photoprism/internal/api.Websocket.func1 (5 handlers),
[GIN-debug] GET    /s/:token                 --> github.com/photoprism/photoprism/internal/api.Shares.func1 (5 handlers),
[GIN-debug] GET    /s/:token/:share          --> github.com/photoprism/photoprism/internal/api.Shares.func2 (5 handlers),
[GIN-debug] GET    /s/:token/:share/preview  --> github.com/photoprism/photoprism/internal/api.SharePreview.func1 (5 handlers),
[GIN-debug] HEAD   /originals/*path          --> github.com/photoprism/photoprism/internal/server.WebDAV.func2 (6 handlers),
time="2021-11-30T07:42:42Z" level=info msg="webdav: /originals/ enabled, waiting for requests",
[GIN-debug] GET    /originals/*path          --> github.com/photoprism/photoprism/internal/server.WebDAV.func2 (6 handlers),
[GIN-debug] PUT    /originals/*path          --> github.com/photoprism/photoprism/internal/server.WebDAV.func2 (6 handlers),
[GIN-debug] POST   /originals/*path          --> github.com/photoprism/photoprism/internal/server.WebDAV.func2 (6 handlers),
[GIN-debug] PATCH  /originals/*path          --> github.com/photoprism/photoprism/internal/server.WebDAV.func2 (6 handlers),
[GIN-debug] DELETE /originals/*path          --> github.com/photoprism/photoprism/internal/server.WebDAV.func2 (6 handlers),
[GIN-debug] OPTIONS /originals/*path          --> github.com/photoprism/photoprism/internal/server.WebDAV.func2 (6 handlers),
[GIN-debug] MKCOL  /originals/*path          --> github.com/photoprism/photoprism/internal/server.WebDAV.func2 (6 handlers),
[GIN-debug] COPY   /originals/*path          --> github.com/photoprism/photoprism/internal/server.WebDAV.func2 (6 handlers),
[GIN-debug] MOVE   /originals/*path          --> github.com/photoprism/photoprism/internal/server.WebDAV.func2 (6 handlers),
[GIN-debug] LOCK   /originals/*path          --> github.com/photoprism/photoprism/internal/server.WebDAV.func2 (6 handlers),
[GIN-debug] UNLOCK /originals/*path          --> github.com/photoprism/photoprism/internal/server.WebDAV.func2 (6 handlers),
[GIN-debug] PROPFIND /originals/*path          --> github.com/photoprism/photoprism/internal/server.WebDAV.func2 (6 handlers),
[GIN-debug] PROPPATCH /originals/*path          --> github.com/photoprism/photoprism/internal/server.WebDAV.func2 (6 handlers),
[GIN-debug] HEAD   /import/*path             --> github.com/photoprism/photoprism/internal/server.WebDAV.func2 (6 handlers),
[GIN-debug] GET    /import/*path             --> github.com/photoprism/photoprism/internal/server.WebDAV.func2 (6 handlers),
[GIN-debug] PUT    /import/*path             --> github.com/photoprism/photoprism/internal/server.WebDAV.func2 (6 handlers),
[GIN-debug] POST   /import/*path             --> github.com/photoprism/photoprism/internal/server.WebDAV.func2 (6 handlers),
[GIN-debug] PATCH  /import/*path             --> github.com/photoprism/photoprism/internal/server.WebDAV.func2 (6 handlers),
[GIN-debug] DELETE /import/*path             --> github.com/photoprism/photoprism/internal/server.WebDAV.func2 (6 handlers),
[GIN-debug] OPTIONS /import/*path             --> github.com/photoprism/photoprism/internal/server.WebDAV.func2 (6 handlers),
[GIN-debug] MKCOL  /import/*path             --> github.com/photoprism/photoprism/internal/server.WebDAV.func2 (6 handlers),
[GIN-debug] COPY   /import/*path             --> github.com/photoprism/photoprism/internal/server.WebDAV.func2 (6 handlers),
[GIN-debug] MOVE   /import/*path             --> github.com/photoprism/photoprism/internal/server.WebDAV.func2 (6 handlers),
[GIN-debug] LOCK   /import/*path             --> github.com/photoprism/photoprism/internal/server.WebDAV.func2 (6 handlers),
[GIN-debug] UNLOCK /import/*path             --> github.com/photoprism/photoprism/internal/server.WebDAV.func2 (6 handlers),
[GIN-debug] PROPFIND /import/*path             --> github.com/photoprism/photoprism/internal/server.WebDAV.func2 (6 handlers),
[GIN-debug] PROPPATCH /import/*path             --> github.com/photoprism/photoprism/internal/server.WebDAV.func2 (6 handlers),
time="2021-11-30T07:42:42Z" level=info msg="webdav: /import/ enabled, waiting for requests",
time="2021-11-30T07:42:42Z" level=info msg="http: starting web server at 0.0.0.0:2342",
time="2021-11-30T07:42:48Z" level=debug msg="http: GET / (200) [9.737396ms]",
time="2021-11-30T07:42:48Z" level=debug msg="http: GET /static/build/app.css?d21ca96c (200) [21.878308ms]",
time="2021-11-30T07:42:48Z" level=debug msg="http: GET /static/build/app.js?390b62fd (200) [176.072175ms]",
time="2021-11-30T07:42:49Z" level=debug msg="http: GET /sw.js (200) [1.035744ms]",
time="2021-11-30T07:42:49Z" level=debug msg="session: open /photoprism/storage/cache/sessions.json: no such file or directory",
time="2021-11-30T07:42:49Z" level=debug msg="http: GET /static/build/fonts/1f0f6cdb23348c639cc50229e5577286.woff2 (200) [9.019015ms]",
time="2021-11-30T07:42:49Z" level=debug msg="http: GET /manifest.json?0e41a7e5 (200) [5.025254ms]",
time="2021-11-30T07:42:49Z" level=debug msg="http: GET /static/img/favicon-16.png (200) [147.234µs]",
time="2021-11-30T07:42:49Z" level=debug msg="http: GET /static/icons/default/144.png (200) [256.119µs]",
time="2021-11-30T07:42:49Z" level=debug msg="http: GET /static/img/favicon-32.png (200) [164.348µs]",
time="2021-11-30T07:44:10Z" level=debug msg="http: POST /api/v1/session (400) [1m16.248297345s]",
time="2021-11-30T07:44:27Z" level=debug msg="http: GET /static/img/badge-chat.svg (200) [489.56µs]",
time="2021-11-30T07:44:27Z" level=debug msg="http: GET /static/img/badge-agpl.svg (200) [400.171µs]",
time="2021-11-30T07:44:27Z" level=debug msg="http: GET /static/img/badge-twitter.svg (200) [381.586µs]",
time="2021-11-30T07:44:27Z" level=debug msg="http: GET /static/img/badge-docs.svg (200) [402.2µs]",
time="2021-11-30T07:52:49Z" level=debug msg="api: abort /api/v1/config with code 401 (Please log in and try again)",
time="2021-11-30T07:52:49Z" level=debug msg="http: GET /api/v1/config (401) [1.499023ms]",
time="2021-11-30T07:52:49Z" level=debug msg="http: GET / (200) [6.952241ms]",
time="2021-11-30T07:52:50Z" level=debug msg="http: GET /api/v1/ws (200) [10m0.921339631s]",
time="2021-11-30T07:52:51Z" level=debug msg="http: GET /manifest.json?0e41a7e5 (200) [5.476776ms]",
time="2021-11-30T07:52:53Z" level=debug msg="http: GET /sw.js (200) [974.73µs]",
time="2021-11-30T07:57:42Z" level=debug msg="metadata: running facial recognition",
time="2021-11-30T07:57:42Z" level=debug msg="faces: found no orphan markers [1.687551ms]",
time="2021-11-30T07:57:42Z" level=debug msg="markers: found no invalid references [3.358076ms]",
time="2021-11-30T07:57:42Z" level=debug msg="markers: found no missing subjects [1.092785ms]",
time="2021-11-30T07:57:42Z" level=debug msg="faces: found no ambiguous subjects [896.225µs]",
time="2021-11-30T07:57:42Z" level=debug msg="faces: found no clusters to be merged [1.005431ms]",
time="2021-11-30T07:57:42Z" level=debug msg="faces: found no existing clusters",
time="2021-11-30T07:57:42Z" level=debug msg="faces: skipped clustering",
time="2021-11-30T07:57:42Z" level=debug msg="faces: found no new faces [1.940847ms]",
time="2021-11-30T07:57:42Z" level=debug msg="faces: found no unmatched markers",
time="2021-11-30T07:57:42Z" level=debug msg="faces: updated 0 markers, recognized 0 faces, 0 unknown [2.54861ms]",
time="2021-11-30T07:57:42Z" level=debug msg="metadata: starting routine check",
time="2021-11-30T07:57:43Z" level=debug msg="moments: analyzing 0 photos and 0 videos, with threshold 3",
time="2021-11-30T07:57:43Z" level=debug msg="moments: not enough files",
time="2021-11-30T07:57:43Z" level=info msg="index: updating counts",
time="2021-11-30T07:57:43Z" level=debug msg="counts: updated 1 place [2.243128ms]",
time="2021-11-30T07:57:43Z" level=debug msg="counts: updated 0 subjects [1.436146ms]",
time="2021-11-30T07:57:43Z" level=debug msg="counts: updated 0 labels [1.395257ms]",
time="2021-11-30T07:57:43Z" level=info msg="index: updating covers",
time="2021-11-30T07:57:43Z" level=debug msg="covers: updated 0 albums [1.439838ms]",
time="2021-11-30T07:57:43Z" level=debug msg="covers: updated 0 folders [1.310863ms]",
time="2021-11-30T07:57:43Z" level=debug msg="covers: updated 0 months [1.37532ms]",
time="2021-11-30T07:57:43Z" level=debug msg="covers: updated 0 labels [1.70995ms]",
time="2021-11-30T07:57:43Z" level=debug msg="covers: updated 0 subjects [1.149882ms]",
time="2021-11-30T08:02:51Z" level=debug msg="api: abort /api/v1/config with code 401 (Please log in and try again)",
time="2021-11-30T08:02:51Z" level=debug msg="http: GET /api/v1/config (401) [1.093263ms]",
time="2021-11-30T08:02:51Z" level=debug msg="http: GET / (200) [6.534204ms]",
time="2021-11-30T08:02:52Z" level=debug msg="http: GET /api/v1/ws (200) [10m1.126569332s]",
time="2021-11-30T08:02:52Z" level=debug msg="http: GET /manifest.json?0e41a7e5 (200) [4.717595ms]",
time="2021-11-30T08:02:54Z" level=debug msg="http: GET /sw.js (200) [982.406µs]"
`
