### DISCUSSION TITLE
Unable to update

### DISCUSSION THREAD

**Discussion by v-bulynkin** [photoprism/photoprism#1958] [Q&A] [answered]
Hello, please help me to update Photoprism because following update procedure doesn't give a result. I stack on version 211010-83b4f783-Linux-x86_64.

I have this docker-compose.yml (a part related to photoprism):
```yaml
version: '3.7'
services:

  photoprism:
    image: photoprism/photoprism
    container_name: photoprism
    depends_on:
      - photoprism-db
    restart: unless-stopped
    environment:
      PHOTOPRISM_ADMIN_PASSWORD: "password"
      PHOTOPRISM_ORIGINALS_LIMIT: 4096
      PHOTOPRISM_PUBLIC: "false"
      PHOTOPRISM_DATABASE_DRIVER: "mysql"
      PHOTOPRISM_DATABASE_SERVER: "photoprism-db:3306"
      PHOTOPRISM_DATABASE_NAME: "photoprism"
      PHOTOPRISM_DATABASE_USER: "photoprism"
      PHOTOPRISM_DATABASE_PASSWORD: "password"
      PHOTOPRISM_SITE_URL: "https://bva.dyndns.info/photo/"
      PHOTOPRISM_SITE_TITLE: "Photos"
      PHOTOPRISM_SITE_CAPTION: ""
      PHOTOPRISM_SITE_DESCRIPTION: ""
      PHOTOPRISM_SITE_AUTHOR: ""
      HOME: "/photoprism"
    working_dir: "/photoprism"
    volumes:
      - photoprism:/photoprism
    secrets:
      - photoprism-db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.photoprism.rule=Host(`bva.dyndns.info`) && PathPrefix(`/photo`)"
      - "traefik.http.routers.photoprism.tls.certresolver=le"

  photoprism-db:
    image: mariadb:10.6
    container_name: photoprism-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: photoprism
      MYSQL_USER: photoprism
      MYSQL_PASSWORD_FILE: /run/secrets/photoprism-db
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/photoprism-db-root
    volumes:
      - photoprism-db:/var/lib/mysql
    secrets:
      - photoprism-db
      - photoprism-db-root

volumes:
  photoprism:
  photoprism-db:

secrets:
  photoprism-db:
    file: ./photoprism-db/photoprism-db.txt
  photoprism-db-root:
    file: ./photoprism-db/photoprism-db-root.txt
```

Firstly, I stopped containers
```
$ docker-compose stop photoprism photoprism-db
Stopping photoprism    ... done
Stopping photoprism-db ... done
```
Then, i removed them and also removed images:
```
$ docker image ls
REPOSITORY              TAG       IMAGE ID       CREATED        SIZE
home_phpsysinfo         latest    b72760c91978   12 days ago    27.1MB
home_alltube            latest    8eafd0b052f9   12 days ago    828MB
photoprism/photoprism   latest    f096af28aba5   5 weeks ago    1.5GB
traefik                 2.5       90d71910d402   5 weeks ago    101MB
<none>                  <none>    94be6ea60e44   7 weeks ago    27MB
redis                   alpine    3900abf41552   7 weeks ago    32.4MB
home_phpsysinfo-php     latest    46baf186200f   2 months ago   34.3MB
mariadb                 10.5      9a0e59bdf6f0   2 months ago   408MB
mariadb                 10.6      e2278f24ac88   2 months ago   410MB
home_webtrees           latest    58a4d5aa8b85   3 months ago   22.9MB
home_bepasty            latest    012a68198ec5   3 months ago   1.03GB
home_wp                 latest    6cde69756de3   3 months ago   22.9MB
home_wp-php             latest    fac3f85c86d2   3 months ago   194MB
home_nc-php             latest    49ae2e012ac7   3 months ago   219MB
home_nc                 latest    b2c3ed06ca6a   3 months ago   23MB
ubuntu                  latest    ba6acccedd29   3 months ago   72.8MB
home_wiki               latest    d6941934a004   3 months ago   22.9MB
home_wiki-php           latest    5128b18b9018   3 months ago   71.9MB
home_webtrees-php       latest    dcc2cfba08bb   3 months ago   80.7MB
<none>                  <none>    f9e6794597e3   3 months ago   828MB
wordpress               latest    938c9eb6c4e7   3 months ago   618MB
nginx                   alpine    513f9a9d8748   4 months ago   22.9MB
alpine                  latest    14119a10abf4   4 months ago   5.6MB
asmaps/bepasty          latest    43bf9868e867   6 months ago   1.03GB
containrrr/watchtower   latest    dd78a816fb76   9 months ago   16.4MB
rudloff/alltube         latest    70ec88f52c24   9 months ago   828MB

$ docker image rm f096af28aba5 94be6ea60e44 f9e6794597e3 dd78a816fb76
Deleted: sha256:94be6ea60e4473486e5ade511b1c18b5418855ad6703930572e460cb372ab9aa
Deleted: sha256:59914543dc944b280d2d09815478ddf63b80796a70e7e05b40e741ba27aa2de4
Deleted: sha256:f9e6794597e3a4e765835ff99b4c9bf484e18793a885c91c64e141268b21a6fb
Untagged: containrrr/watchtower:latest
Untagged: containrrr/watchtower@sha256:3283e0b5be326d77ff4f4e8b7a91d46aaa1d511c74877b5a32f161548812d00c
Deleted: sha256:dd78a816fb764ac6f44bd30d599e3605ebce50bc987e627573ab495092561a69
Deleted: sha256:ece10e098da096a72affbfec49c128b9f340b8ab092a4935d2c6c8d411c86076
Deleted: sha256:af5638eec38bd2e22196e1b8741dddd44aea22736749bef2d22935706778a880
Deleted: sha256:eafe2d84d8844f207037d375d1b9d5fe1fa37bda9963891a41bc0f71183f4ecf
Error response from daemon: conflict: unable to delete f096af28aba5 (must be forced) - image is being used by stopped container e34f6abb3681

$ docker ps -a
CONTAINER ID   IMAGE                   COMMAND                  CREATED        STATUS                       PORTS                                                                      NAMES
40bce5590478   home_alltube            "docker-php-entrypoi…"   12 days ago    Up 12 days                   80/tcp                                                                     alltube
0a09579ce988   home_phpsysinfo         "/docker-entrypoint.…"   12 days ago    Up 12 days                   80/tcp, 443/tcp                                                            phpsysinfo
e34f6abb3681   photoprism/photoprism   "/entrypoint.sh phot…"   3 weeks ago    Exited (143) 2 minutes ago                                                                              photoprism
e5f60b02cc89   mariadb:10.6            "docker-entrypoint.s…"   3 weeks ago    Exited (0) 2 minutes ago                                                                                photoprism-db
e6d50f0bc63b   home_bepasty            "./start.sh"             4 weeks ago    Up 12 days                   5000/tcp                                                                   bepasty
730c1087ee95   home_webtrees           "/docker-entrypoint.…"   4 weeks ago    Up 12 days                   80/tcp, 443/tcp                                                            webtrees
42bd674dc2a6   home_wiki               "/docker-entrypoint.…"   4 weeks ago    Up 12 days                   80/tcp, 443/tcp                                                            wiki
81bfb9506d6c   home_nc                 "/docker-entrypoint.…"   4 weeks ago    Up 12 days                   80/tcp, 443/tcp                                                            nc
61331291a1a6   home_wp                 "/docker-entrypoint.…"   4 weeks ago    Up 12 days                   80/tcp, 443/tcp                                                            wp
70d46044b8db   traefik:2.5             "/entrypoint.sh --pr…"   4 weeks ago    Up 12 days                   0.0.0.0:80->80/tcp, :::80->80/tcp, 0.0.0.0:443->443/tcp, :::443->443/tcp   reverse-proxy
21067463bc56   ubuntu                  "ls /home -lh"           6 weeks ago    Exited (0) 6 weeks ago                                                                                  fervent_banach
00f85daa1e20   ubuntu                  "ls / -lh"               6 weeks ago    Exited (0) 6 weeks ago                                                                                  affectionate_goldstine
5db6166e01ed   ubuntu                  "ls /home -lh"     6 weeks ago    Exited (2) 6 weeks ago                                                                                  magical_hamilton
c3f65b40c6c4   ubuntu                  "sleep 10"               6 weeks ago    Exited (0) 6 weeks ago                                                                                  vibrant_lamarr
0d5efda4a6b6   ubuntu                  "ping 8.8.8.8"           6 weeks ago    Created                                                                                                 cool_diffie
d6f039da6766   redis:alpine            "docker-entrypoint.s…"   6 weeks ago    Up 12 days                   6379/tcp                                                                   nc-redis
2fa2033b3960   home_phpsysinfo-php     "/bin/sh -c 'deluser…"   2 months ago   Up 12 days                                                                                              phpsysinfo-php
1949aa38e893   mariadb:10.5            "docker-entrypoint.s…"   2 months ago   Up 12 days                   3306/tcp                                                                   nc-db
c0f8b37c554a   mariadb:10.5            "docker-entrypoint.s…"   2 months ago   Up 12 days                   3306/tcp                                                                   wp-db
110f28d7da4a   mariadb:10.5            "docker-entrypoint.s…"   2 months ago   Up 12 days                   3306/tcp                                                                   webtrees-db
1cf7f799d189   home_wp-php             "/bin/sh -c 'deluser…"   3 months ago   Up 12 days                                                                                              wp-php
6a9eac65f1f8   home_nc-php             "/bin/sh -c 'deluser…"   3 months ago   Up 12 days                                                                                              nc-php
b91f714be193   home_webtrees-php       "/bin/sh -c 'deluser…"   3 months ago   Up 12 days                                                                                              webtrees-php
6cfd9dab00f7   home_wiki-php           "/bin/sh -c 'deluser…"   3 months ago   Up 12 days                                                                                              wiki-php

$ docker container rm e34f6abb3681
e34f6abb3681

$ docker image rm f096af28aba5 94be6ea60e44 f9e6794597e3 dd78a816fb76
Untagged: photoprism/photoprism:latest
Untagged: photoprism/photoprism@sha256:12f336c85dce05daab81e5e85bd73af228ed21cf4092882df988f8fcc20595bc
Deleted: sha256:f096af28aba53549b9c4dddd5ddae24017b6cab4111df93f1364429dacb34e64
Deleted: sha256:564b74e310e57e0b77d6f06d857ed046b86b12054242cc06173f1c227510f080
Deleted: sha256:6587a9f4eff3f10db510624814c8c1aceb3a701aceef9c413c127c8ac89e779c
Deleted: sha256:cf45a6ba376dd0b17a56339ff13f615f1df2da141f2b8b286b344e135e808106
Deleted: sha256:aeef4206fe7aca772531344fdde61adda698515f2347163971d0460865f7b000
Deleted: sha256:b896fe3e20cc353338356e5669b7c8e6ebfaa27fa0731d78c0337f7053f6a2fa
Deleted: sha256:30eacd68e3451e20fa960e48902c616c9d83d287aed19f0d2ca909c8636fe17d
Deleted: sha256:d42311c15b3d49e61d71afc6f1e9a28c12530f826318b0ba1ce50bbb21a9de41
Deleted: sha256:96f2a7df8f0466e1c48eed69d118e2a3e0f60acca7f7da160c4578497d3d2a91
Deleted: sha256:7230d4188db23c743bc1c474917a6501486bb66ef899d75fedcf31dcaa1a5735
Deleted: sha256:2b3b2da56c7048998fdedc095d49fdad7777dc08d7dc3412511bfa7b2bdfff29
Deleted: sha256:32f1061650d84e927008c2fdfaceac4d23ae9548408a7e701afa1b31db82b366
Deleted: sha256:fcc982cd9a053d94c142cc9ecd76f86e3e2e5f9f535f55ff3d15a99b503f93d6
Deleted: sha256:672fae6f974f96a022252aac3a80a65ab33e681e54b4e8aec8e23ceebee941e4
Deleted: sha256:6d094c7041bba377de6013dde27184343d02e05d08a91fc48d7a0e857ec726a2
Error: No such image: 94be6ea60e44
Error: No such image: f9e6794597e3
Error: No such image: dd78a816fb76
```

After that, I'd got the following images (no photoprism among them):
```
$ docker image ls
REPOSITORY            TAG       IMAGE ID       CREATED        SIZE
home_phpsysinfo       latest    b72760c91978   12 days ago    27.1MB
home_alltube          latest    8eafd0b052f9   12 days ago    828MB
traefik               2.5       90d71910d402   5 weeks ago    101MB
redis                 alpine    3900abf41552   7 weeks ago    32.4MB
home_phpsysinfo-php   latest    46baf186200f   2 months ago   34.3MB
mariadb               10.5      9a0e59bdf6f0   2 months ago   408MB
mariadb               10.6      e2278f24ac88   2 months ago   410MB
home_webtrees         latest    58a4d5aa8b85   3 months ago   22.9MB
home_bepasty          latest    012a68198ec5   3 months ago   1.03GB
home_wp               latest    6cde69756de3   3 months ago   22.9MB
home_wp-php           latest    fac3f85c86d2   3 months ago   194MB
home_nc-php           latest    49ae2e012ac7   3 months ago   219MB
home_nc               latest    b2c3ed06ca6a   3 months ago   23MB
ubuntu                latest    ba6acccedd29   3 months ago   72.8MB
home_wiki             latest    d6941934a004   3 months ago   22.9MB
home_wiki-php         latest    5128b18b9018   3 months ago   71.9MB
home_webtrees-php     latest    dcc2cfba08bb   3 months ago   80.7MB
wordpress             latest    938c9eb6c4e7   3 months ago   618MB
nginx                 alpine    513f9a9d8748   4 months ago   22.9MB
alpine                latest    14119a10abf4   4 months ago   5.6MB
asmaps/bepasty        latest    43bf9868e867   6 months ago   1.03GB
rudloff/alltube       latest    70ec88f52c24   9 months ago   828MB
```

Pulled new images:
```
$ docker-compose pull
Pulling reverse-proxy ... done
Pulling wp-db         ... done
Pulling nc-redis      ... done
Pulling nc-db         ... done
Pulling webtrees-db   ... done
Pulling photoprism-db ... done
Pulling photoprism    ... done
```
Now, I have the following image list:
```
$ docker image ls
REPOSITORY              TAG       IMAGE ID       CREATED        SIZE
photoprism/photoprism   latest    11ca96f44a0c   28 hours ago   1.5GB
home_phpsysinfo         latest    b72760c91978   12 days ago    27.1MB
home_alltube            latest    8eafd0b052f9   12 days ago    828MB
mariadb                 10.5      4db72891d344   12 days ago    408MB
mariadb                 10.6      d462573d8688   12 days ago    410MB
traefik                 2.5       2cd4bc25ad14   3 weeks ago    101MB
traefik                 <none>    90d71910d402   5 weeks ago    101MB
redis                   alpine    3900abf41552   7 weeks ago    32.4MB
home_phpsysinfo-php     latest    46baf186200f   2 months ago   34.3MB
mariadb                 <none>    9a0e59bdf6f0   2 months ago   408MB
mariadb                 <none>    e2278f24ac88   2 months ago   410MB
home_webtrees           latest    58a4d5aa8b85   3 months ago   22.9MB
home_bepasty            latest    012a68198ec5   3 months ago   1.03GB
home_wp                 latest    6cde69756de3   3 months ago   22.9MB
home_wp-php             latest    fac3f85c86d2   3 months ago   194MB
home_nc-php             latest    49ae2e012ac7   3 months ago   219MB
home_nc                 latest    b2c3ed06ca6a   3 months ago   23MB
ubuntu                  latest    ba6acccedd29   3 months ago   72.8MB
home_wiki               latest    d6941934a004   3 months ago   22.9MB
home_wiki-php           latest    5128b18b9018   3 months ago   71.9MB
home_webtrees-php       latest    dcc2cfba08bb   3 months ago   80.7MB
wordpress               latest    938c9eb6c4e7   3 months ago   618MB
nginx                   alpine    513f9a9d8748   4 months ago   22.9MB
alpine                  latest    14119a10abf4   4 months ago   5.6MB
asmaps/bepasty          latest    43bf9868e867   6 months ago   1.03GB
rudloff/alltube         latest    70ec88f52c24   9 months ago   828MB
```
Let's inspect the photoprism image, it's been created 18 January 2022 (part):
```
$ docker image inspect 11ca96f44a0c
[
    {
        "Id": "sha256:11ca96f44a0c6f6a756eec0914f079fa9a80fd41dd2220e2feb1cc30b1911f20",
        "RepoTags": [
            "photoprism/photoprism:latest"
        ],
        "RepoDigests": [
            "photoprism/photoprism@sha256:d05793f7193b8281b5acd0edf184ba5f5bd4c13be984d7ec7b956a39e8b257c9"
        ],
        "Parent": "",
        "Comment": "buildkit.dockerfile.v0",
        "Created": "2022-01-18T15:33:55.508946564Z",
```

Let's kick it off:
```
$ docker-compose up -d
phpsysinfo-php is up-to-date
Recreating reverse-proxy ...
nc-redis is up-to-date
nc-php is up-to-date
webtrees-php is up-to-date
bepasty is up-to-date
wiki-php is up-to-date
alltube is up-to-date
Recreating webtrees-db   ...
Recreating nc-db         ...
Recreating wp-db         ...
Recreating nc-db         ... done
Recreating reverse-proxy ... done
Recreating webtrees-db   ... done
Recreating photoprism-db ... done
Creating photoprism      ...
nc is up-to-date
webtrees is up-to-date
Creating photoprism      ... done
```

Finally, it's working, but I still have version 211010-83b4f783-Linux-x86_64! Why? It's not the first time trying.
How to force it to update?
