### DISCUSSION TITLE
"config: unsupported database driver \"mysql\", using sqlite", Running with Docker-Compose and a .env file

### DISCUSSION THREAD

**Discussion by R0NAM1** [photoprism/photoprism#2108] [Q&A] [answered]
I'm trying to spin this up using Docker-Compose and a file for the environment variables, but I keep getting this issue, no more verbosity even with debug mode on.

Docker-Compose:
```
    photoprism:
      image: photoprism/photoprism:latest
      container_name: photoprism
      environment:
        - TZ=America/Los_Angles
      volumes:
        - ./mnt/TrueNas/Indexed:/photoprism/originals
        - ./mnt/TrueNas/Indexed-Import:/photoprism/import
        - ./photoprism/config:/photoprism/storage
      restart: unless-stopped
      labels:
        - 'traefik.enable=true'
        - 'traefik.http.routers.photoprism.rule=Host(`photoprism.internal.my.domain`)'
        - 'traefik.http.routers.photoprism.entrypoints=websecure'
        - 'traefik.http.routers.photoprism.tls=true'
        - 'traefik.http.services.photoprism.loadbalancer.server.port=2342'
        - 'traefik.http.routers.photoprism.tls.options=default'
        - 'traefik.port=443'
      depends_on:
        - mariadb
      env_file:
        - photoprism.env
   
    mariadb:
      image: mariadb:latest
      restart: unless-stopped
      environment:
        - MARIADB_ROOT_PASSWORD=insecure
      volumes:
        - ./mariadb/data:/var/lib/mysql
      command: mysqld --innodb-buffer-pool-size=128M --transaction-isolation=READ-COMMITTED --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-connections=512 --innodb-rollback-on-timeout=OFF --innodb-lock-wait-timeout=120
```

photoprism.env:
```
PHOTOPRISM_ADMIN_PASSWORD="insecure"
PHOTOPRISM_SITE_URL="https://photoprism.internal.my.domain"
PHOTOPRISM_ORIGINALS_LIMIT=50000 
PHOTOPRISM_HTTP_COMPRESSION= "gzip"
PHOTOPRISM_DEBUG=true
PHOTOPRISM_PUBLIC=false 
PHOTOPRISM_READONLY=false 
PHOTOPRISM_EXPERIMENTAL=false
PHOTOPRISM_DISABLE_CHOWN=false  
PHOTOPRISM_DISABLE_WEBDAV=false 
PHOTOPRISM_DISABLE_SETTINGS=false    
PHOTOPRISM_DISABLE_TENSORFLOW=false  
PHOTOPRISM_DISABLE_FACES=false 
PHOTOPRISM_DISABLE_CLASSIFICATION=false
PHOTOPRISM_DARKTABLE_PRESETS=false
PHOTOPRISM_DETECT_NSFW=false
PHOTOPRISM_UPLOAD_NSFW=true       
PHOTOPRISM_DATABASE_DRIVER="mysql"    
PHOTOPRISM_DATABASE_SERVER="mariadb:3306"
PHOTOPRISM_DATABASE_NAME="photoprism"
PHOTOPRISM_DATABASE_USER="photoprism"
PHOTOPRISM_DATABASE_PASSWORD="insecure"
PHOTOPRISM_SITE_TITLE="PhotoPrism"
PHOTOPRISM_SITE_CAPTION="AI-Powered Photos App"
PHOTOPRISM_SITE_DESCRIPTION=""
PHOTOPRISM_SITE_AUTHOR=""
```
