### DISCUSSION TITLE
Photoprism behind Traefik+Authelia with possibility to share

### DISCUSSION THREAD

**Discussion by Alestrix** [photoprism/photoprism#2117] [Q&A]
Hi,

For external access I'm running PhotoPrism behind Traefik and for 2FA I use Authelia. However, when sharing an album with someone this should bypass 2FA Authentication and go right pass Authelia. So I started with bypassing the Authelia middleware for every path starting with `/s/` and worked my way through the logs from there as I saw that there were more URLs that the browser requested. The Traefik config I came up with so far is this (only the `routers:` part):

```
    photoprism_share:
      rule: "Host(`photoprism.mydomain.de`) && ( PathPrefix(`/s/`, `/manifest.json`, `/static/`) || Path(`/`, `/favicon.ico`, `/sw.js`) )"
      entrypoints: https
      tls: true
      service: photoprism
    photoprism:
      rule: Host(`photoprism.mydomain.de`)
      entrypoints: https
      tls:
        certresolver: letsencrypt
      middlewares:
      - authelia@docker
      service: photoprism
```

This already gets me something that looks like the PhotoPrism GUI, but still wouldn't display any pictures. If I authenticate against Authelia and retry, then the pictures load properly. So something still isn't caught by that `photoprism_share` rule, but I cannot find anymore blocked/401'ed access attempts in the logs, so don't know where's my error.

What am I missing? Does anybody have something similar at work?

Cheers
 Alex
