### DISCUSSION TITLE
When I use the "Upload" feature on the WebUI, where is the file physically stored?

### DISCUSSION THREAD

**Discussion by azaloum90** [photoprism/photoprism#2296] [Q&A] [answered]
This might be a dumb question, but I would like to know for my own sanity, LOL...

My config is the following:

- Nextcloud and PhotoPrism both running on the same docker host, there is no issue with either program, they both work as desired (e.g. not asking for troubleshooting here LOL)
- Originals are in my Nextcloud User Account Photos Folder
- PhotoPrism is using that folder as an Originals folder.  PhotoPrism sees all the photos without issue

Today, I tested the "Upload" feature within PhotoPrism, and I am confused as to where PhotoPrism is storing said photo.  It shows a filename (both original and newly created), but doesn't show me where said file exists.

So, where is this newly uploaded file stored?

I guess a follow up question to this would be -- am I using PhotoPrism incorrectly?  Should I be dumping files into a folder and then using a WebDAV Connection?

Thanks!
Adam

```

version: '3.5'

services:
######################################## Nextcloud Stack ########################################
  app:
    image: nextcloud
    container_name: nextcloud
    restart: always
    ports:
      - 8080:80
    depends_on:
      - db
    volumes:
      - /mnt/docker/nextcloud:/var/www/html
      - /mnt/docker/nextcloud_externalshare:/mnt/share
    environment:
      - MYSQL_PASSWORD=Removed
      - MYSQL_DATABASE=nextcloud_db
      - MYSQL_USER=nextcloud_db_admin
      - MYSQL_HOST=nextcloud_db
    networks:
      - net_nextcloud

  db:
    image: mariadb:10.5
    container_name: nextcloud_db
    restart: always
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - /mnt/docker/nextcloud_db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=Removed
      - MYSQL_PASSWORD=Removed
      - MYSQL_DATABASE=nextcloud_db
      - MYSQL_USER=nextcloud_db_admin
    networks:
      - net_nextcloud

######################################## Photoprism Stack ########################################

  photoprism:
    image: photoprism/photoprism:latest
    container_name: photoprism
    depends_on:
      - mariadb
    restart: unless-stopped
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    ports:
      - "2342:2342" # HTTP port (host:container)
    environment:
      PHOTOPRISM_ADMIN_PASSWORD: "Removed"       # !!! PLEASE CHANGE YOUR INITIAL "admin" PASSWORD !!!
      PHOTOPRISM_SITE_URL: "https://photos.atozcc.net/"  # public server URL incl http:// or https:// and /path, :port is optional
      PHOTOPRISM_ORIGINALS_LIMIT: 5000               # file size limit for originals in MB (increase for high-res video)
      PHOTOPRISM_HTTP_COMPRESSION: "gzip"            # improves transfer speed and bandwidth utilization (none or gzip)
      PHOTOPRISM_DEBUG: "false"                      # run in debug mode (shows additional log messages)
      PHOTOPRISM_PUBLIC: "false"                     # no authentication required (disables password protection)
      PHOTOPRISM_READONLY: "false"                   # don't modify originals directory (reduced functionality)
      PHOTOPRISM_EXPERIMENTAL: "false"               # enables experimental features
      PHOTOPRISM_DISABLE_CHOWN: "false"              # disables storage permission updates on startup
      PHOTOPRISM_DISABLE_WEBDAV: "false"             # disables built-in WebDAV server
      PHOTOPRISM_DISABLE_SETTINGS: "false"           # disables Settings in Web UI
      PHOTOPRISM_DISABLE_TENSORFLOW: "false"         # disables all features depending on TensorFlow
      PHOTOPRISM_DISABLE_FACES: "false"              # disables facial recognition
      PHOTOPRISM_DISABLE_CLASSIFICATION: "false"     # disables image classification
      PHOTOPRISM_DARKTABLE_PRESETS: "false"          # enables Darktable presets and disables concurrent RAW conversion
      PHOTOPRISM_DETECT_NSFW: "false"                # flag photos as private that MAY be offensive (requires TensorFlow)
      PHOTOPRISM_UPLOAD_NSFW: "true"                 # allows uploads that MAY be offensive
      PHOTOPRISM_DATABASE_DRIVER: "mysql"            # use MariaDB 10.5+ or MySQL 8+ instead of SQLite for improved performance
      PHOTOPRISM_DATABASE_SERVER: "mariadb:3306"     # MariaDB or MySQL database server (hostname:port)
      PHOTOPRISM_DATABASE_NAME: "photoprism_db"         # MariaDB or MySQL database schema name
      PHOTOPRISM_DATABASE_USER: "photoprism_db_admin"         # MariaDB or MySQL database user name
      PHOTOPRISM_DATABASE_PASSWORD: "AMr5HShX%5B9"       # MariaDB or MySQL database user password
      PHOTOPRISM_SITE_TITLE: "PhotoPrism"
      PHOTOPRISM_SITE_CAPTION: "AI-Powered Photos App"
      PHOTOPRISM_SITE_DESCRIPTION: ""
      PHOTOPRISM_SITE_AUTHOR: ""
      ## Run/install on first startup (options: update, gpu, tensorflow, davfs, nano, clean):
      PHOTOPRISM_INIT: "gpu tensorflow"
      ## Hardware video transcoding config (optional)
      # PHOTOPRISM_FFMPEG_BUFFERS: "64"              # FFmpeg capture buffers (default: 32)
      # PHOTOPRISM_FFMPEG_BITRATE: "32"              # FFmpeg encoding bitrate limit in Mbit/s (default: 50)
      # PHOTOPRISM_FFMPEG_ENCODER: "h264_v4l2m2m"    # use Video4Linux for AVC transcoding (default: libx264)
      # PHOTOPRISM_FFMPEG_ENCODER: "h264_qsv"        # use Intel Quick Sync Video for AVC transcoding (default: libx264)
      ## Run as a specific user, group, or with a custom umask (does not work together with "user:")
      # PHOTOPRISM_UID: 1000
      # PHOTOPRISM_GID: 1000
      HOME: "/photoprism"
 ## Start as a non-root user (see https://docs.docker.com/engine/reference/run/#user)
    # user: "1000:1000"
    ## Share hardware devices with FFmpeg and TensorFlow (optional):
    # devices:
    #  - "/dev/dri:/dev/dri"
    #  - "/dev/nvidia0:/dev/nvidia0"
    #  - "/dev/nvidiactl:/dev/nvidiactl"
    #  - "/dev/video11:/dev/video11" # Video4Linux (h264_v4l2m2m)
    working_dir: "/photoprism"
    ## Storage Folders: "~" is a shortcut for your home directory, "." for the current directory
    volumes:
      - "/mnt/docker/photoprism:/photoprism"
      # "/host/folder:/photoprism/folder"                                   # example
      - "/mnt/docker/photoprism_symlinks/AZaloum:/photoprism/originals"     # original media files (photos and videos)
      # - "/example/family:/photoprism/originals/family"                    # *additional* media folders can be mounted like this
      # - "~/Import:/photoprism/import"                                     # *optional* base folder from which files can be imported to originals
      - "/mnt/docker/photoprism/storage:/photoprism/storage"                # *writable* storage folder for cache, database, and sidecar files (never remove)
    networks:
      - net_photoprism

  ## Database Server (recommended)
  ## see https://docs.photoprism.app/getting-started/faq/#should-i-use-sqlite-mariadb-or-mysql
  mariadb:
    ## If MariaDB gets stuck in a restart loop, this points to a memory or filesystem issue:
    ## https://docs.photoprism.app/getting-started/troubleshooting/#fatal-server-errors
    restart: unless-stopped
    container_name: photoprism_db
    image: mariadb:10.6
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    command: mysqld --innodb-buffer-pool-size=128M --transaction-isolation=READ-COMMITTED --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-connections=512 --innodb-rollback-on-timeout=OFF --innodb-lock-wait-timeout=120
    ## Never store database files on an unreliable device such as a USB flash drive, an SD card, or a shared network folder:
    volumes:
      - "/mnt/docker/photoprism_db:/var/lib/mysql" # important, don't remove
    environment:
      MYSQL_ROOT_PASSWORD: Removed
      MYSQL_DATABASE: photoprism_db
      MYSQL_USER: photoprism_db_admin
      MYSQL_PASSWORD: Removed
    networks:
      - net_photoprism
```
