### DISCUSSION TITLE
Photoprism docker container fails to connect to maria-db container

### DISCUSSION THREAD

**Discussion by SLeitgeb** [photoprism/photoprism#2457] [Q&A] [answered]
Hello,
I have been using Photoprism for a while now (Ubuntu 20.04 on a RPi model 4B), but after a reboot, one of my two instances failed to start, apparently the `photoprism` container is refused connection to the `maria-db` container. I haven't made any configuration changes, other containers started cleanly. `docker-compose down`, `docker image prune -a`, `docker-compose up` produce the same results.
```
photoprism                | time="2022-06-22T10:26:56Z" level=fatal msg="Error 1044: Access denied for user 'photoprism'@'%' to database 'photoprism'"
photoprism exited with code 0
photoprism                | running as uid 0
photoprism                | /opt/photoprism/bin/photoprism start
ofelia                    | 2022-06-22T10:27:00.025Z  common.go:125 ▶ NOTICE [Job "photoprism convert" (b25062a22c8d)] Started - photoprism convert
photoprism                | time="2022-06-22T10:27:10Z" level=debug msg="config: overriding config with values from /photoprism/storage/config/options.yml"
photoprism                | time="2022-06-22T10:27:10Z" level=debug msg="settings: loaded from /photoprism/storage/config/settings.yml "
photoprism-rpi-mariadb-1  | 2022-06-22 10:27:10 16 [Warning] Access denied for user 'photoprism'@'%' to database 'photoprism'
```

I checked again that the db `photoprism` user password is set correctly for the db and photoprism containers.
Filesystem permissions also seem to be correct:
```
ls -la .
------------------------------------------------------------------------------
-rw-r--r-- 1 user user    60 Apr  4 16:39 .env
drwxr-xr-x 2 user user  4096 Jun 20 22:15 .secrets
-rw-r--r-- 1 user user   121 Apr  5 14:54 .secrets.env

ls -la .secrets/
------------------------------------------------------------------------------
-rw-r--r-- 1 user user   21 Apr  4 16:40 admin_password
-rw-r--r-- 1 user user   21 Apr  4 16:40 db_password
-rw-r--r-- 1 user user   21 Apr  4 16:40 db_root_password
```

Any ideas what might be the issue? 

`docker-compose.yml`:
```yml
version: '3.5'

services:
  photoprism:
    ## Use photoprism/photoprism:preview-arm64 for testing preview builds:
    image: photoprism/photoprism:arm64
    container_name: photoprism
    depends_on:
      - mariadb
    ## Don't enable automatic restarts until PhotoPrism has been properly configured and tested!
    ## If the service gets stuck in a restart loop, this points to a memory, filesystem, network, or database issue:
    ## https://docs.photoprism.app/getting-started/troubleshooting/#fatal-server-errors
    restart: unless-stopped
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    ports:
      - "2342:2342" # HTTP port (host:container)
    env_file: .secrets.env
    environment:
      # PHOTOPRISM_ADMIN_PASSWORD: "insecure"          # !!! PLEASE CHANGE YOUR INITIAL "admin" PASSWORD !!!
      PHOTOPRISM_SITE_URL: "http://localhost:2342/"  # public server URL incl http:// or https:// and /path, :port is optional
      PHOTOPRISM_ORIGINALS_LIMIT: 5000               # file size limit for originals in MB (increase for high-res video)
      PHOTOPRISM_HTTP_COMPRESSION: "none"            # improves transfer speed and bandwidth utilization (none or gzip)
      PHOTOPRISM_WORKERS: 1                          # limits the number of indexing workers to reduce system load
      PHOTOPRISM_DEBUG: "true"                      # run in debug mode (shows additional log messages)
      PHOTOPRISM_PUBLIC: "false"                     # no authentication required (disables password protection)
      PHOTOPRISM_READONLY: "false"                   # don't modify originals directory (reduced functionality)
      PHOTOPRISM_EXPERIMENTAL: "false"               # enables experimental features
      PHOTOPRISM_DISABLE_CHOWN: "false"              # disables storage permission updates on startup
      PHOTOPRISM_DISABLE_WEBDAV: "false"             # disables built-in WebDAV server
      PHOTOPRISM_DISABLE_SETTINGS: "false"           # disables Settings in Web UI
      PHOTOPRISM_DISABLE_TENSORFLOW: "false"         # disables all features depending on TensorFlow
      PHOTOPRISM_DISABLE_FACES: "false"              # disables facial recognition
      PHOTOPRISM_DISABLE_CLASSIFICATION: "false"     # disables image classification
      PHOTOPRISM_DARKTABLE_PRESETS: "true"           # enables Darktable presets and disables concurrent RAW conversion
      PHOTOPRISM_FFMPEG_ENCODER: "h264_v4l2m2m"    # FFmpeg AVC encoder for video transcoding (default: libx264)
      # PHOTOPRISM_FFMPEG_BUFFERS: "64"              # FFmpeg capture buffers (default: 32)
      # PHOTOPRISM_THUMB_SIZE: "720"
      # PHOTOPRISM_THUMB_SIZE_UNCACHED: "720"
      PHOTOPRISM_JPEG_SIZE: "2048"
      PHOTOPRISM_JPEG_QUALITY: "87"
      PHOTOPRISM_DETECT_NSFW: "true"                # flag photos as private that MAY be offensive
      PHOTOPRISM_UPLOAD_NSFW: "true"                 # allow uploads that MAY be offensive
      # PHOTOPRISM_DATABASE_DRIVER: "sqlite"         # SQLite is an embedded database that doesn't require a server
      PHOTOPRISM_DATABASE_DRIVER: "mysql"            # use MariaDB 10.5+ or MySQL 8+ instead of SQLite for improved performance
      PHOTOPRISM_DATABASE_SERVER: "mariadb:3306"     # MariaDB or MySQL database server (hostname:port)
      PHOTOPRISM_DATABASE_NAME: "photoprism"         # MariaDB or MySQL database schema name
      PHOTOPRISM_DATABASE_USER: "photoprism"         # MariaDB or MySQL database user name
      # PHOTOPRISM_DATABASE_PASSWORD_FILE: /run/secrets/db_password       # MariaDB or MySQL database user password
      PHOTOPRISM_SITE_TITLE: "PhotoPrism"
      PHOTOPRISM_SITE_CAPTION: "AI-Powered Photos App"
      PHOTOPRISM_SITE_DESCRIPTION: ""
      PHOTOPRISM_SITE_AUTHOR: ""
      PHOTOPRISM_SITE_URL: "REDACTED"
      ## Run/install on first startup (options: update, gpu, tensorflow, davfs, clean):
      # PHOTOPRISM_INIT: "update clean"
      ## Run as a specific user, group, or with a custom umask (does not work together with "user:")
      # PHOTOPRISM_UID: 1000
      # PHOTOPRISM_GID: 1000
      # PHOTOPRISM_UMASK: 0000
      HOME: "/photoprism"
    ## Start as a non-root user (see https://docs.docker.com/engine/reference/run/#user)
    # user: "1000:1000"
    ## Share hardware devices with FFmpeg and TensorFlow (optional):
    devices:
     - "/dev/video11:/dev/video11" # Video4Linux (h264_v4l2m2m)
    working_dir: "/photoprism"
    ## Storage Folders: "~" is a shortcut for your home directory, "." for the current directory
    volumes:
      - "${USER_FOLDER}/Photos:/photoprism/originals" # original media files (photos and videos)
      - "${USER_FOLDER}/InstantUpload:/photoprism/originals/uploaded" # original media files (photos and videos)
      # - "~/Import:/photoprism/import" # *optional* base folder from which files can be imported to originals
      - "./appdata/storage:/photoprism/storage" # *writable* storage folder for cache, database, and sidecar files (never remove)
      - "/etc/localtime:/etc/localtime:ro"
    networks:
      - default
      - proxy-net

  ## Database Server (recommended)
  ## see https://docs.photoprism.app/getting-started/faq/#should-i-use-sqlite-mariadb-or-mysql
  mariadb:
    ## If MariaDB gets stuck in a restart loop, this points to a memory or filesystem issue:
    ## https://docs.photoprism.app/getting-started/troubleshooting/#fatal-server-errors
    restart: unless-stopped
    image: arm64v8/mariadb:10.6 # this mariadb image runs on ARM64-based devices only
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    command: mysqld --innodb-buffer-pool-size=128M --transaction-isolation=READ-COMMITTED --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-connections=512 --innodb-rollback-on-timeout=OFF --innodb-lock-wait-timeout=120
    ## Never store database files on an unreliable device such as a USB flash drive, an SD card, or a shared network folder:
    volumes:
      - "./appdata/database:/var/lib/mysql" # important, don't remove
      - "/etc/localtime:/etc/localtime:ro"
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/db_root_password
      MYSQL_DATABASE: photoprism
      MYSQL_USER: photoprism
      MYSQL_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_root_password
      - db_password

  ## Ofelia Job Runner (recommended for running background jobs)
  ## see https://github.com/mcuadros/ofelia
  ## from the example at https://dl.photoprism.org/docker/scheduler/
  ofelia:
    restart: unless-stopped
    image: mcuadros/ofelia:latest
    container_name: ofelia
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./jobs.ini:/etc/ofelia/config.ini"

secrets:
  db_root_password:
    file: ./.secrets/db_root_password
  db_password:
    file: ./.secrets/db_password

networks:
  proxy-net:
    external: true
```
