### DISCUSSION TITLE
Upload images with yaml sidecar file - Description field not populating

### DISCUSSION THREAD

**Discussion by swiftony** [photoprism/photoprism#2971] [Q&A] [answered]
When I upload an image with a yaml side car file it populates all the photo detail fields except the 'Description' field.

Is it possible to populate the 'Description' field from a yaml sidecar file, or am I missing something?

Here is an example of my yaml sidecar file:

Details:
  Artist:  "Test Artist John Doe"
  Copyright: "Test Copyright"
  License: "Test License"
  Subject: "This is a test subject"
  Description: "Test Description"
  Keywords: "test, keywords"
  Notes: "Test Notes 123"

**Comment by graciousgrey** [comment, marked as answer]
It works, when the yml matches the PhotoPrism format:

```
Description: "Test Description"
DescriptionSrc: "manual"
Details:
  Artist: "Test Artist John Doe"
  Copyright: "Test Copyright"
  License: "Test License"
  Subject: "This is a test subject"
  Keywords: "test, keywords"
  Notes: "Test Notes 123"
```

Please Note: The information from yml files in originals is only read during the initial indexing.
Since we don't edit files in the originals directory, there could be conflicts otherwise, since we might overwrite manual changes made in PhotoPrism with data from the yml files in originals. If your images are already indexed, you can either use Exiftool to write the appropriate tags in your original files or use xmp sidecars. You can find the supported fields here:
https://photoprism.app/kb/metadata. Changes in xmp files are read during a complete rescan.
