### DISCUSSION TITLE
Incorrect date initialization

### DISCUSSION THREAD

**Discussion by jean-louis67** [photoprism/photoprism#3103] [General]
Hello
I'm coming back to a subject that has already been discussed, but unfortunately I can't find the discussion.
When a photo only has the year, we expect the month and day to be unknown. PhotoPrism had also been improved in this direction, perhaps in 2021. It was a success and very convenient.
But this is no longer the case for some weeks or months.
Example, this photo whose date is: _Date/Time Original: 1923_ is indexed in PhotoPrism with the date  January 1, 1923.

Jean Louis
A user despite this little problem very happy to use PhotoPrism daily.
I wish a happy new year to its creators and all its users!

**Comment by graciousgrey** [comment]
Thank you very much, we wish you a happy new year as well :tada: 

I assume you are referring to:
- https://github.com/photoprism/photoprism/issues/625

We will have a look at this as soon as possible.

**Comment by lastzero** [comment]
**While Exif allows incomplete dates by leaving the values between the `:` blank, as far as I know XMP should always use some kind of ISO format. And if it uses (incomplete) Exif fields, they should have the format specified by Exif, e.g. `2015:07:  ` instead of `2015:07`.**

Could you try again with files that contain actual Exif data, rather than the date in an XMP field named like the corresponding Exif field?

```
exiftool -n -j -g Lauch.jpg
[{
  "SourceFile": "Lauch.jpg",
  "ExifTool": {
    "ExifToolVersion": 12.40
  },
  "File": {
    "FileName": "Lauch.jpg",
    "Directory": ".",
    "FileSize": 3467138,
    "FileModifyDate": "2023:02:09 12:37:20+00:00",
    "FileAccessDate": "2023:02:09 12:39:54+00:00",
    "FileInodeChangeDate": "2023:02:09 12:39:53+00:00",
    "FilePermissions": 100664,
    "FileType": "JPEG",
    "FileTypeExtension": "JPG",
    "MIMEType": "image/jpeg",
    "ImageWidth": 4032,
    "ImageHeight": 3024,
    "EncodingProcess": 0,
    "BitsPerSample": 8,
    "ColorComponents": 3,
    "YCbCrSubSampling": "2 2"
  },
  "XMP": {
    "XMPToolkit": "Image::ExifTool 12.16",
    "DateTimeOriginal": "2015:07"
  },
  "Composite": {
    "ImageSize": "4032 3024",
    "Megapixels": 12.192768
  }
}]
```

**Comment by jean-louis67** [comment]
Thank you for your advice.
To define this field as Exif data, I do this:
`exiftool -ExifIFD:DateTimeOriginal='1984:03:01 12:11:34' test.jpg`

And here is the data:
`exiftool -n -j -g test.jpg`
```yaml [{
  "SourceFile": "test.jpg",
  "ExifTool": {
    "ExifToolVersion": 12.40
  },
  "File": {
    "FileName": "test.jpg",
 …
  },
  "JFIF": {
…
  },
  "EXIF": {
    "Orientation": 1,
    "XResolution": 1,
    "YResolution": 1,
    "ResolutionUnit": 1,
    "YCbCrPositioning": 1,
    "ExifVersion": "0232",
    "DateTimeOriginal": "1984:03:01 12:11:34",
    "ComponentsConfiguration": "1 2 3 0",
    "FlashpixVersion": "0100",
    "ColorSpace": 65535
  },
  "Composite": {
    "ImageSize": "949 320",
    "Megapixels": 0.30368
  }
}]
```
But I can't get the field to be truncated as you suggest.
`exiftool -DateTimeOriginal='1984:03:' test.jpg`
`Warning: Invalid date/time (use YYYY:mm:dd HH:MM:SS[.ss][+/-HH:MM|Z]) in ExifIFD:DateTimeOriginal (PrintConvInv)
    0 image files updated
    1 image files unchanged
`
