### DISCUSSION TITLE
Thumbnails from other photoprism container being displayed

### DISCUSSION THREAD

**Discussion by dsuresh-ap** [photoprism/photoprism#3137] [Q&A]
I have 2 photoprism containers. `photoprism` and `photoprism_suresh`. They are both connected to the same MariaDB container but they have different databases. The `photoprism` database is the default that was created automatically. `photoprism_suresh` was created using the Advance DB setup docs.

The issue is that after a normal index (for new images from Photosync) thumbnails for images from `photoprism` are shown in `photoprism_suresh`. Clicking on the thumbnail shows the correct image. Not sure how this happens because I have 2 separate drives and they are mounted properly.

docker-compose.yml below with same values omitted:
```
photoprism:
   ports:
      - "2342:2342" # HTTP port (host:container)
    environment:
    ## Storage Folders: "~" is a shortcut for your home directory, "." for the current directory
    volumes:
      - "/Volumes/Storage_2TB/photoprism/originals:/photoprism/originals"      # Original media files (DO NOT REMOVE)
      - "/Volumes/Storage_2TB/photoprism/storage:/photoprism/storage"       # *Writable* storage folder for cache, database, and sidecar files (DO NOT REMOVE)

photoprism_suresh:
    ports:
      - "2343:2342" # HTTP port (host:container)
    environment:
      PHOTOPRISM_DATABASE_NAME: "photoprism_suresh"  # MariaDB or MySQL database schema name
    ## Storage Folders: "~" is a shortcut for your home directory, "." for the current directory
    volumes:
      - "/Volumes/Suresh_S2TB/photoprism/originals:/photoprism/originals"      # Original media files (DO NOT REMOVE)
      - "/Volumes/Suresh_S2TB/photoprism/storage:/photoprism/storage"       # *Writable* storage folder for cache, database, and sidecar files (DO NOT REMOVE)
```
