### DISCUSSION TITLE
Nvidia & K8s

### DISCUSSION THREAD

**Discussion by sfxworks** [photoprism/photoprism#3391] [Q&A]
Hi. Just sponsored the project. Got registered. Not sure why im not seeing any ffmpeg activity with nvidia-smi in the container though. Can someone take a look? I have all the vars correct based on the doc, save for the all devices option since theres 4 other gpus on this node. Though even with that, it still doesn't use any of them. I also ensured that I registered my account in the dashboard against the photoprism sponsor account.  Thanks.

Also I should mention, other containers that use gpus, such as stablediffusion and anaconda, work fine on the node. So I don't believe there's any hook issues. 

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: photoprism-configmap
  namespace: photoprism
data:
  NVIDIA_DRIVER_CAPABILITIES: compute,video,utility
  PHOTOPRISM_ADMIN_PASSWORD: redacted
  PHOTOPRISM_ADMIN_USER: admin
  PHOTOPRISM_AUTH_MODE: password
  PHOTOPRISM_DATABASE_DRIVER: mysql
  PHOTOPRISM_DATABASE_NAME: photoprism
  PHOTOPRISM_DATABASE_PASSWORD: redacted
  PHOTOPRISM_DATABASE_SERVER: mariadb:3306
  PHOTOPRISM_DATABASE_USER: photoprism
  PHOTOPRISM_DEBUG: "true"
  PHOTOPRISM_DETECT_NSFW: "false"
  PHOTOPRISM_DISABLE_CHOWN: "false"
  PHOTOPRISM_DISABLE_CLASSIFICATION: "false"
  PHOTOPRISM_DISABLE_FACES: "false"
  PHOTOPRISM_DISABLE_RAW: "false"
  PHOTOPRISM_DISABLE_SETTINGS: "false"
  PHOTOPRISM_DISABLE_TENSORFLOW: "false"
  PHOTOPRISM_DISABLE_VECTORS: "false"
  PHOTOPRISM_DISABLE_WEBDAV: "false"
  PHOTOPRISM_EXPERIMENTAL: "false"
  PHOTOPRISM_FFMPEG_ENCODER: nvidia
  PHOTOPRISM_HTTP_COMPRESSION: gzip
  PHOTOPRISM_INIT: gpu tensorflow
  PHOTOPRISM_JPEG_QUALITY: "85"
  PHOTOPRISM_LOG_LEVEL: info
  PHOTOPRISM_ORIGINALS_LIMIT: "10000"
  PHOTOPRISM_RAW_PRESETS: "false"
  PHOTOPRISM_READONLY: "false"
  PHOTOPRISM_SITE_AUTHOR: ""
  PHOTOPRISM_SITE_CAPTION: Sams Media
  PHOTOPRISM_SITE_DESCRIPTION: ""
  PHOTOPRISM_SITE_URL: https://redacted.net/
  PHOTOPRISM_UPLOAD_NSFW: "true"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: photoprism-pvc
  namespace: photoprism
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Ti
  storageClassName: hdd-ec
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: photoprism
  namespace: photoprism
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: photoprism
  template:
    metadata:
      labels:
        app: photoprism
    spec:
      securityContext:
        fsGroup: 1000
      containers:
      - name: photoprism
        image: photoprism/photoprism:latest
        ports:
        - containerPort: 2342
        envFrom:
        - configMapRef:
            name: photoprism-configmap
        resources:
          requests:
            cpu: 3
            memory: 16Gi
          limits:
            cpu: 3
            memory: 32Gi
            nvidia.com/gpu: 2
        volumeMounts:
        - mountPath: /photoprism/originals
          name: photoprism-volume
          subPath: originals
        - mountPath: /photoprism/storage
          name: photoprism-volume
          subPath: storage
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
      volumes:
      - name: photoprism-volume
        persistentVolumeClaim:
          claimName: photoprism-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: photoprism
  namespace: photoprism
spec:
  type: ClusterIP
  ports:
  - port: 2342
    targetPort: 2342
    protocol: TCP
  selector:
    app: photoprism
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: photoprism
  namespace: photoprism
  annotations:
    kubernetes.io/ingress.class: "cilium"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
  - hosts:
    - redacted.net
    secretName: photoprism-tls
  rules:
  - host: redacted.net
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: photoprism
            port:
              number: 2342
```
