### DISCUSSION TITLE
Traefik setup with user defined certificates

### DISCUSSION THREAD

**Discussion by maiatobi** [photoprism/photoprism#3616] [General]
The current guide for Photoprism/Traefik is very basic and assumes:
1. You will be using port 80 and 443 
2. You want to use a Certificate Resolver that will pull your certificate automatically, probably using the letscrypt's HTTP-01 challenge.

The problem is if you are not using port 80/443, then you cannot complete a HTTP-01 challenge, you need to use DNS-01 challenge and that requires you to configure your DNS provider credentials in the machine hosting photoprism, which I am not willing to do.

This setup allows you to manually configure your certificates without using a resolver, which allows you to pull your certificates from a different machine and then copy them to the machine hosting photoprism. Your photoprism instance will be accessible using https using port 3342.

This is the first time I use traefik so please let me know if there are mistakes or something can be improved, my first concern is that the setup is secure.

1. Aff the Traefik container to docker-compose.yml. I had several problems with the 2.5 image to mount a volume under /configuration (also crashes while trying to create logs in a mounted volume). At the end I needed to specify the latest label which at this moment sits at 2.10.4. The /configuration is used to create a dynamic configuration that will have the location of the certificate and key. The /certs volume is used to hold the certificate and private key files:

```
  traefik:
    image: traefik:latest
    restart: unless-stopped
    ports:
      - "3342:3342"
    volumes:
      - "/home/photoprism/traefik/config/traefik.yaml:/etc/traefik/traefik.yaml"
      - "/home/photoprism/traefik/data:/data"
      - "/home/photoprism/traefik/configuration/:/configuration/"
      - "/home/photoprism/traefik/certs:/certs"
      - "/var/run/docker.sock:/var/run/docker.sock"

```
2. In the photoprims container add the follwoing labels. Here photoprism-cr is the name of the photoprism container
```
      # This replaces the 'routers' section in the Traefik configuration file
      # We manually copy the certificate/key so we do not use resolver.
      - "traefik.http.routers.photoprism-router.rule=Host(`your-domain.com`)"
      - "traefik.http.routers.photoprism-router.entrypoints=photoprism-ep"
      - "traefik.http.routers.photoprism-router.service=photoprism-service"
      - "traefik.http.routers.photoprism-router.tls=true"
      # Tell Traefik to use the port 2342 to connect to `photoprism-cr. Since we only expose port 2342 in this
      # container, this is not really needed, just to make clear this is the equivalent of a 'services' section
      # in the traefik configuration file.`
      - "traefik.http.services.photoprism-service.loadbalancer.server.port=2342"

```
3. Add /configuration as a provider in the traefik configuration file (/home/photoprism/traefik/config/traefik.yaml). Also add the entry point referenced in the labels of step 2 (photoprism-ep)
```
$ cat  /home/photoprism/traefik/config/traefik.yaml
entryPoints:
  photoprism-ep:
    address: ":3342"

providers:
  docker: {}
  file:
    directory: /configuration
    watch: true

```
4. Add a Traefik Dynamic Configuration file  under /configuration (/home/photoprism/traefik/configuration in the host) with the certificate information
```
$ ls -l /home/photoprism/traefik/configuration
total 4
-rw-rw-r-- 1 photoprism photoprism 177 Aug  7 23:03 certificates.yaml

$ cat /home/photoprism/traefik/configuration/certificates.yaml
# Dynamic Configuration
# in configuration/certificates.yaml
#
tls:
  certificates:
    - certFile: /certs/your-domain.com-cert.pem
      keyFile: /certs/your-domain.com-key.pem

$ ls -l /home/photoprism/traefik/certs
total 8
-rw-rw-r-- 1 photoprism photoprism 1484 Aug  7 22:06 your-domain.com-cert.pem
-rw------- 1 photoprism photoprism  241 Aug  7 17:57 your-domain.com-key.pem

```
