### DISCUSSION TITLE
CIFS share as originals / no route to host

### DISCUSSION THREAD

**Discussion by jefft4** [photoprism/photoprism#3617] [Q&A]
Hi,

I'm trying to use a CIFS mount from my NAS as the originals folder, but cannot deploy the docker stack; it's not happy with the CIFS mount.

The error in the portainer log when I try to deploy the stack is this:
`2023/08/08 12:53PM WRN composeplugin/composeplugin.go:161 > docker compose command failed | error="exit status 1" error_output=" Network photoprism_default  Creating\n Network photoprism_default  Created\n Container photoprism-mariadb-1  Creating\n Container photoprism-mariadb-1  Created\n Container photoprism-photoprism-1  Creating\nError response from daemon: failed to mount local volume: mount //dougal/FamilyPics:/var/lib/docker/volumes/photoprism_familypics/_data, data: username=photolibrary,password=********: no route to host\n" output=`

I've confirmed that (1) the host can mount that CIFS share; (2) a vanilla Ubuntu docker on the same host with default networking can mount that share. So there's something particular to the photoprism docker that's not happy.

The relevant sections of the yml file are:
```
volumes:
  familypics:
    driver_opts:
      type: cifs
      o: "username=photolibrary,password=********,rw"
      device: "//192.168.11.22/FamilyPics"

``` 
and 
```
services:
  photoprism:
    volumes:
      - "familypics:/photoprism/originals" # Originals mount path can be changed as needed (DO NOT REMOVE)
      - "/opt/photoprism/storage:/photoprism/storage"     # *Writable* storage folder for cache, database, and sidecar files (DO NOT REMOVE)
```
As you can see, I've even used the IP of the NAS, as the hostname didn't work (same error).

This one's driving me mad; I'd rather not mount the share to the host as that exposes it to any docker running there and also means the PP container can start without it, which causes issues.

Any ideas?  Thanks!
