### DISCUSSION TITLE
Is it possible to change the logo/favicon without using a custom theme?

### DISCUSSION THREAD

**Discussion by ninbura** [photoprism/photoprism#3717] [Q&A]
If possible, I'd like to change the
1. favicon
2. logo on the login screen
3. logo in the main interface/menu

It looks like you can set the favicon via [custom theming](https://www.photoprism.app/pro/kb/customization), but I'm not sure it covers all my bases & just seems a bit extra for what I'm trying to do.

Thought I might be able to manually swap out some files by using the `PHOTOPRISM_ASSETS_PATH` option. But when I set that option new assets aren't generated by default; which seems to totally break the website.
```yml
services:
  photoprism:
    PHOTOPRISM_ASSETS_PATH: "/photoprism/assets"
volumes:
  - "./assets:/photoprism/assets"
```

Maybe if I could find the assets path, copy the contents to my custom assets path, and change out the files it could work. Any ideas?
