### DISCUSSION TITLE
Uploading Photos via WebDav (PhotoSync - Android) scans the entire WebDav folders

### DISCUSSION THREAD

**Discussion by ant0nwax** [photoprism/photoprism#3732] [Q&A]
Hi community, 

I have the following setup for docker-compose:

```
root@photoprism:~/photoprism# cat docker-compose.yml | grep -vE "^\s*#"
version: '3.5'


services:
  photoprism:
    image: photoprism/photoprism:latest
    depends_on:
      - mariadb
    restart: unless-stopped
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    ports:
      - "2342:2342" # HTTP port (host:container)
    environment:
      PHOTOPRISM_ADMIN_PASSWORD: "REMOVED"          # !!! PLEASE CHANGE YOUR INITIAL "admin" PASSWORD !!!
      PHOTOPRISM_SITE_URL: "REMOVED"  # public server URL incl http:// or https:// and /path, :port is optional
      PHOTOPRISM_ORIGINALS_LIMIT: 5000               # file size limit for originals in MB (increase for high-res video)
      PHOTOPRISM_HTTP_COMPRESSION: "gzip"            # improves transfer speed and bandwidth utilization (none or gzip)
      PHOTOPRISM_DEBUG: "false"                      # run in debug mode (shows additional log messages)
      PHOTOPRISM_PUBLIC: "false"                     # no authentication required (disables password protection)
      PHOTOPRISM_READONLY: "false"                   # don't modify originals directory (reduced functionality)
      PHOTOPRISM_EXPERIMENTAL: "false"               # enables experimental features
      PHOTOPRISM_DISABLE_CHOWN: "false"              # disables storage permission updates on startup
      PHOTOPRISM_DISABLE_WEBDAV: "false"             # disables built-in WebDAV server
      PHOTOPRISM_DISABLE_SETTINGS: "false"           # disables Settings in Web UI
      PHOTOPRISM_DISABLE_TENSORFLOW: "false"         # disables all features depending on TensorFlow
      PHOTOPRISM_DISABLE_FACES: "false"              # disables facial recognition
      PHOTOPRISM_DISABLE_CLASSIFICATION: "false"     # disables image classification
      PHOTOPRISM_DARKTABLE_PRESETS: "false"          # enables Darktable presets and disables concurrent RAW conversion
      PHOTOPRISM_DETECT_NSFW: "false"                # flag photos as private that MAY be offensive (requires TensorFlow)
      PHOTOPRISM_UPLOAD_NSFW: "true"                 # allows uploads that MAY be offensive
      PHOTOPRISM_DATABASE_DRIVER: "mysql"            # use MariaDB 10.5+ or MySQL 8+ instead of SQLite for improved performance
      PHOTOPRISM_DATABASE_SERVER: "mariadb:3306"     # MariaDB or MySQL database server (hostname:port)
      PHOTOPRISM_DATABASE_NAME: "REMOVED"         # MariaDB or MySQL database schema name
      PHOTOPRISM_DATABASE_USER: "REMOVED"         # MariaDB or MySQL database user name
      PHOTOPRISM_DATABASE_PASSWORD: "REMOVED"       # MariaDB or MySQL database user password
      PHOTOPRISM_SITE_TITLE: "REMOVED"
      PHOTOPRISM_SITE_CAPTION: "AI-Powered Photos App"
      PHOTOPRISM_SITE_DESCRIPTION: ""
      PHOTOPRISM_SITE_AUTHOR: ""
      HOME: "/photoprism"
    working_dir: "/photoprism"
    volumes:
      - "~/Pictures:/photoprism/originals"               # original media files (photos and videos)
      - "/media/photos:/photoprism/originals/PHOTOS"
      - "./storage:/photoprism/storage"                  # *writable* storage folder for cache, database, and sidecar files (never remove)

  mariadb:
    restart: unless-stopped
    image: mariadb:10.6
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    command: mysqld --innodb-buffer-pool-size=128M --transaction-isolation=READ-COMMITTED --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-connections=512 --innodb-rollback-on-timeout=OFF --innodb-lock-wait-timeout=120
    volumes:
      - "./database:/var/lib/mysql" # important, don't remove
    environment:
     REMOVED FROM HERE
```

the machine looks like this:

```
root@photoprism:~/photoprism# df -h
Filesystem                                                      Size  Used Avail Use% Mounted on
udev                                                            5.8G     0  5.8G   0% /dev
tmpfs                                                           1.2G  1.3M  1.2G   1% /run
/dev/mapper/ubuntu--vg-ubuntu--lv                               147G  124G   17G  88% /
tmpfs                                                           5.9G     0  5.9G   0% /dev/shm
tmpfs                                                           5.0M     0  5.0M   0% /run/lock
tmpfs                                                           5.9G     0  5.9G   0% /sys/fs/cgroup
/dev/loop0                                                       56M   56M     0 100% /snap/core18/2785
/dev/sda2                                                       974M  209M  698M  24% /boot
/dev/loop2                                                       92M   92M     0 100% /snap/lxd/24061
/dev/loop1                                                       56M   56M     0 100% /snap/core18/2790
/dev/loop3                                                       92M   92M     0 100% /snap/lxd/23991
/dev/loop5                                                       64M   64M     0 100% /snap/core20/1974
/dev/loop4                                                       64M   64M     0 100% /snap/core20/2015
192.168.X.Y:/mnt/truenaspool/truenasdataset/MEDIA/PHOTOS  3.5T  2.2T  1.4T  62% /media/photos
overlay                                                         147G  124G   17G  88% /var/lib/docker/overlay2/3051108eb3578ad1254d4e12d76f37259c974fb077a85c378167ab50e565e5b6/merged
overlay                                                         147G  124G   17G  88% /var/lib/docker/overlay2/f1362b81ec0185a130430d2017c6948b1e76364fa20e6b08950c0612759ab204/merged
/dev/loop8                                                       41M   41M     0 100% /snap/snapd/19993
/dev/loop7                                                       41M   41M     0 100% /snap/snapd/20092
tmpfs                                                           1.2G     0  1.2G   0% /run/user/1000
```

My question:

Often When I update some few photos via Android, I need to wait 2-3 hours to see the few 4 or 10 photos in the photo prism web-app. What is wrong here?

Amount of Photos:
```
root@photoprism:/media/photos# find -type f | wc -l
97476
```

Thank you for construcive feedback.

I am running on Ubuntu and will do a dist-upgrade and an update / upgrade of the containers after the indexing finished :)
