### DISCUSSION TITLE
WebDav not working as expected after reinstall

### DISCUSSION THREAD

**Discussion by benne** [photoprism/photoprism#3746] [Q&A]
Short summary:
I have been using PhotoPrism happily for a long time, running on docker, uploading pictures from my phone using PhotoSync with WebDav. I decided to reinstall my server, and PhotoPrism is running flawlessly again without any problems, except I have some problems with WebDav.

WebDav is enabled, the instance is not read-only, I can manually import pictures, PhotoSync connects to the server (I can see that in the logs), but rashes afterwards. Mapping PhotoPrism /import/ as a drive on Windows, using WebDav, simply gives me the response that the folder doesn't exist (again, I can see in the logs that Windows connects and does some PROPFINDs).

Digging deeper, manually executing a PROPFIND on the /import/-folder (or any other folder for that matter, like /originals/), gives me an expected HTTP 207 multi-statuscode answer, but it seems there is a lack of Content-Length, confusing the receiver.

I can't for the life of me find out what should be changed. Everything else is working, WebDav is exposed and answers, but maybe sending me a body, but no length. Is this anything you have noticed before? Enabling debugging logs gives zero entries.

A bit of detail about my setup:

docker-compose.yml
```yaml
version: "3.9"

services:
  photoprism:
    image: photoprism/photoprism:latest
    restart: always
    depends_on:
      - db
    volumes:
      - originals:/photoprism/originals
      - import:/photoprism/import
      - storage:/photoprism/storage
    environment:
      PHOTOPRISM_ADMIN_USER: "me"
      PHOTOPRISM_ADMIN_PASSWORD: "password"
      PHOTOPRISM_AUTH_MODE: "password"
      PHOTOPRISM_SITE_URL: "https://my.domain.com"
      PHOTOPRISM_ORIGINALS_LIMIT: 50000
      PHOTOPRISM_HTTP_COMPRESSION: "gzip"
      PHOTOPRISM_LOG_LEVEL: "info"
      PHOTOPRISM_READONLY: "false"
      PHOTOPRISM_EXPERIMENTAL: "false"
      PHOTOPRISM_DISABLE_CHOWN: "false"
      PHOTOPRISM_DISABLE_WEBDAV: "false"
      PHOTOPRISM_DISABLE_SETTINGS: "false"
      PHOTOPRISM_DISABLE_TENSORFLOW: "false"
      PHOTOPRISM_DISABLE_FACES: "false"
      PHOTOPRISM_DISABLE_CLASSIFICATION: "false"
      PHOTOPRISM_DISABLE_RAW: "false"
      PHOTOPRISM_RAW_PRESETS: "false"
      PHOTOPRISM_JPEG_QUALITY: 85
      PHOTOPRISM_DETECT_NSFW: "false"
      PHOTOPRISM_UPLOAD_NSFW: "true"
      PHOTOPRISM_DATABASE_DRIVER: "mysql"
      PHOTOPRISM_DATABASE_SERVER: "db:3306"
      PHOTOPRISM_DATABASE_NAME: "photoprism"
      PHOTOPRISM_DATABASE_USER: "photoprism"
      PHOTOPRISM_DATABASE_PASSWORD: "secret"
      PHOTOPRISM_SPONSOR: "true"
      VIRTUAL_HOST: my.domain.com
      VIRTUAL_PORT: 2342
      LETSENCRYPT_HOST: my.domain.com
    networks:
      - photoprism
...
```

I'm using nginx with a Let's Encrypt companion container, where the vhost is as proposed in the docs:

```
client_max_body_size 50000M;

proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header Host $host;
proxy_buffering off;
proxy_http_version 1.1;
proxy_set_header Upgrade $http_upgrade;
proxy_set_header Connection "upgrade";
```

Manually probing WebDav with a PROPFIND reveals the possible body, but no Content-Length:

```
curl -I -X PROPFIND  -u me:secret https://my.domain.com/import/ -v
*   Trying 123.123.123.123:443...
* Connected to my.domain.com (123.123.123.123) port 443 (#0)
* ALPN: offers h2,http/1.1
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
*  CAfile: /etc/ssl/certs/ca-certificates.crt
*  CApath: /etc/ssl/certs
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.3 (IN), TLS handshake, Encrypted Extensions (8):
* TLSv1.3 (IN), TLS handshake, Certificate (11):
* TLSv1.3 (IN), TLS handshake, CERT verify (15):
* TLSv1.3 (IN), TLS handshake, Finished (20):
* TLSv1.3 (OUT), TLS change cipher, Change cipher spec (1):
* TLSv1.3 (OUT), TLS handshake, Finished (20):
* SSL connection using TLSv1.3 / TLS_AES_256_GCM_SHA384
* ALPN: server accepted h2
* Server certificate:
*  subject: CN=my.domain.com
*  start date: Jul 29 22:30:07 2023 GMT
*  expire date: Oct 27 22:30:06 2023 GMT
*  subjectAltName: host "my.domain.com" matched cert's "my.domain.com"
*  issuer: C=US; O=Let's Encrypt; CN=R3
*  SSL certificate verify ok.
* using HTTP/2
* Server auth using Basic with user 'me'
* h2h3 [:method: PROPFIND]
* h2h3 [:path: /import/]
* h2h3 [:scheme: https]
* h2h3 [:authority: my.domain.com]
* h2h3 [authorization: Basic xxxx=]
* h2h3 [user-agent: curl/7.88.1]
* h2h3 [accept: */*]
* Using Stream ID: 1 (easy handle 0x556a8830cc50)
> PROPFIND /import/ HTTP/2
> Host: my.domain.com
> authorization: Basic xxxx=
> user-agent: curl/7.88.1
> accept: */*
>
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* TLSv1.3 (IN), TLS handshake, Newsession Ticket (4):
* old SSL session ID is stale, removing
< HTTP/2 207
HTTP/2 207
< server: nginx/1.25.2
server: nginx/1.25.2
< date: Tue, 19 Sep 2023 21:27:57 GMT
date: Tue, 19 Sep 2023 21:27:57 GMT
< content-type: text/xml; charset=utf-8
content-type: text/xml; charset=utf-8
< content-security-policy: frame-ancestors 'none';
content-security-policy: frame-ancestors 'none';
< x-frame-options: DENY
x-frame-options: DENY
< strict-transport-security: max-age=31536000
strict-transport-security: max-age=31536000

<
* Excess found: excess = 3878 url = /import/ (zero-length body)
* Connection #0 to host my.domain.com left intact 
```

I'm by no means an expert in WebDav, so I could use some pointers - any ideas?
