### DISCUSSION TITLE
Videos not playing

### DISCUSSION THREAD

**Discussion by grannymaster** [photoprism/photoprism#3796] [Q&A] [answered]
Hello, 

I have a problem that most of my videos aren't playing. I've tried to play them with Firefox, Chrome, and Vivaldi. Both mobile and desktop versions.

Videos get stuck like this:
https://i.imgur.com/SrRQKP8.png

Photoprism is running in Docker on an Ubuntu 22.04.3 VM. The VM has 8 cores (i7-8700K) and 6GB of RAM allocated. Everything that I could, I updated.

I noticed that when I try opening videos, ffmpeg is trying to do something really hard:
https://i.imgur.com/YHT8VRP.png

Files are stored on a TrueNAS share. I can play the same videos directly from the share on my PC and phone over wifi.

Docker yaml:
```
version: ‘3.5’

services:
 photoprism:
   image: photoprism/photoprism:latest
   stop_grace_period: 10s
   depends_on:
     - mariadb
   security_opt:
     - seccomp:unconfined
     - apparmor:unconfined
   ports:
     - "2342:2342" # HTTP port (host:container)
   environment:
     PHOTOPRISM_ADMIN_USER: "admin"                 # admin login username
     PHOTOPRISM_ADMIN_PASSWORD: "insecure"          # initial admin password (8-72 characters)
     PHOTOPRISM_AUTH_MODE: "password"               # authentication mode (public, password)
     PHOTOPRISM_SITE_URL: "http://localhost:2342/"  # server URL in the format "http(s)://domain.name(:port)/(path)"
     PHOTOPRISM_DISABLE_TLS: "false"                # disables HTTPS/TLS even if the site URL starts with https:// and a certificate is available
     PHOTOPRISM_DEFAULT_TLS: "true"                 # defaults to a self-signed HTTPS/TLS certificate if no other certificate is available
     PHOTOPRISM_ORIGINALS_LIMIT: 5000               # file size limit for originals in MB (increase for high-res video)
     PHOTOPRISM_HTTP_COMPRESSION: "gzip"            # improves transfer speed and bandwidth utilization (none or gzip)
     PHOTOPRISM_LOG_LEVEL: "info"                   # log level: trace, debug, info, warning, error, fatal, or panic
     PHOTOPRISM_READONLY: "false"                   # do not modify originals directory (reduced functionality)
     PHOTOPRISM_EXPERIMENTAL: "false"               # enables experimental features
     PHOTOPRISM_DISABLE_CHOWN: "false"              # disables updating storage permissions via chmod and chown on startup
     PHOTOPRISM_DISABLE_WEBDAV: "false"             # disables built-in WebDAV server
     PHOTOPRISM_DISABLE_SETTINGS: "false"           # disables settings UI and API
     PHOTOPRISM_DISABLE_TENSORFLOW: "false"         # disables all features depending on TensorFlow
     PHOTOPRISM_DISABLE_FACES: "false"              # disables face detection and recognition (requires TensorFlow)

```

VM specs:
https://i.imgur.com/8J6mxlZ.png

Proxmox conf:

```
boot: order=scsi0;ide2;net0
cores: 8
cpu: x86-64-v2-AES,flags=+aes
ide2: ISO:iso/ubuntu-22.04.2-live-server-amd64.iso,media=cdrom,size=1929660K
memory: 6144
meta: creation-qemu=8.0.2,ctime=1696617228
name: heavy-docker
net0: virtio=CE:81:52:59:45:08,bridge=vmbr0,firewall=1
numa: 0
ostype: l26
scsi0: Storage:vm-130-disk-0,iothread=1,size=40G
scsihw: virtio-scsi-single
smbios1: uuid=f954bffe-143c-4efe-ac29-6de26de0906c
sockets: 1
vmgenid: e91d18ab-d1a9-4994-b96a-2a8fe92fbfbe

```
