### DISCUSSION TITLE
Error during indexing

### DISCUSSION THREAD

**Discussion by vuurvoske** [photoprism/photoprism#3856] [Q&A] [answered]
Hello,

I recently deciced to rebuild my library of photo's and to update my photoprism k3s deployment. However i constantly get the following error:

```
time="2023-10-31T13:00:42+01:00" level=info msg="convert: converting _DSC8007.NEF to _DSC8007.NEF.jpg (darktable-cli)"
/scripts/entrypoint.sh: line 118:    23 Killed                  "$@"
```

I've been looking in the sourcecode and found these two files:

https://github.com/photoprism/photoprism/blob/develop/scripts/dist/entrypoint.sh#L118
```
  # run command
  ([[ ${DOCKER_ENV} != "prod" ]] || "/scripts/audit.sh") \
   && (while "$@"; ret=$?; [[ $ret -eq 0 ]]; do echo "${@}"; done) &
   ```
   
   https://github.com/photoprism/photoprism/blob/develop/scripts/dist/audit.sh

I've already recreated the database, chmod 777 everything under photoprism/storage, tried different ways to build my deployment. I also tried to et DOCKER_ENV to "prod" to bypass the audit.sh but to no avail.
So i keep getting this error. I'd be very appreciative of any help / suggestions.

Underneath my k3s photoprism deployment
```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: photoprism
  labels:
    app: photoprism
spec:
  replicas: 1
  selector:
    matchLabels:
      app: photoprism
  template:
    metadata:
      labels:
        app: photoprism
    spec:
      restartPolicy: Always
      containers:
      - name: photoprism
        image: photoprism/photoprism:latest
        imagePullPolicy: "Always"
        env:
        - name: DOCKER_ENV
          name: prod
        - name: TZ
          value: Europe/Amsterdam
        - name: PHOTOPRISM_DATABASE_DRIVER
          value: "mysql"
        - name: PHOTOPRISM_DATABASE_SERVER
          value: "10.10.10.205:3306"
        - name: PHOTOPRISM_DATABASE_NAME
          value: "photoprism_new"
        - name: PHOTOPRISM_DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: mysql-photoprism
              key: mysql_user
        - name: PHOTOPRISM_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-photoprism
              key: mysql_password
        - name: PHOTOPRISM_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef: 
              name: mysql-photoprism # same as mysql-user
              key: mysql_password # same as mysql-user
        volumeMounts:
        - mountPath: /photoprism/originals
          name: originals
        - mountPath: /photoprism/import
          name: import
        - mountPath: /photoprism/storage
          name: storage
        ports:
        - containerPort: 2342
          name: http-2342
          protocol: TCP
        resources:
          requests:
            memory: "1024Mi"
            cpu: "500m"
          limits:
            memory: "3074Mi"
            cpu: "750m"
      volumes:
      - name: originals
        nfs: 
          server: 192.168.1.100
          path: /mnt/storagepool/Fotos_videos/originals
          readOnly: true
      - name: storage
        nfs: 
          server: 192.168.1.100
          path: /mnt/storagepool/photoprism/storage
          readOnly: false
      - name: import
        nfs: 
          server: 192.168.1.100
          path: /mnt/storagepool/photoprism/import
          readOnly: false
   ```

**Comment by lastzero** [comment]
Since this seems to happen when converting RAW images, I would recommend checking your memory and other resource limits as this requires a lot of CPU and memory.

**Reply by vuurvoske** [reply]
What is recommended?

**Reply by lastzero** [reply]
https://docs.photoprism.app/getting-started/#system-requirements

**Reply by vuurvoske** [reply]
even with the resources underneath i get the same error:
```
        resources:
          requests:
            memory: "1024Mi"
            cpu: "500m"
          limits:
            memory: "4096Mi"
            cpu: "2000m"
  ```
  
entire log:
  ```
  vuurvoske@vm1:~$ k logs -f photoprism-658c6d9658-ph7l5
started 231021 as root (amd64-prod)
init: https
Creation of a default HTTPS/TLS certificate is skipped because PHOTOPRISM_DEFAULT_TLS is "false".
Problems? Our Troubleshooting Checklists help you quickly diagnose and solve them:
https://docs.photoprism.app/getting-started/troubleshooting/
file umask....: "0002" (u=rwx,g=rwx,o=rx)
home directory: /photoprism
assets path...: /opt/photoprism/assets
storage path..: /photoprism/storage
config path...: default
cache path....: default
backup path...: /photoprism/storage/backups
import path...: /photoprism/import
originals path: /photoprism/originals
running as uid 0
/opt/photoprism/bin/photoprism start
time="2023-10-31T13:41:35+01:00" level=info msg="config: case-insensitive file system detected"
time="2023-10-31T13:41:35+01:00" level=info msg="Become a member today, support our mission and enjoy our member benefits! �"
time="2023-10-31T13:41:35+01:00" level=info msg="Visit https://www.photoprism.app/membership to learn more."
time="2023-10-31T13:41:35+01:00" level=info msg="webdav: shared /originals/"
time="2023-10-31T13:41:35+01:00" level=info msg="webdav: shared /import/"
time="2023-10-31T13:41:35+01:00" level=info msg="server: disabled tls"
time="2023-10-31T13:41:35+01:00" level=info msg="server: listening on 0.0.0.0:2342 [1.543684ms]"
time="2023-10-31T13:42:11+01:00" level=info msg="indexing originals..."
time="2023-10-31T13:42:11+01:00" level=info msg="classify: loading nasnet"
time="2023-10-31T13:42:15+01:00" level=info msg="classify: loading labels from labels.txt"
time="2023-10-31T13:42:15+01:00" level=info msg="index: found no .ppignore file"
time="2023-10-31T13:43:03+01:00" level=warning msg="index: 'LOREMASTER/World of Warcraft_2022.01.11-19.01.mp4' exceeds file size limit (5.3 GB / 1.0 GB)"
time="2023-10-31T13:43:04+01:00" level=info msg="convert: converting _DSC8006.NEF to _DSC8006.NEF.jpg (darktable-cli)"
time="2023-10-31T13:43:04+01:00" level=info msg="convert: converting _DSC8135.NEF to _DSC8135.NEF.jpg (darktable-cli)"
time="2023-10-31T13:43:22+01:00" level=info msg="convert: _DSC8135.NEF.jpg created in 18.451028941s (darktable-cli)"
time="2023-10-31T13:43:22+01:00" level=info msg="convert: _DSC8006.NEF.jpg created in 18.880234009s (darktable-cli)"
time="2023-10-31T13:43:26+01:00" level=info msg="media: created 11 thumbnails for fotografie/categorie/Familie/09-10-2022/_DSC8135.NEF.jpg [4.153738952s]"
time="2023-10-31T13:43:27+01:00" level=info msg="media: created 11 thumbnails for fotografie/categorie/Familie/09-10-2022/_DSC8006.NEF.jpg [4.256570092s]"
time="2023-10-31T13:43:27+01:00" level=info msg="index: added main raw file fotografie/categorie/Familie/09-10-2022/_DSC8135.NEF"
time="2023-10-31T13:43:27+01:00" level=info msg="faces: loading facenet"
time="2023-10-31T13:43:27+01:00" level=info msg="index: added main raw file fotografie/categorie/Familie/09-10-2022/_DSC8006.NEF"
time="2023-10-31T13:43:30+01:00" level=info msg="index: found 1 face in _DSC8006.NEF.jpg [2.603371458s]"
time="2023-10-31T13:43:31+01:00" level=info msg="index: found 2 faces in _DSC8135.NEF.jpg [4.113154123s]"
time="2023-10-31T13:43:37+01:00" level=info msg="index: stacked related jpg file fotografie/categorie/Familie/09-10-2022/_DSC8006.NEF.jpg"
time="2023-10-31T13:43:38+01:00" level=info msg="convert: converting _DSC8136.NEF to _DSC8136.NEF.jpg (darktable-cli)"
time="2023-10-31T13:43:38+01:00" level=info msg="index: stacked related jpg file fotografie/categorie/Familie/09-10-2022/_DSC8135.NEF.jpg"
time="2023-10-31T13:43:38+01:00" level=info msg="convert: converting _DSC8137.NEF to _DSC8137.NEF.jpg (darktable-cli)"
/scripts/entrypoint.sh: line 118:    23 Killed                  "$@"
```

**Reply by vuurvoske** [reply]
Question on the side: Why does it convert RAW straight away? I only want to convert RAW to jpeg when i want to download something. Or is this conversion default functionality?

**Reply by graciousgrey** [reply]
RAW files must be converted in order to be displayed in PhotoPrism. If you already have sidecar JPG files for your RAWs with correct naming, PhotoPrism will not create sidecar JPGs.

https://docs.photoprism.app/user-guide/settings/library/#convert-to-jpeg

**Reply by vuurvoske** [reply]
Oke i used the following parameters and now it seems to work more stable, I still cannot use the application and index at the same time, but that's fine for now.
```
        - name: PHOTOPRISM_THUMB_SIZE
          value: "1024"
        - name: PHOTOPRISM_JPEG_QUALITY
          value: "85"
        - name: PHOTOPRISM_THUMB_SIZE_UNCACHED
          value: "1024"
        - name: PHOTOPRISM_THUMB_UNCACHED
          value: "false"
        - name: PHOTOPRISM_JPEG_SIZE
          value: "2560"
        - name: PHOTOPRISM_PNG_SIZE
          value: "2560"
        - name: PHOTOPRISM_DISABLE_RAWTHERAPEE
          value: "false"
        - name: PHOTOPRISM_DISABLE_DARKTABLE
          value: "false"
   ```

**Reply by lastzero** [reply]
Limit the number of indexing workers if you have a lot of CPU cores.

**Reply by vuurvoske** [reply]
Which option would that be? I haven't be able to find it. the main CPU is a I5-6500, but the rest of the VM's aren't using alot of resources

**Reply by lastzero** [reply]
see https://docs.photoprism.app/getting-started/troubleshooting/performance/#troubleshooting

**Reply by vuurvoske** [reply]
An update. I used some tuning. And everything seemed to go fine. However i have a directory with .ARW files of which some are bigger than 85MB a piece. I added an additional node to my k3s cluster with 6GB of RAM, also i upped the resources to 3000m CPU and 6144Mi RAM. And still the indexing would crash. In the past this would run fine with 1000m CPU and 3074Mi RAM. Also on the new k3s node i can see my console getting filed with OOM messages. Why cant photoprism restrain itself? Why is it allowed to go OOM and crash? 
![OOM_errors_hestia](https://github.com/photoprism/photoprism/assets/31343570/e80b78a1-27d2-485e-a784-6daff9e3c037)

**Reply by lastzero** [reply]
Kindly note that RAW conversion is performed using Darktable and RawTherapee, which are pre-installed in the Docker image we provide. You can enable the Darktable presets option to prevent multiple files from being converted at the same time: https://docs.photoprism.app/user-guide/settings/advanced/#use-presets

It also doesn't hurt to [be less emotional](https://www.photoprism.app/code-of-conduct)  when you get free support from us. Thanks a lot! :heart:

**Reply by vuurvoske** [reply]
Sorry for giving the impression that i was emotional. That having said i do feel a bit frustrated not being able to get this application to run stable. I understand that both darktable and rawtherapee do the conversion. I already disabled one of them. Althought it doesnt make much difference. I'll give the darktable preset a go. Thank you.

**Comment by vuurvoske** [comment, marked as answer]
I seem to have fixed it. Drop everything in regard to resources, especially limits. That seemed to be the main culprit. My deployment file looks at follows now: ( i hope this will help somebody else too)

Thnx alot for the support on this matter!

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: photoprism
  labels:
    app: photoprism
spec:
  replicas: 1
  selector:
    matchLabels:
      app: photoprism
  template:
    metadata:
      labels:
        app: photoprism
    spec:
      # optional: assign pod/deployment to specific k3s node
      nodeName: node.somedomain.local
      restartPolicy: Always
      containers:
      - name: photoprism
        image: photoprism/photoprism:latest
        imagePullPolicy: "Always"
        env:                      
        - name: PHOTOPRISM_DEBUG
          value: "true"
        - name: PHOTOPRISM_THUMB_SIZE
          value: "2560"
        - name: PHOTOPRISM_JPEG_QUALITY
          value: "90"
        - name: PHOTOPRISM_THUMB_SIZE_UNCACHED
          value: "2560"
        # - name: PHOTOPRISM_THUMB_UNCACHED
        #   value: "false"
        - name: PHOTOPRISM_JPEG_SIZE
          value: "2560"
        - name: PHOTOPRISM_PNG_SIZE
          value: "2560"
        - name: PHOTOPRISM_DISABLE_RAWTHERAPEE
          value: "false"
        - name: PHOTOPRISM_DISABLE_DARKTABLE
          value: "true"
        - name: PHOTOPRISM_RAW_PRESETS
          value: "false"
        # - name: PHOTOPRISM_WORKERS
        #   value: "4" #4 is default
        - name: TZ
          value: Europe/Amsterdam
        - name: PHOTOPRISM_DATABASE_DRIVER
          value: "mysql"
        - name: PHOTOPRISM_DATABASE_SERVER
          value: "192.168.1.205:3306"
        - name: PHOTOPRISM_DATABASE_NAME
          value: "photoprism"
        - name: PHOTOPRISM_DATABASE_USER
          valueFrom:
            secretKeyRef:
              name: mysql-photoprism
              key: mysql_user
        - name: PHOTOPRISM_DATABASE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-photoprism
              key: mysql_password
        - name: PHOTOPRISM_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef: 
              name: mysql-photoprism # same as mysql-user
              key: mysql_password # same as mysql-user
        volumeMounts:
        - mountPath: /photoprism/originals
          name: originals
        - mountPath: /photoprism/import
          name: import
        - mountPath: /photoprism/storage
          name: storage
        ports:
        - containerPort: 2342
          name: http-2342
          protocol: TCP
        resources:
          requests:
            memory: "1024Mi"
            cpu: "500m"
      volumes:
      - name: originals
        nfs: 
          server: 192.168.1.200
          path: /mnt/storagepool/Fotos_videos/originals
          readOnly: true
      - name: storage
        nfs: 
          server: 192.168.1.200
          path: /mnt/storagepool/photoprism/storage
          readOnly: false
      - name: import
        nfs: 
          server: 192.168.1.200
          path: /mnt/storagepool/photoprism/import
          readOnly: false
 ```
