### DISCUSSION TITLE
Files getting mixed?

### DISCUSSION THREAD

**Discussion by cschramm** [photoprism/photoprism#3877] [Q&A] [answered]
I recently saw strange combinations of old and and new files getting mixed up in PhotoPrism. It seems to be related to a common filename that only differs by extension. Here's an example:

There's an IMG_8070.HEIC from 2021 in my originals, as well as a recent IMG_8070.MOV. Sidecar has a IMG_8070.yml with data matching the 2021 file as well as a IMG_8070.HEIC.jpg for it. For the recent file there's an IMG_8070.MOV.jpg and an IMG_8070.MOV.avc.

Now, in the gallery this becomes a single entry. It first showed up at the chronological position of the new IMG_8070.MOV with the old thumbnail IMG_8070.HEIC.jpg and data but appeared as a video and when clicking on it played IMG_8070.MOV or rather IMG_8070.MOV.avc. Both originals and both sidecar .jpgs get listed as related files in the entry. After re-indexing everything, the IMG_8070.yml got updated and the same entry (old thumbnail and data, new video content, all four files connected) now shows up at the chronological position of the old IMG_8070.HEIC.

Re-indexing changed the IMG_8070.yml from

```
TakenAt: 2021-02-04T18:16:04Z
TakenSrc: meta
UID: pqp6uvq1tv25fwyc
Type: image
Title: Synology / 2021
Year: 2021
Month: 2
Day: 4
ISO: 320
Exposure: 1/40
FNumber: 1.8
FocalLength: 28
Quality: 3
Details:
  Keywords: brown, synology
  Software: "14.3"
  SoftwareSrc: meta
CreatedAt: 2021-02-27T13:02:14.739205254Z
UpdatedAt: 2022-09-30T11:46:02.427089948Z
```

to

```
TakenAt: 2021-02-04T16:16:04Z
TakenAtLocal: 2021-02-04T18:16:04Z
TakenSrc: meta
UID: pqp6uvq1tv25fwyc
Type: video
Title: Synology / 2021
TimeZone: UTC+2
Year: 2021
Month: 2
Day: 4
ISO: 320
Exposure: 1/40
FNumber: 1.8
FocalLength: 28
Quality: 3
Duration: 44.23s
Details:
  Keywords: brown, synology
  Software: "14.3"
  SoftwareSrc: meta
CreatedAt: 2021-02-27T13:02:14Z
UpdatedAt: 2023-11-11T09:27:36Z
```

Is it a known limitation that files with equal names but different extensions get merged together or is this just some kind of configuration issue or something?
