### DISCUSSION TITLE
Photoprism does not connect to MariaDB database

### DISCUSSION THREAD

**Discussion by DaCHack** [photoprism/photoprism#3904] [Q&A]
Hi,

please find my docker-compose below.
My log looks as follows. Could you please help me find the root cause for photoprism being not accissible through the browser (receiving connection refused message and assuming this is due to issues with the DB connection).

```
time="2023-11-23T00:31:09Z" level=info msg="config: make sure your server has enough swap configured to prevent restarts when there are memory usage spikes"
time="2023-11-23T00:32:09Z" level=error msg="Error 1130: Host '172.24.0.3' is not allowed to connect to this MariaDB server"
/opt/photoprism/bin/photoprism start
time="2023-11-23T00:32:17Z" level=info msg="config: make sure your server has enough swap configured to prevent restarts when there are memory usage spikes"
time="2023-11-23T00:33:18Z" level=error msg="Error 1130: Host '172.24.0.3' is not allowed to connect to this MariaDB server"
/opt/photoprism/bin/photoprism start
time="2023-11-23T00:33:26Z" level=info msg="config: make sure your server has enough swap configured to prevent restarts when there are memory usage spikes"
```

```
version: '3.5'

services:
  photoprism:
    image: photoprism/photoprism:arm64
    stop_grace_period: 10s
    depends_on:
      - mariadb
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    ports:
      - "8808:2342"
    environment:
      PHOTOPRISM_ADMIN_USER: "administrator"                 # admin login username
      PHOTOPRISM_ADMIN_PASSWORD: "samepw"          # initial admin password (8-72 characters)
      PHOTOPRISM_AUTH_MODE: "password"               # authentication mode (public, password)
      PHOTOPRISM_SITE_URL: "http://localhost:8808/"  # server URL in the format "http(s)://domain.name(:port)/(path)"
      PHOTOPRISM_DISABLE_TLS: "false"                # disables HTTPS/TLS even if the site URL starts with https:// and a certificate is available
      PHOTOPRISM_DEFAULT_TLS: "true"                 # defaults to a self-signed HTTPS/TLS certificate if no other certificate is available
      PHOTOPRISM_ORIGINALS_LIMIT: 50000               # file size limit for originals in MB (increase for high-res video)
      PHOTOPRISM_HTTP_COMPRESSION: "none"            # improves transfer speed and bandwidth utilization (none or gzip)
      PHOTOPRISM_WORKERS: 2                          # Limits the number of indexing workers to reduce system load
      PHOTOPRISM_LOG_LEVEL: "info"                   # log level: trace, debug, info, warning, error, fatal, or panic
      PHOTOPRISM_READONLY: "true"                   # do not modify originals directory (reduced functionality)
      PHOTOPRISM_EXPERIMENTAL: "true"               # enables experimental features
      PHOTOPRISM_DISABLE_CHOWN: "false"              # disables updating storage permissions via chmod and chown on startup
      PHOTOPRISM_DISABLE_WEBDAV: "true"             # disables built-in WebDAV server
      PHOTOPRISM_DISABLE_SETTINGS: "false"           # disables Settings in Web UI
      PHOTOPRISM_DISABLE_TENSORFLOW: "false"         # disables all features depending on TensorFlow
      PHOTOPRISM_DISABLE_FACES: "false"               # disables face detection and recognition (requires TensorFlow)
      PHOTOPRISM_DISABLE_CLASSIFICATION: "false"     # disables image classification (requires TensorFlow)
      PHOTOPRISM_DISABLE_RAW: "true"                 # disables indexing and conversion of RAW images
      PHOTOPRISM_RAW_PRESETS: "false"                # enables applying user presets when converting RAW images (reduces performance)
      PHOTOPRISM_JPEG_QUALITY: 85                    # a higher value increases the quality and file size of JPEG images and thumbnails (25-100)
      PHOTOPRISM_DETECT_NSFW: "false"                # automatically flags photos as private that MAY be offensive (requires TensorFlow)
      PHOTOPRISM_UPLOAD_NSFW: "false"                 # allows uploads that MAY be offensive (no effect without TensorFlow)
      PHOTOPRISM_DATABASE_DRIVER: "mysql"            # use MariaDB 10.5+ or MySQL 8+ instead of SQLite for improved performance
      PHOTOPRISM_DATABASE_SERVER: "mariadb:3306"     # MariaDB or MySQL database server (hostname:port)
      PHOTOPRISM_DATABASE_NAME: "photoprism"         # MariaDB or MySQL database schema name
      PHOTOPRISM_DATABASE_USER: "photoprism"         # MariaDB or MySQL database user name
      PHOTOPRISM_DATABASE_PASSWORD: "samepw"       # MariaDB or MySQL database user password
      PHOTOPRISM_SITE_CAPTION: "Fotoarchiv"
      PHOTOPRISM_SITE_DESCRIPTION: ""                # meta site description
      PHOTOPRISM_SITE_AUTHOR: ""                     # meta site author

    devices:
      - "/dev/video11:/dev/video11" # Video4Linux Video Encode Device (h264_v4l2m2m)
    working_dir: "/photoprism" # do not change or remove
    ## Storage Folders: "~" is a shortcut for your home directory, "." for the current directory
    volumes:
      - "nas-photos:/photoprism/originals"               # Original media files (DO NOT REMOVE)
      - "/root/containers/photoprism/app:/photoprism/storage"                  # *Writable* storage folder for cache, database, and sidecar files (DO NOT REMOVE)

  mariadb:
    image: arm64v8/mariadb:10.11 # ARM64 IMAGE ONLY, DOES NOT WORK ON ARMv7, AMD or Intel
    restart: unless-stopped
    stop_grace_period: 5s
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    command: mariadbd --innodb-buffer-pool-size=256M --transaction-isolation=READ-COMMITTED --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-connections=512 --innodb-rollback-on-timeout=OFF --innodb-lock-wait-timeout=120
      - "/root/containers/photoprism/db:/var/lib/mysql" # DO NOT REMOVE
    environment:
      MARIADB_AUTO_UPGRADE: "1"
      MARIADB_INITDB_SKIP_TZINFO: "1"
      MYSQL_ROOT_PASSWORD: samepw
      MYSQL_DATABASE: photoprism
      MYSQL_USER: photoprism
      MYSQL_PASSWORD: samepw
      MYSQL_ROOT_HOST: 172.*.*.*

volumes:
  nas-photos:
   driver: local
   driver_opts:
     type: cifs
     o: "username=photoprism,password=otherpw,ro"
     device: "//192.168.1.2/photo/"
```
