### DISCUSSION TITLE
Cannot open PhotoPrism in the browser (connection was reset)

### DISCUSSION THREAD

**Discussion by p3k** [photoprism/photoprism#4105] [Q&A]
I followed the installation guide, modified the `docker-compose.yml` file, and invoked `docker compose up` – but opening the URL `http://localhost:2342` in the browser just returns the error message “This site can’t be reached – The connection was reset.“

## Download compose file

```shell
❯ wget https://dl.photoprism.app/docker/docker-compose.yml
--2024-03-16 10:48:59--  https://dl.photoprism.app/docker/docker-compose.yml
Resolving dl.photoprism.app (dl.photoprism.app)... 176.9.111.126
Connecting to dl.photoprism.app (dl.photoprism.app)|176.9.111.126|:443... connected.
HTTP request sent, awaiting response... 
  HTTP/1.1 200 OK
  Accept-Ranges: bytes
  Content-Length: 9828
  Content-Security-Policy: frame-ancestors 'none'; frame-src *; default-src 'self' 'unsafe-inline' 'unsafe-eval' data: blob: wss: photoprism.app *.photoprism.app *.photoprism.xyz *.photoprism.pro *.stripe.com *.maptiler.com; img-src * data: blob:; media-src * data: blob:
  Cross-Origin-Opener-Policy: same-origin
  Date: Sat, 16 Mar 2024 09:49:03 GMT
  Etag: "s95u8u7l0"
  Last-Modified: Tue, 20 Feb 2024 15:12:30 GMT
  Referrer-Policy: same-origin
  Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
  X-Frame-Options: DENY
  X-Xss-Protection: 1; mode=block
  Content-Type: text/plain; charset=utf-8
Length: 9828 (9,6K) [text/plain]
Saving to: ‘docker-compose.yml’

docker-compose.yml            100%[===============================================>]   9,60K  --.-KB/s    in 0,002s  

2024-03-16 10:49:03 (4,35 MB/s) - ‘docker-compose.yml’ saved [9828/9828]
```

## Modify compose file

```yaml
❯ cat docker-compose.yml 
version: '3.5'

# Example Docker Compose config file for PhotoPrism (Linux / AMD64)
#
# Note:
# - Running PhotoPrism on a server with less than 4 GB of swap space or setting a memory/swap limit can cause unexpected
#   restarts ("crashes"), for example, when the indexer temporarily needs more memory to process large files.
# - If you install PhotoPrism on a public server outside your home network, please always run it behind a secure
#   HTTPS reverse proxy such as Traefik or Caddy. Your files and passwords will otherwise be transmitted
#   in clear text and can be intercepted by anyone, including your provider, hackers, and governments:
#   https://docs.photoprism.app/getting-started/proxies/traefik/
#
# Setup Guides:
# - https://docs.photoprism.app/getting-started/docker-compose/
# - https://docs.photoprism.app/getting-started/raspberry-pi/
# - https://www.photoprism.app/kb/activation
#
# Troubleshooting Checklists:
# - https://docs.photoprism.app/getting-started/troubleshooting/
# - https://docs.photoprism.app/getting-started/troubleshooting/docker/
# - https://docs.photoprism.app/getting-started/troubleshooting/mariadb/
#
# CLI Commands:
# - https://docs.photoprism.app/getting-started/docker-compose/#command-line-interface
#
# All commands may have to be prefixed with "sudo" when not running as root.
# This will point the home directory shortcut ~ to /root in volume mounts.

services:
  photoprism:
    ## Use photoprism/photoprism:preview for testing preview builds:
    image: photoprism/photoprism:latest
    ## Don't enable automatic restarts until PhotoPrism has been properly configured and tested!
    ## If the service gets stuck in a restart loop, this points to a memory, filesystem, network, or database issue:
    ## https://docs.photoprism.app/getting-started/troubleshooting/#fatal-server-errors
    # restart: unless-stopped
    stop_grace_period: 10s
    depends_on:
      - mariadb
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    ## Server port mapping in the format "Host:Container". To use a different port, change the host port on
    ## the left-hand side and keep the container port, e.g. "80:2342" (for HTTP) or "443:2342 (for HTTPS):
    ports:
      - "2342:2342"
    ## Before you start the service, please check the following config options (and change them as needed):
    ## https://docs.photoprism.app/getting-started/config-options/
    environment:
      PHOTOPRISM_ADMIN_USER: "admin"                 # admin login username
      PHOTOPRISM_ADMIN_PASSWORD: "insecure"          # initial admin password (8-72 characters)
      PHOTOPRISM_AUTH_MODE: "password"               # authentication mode (public, password)
      PHOTOPRISM_SITE_URL: "http://localhost:2342/"  # server URL in the format "http(s)://domain.name(:port)/(path)"
      PHOTOPRISM_DISABLE_TLS: "false"                # disables HTTPS/TLS even if the site URL starts with https:// and a certificate is available
      PHOTOPRISM_DEFAULT_TLS: "true"                 # defaults to a self-signed HTTPS/TLS certificate if no other certificate is available
      PHOTOPRISM_ORIGINALS_LIMIT: 5000               # file size limit for originals in MB (increase for high-res video)
      PHOTOPRISM_HTTP_COMPRESSION: "gzip"            # improves transfer speed and bandwidth utilization (none or gzip)
      PHOTOPRISM_LOG_LEVEL: "info"                   # log level: trace, debug, info, warning, error, fatal, or panic
      PHOTOPRISM_READONLY: "false"                   # do not modify originals directory (reduced functionality)
      PHOTOPRISM_EXPERIMENTAL: "false"               # enables experimental features
      PHOTOPRISM_DISABLE_CHOWN: "false"              # disables updating storage permissions via chmod and chown on startup
      PHOTOPRISM_DISABLE_WEBDAV: "false"             # disables built-in WebDAV server
      PHOTOPRISM_DISABLE_SETTINGS: "false"           # disables settings UI and API
      PHOTOPRISM_DISABLE_TENSORFLOW: "false"         # disables all features depending on TensorFlow
      PHOTOPRISM_DISABLE_FACES: "false"              # disables face detection and recognition (requires TensorFlow)
      PHOTOPRISM_DISABLE_CLASSIFICATION: "false"     # disables image classification (requires TensorFlow)
      PHOTOPRISM_DISABLE_VECTORS: "false"            # disables vector graphics support
      PHOTOPRISM_DISABLE_RAW: "false"                # disables indexing and conversion of RAW images
      PHOTOPRISM_RAW_PRESETS: "false"                # enables applying user presets when converting RAW images (reduces performance)
      PHOTOPRISM_JPEG_QUALITY: 85                    # a higher value increases the quality and file size of JPEG images and thumbnails (25-100)
      PHOTOPRISM_DETECT_NSFW: "false"                # automatically flags photos as private that MAY be offensive (requires TensorFlow)
      PHOTOPRISM_UPLOAD_NSFW: "true"                 # allows uploads that MAY be offensive (no effect without TensorFlow)
      # PHOTOPRISM_DATABASE_DRIVER: "sqlite"         # SQLite is an embedded database that doesn't require a server
      PHOTOPRISM_DATABASE_DRIVER: "mysql"            # use MariaDB 10.5+ or MySQL 8+ instead of SQLite for improved performance
      PHOTOPRISM_DATABASE_SERVER: "mariadb:3306"     # MariaDB or MySQL database server (hostname:port)
      PHOTOPRISM_DATABASE_NAME: "photoprism"         # MariaDB or MySQL database schema name
      PHOTOPRISM_DATABASE_USER: "photoprism"         # MariaDB or MySQL database user name
      PHOTOPRISM_DATABASE_PASSWORD: "insecure"       # MariaDB or MySQL database user password
      PHOTOPRISM_SITE_CAPTION: "AI-Powered Photos App"
      PHOTOPRISM_SITE_DESCRIPTION: ""                # meta site description
      PHOTOPRISM_SITE_AUTHOR: ""                     # meta site author
      ## Video Transcoding (https://docs.photoprism.app/getting-started/advanced/transcoding/):
      # PHOTOPRISM_FFMPEG_ENCODER: "software"        # H.264/AVC encoder (software, intel, nvidia, apple, raspberry, or vaapi)
      # PHOTOPRISM_FFMPEG_SIZE: "1920"               # video size limit in pixels (720-7680) (default: 3840)
      # PHOTOPRISM_FFMPEG_BITRATE: "32"              # video bitrate limit in Mbit/s (default: 50)
      ## Run/install on first startup (options: update https gpu tensorflow davfs clitools clean):
      # PHOTOPRISM_INIT: "https gpu tensorflow"
      ## Run as a non-root user after initialization (supported: 0, 33, 50-99, 500-600, and 900-1200):
      # PHOTOPRISM_UID: 1000
      # PHOTOPRISM_GID: 1000
      # PHOTOPRISM_UMASK: 0000
    ## Start as non-root user before initialization (supported: 0, 33, 50-99, 500-600, and 900-1200):
    # user: "1000:1000"
    ## Share hardware devices with FFmpeg and TensorFlow (optional):
    # devices:
    #  - "/dev/dri:/dev/dri"                         # Intel QSV
    #  - "/dev/nvidia0:/dev/nvidia0"                 # Nvidia CUDA
    #  - "/dev/nvidiactl:/dev/nvidiactl"
    #  - "/dev/nvidia-modeset:/dev/nvidia-modeset"
    #  - "/dev/nvidia-nvswitchctl:/dev/nvidia-nvswitchctl"
    #  - "/dev/nvidia-uvm:/dev/nvidia-uvm"
    #  - "/dev/nvidia-uvm-tools:/dev/nvidia-uvm-tools"
    #  - "/dev/video11:/dev/video11"                 # Video4Linux Video Encode Device (h264_v4l2m2m)
    working_dir: "/photoprism" # do not change or remove
    ## Storage Folders: "~" is a shortcut for your home directory, "." for the current directory
    volumes:
      # "/host/folder:/photoprism/folder"                # Example
      - "~/Projects/photoprism/test:/photoprism/originals"               # Original media files (DO NOT REMOVE)
      # - "/example/family:/photoprism/originals/family" # *Additional* media folders can be mounted like this
      # - "~/Import:/photoprism/import"                  # *Optional* base folder from which files can be imported to originals
      - "~/.local/share/photoprism/storage:/photoprism/storage"                  # *Writable* storage folder for cache, database, and sidecar files (DO NOT REMOVE)

  ## Database Server (recommended)
  ## see https://docs.photoprism.app/getting-started/faq/#should-i-use-sqlite-mariadb-or-mysql
  mariadb:
    image: mariadb:11
    ## If MariaDB gets stuck in a restart loop, this points to a memory or filesystem issue:
    ## https://docs.photoprism.app/getting-started/troubleshooting/#fatal-server-errors
    restart: unless-stopped
    stop_grace_period: 5s
    security_opt: # see https://github.com/MariaDB/mariadb-docker/issues/434#issuecomment-1136151239
      - seccomp:unconfined
      - apparmor:unconfined
    command: --innodb-buffer-pool-size=512M --transaction-isolation=READ-COMMITTED --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-connections=512 --innodb-rollback-on-timeout=OFF --innodb-lock-wait-timeout=120
    ## Never store database files on an unreliable device such as a USB flash drive, an SD card, or a shared network folder:
    volumes:
      - "./database:/var/lib/mysql" # DO NOT REMOVE
    environment:
      MARIADB_AUTO_UPGRADE: "1"
      MARIADB_INITDB_SKIP_TZINFO: "1"
      MARIADB_DATABASE: "photoprism"
      MARIADB_USER: "photoprism"
      MARIADB_PASSWORD: "insecure"
      MARIADB_ROOT_PASSWORD: "insecure"

  ## Watchtower upgrades services automatically (optional)
  ## see https://docs.photoprism.app/getting-started/updates/#watchtower
  ## activate via "COMPOSE_PROFILES=update docker compose up -d"
  watchtower:
    restart: unless-stopped
    image: containrrr/watchtower
    profiles: ["update"]
    environment:
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_POLL_INTERVAL: 7200 # checks for updates every two hours
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "~/.docker/config.json:/config.json" # optional, for authentication if you have a Docker Hub account
```

The changes:

```yaml
volumes:
  - "~/Projects/photoprism/test:/photoprism/originals"`
  - "~/.local/share/photoprism/storage:/photoprism/storage"
```

The contents of the “originals” directory:

```shell
❯ ls ~/Projects/photoprism/test/
290805700_5521074917903688_2408325609706952242_n.jpg  296591089_165690555980357_4761650669197509960_n.jpg
295489270_1183406102503617_5594621521229211901_n.jpg  296598643_1085231872367645_3017518046790255363_n.jpg
296041002_435584321914573_2971881323699073354_n.jpg   297890674_1156080801647367_6625345934275637320_n.jpg
```

## First run

```shell
❯ docker compose up -d
[+] Running 17/17
 ✔ photoprism 7 layers [⣿⣿⣿⣿⣿⣿⣿]      0B/0B      Pulled                                                        274.8s 
   ✔ d1cf823cf1f0 Pull complete                                                                                 27.6s 
   ✔ 4cd4d808ccce Pull complete                                                                                 23.7s 
   ✔ b038a7d222a9 Pull complete                                                                                262.9s 
   ✔ 4f4fb700ef54 Pull complete                                                                                 28.6s 
   ✔ cfc84efec0ed Pull complete                                                                                 29.5s 
   ✔ b687b53e79dc Pull complete                                                                                 43.1s 
   ✔ 22a8edb37a8e Pull complete                                                                                167.6s 
 ✔ mariadb 8 layers [⣿⣿⣿⣿⣿⣿⣿⣿]      0B/0B      Pulled                                                           76.6s 
   ✔ bccd10f490ab Pull complete                                                                                 23.1s 
   ✔ d9d8e1823c6f Pull complete                                                                                  0.6s 
   ✔ 4b658f15686b Pull complete                                                                                  4.6s 
   ✔ 153080ffcddf Pull complete                                                                                  3.2s 
   ✔ fc35f7aae1e5 Pull complete                                                                                  3.8s 
   ✔ 59efd043a883 Pull complete                                                                                 72.6s 
   ✔ 676a7ad9f737 Pull complete                                                                                  5.2s 
   ✔ 335ef3100b9e Pull complete                                                                                  6.7s 
[+] Running 2/3
 ⠸ Network tobi_default         Created                                                                          1.4s 
 ✔ Container tobi-mariadb-1     Started                                                                          1.1s 
 ✔ Container tobi-photoprism-1  Started                                                                          0.6s 
```

### Testing with telnet

```shell
❯ telnet localhost 2342
Trying 127.0.0.1...
Connected to localhost.
Escape character is '^]'.
Connection closed by foreign host.
```

### Checking the storage

```shell
❯ ls ~/.local/share/photoprism/storage/
albums/  backup/  cache/  config/  serial  sidecar/  users/
```

## Second run in foreground

```shell
❯ docker compose up 
[+] Running 2/0
 ✔ Container tobi-mariadb-1     Created                                                                          0.0s 
 ✔ Container tobi-photoprism-1  Created                                                                          0.0s 
Attaching to mariadb-1, photoprism-1
mariadb-1     | 2024-03-16 10:01:30+00:00 [Note] [Entrypoint]: Entrypoint script for MariaDB Server 1:11.3.2+maria~ubu2204 started.
photoprism-1  | started 231128 as root (amd64-prod)
photoprism-1  | Problems? Our Troubleshooting Checklists help you quickly diagnose and solve them:
photoprism-1  | https://docs.photoprism.app/getting-started/troubleshooting/
photoprism-1  | file umask....: "0002" (u=rwx,g=rwx,o=rx)
photoprism-1  | home directory: /photoprism
photoprism-1  | assets path...: /opt/photoprism/assets
photoprism-1  | storage path..: /photoprism/storage
photoprism-1  | config path...: default
photoprism-1  | cache path....: default
photoprism-1  | backup path...: /photoprism/storage/backups
photoprism-1  | import path...: /photoprism/import
photoprism-1  | originals path: /photoprism/originals
photoprism-1  | running as uid 0
photoprism-1  | /opt/photoprism/bin/photoprism start
mariadb-1     | 2024-03-16 10:01:30+00:00 [Warn] [Entrypoint]: /sys/fs/cgroup///memory.pressure not writable, functionality unavailable to MariaDB
mariadb-1     | 2024-03-16 10:01:30+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
mariadb-1     | 2024-03-16 10:01:30+00:00 [Note] [Entrypoint]: Entrypoint script for MariaDB Server 1:11.3.2+maria~ubu2204 started.
mariadb-1     | 2024-03-16 10:01:30+00:00 [Note] [Entrypoint]: MariaDB upgrade not required
mariadb-1     | 2024-03-16 10:01:30 0 [Note] Starting MariaDB 11.3.2-MariaDB-1:11.3.2+maria~ubu2204 source revision 068a6819eb63bcb01fdfa037c9bf3bf63c33ee42 as process 1
mariadb-1     | 2024-03-16 10:01:30 0 [Note] InnoDB: Compressed tables use zlib 1.2.11
mariadb-1     | 2024-03-16 10:01:30 0 [Note] InnoDB: Number of transaction pools: 1
mariadb-1     | 2024-03-16 10:01:30 0 [Note] InnoDB: Using crc32 + pclmulqdq instructions
mariadb-1     | 2024-03-16 10:01:30 0 [Note] mariadbd: O_TMPFILE is not supported on /tmp (disabling future attempts)
mariadb-1     | 2024-03-16 10:01:30 0 [Note] InnoDB: Using liburing
mariadb-1     | 2024-03-16 10:01:30 0 [Note] InnoDB: Initializing buffer pool, total size = 512.000MiB, chunk size = 8.000MiB
mariadb-1     | 2024-03-16 10:01:30 0 [Note] InnoDB: Completed initialization of buffer pool
mariadb-1     | 2024-03-16 10:01:30 0 [Note] InnoDB: File system buffers for log disabled (block size=512 bytes)
mariadb-1     | 2024-03-16 10:01:31 0 [Note] InnoDB: End of log at LSN=47733
mariadb-1     | 2024-03-16 10:01:31 0 [Note] InnoDB: Opened 3 undo tablespaces
mariadb-1     | 2024-03-16 10:01:31 0 [Note] InnoDB: 128 rollback segments in 3 undo tablespaces are active.
mariadb-1     | 2024-03-16 10:01:31 0 [Note] InnoDB: Setting file './ibtmp1' size to 12.000MiB. Physically writing the file full; Please wait ...
mariadb-1     | 2024-03-16 10:01:31 0 [Note] InnoDB: File './ibtmp1' size is now 12.000MiB.
mariadb-1     | 2024-03-16 10:01:31 0 [Note] InnoDB: log sequence number 47733; transaction id 14
mariadb-1     | 2024-03-16 10:01:31 0 [Note] Plugin 'FEEDBACK' is disabled.
mariadb-1     | 2024-03-16 10:01:31 0 [Note] Plugin 'wsrep-provider' is disabled.
mariadb-1     | 2024-03-16 10:01:31 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
mariadb-1     | 2024-03-16 10:01:31 0 [Note] InnoDB: Buffer pool(s) load completed at 240316 10:01:31
mariadb-1     | 2024-03-16 10:01:31 0 [Note] Server socket created on IP: '0.0.0.0'.
mariadb-1     | 2024-03-16 10:01:31 0 [Note] Server socket created on IP: '::'.
mariadb-1     | 2024-03-16 10:01:31 0 [Note] mariadbd: Event Scheduler: Loaded 0 events
mariadb-1     | 2024-03-16 10:01:31 0 [Note] mariadbd: ready for connections.
mariadb-1     | Version: '11.3.2-MariaDB-1:11.3.2+maria~ubu2204'  socket: '/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution
```

### Entering the container

```shell
❯ docker exec -it photoprism-photoprism-1 bash
root@231128:/photoprism$ ls originals
290805700_5521074917903688_2408325609706952242_n.jpg  296591089_165690555980357_4761650669197509960_n.jpg
295489270_1183406102503617_5594621521229211901_n.jpg  296598643_1085231872367645_3017518046790255363_n.jpg
296041002_435584321914573_2971881323699073354_n.jpg   297890674_1156080801647367_6625345934275637320_n.jpg
root@231128:/photoprism$ photoprism status
# no output, needs ^C
^C
^D
```

## Increase log level

Changes in the compose file:

```yaml
environment:
  PHOTOPRISM_LOG_LEVEL: "debug"
  PHOTOPRISM_DEBUG: "true"
```

(Not sure which setting is the correct one, the compose file did not contain `PHOTOPRISM_DEBUG` but the [troubleshooting guide](https://docs.photoprism.app/getting-started/troubleshooting/#debug-mode) refers to it.)

I now see a few more lines of output:

```plain
photoprism-1  | time="2024-03-16T11:13:50Z" level=debug msg="settings: loaded from /photoprism/storage/config/settings.yml"
photoprism-1  | time="2024-03-16T11:15:20Z" level=debug msg="config: Post \"https://my.photoprism.app/v1/hello\": dial tcp 136.243.33.46:443: i/o timeout, see https://docs.photoprism.app/getting-started/troubleshooting/firewall/"
photoprism-1  | time="2024-03-16T11:15:20Z" level=debug msg="config: running on '11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz', 33 GB memory detected"
```

### Testing the failing URL

I have no issues reaching the URL from the host, albeit GET returns a 405:

```shell
❯ curl -I https://my.photoprism.app/v1/hello
HTTP/2 405 
cache-control: no-cache, private
content-security-policy: frame-ancestors 'none'; frame-src *; default-src 'self' 'unsafe-inline' 'unsafe-eval' data: blob: wss: photoprism.app *.photoprism.app *.photoprism.xyz *.photoprism.pro *.stripe.com *.maptiler.com; img-src * data: blob:; media-src * data: blob:
content-type: text/html; charset=utf-8
cross-origin-opener-policy: same-origin
date: Sat, 16 Mar 2024 11:22:22 GMT
referrer-policy: same-origin
strict-transport-security: max-age=31536000; includeSubDomains; preload
vary: Accept-Encoding
vary: Accept-Encoding
x-frame-options: DENY
x-xss-protection: 1; mode=block
```

In the container the URL times out, though:

```shell
root@231128:/photoprism$ curl -I https://my.photoprism.app/v1/hello
curl: (28) Failed to connect to my.photoprism.app port 443 after 137646 ms: Couldn't connect to server
```

What could I do now?

PS. I found https://github.com/photoprism/photoprism/discussions/1658, but so far did not restart the machine.
