### DISCUSSION TITLE
PhotoSync App Password

### DISCUSSION THREAD

**Discussion by modem7** [photoprism/photoprism#4206] [Q&A] [answered]
#### 1. What is not working as documented?

Have attempted to use the new app password in photosync. Getting 405 error.

#### 2. How can we reproduce it?

1. Try to login in photosync.
2. Username + app password

#### 3. What behavior do you expect?

For app password to allow me to login

#### 6. Which software versions do you use?

[PhotoPrism® CE](https://photoprism.modem7.com/library/about)
Build [240420-ef5f14bc4](https://docs.photoprism.app/release-notes/)

Photosync 4.0.10

Docker installed Photoprism on Ubuntu 22.04

Compose:

```yaml
 ##############
 ##Photoprism##
 ##############

  photoprism:
    container_name: Photoprism
    image: photoprism/photoprism:latest
    restart: always
    depends_on:
      - photoprismdb
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    networks:
      pihole:
        ipv4_address: '172.22.0.146'
      isolated:
    ports:
      - "2342:2342" # HTTP port (host:container)
    environment:
      PHOTOPRISM_ADMIN_USER: $PHOTOPRISM_ADMIN_USER
      PHOTOPRISM_ADMIN_PASSWORD: $PHOTOPRISM_ADMIN_PASSWORD
      PHOTOPRISM_AUTH_MODE: "password"
      PHOTOPRISM_SITE_URL: https://photoprism.$DOMAINNAME
      PHOTOPRISM_DISABLE_TLS: "true"                # disables HTTPS/TLS even if the site URL starts with https:// and a certificate is available
      PHOTOPRISM_DEFAULT_TLS: "false"                 # defaults to a self-signed HTTPS/TLS certificate if no other certificate is available
      # PHOTOPRISM_ORIGINALS_LIMIT: -1               # file size limit for originals in MB (increase for high-res video)
      # PHOTOPRISM_RESOLUTION_LIMIT: -1
      # PHOTOPRISM_JPEG_SIZE: 0
      PHOTOPRISM_HTTP_COMPRESSION: "gzip"            # improves transfer speed and bandwidth utilization (none or gzip)
      PHOTOPRISM_LOG_LEVEL: "info"                   # log level: trace, debug, info, warning, error, fatal, or panic
      PHOTOPRISM_READONLY: "false"                   # do not modify originals directory (reduced functionality)
      PHOTOPRISM_CACHE_PATH: "/photoprism_cache"
      PHOTOPRISM_SIDECAR_PATH: "/photoprism_sidecar" 
      PHOTOPRISM_USERS_PATH: "/photoprism_users"
      PHOTOPRISM_WORKERS: "20"
      PHOTOPRISM_FACE_SCORE: "5"
      PHOTOPRISM_EXPERIMENTAL: "false"               # enables experimental features
      PHOTOPRISM_DISABLE_CHOWN: "false"              # disables updating storage permissions via chmod and chown on startup
      PHOTOPRISM_DISABLE_WEBDAV: "false"             # disables built-in WebDAV server
      PHOTOPRISM_DISABLE_SETTINGS: "false"           # disables settings UI and API
      PHOTOPRISM_DISABLE_TENSORFLOW: "false"         # disables all features depending on TensorFlow
      PHOTOPRISM_DISABLE_FACES: "false"              # disables face detection and recognition (requires TensorFlow)
      PHOTOPRISM_DISABLE_CLASSIFICATION: "false"     # disables image classification (requires TensorFlow)
      PHOTOPRISM_DISABLE_VECTORS: "false"            # disables vector graphics support
      PHOTOPRISM_DISABLE_RAW: "true"                # disables indexing and conversion of RAW images
      PHOTOPRISM_RAW_PRESETS: "false"                # enables applying user presets when converting RAW images (reduces performance)
      # PHOTOPRISM_JPEG_QUALITY: 85                    # a higher value increases the quality and file size of JPEG images and thumbnails (25-100)
      PHOTOPRISM_DETECT_NSFW: "false"                # automatically flags photos as private that MAY be offensive (requires TensorFlow)
      PHOTOPRISM_UPLOAD_NSFW: "true"                 # allows uploads that MAY be offensive (no effect without TensorFlow)
      PHOTOPRISM_DATABASE_DRIVER: "mysql"
      PHOTOPRISM_DATABASE_SERVER: photoprismdb:3306
      PHOTOPRISM_DATABASE_NAME: $PHOTOPRISM_DATABASE
      PHOTOPRISM_DATABASE_USER: $PHOTOPRISM_USER
      PHOTOPRISM_DATABASE_PASSWORD: $PHOTOPRISM_PASSWORD
      PHOTOPRISM_SITE_CAPTION: "AI-Powered Photos App"
      PHOTOPRISM_SITE_DESCRIPTION: ""                # meta site description
      PHOTOPRISM_SITE_AUTHOR: ""                     # meta site author
      ## Video Transcoding (https://docs.photoprism.app/getting-started/advanced/transcoding/):
      # PHOTOPRISM_FFMPEG_ENCODER: "software"        # H.264/AVC encoder (software, intel, nvidia, apple, raspberry, or vaapi)
      # PHOTOPRISM_FFMPEG_SIZE: "1920"               # video size limit in pixels (720-7680) (default: 3840)
      # PHOTOPRISM_FFMPEG_BITRATE: "32"              # video bitrate limit in Mbit/s (default: 50)
      ## Run/install on first startup (options: update https gpu tensorflow davfs clitools clean):
      PHOTOPRISM_INIT: "update https gpu tensorflow davfs clean"
      ## Run as a non-root user after initialization (supported: 0, 33, 50-99, 500-600, and 900-1200):
      PHOTOPRISM_UID: $PUID
      PHOTOPRISM_GID: $PGID
      NVIDIA_VISIBLE_DEVICES: 0
      NVIDIA_DRIVER_CAPABILITIES: "compute,video,utility"
      # PHOTOPRISM_UMASK: 0000
    healthcheck:
      test: "photoprism status || exit 1"
      interval: 60s
      timeout: 15s
      retries: 5
      start_period: 20s
    labels:
      - backup
      - autoheal=true
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.photoprism-rtr.entrypoints=https"
      - "traefik.http.routers.photoprism-rtr.rule=Host(`photoprism.$DOMAINNAME`)"
         ## Middlewares
      # - "traefik.http.routers.photoprism-rtr.middlewares=chain-no-auth@file" # No Authentication
      # - "traefik.http.routers.photoprism-rtr.middlewares=chain-basic-auth@file" # Basic Authentication
      - "traefik.http.routers.photoprism-rtr.middlewares=chain-oauth-users@file" # Google OAuth 2.0
      # - "traefik.http.routers.photoprism-rtr.middlewares=chain-authelia@file" # Authelia
      ## HTTP Services
      - "traefik.http.routers.photoprism-rtr.service=photoprism-svc"
      - "traefik.http.services.photoprism-svc.loadbalancer.server.port=2342"
      ## Homepage
      - homepage.name=Photoprism
      - homepage.group=Tools
      - homepage.icon=photoprism
      - homepage.href=https://photoprism.$DOMAINNAME
      - homepage.widget.type=photoprism
      - homepage.widget.url=http://photoprism:2342
      - homepage.widget.username=$PHOTOPRISM_ADMIN_USER
      - homepage.widget.password=$PHOTOPRISM_ADMIN_PASSWORD
    runtime: nvidia
    devices:
      - /dev/dri:/dev/dri
      - /dev/nvidia0:/dev/nvidia0
      - /dev/nvidiactl:/dev/nvidiactl
      - /dev/nvidia-modeset:/dev/nvidia-modeset
      - /dev/nvidia-uvm:/dev/nvidia-uvm
      - /dev/nvidia-uvm-tools:/dev/nvidia-uvm-tools
    working_dir: "/photoprism" # do not change or remove
    volumes:
      - /mnt/docker_data/photoprism/originals:/photoprism/originals
      - /mnt/docker_data/photoprism/cache:/photoprism_cache
      - /mnt/oldhd/Pictures:/photoprism/originals/pictures
      - $USERDIR/Photoprism/storage:/photoprism/storage
      - /mnt/docker_data/photoprism/sidecar:/photoprism_sidecar
      - /mnt/docker_data/photoprism/users:/photoprism_users

  photoprismdb:
    image: linuxserver/mariadb
    container_name: Photoprism-db
    hostname: Photoprism-db
    networks:
      - isolated
    expose:
      - "3306"
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - MYSQL_DATABASE=$PHOTOPRISM_DATABASE
      - MYSQL_USER=$PHOTOPRISM_USER
      - MYSQL_PASSWORD=$PHOTOPRISM_PASSWORD
      - MYSQL_ROOT_PASSWORD=$PHOTOPRISM_ROOT_PASSWORD
    logging:
      driver: "local"
      options:
        max-size: 10m
        max-file: "3"
    volumes:
      - $USERDIR/Photoprism/DB:/config
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 30s
      timeout: 1s
      retries: 5
    labels:
      - backup
      - autoheal=true
    restart: always
```
