### DISCUSSION TITLE
Orientation operation, returned error 500

### DISCUSSION THREAD

**Discussion by kcrazy** [photoprism/photoprism#4217] [Q&A] [answered]
I want to flip an image using the orientation operation, 

calling the API: 
/api/v1/photos/psceoaw65z11gr0i/files/fsceoax5ool8vusl/orientation, 

which returns a 500 Internal Server Error. 

Version: April 20, 2024.

**Comment by lastzero** [comment]
Please enable trace log mode and provide the full logs:
- https://docs.photoprism.app/getting-started/troubleshooting/docker/#viewing-logs
- https://docs.photoprism.app/developer-guide/issues/#creating-bug-reports

**Comment by kcrazy** [comment]
```
photoprism --debug --trace start
```

log:
```
...
DEBU[2024-04-26T08:45:57+08:00] server: GET /api/v1/t/bbf499c0ae50ed4f4b0445b4b47a7c3fa7d0153d/xoql6sbt/tile_224 (200) [327.410552ms]
DEBU[2024-04-26T08:46:04+08:00] server: PUT /api/v1/photos/psciez55jlk1bg4b/files/fsciez7kwnprtk7e/orientation (500) [686.201µs]
DEBU[2024-04-26T08:46:50+08:00] server: PUT /api/v1/photos/psciez55jlk1bg4b/files/fsciez7kwnprtk7e/orientation (500) [1.428872ms]
DEBU[2024-04-26T08:47:09+08:00] server: PUT /api/v1/photos/psciez55jlk1bg4b/files/fsciez7kwnprtk7e/orientation (500) [416.362µs]
```

**Comment by lastzero** [comment]
So you don't use our Docker image? A dependency is probably missing then. We can't help with that within the scope of a bug ticket.

**Comment by kcrazy** [comment]
Yes, I'm not using Docker, 
but I'm using the [photoprism_240420-ef5f14bc4-linux-amd64.tar.gz](https://github.com/photoprism/photoprism/releases/download/240420-ef5f14bc4/photoprism_240420-ef5f14bc4-linux-amd64.tar.gz) from the [Release page](https://github.com/photoprism/photoprism/releases).

**Reply by graciousgrey** [reply]
Did you install the dependencies as described here:  https://dl.photoprism.app/pkg/linux/README.md ? If all dependencies are installed and you still get an error is it possible that you are trying to rotate images that are not JPG or PNG files?

**Comment by guilhermearaujo** [comment]
I'm having an issue with the same symptoms. I'm trying to change the image orientation, but it fails with status code 500 and the message `Changes could not be saved` in the toast.

These are the server logs shown after the request:
```
time="2024-06-15T08:25:20-03:00" level=trace msg="/usr/bin/exiftool -overwrite_original -n -Orientation=8 /photoprism/originals/2016 Trip/IMG_0661.jpg"
time="2024-06-15T08:25:20-03:00" level=debug msg="file: Error: Error creating file: /photoprism/originals/2016 Trip/IMG_0661.jpg_exiftool_tmp - /photoprism/originals/2016 Trip/IMG_0661.jpg\n in IMG_0661.jpg (change orientation)"
time="2024-06-15T08:25:20-03:00" level=debug msg="api-v1: abort /api/v1/photos/:uid/files/:file_uid/orientation with code 500 (changes could not be saved)"
time="2024-06-15T08:25:20-03:00" level=debug msg="server: PUT /api/v1/photos/psf3s5dgaj0yr7vm/files/fsf3s5dj7burkwii/orientation (500) [132.831778ms]"
```

Here's the docker-compose settings:
```yaml
x-service: &service
  deploy:
    resources:
      limits:
        cpus: "1"
        memory: 512M
  environment: &env
    LANG: C.UTF-8
    PGID: 1000
    PUID: 1000
    TZ: America/Sao_Paulo
  restart: unless-stopped
  stop_grace_period: 15s

volumes:
  photos:
    driver: local
    driver_opts:
      type: cifs
      device: //${SMB_IP}/photos
      o: username=${SMB_USERNAME},password=${SMB_PASSWORD},iocharset=utf8,rw

services:
  mariadb:
    <<: *service
    image: mariadb:11
    container_name: mariadb
    command:
      - --innodb-buffer-pool-size=256M
      - --transaction-isolation=READ-COMMITTED
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --max-connections=50
      - --innodb-rollback-on-timeout=OFF
      - --innodb-lock-wait-timeout=120
    environment:
      <<: *env
      MARIADB_AUTO_UPGRADE: 1
      MARIADB_INITDB_SKIP_TZINFO: 1
      MARIADB_DATABASE: mariadb
      MARIADB_USER: ${MARIADB_USERNAME}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    volumes:
      - ${SETTINGS_PATH}/mariadb:/var/lib/mysql

  photoprism:
    <<: *service
    image: photoprism/photoprism:latest
    container_name: photoprism
    depends_on:
      - mariadb
    deploy:
      resources:
        limits:
          cpus: "8.0"
          memory: 4G
    environment:
      <<: *env
      PHOTOPRISM_WORKERS: 8
      PHOTOPRISM_ADMIN_PASSWORD: ${PHOTOPRISM_ADMIN_PASSWORD}
      PHOTOPRISM_HTTP_COMPRESSION: gzip
      PHOTOPRISM_DATABASE_DRIVER: mysql
      PHOTOPRISM_DATABASE_SERVER: mariadb:3306
      PHOTOPRISM_DATABASE_NAME: photoprism
      PHOTOPRISM_DATABASE_USER: ${PHOTOPRISM_DB_USERNAME}
      PHOTOPRISM_DATABASE_PASSWORD: ${PHOTOPRISM_DB_PASSWORD}
      PHOTOPRISM_LOG_LEVEL: trace
    ports:
      - 2342:2342/tcp
    volumes:
      - photos:/photoprism/originals
      - ${SETTINGS_PATH}/photoprism/storage:/photoprism/storage
    working_dir: /photoprism
```

I was tinkering in the container console and decided to run the exiftool command there, and this is the output:
```
root@240531:/photoprism$ exiftool -overwrite_original -n -Orientation=8 "/photoprism/originals/2016 Trip/IMG_0661.jpg"
Error: File not found - /photoprism/originals/2016 Trip/IMG_0661.jpg
    1 image files updated
```

So the CLI seems to work. Write permissions and filesystem seems ok. Yet, the same command, when invoked from the application returns an error 🤔
