### DISCUSSION TITLE
Full indexing of all photos is always running when WebDAV ingest, how to avoid?

### DISCUSSION THREAD

**Discussion by jnernst** [photoprism/photoprism#4307] [Q&A]
It appears that Photoprism always runs a full re-indexing automatically, whenever I upload Photos via WebDAV (using PhotoSync). I'm aware that new photos have to be indexed. This is frustrating as the indexing (~60k) photos takes hours on end.

I'm happy to dig in, but how can I find out why this is happening? My first intuition was somehow timestamping being off, but I'm sure that Photoprism wouldn't use file timestamps to determine if something needs indexing? Naturally, it may be related to my specific setup. I tried to keep it as vanilla as possible, and I posted the docker-compose and env below. Could it be a permissions issue (e.g. DB generated, but never written)?

I feel that the only non-vanilla thing I do is to run in non-privileged docker (via setting UID/GID).

All other Photoprim functionality seems to be working fine.

[Update]
This is what I see in the log for all already indexed images:
```
[ ... ]
2024-05-30 10:02:24 INFO photo: updated sidecar file 2006/12/20061228_062251_AC0E1A0F.yml
2024-05-30 10:02:24 INFO index: updated main jpg file 2006/12/20061228_061721_33B67F88.jpg
[ ... ]
```

Version is
```
Build [240523-923ee0cf7]
```

`docker-compose`
```
services:
  photoprism:
    image: photoprism/photoprism:latest
    stop_grace_period: 10s
    depends_on:
      - mariadb
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    ports:
      - "2342:2342"

    devices:
     - "/dev/dri:/dev/dri"                         # Intel QSV
    working_dir: "/photoprism" # do not change or remove
    volumes:
      - "${FOLDER_ORIGINALS}:/photoprism/originals"               # Original media files (DO NOT REMOVE)
      - "${FOLDER_IMPORT}:/photoprism/import"                  # *Optional* base folder from which files can be imported to originals
      - "${FOLDER_STORAGE}:/photoprism/storage"                  # *Writable* storage folder for cache, database, and sidecar files (DO NOT REMOVE)
    env_file:
      - .env

  mariadb:
    image: mariadb:11
    restart: unless-stopped
    stop_grace_period: 5s
    security_opt: # see https://github.com/MariaDB/mariadb-docker/issues/434#issuecomment-1136151239
      - seccomp:unconfined
      - apparmor:unconfined
    command: --innodb-buffer-pool-size=512M --transaction-isolation=READ-COMMITTED --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-connections=512 --innodb-rollback-on-timeout=OFF --innodb-lock-wait-timeout=120
    volumes:
      - "${FOLDER_DATABASE}:/var/lib/mysql" # DO NOT REMOVE
    env_file:
      - .env

  watchtower:
    restart: unless-stopped
    image: containrrr/watchtower
    profiles: ["update"]
    environment:
      WATCHTOWER_CLEANUP: "true"
      WATCHTOWER_POLL_INTERVAL: 7200 # checks for updates every two hours
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "~/.docker/config.json:/config.json" # optional, for authentication if you have a Docker Hub account

```

`env`
```
## Before you start the service, please check the following config options (and change them as needed):
## https://docs.photoprism.app/getting-started/config-options/

FOLDER_ORIGINALS="/mnt/<folder-on-NAS>"
FOLDER_IMPORT="/mnt/<another-folder-on-NAS>"
FOLDER_STORAGE="/home/<local-folder-for-efficiency>/storage"
FOLDER_DATABASE="/home/<local-folder-for-efficiency>/database"

PHOTOPRISM_ADMIN_USER="admin"                 # admin login username
PHOTOPRISM_ADMIN_PASSWORD=<noneyabusiness>          # initial admin password (8-72 characters)
PHOTOPRISM_AUTH_MODE="password"               # authentication mode (public, password)
PHOTOPRISM_SITE_URL="http://localhost:2342/"  # server URL in the format "http(s)://domain.name(:port)/(path)"
PHOTOPRISM_DISABLE_TLS="false"                # disables HTTPS/TLS even if the site URL starts with https:// and a certificate is available
PHOTOPRISM_DEFAULT_TLS="true"                 # defaults to a self-signed HTTPS/TLS certificate if no other certificate is available
PHOTOPRISM_ORIGINALS_LIMIT=5000               # file size limit for originals in MB (increase for high-res video)
PHOTOPRISM_HTTP_COMPRESSION="gzip"            # improves transfer speed and bandwidth utilization (none or gzip)
PHOTOPRISM_LOG_LEVEL="info"                   # log level=trace, debug, info, warning, error, fatal, or panic
PHOTOPRISM_READONLY="false"                   # do not modify originals directory (reduced functionality)
PHOTOPRISM_EXPERIMENTAL="false"               # enables experimental features
PHOTOPRISM_DISABLE_CHOWN="false"              # disables updating storage permissions via chmod and chown on startup
PHOTOPRISM_DISABLE_WEBDAV="false"             # disables built-in WebDAV server
PHOTOPRISM_DISABLE_SETTINGS="false"           # disables settings UI and API
PHOTOPRISM_DISABLE_TENSORFLOW="false"         # disables all features depending on TensorFlow
PHOTOPRISM_DISABLE_FACES="false"              # disables face detection and recognition (requires TensorFlow)
PHOTOPRISM_DISABLE_CLASSIFICATION="false"     # disables image classification (requires TensorFlow)
PHOTOPRISM_DISABLE_VECTORS="false"            # disables vector graphics support
PHOTOPRISM_DISABLE_RAW="false"                # disables indexing and conversion of RAW images
PHOTOPRISM_RAW_PRESETS="false"                # enables applying user presets when converting RAW images (reduces performance)
PHOTOPRISM_SIDECAR_YAML="true"                # creates YAML sidecar files to back up picture metadata
PHOTOPRISM_BACKUP_ALBUMS="true"               # creates YAML files to back up album metadata
PHOTOPRISM_BACKUP_DATABASE="true"             # creates regular backups based on the configured schedule
PHOTOPRISM_BACKUP_SCHEDULE="daily"            # backup SCHEDULE in cron format (e.g. "0 12 * * *" for daily at noon) or at a random time (daily, weekly)
PHOTOPRISM_INDEX_SCHEDULE=""                  # indexing SCHEDULE in cron format (e.g. "@every 3h" for every 3 hours; "" to disable)
PHOTOPRISM_AUTO_INDEX=120                     # delay before automatically indexing files in SECONDS when uploading via WebDAV (-1 to disable)
PHOTOPRISM_AUTO_IMPORT=150                    # delay before automatically importing files in SECONDS when uploading via WebDAV (-1 to disable)
PHOTOPRISM_DETECT_NSFW="false"                # automatically flags photos as private that MAY be offensive (requires TensorFlow)
PHOTOPRISM_UPLOAD_NSFW="true"                 # allows uploads that MAY be offensive (no effect without TensorFlow)
# PHOTOPRISM_DATABASE_DRIVER="sqlite"         # SQLite is an embedded database that doesn't require a server
PHOTOPRISM_DATABASE_DRIVER="mysql"            # use MariaDB 10.5+ or MySQL 8+ instead of SQLite for improved performance
PHOTOPRISM_DATABASE_SERVER="mariadb:3306"     # MariaDB or MySQL database server (hostname:port)
PHOTOPRISM_DATABASE_NAME="photoprism"         # MariaDB or MySQL database schema name
PHOTOPRISM_DATABASE_USER="photoprism"         # MariaDB or MySQL database user name
PHOTOPRISM_DATABASE_PASSWORD="insecure"       # MariaDB or MySQL database user password
PHOTOPRISM_SITE_CAPTION="Family Photos"
PHOTOPRISM_SITE_DESCRIPTION=""                # meta site description
PHOTOPRISM_SITE_AUTHOR=""                     # meta site author
PHOTOPRISM_UID=1000
PHOTOPRISM_GID=1000

MARIADB_AUTO_UPGRADE="1"
MARIADB_INITDB_SKIP_TZINFO="1"
MARIADB_DATABASE="photoprism"
MARIADB_USER="photoprism"
MARIADB_PASSWORD="insecure"
MARIADB_ROOT_PASSWORD="insecure"
```
