### DISCUSSION TITLE
Unable to manually add labels

### DISCUSSION THREAD

**Discussion by robinchm** [photoprism/photoprism#4509] [Q&A] [answered]
New to photoprism, using the latest docker image and find it unable to add labels to a photo.

My `docker-compose.yml` looks like:

```yaml
services:
  photoprism:
    container_name: photoprism
    image: photoprism/photoprism:latest
    stop_grace_period: 10s
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    ports:
      - "2342:2342"
    environment:
      PHOTOPRISM_ADMIN_USER: "admin"
      PHOTOPRISM_ADMIN_PASSWORD: "admin123"
      PHOTOPRISM_AUTH_MODE: "password"
      PHOTOPRISM_SITE_URL: "http://localhost:2342/"
      PHOTOPRISM_DISABLE_TLS: "true"
      PHOTOPRISM_DEFAULT_TLS: "false"
      PHOTOPRISM_ORIGINALS_LIMIT: 5000
      PHOTOPRISM_HTTP_COMPRESSION: "gzip"
      PHOTOPRISM_LOG_LEVEL: "info"
      PHOTOPRISM_READONLY: "true"
      PHOTOPRISM_EXPERIMENTAL: "false"
      PHOTOPRISM_DISABLE_CHOWN: "false"
      PHOTOPRISM_DISABLE_WEBDAV: "true"
      PHOTOPRISM_DISABLE_SETTINGS: "false"
      PHOTOPRISM_DISABLE_TENSORFLOW: "true"
      PHOTOPRISM_DISABLE_FACES: "true"
      PHOTOPRISM_DISABLE_CLASSIFICATION: "true"
      PHOTOPRISM_DISABLE_OIDC: "true"
      PHOTOPRISM_DISABLE_VECTORS: "true"
      PHOTOPRISM_DISABLE_RAW: "false"
      PHOTOPRISM_RAW_PRESETS: "false"
      PHOTOPRISM_SIDECAR_YAML: "true"
      PHOTOPRISM_BACKUP_ALBUMS: "true"
      PHOTOPRISM_BACKUP_DATABASE: "true"
      PHOTOPRISM_BACKUP_SCHEDULE: "daily"
      PHOTOPRISM_INDEX_SCHEDULE: ""
      PHOTOPRISM_AUTO_INDEX: 300
      PHOTOPRISM_AUTO_IMPORT: -1
      PHOTOPRISM_DETECT_NSFW: "false"
      PHOTOPRISM_UPLOAD_NSFW: "true"
      PHOTOPRISM_DATABASE_DRIVER: "sqlite"
      PHOTOPRISM_SITE_CAPTION: "Photoprism"
      PHOTOPRISM_THUMB_SIZE: 720
    working_dir: "/photoprism"
    volumes:
      - "/path/to/photos:/photoprism/originals:ro"
      - "photoprism-storage:/photoprism/storage"

volumes:
  photoprism-storage:
```

While editing photo details works without issue, editing photo labels seems not working.

![image](https://github.com/user-attachments/assets/8982971c-a152-48f2-8a34-929009b77823)

In the labels panel of the photo I see this plus sign which I thought must be the button to add labels, but clicking on it has no effect. No pop-up or redirect, no new entry in the server log, in fact no request sent to the server. Am I doing anything wrong?
