### DISCUSSION TITLE
Subtitle Generation and View

### DISCUSSION THREAD

**Discussion by sfxworks** [photoprism/photoprism#4513] [Ideas]
Hey all

Anyone using k8s can benefit from this job I made that generates subtitles for all videos in your photoprism library. 

That being said, is there a way for photoprism to load subtitles in the video player, similar to how VLC looks for the filename.srt of the video and uses them?

```yaml
apiVersion: batch/v1
kind: Job
metadata:
  name: whisperx-job
  namespace: default
spec:
  template:
    spec:
      securityContext:
        fsGroup: 100  
        runAsGroup: 1000
      nodeSelector:
        kubernetes.io/hostname: ___SAME_NODE_AS_PHOTOPRISM___
      containers:
      - name: whisperx-container
        image: ghcr.io/jim60105/whisperx:medium-en
        command:
          - /bin/bash
          - "-c"
          - |
            echo "Starting recursive processing..."
            find /data/originals/ -type f \( -iname '*.mp4' -o -iname '*.mp3' -o -iname '*.avi' -o -iname '*.wav' -o -iname '*.ogg' -o -iname '*.mov' \) | while read -r file; do
              directory=$(dirname -- "$file")
              basename=$(basename -- "$file" | cut -f 1 -d '.')
              srt_file="${directory}/${basename}.srt"

              if [ -f "$srt_file" ]; then
                echo "Skipping $file, SRT file already exists"
              else
                echo "Processing $file"
                whisperx --hf_token $HF_TOKEN \
                         --print_progress True \
                         --highlight_words True \
                         --align_model WAV2VEC2_ASR_LARGE_LV60K_960H \
                         --model medium \
                         --output_format srt \
                         --output_dir "$directory" \
                         --language en \
                         "$file"
              fi
            done
        env:
        - name: HF_HUB_DOWNLOAD_TIMEOUT
          value: "60"
        - name: HF_TOKEN
          value: "___TOKEN___"
        resources:
          requests:
            cpu: 1
            memory: 2Gi
          limits:
            nvidia.com/gpu: 1
            cpu: 1
            memory: 8Gi
        volumeMounts:
        - name: data-volume
          mountPath: /data
      restartPolicy: Never
      volumes:
      - name: data-volume
        persistentVolumeClaim:
          claimName: photoprism-photoprism-0
  backoffLimit: 4
```

PS:
If your photoprism app is using a nvidia gpu like mine, make sure you turn on gpu sharing like below

```yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: timeslicing-configmap
  namespace: kube-system
data:
  config.yaml: |
    version: v1
    sharing:
      timeSlicing:
        resources:
        - name: nvidia.com/gpu
          replicas: 10
```

Mounting it against the nvidia daemonset
```yaml
        args:
          - "--config-file=/etc/config/config.yaml"
...
      - name: config-volume
        configMap:
          name: timeslicing-configmap 
```
