### DISCUSSION TITLE
Photoprism doesn't start on boot/reboot

### DISCUSSION THREAD

**Discussion by andrew-manger** [photoprism/photoprism#4517] [Q&A] [answered]
I am running photoprism on a raspberry pi 4. Whenever I restart my Pi, I have to run “docker compose up -d” again in my .photoprism folder to get the service to start up again. I’m considering making a systemd service to do this for me, but I’d love to figure out how to make it work correctly out of the box. I'm attaching my YAML file here, please let me know if there are any additional files would help! Thank you all so much in advance!

[docker-compose.txt](https://github.com/user-attachments/files/16966274/docker-compose.txt)

**Comment by lastzero** [comment, marked as answer]
Automatic (re)starts are commented out (disabled) in your configuration file:

```yaml
services:
  photoprism:
    # restart: unless-stopped
```

This starts the service automatically, e.g. when the computer is (re)started:

```yaml
services:
  photoprism:
    restart: unless-stopped
```
