### DISCUSSION TITLE
Photoprism PMTU issues

### DISCUSSION THREAD

**Discussion by Cyberax** [photoprism/photoprism#4529] [General]
It looks like there might be issues with PMTU discovery for https://places.photoprism.app and the registration endpoint. This can be very annoying for users, because these endpoints just time out on connection: "curl https://places.photoprism.app" just times out.

I fixed the issue by reducing the MTU from the default 1500 on Docker interfaces:

```
# Fix incorrect MTU
networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1460
```

My network has 1492 MTU, and I'm certain that I don't have anything mucking with my ICMP (my NAS even has a public IPv4).
