### DISCUSSION TITLE
Can't mount a subfolder of my smb folder

### DISCUSSION THREAD

**Discussion by LeKwisatz** [photoprism/photoprism#4547] [Q&A]
Hello,
I have successfully mounted my CIFS network volume thanks to this doc : https://docs.photoprism.app/getting-started/troubleshooting/docker/#smb-cifs
But I can't find a way to use the subfolder PHOTOS of this disk as a volume... 
I've tried anything I could imagine but none worked, it's always the subfolders of EXTERNAL_USB that appears in my originals : 

```
services:
  photoprism:
    volumes:
      - "originals:/photoprism/originals"     
     
volumes:
  originals:
    driver_opts:
      type: cifs
      o: "iocharset=utf8,username=admin,password=****,rw"
      device: "//freebox_server/EXTERNAL_USB/PHOTOS"
```
```
services:
  photoprism:
    volumes:
      - "originals:/PHOTOS:/photoprism/originals"     
     
volumes:
  originals:
    driver_opts:
      type: cifs
      o: "iocharset=utf8,username=admin,password=****,rw"
      device: "//freebox_server/EXTERNAL_USB"
````
```
services:
  photoprism:
    volumes:
      - "originals/PHOTOS:/photoprism/originals"     
     
volumes:
  originals:
    driver_opts:
      type: cifs
      o: "iocharset=utf8,username=admin,password=****,rw"
      device: "//freebox_server/EXTERNAL_USB"
```

Any idea ?
