### DISCUSSION TITLE
Nothing is found under library

### DISCUSSION THREAD

**Discussion by zer0isdoing** [photoprism/photoprism#4696] [Q&A]
Hello,

I created stack with yaml file in photoprism's documentation. I have only changed ./originals and ./storage path to external HDD and of course password and username. Now, I can access web UI, however in the library there is no photo or subfolder found/selectable. I can only see All Files, and START of course does not do anything. I am sure that I could succesfully mount external HDD since I can access these files from docker's terminal with ls /photoprism/originals. And it created required files in that same shared folder for /photoprism/storage. 

docker.yaml:
```
`## PhotoPrism Stack Configuration for Portainer
services:
  photoprism:
    image: photoprism/photoprism:latest
    ## Don't enable automatic restarts until PhotoPrism has been properly configured and tested!
    ## If the service gets stuck in a restart loop, this points to a memory, filesystem, network, or database issue:
    ## https://docs.photoprism.app/getting-started/troubleshooting/#fatal-server-errors
    restart: unless-stopped
    stop_grace_period: 10s
    depends_on:
      - mariadb
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    ## Server port mapping in the format "Host:Container". To use a different port, change the host port on
    ## the left-hand side and keep the container port, e.g. "80:2342" (for HTTP) or "443:2342 (for HTTPS):
    ports:
      - "2342:2342"
    ## Changes to the config options in stack.env always require a restart to take effect:
    ## https://docs.photoprism.app/getting-started/config-options/
    env_file:
      - stack.env
    working_dir: "/photoprism" # do not change or remove
    ## Storage Folders: "~" is a shortcut for your home directory, "." for the current directory
    volumes:
      - "/mnt/photoprism:/photoprism/originals" # Originals mount path can be changed as needed (DO NOT REMOVE)
      - "/mnt/photoprism/Data:/photoprism/storage"     # *Writable* storage folder for cache, database, and sidecar files (DO NOT REMOVE)

  mariadb:
    image: mariadb:11
    ## If MariaDB gets stuck in a restart loop, this points to a memory or filesystem issue:
    ## https://docs.photoprism.app/getting-started/troubleshooting/#fatal-server-errors
    restart: unless-stopped
    stop_grace_period: 5s
    security_opt: # see https://github.com/MariaDB/mariadb-docker/issues/434#issuecomment-1136151239
      - seccomp:unconfined
      - apparmor:unconfined
    command: --innodb-buffer-pool-size=512M --transaction-isolation=READ-COMMITTED --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-connections=512 --innodb-rollback-on-timeout=OFF --innodb-lock-wait-timeout=120
    ## Never store database files on an unreliable device such as a USB flash drive, an SD card, or a shared network folder:
    volumes:
      - "./database:/var/lib/mysql" # DO NOT REMOVE
    env_file:
      - stack.env`
```

mounted folder:
![image](https://github.com/user-attachments/assets/06577ab9-fb43-4ae7-a89a-6064946c2e24)
UI:
![image](https://github.com/user-attachments/assets/90f5c12f-f713-4ee6-815d-04b7521b6f8a)
