### DISCUSSION TITLE
Unable to start photoprism container if domain socket file is exist

### DISCUSSION THREAD

**Discussion by Pusnow** [photoprism/photoprism#4710] [Q&A]
PLEASE PROCEED ONLY IF YOU ARE ABSOLUTELY SURE THAT THIS IS NOT A TECHNICAL SUPPORT INCIDENT AND/OR POSSIBLY A PROBLEM WITH SOME OTHER SOFTWARE YOU ARE USING. VISIT <https://www.photoprism.app/kb/getting-support> TO LEARN MORE ABOUT OUR SUPPORT OPTIONS. THANK YOU FOR YOUR CAREFUL CONSIDERATION!

---------------------------------------------------------------------------

#### 1. What is not working as documented?

If a domain socket file persists, photoprism container does not start.
The socket file usually is created and not deleted in previous container run. 

#### 2. How can we reproduce it?

1. Start photoprism container using unix domain socket in a persistent volume or bind mount.
2. Stop and restart the same container.

#### 3. What behavior do you expect?

Start normally. To do so, photoprism container should delete the socket file on exit or on start.

#### 4. What could be the cause of your problem?

The undeleted unix socket file. 

#### 5. Can you provide us with example files for testing, error logs, or screenshots?

My container log:

```
started 240915 as root (amd64-prod)
init: https
Creation of a default HTTPS/TLS certificate is skipped because PHOTOPRISM_DEFAULT_TLS is "false".
Problems? Our Troubleshooting Checklists help you quickly diagnose and solve them:
https://docs.photoprism.app/getting-started/troubleshooting/
file umask....: "0002" (u=rwx,g=rwx,o=rx)
home directory: /photoprism
assets path...: /opt/photoprism/assets
storage path..: /photoprism/storage
config path...: default
cache path....: default
backup path...: /photoprism/storage/backups
import path...: /photoprism/import
originals path: /photoprism/originals
running as uid 0
/opt/photoprism/bin/photoprism start
time="2024-12-20T07:48:48Z" level=info msg="Become a member today, support our mission and enjoy our member benefits! 💎"
time="2024-12-20T07:48:48Z" level=info msg="Visit https://www.photoprism.app/membership to learn more."
time="2024-12-20T07:48:48Z" level=info msg="server: enabled gzip compression"
time="2024-12-20T07:48:48Z" level=info msg="webdav: disabled"
time="2024-12-20T07:48:48Z" level=error msg="server: failed to listen on unix socket (listen unix /var/sock/photoprism.sock: bind: address already in use)"
```

#### 6. Which software versions do you use?

(a) PhotoPrism Architecture & Build Number: AMD64 &  `docker.io/photoprism/photoprism:latest`

(b) Database Type & Version: MariaDB & `mariadb:11`

(c) Operating System Types & Versions: Linux, Fedora 41, Podman 5.3.1 

(d) Browser Types & Versions: Not related

(e) Ad Blockers, Browser Plugins, and/or Firewall Software? Not related

#### 7. On what kind of device is PhotoPrism installed?

(a) Device / Processor Type: DeskMini X300 / AMD Ryzen 7 5700G

(b) Physical Memory & Swap Space in GB: 32GB

(c) Storage Type: SSD

(d) Anything else that might be helpful to know?

#### 8. Do you use a Reverse Proxy, Firewall, VPN, or CDN?

I'm using Apache as a Reverse Proxy using the domain socket.

**Comment by lastzero** [comment]
@Pusnow I've tested this up and down, but even without a patch, the socket was automatically closed and removed when the server was shut down.

So what you are requesting seems to be the default behavior, and calling `listener.Close()` actually resulted in an error because the socket was already closed, see https://pkg.go.dev/net#UnixListener.SetUnlinkOnClose.

Therefore, if you want us to process your report and treat it as a valid high-priority bug, you will need to explain in detail how to reproduce the behavior you observe:

- If you are using Docker Compose, does it help to [set a `stop_grace_period`](https://docs.docker.com/reference/compose-file/services/#stop_grace_period) (e.g. "10s") for the photoprism and mariadb services?
- Does it happen when the server crashes, e.g. because it runs out of memory (or hits a configured memory limit)?
- Do you believe it could be because Apache is still listening on the socket and therefore it cannot be removed/closed by the process that created it?

Note that since you MAY have configured the same socket name on multiple instances, it is generally not a good idea to simply remove an existing socket at startup and then recreate it as a sort of brute-force approach. However, if you want to, you can write a small script/wrapper that does this before/when you start PhotoPrism. It should not be the default behavior though.

**Reply by Pusnow** [reply]
Thank you for your answer.
I'm using podman and podman kube play to serve photoprism.

* I've used `TerminationGracePeriodSeconds` to set grace period.
* My server has enough free memory.
* I've changed to different domain socket file path not accessed by Apache, but the problem persists.

Currently, I am using a simple script to remove before starting Photoprism.
I agree that removing socket file on startup can lead to some problem.
Removing it on exit should be enough.


```yaml
apiVersion: v1
data:
  password: <CUT>
kind: Secret
metadata:
  creationTimestamp: null
  name: my-kube-password
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: photoprism-pod
  name: photoprism-pod
spec:
  containers:
    - env:
        - name: MARIADB_AUTO_UPGRADE
          value: 1
        - name: MARIADB_INITDB_SKIP_TZINFO
          value: 1
        - name: MARIADB_DATABASE
          value: photoprism
        - name: MARIADB_USER
          value: photoprism
        - name: MYSQL_ROOT_HOST
          value: localhost
        - name: MARIADB_PASSWORD
          value: <CUT>
        - name: MARIADB_ROOT_PASSWORD
          value: <CUT>
      image: docker.io/mariadb:11
      name: mariadb
      args:
        - --innodb-buffer-pool-size=2G
        - --transaction-isolation=READ-COMMITTED
        - --character-set-server=utf8mb4
        - --collation-server=utf8mb4_unicode_ci
        - --max-connections=512
        - --innodb-rollback-on-timeout=OFF
        - --innodb-lock-wait-timeout=120
      volumeMounts:
        - mountPath: /var/lib/mysql
          name: photoprism-db
        - mountPath: /var/run/mysqld
          name: photoprism-sock-db
    - env:
        - name: PHOTOPRISM_ADMIN_USER
          value: <CUT>
        - name: PHOTOPRISM_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: photoprism-pw
              key: password
        - name: PHOTOPRISM_AUTH_MODE
          value: password
        - name: PHOTOPRISM_SITE_URL
          value: <CUT>
        - name: PHOTOPRISM_DISABLE_TLS
          value: true
        - name: PHOTOPRISM_DEFAULT_TLS
          value: false
        - name: PHOTOPRISM_ORIGINALS_LIMIT
          value: 5000
        - name: PHOTOPRISM_HTTP_COMPRESSION
          value: gzip
        - name: PHOTOPRISM_LOG_LEVEL
          value: info
        - name: PHOTOPRISM_READONLY
          value: false
        - name: PHOTOPRISM_EXPERIMENTAL
          value: false
        - name: PHOTOPRISM_DISABLE_CHOWN
          value: false
        - name: PHOTOPRISM_DISABLE_WEBDAV
          value: true
        - name: PHOTOPRISM_DISABLE_SETTINGS
          value: false
        - name: PHOTOPRISM_DISABLE_TENSORFLOW
          value: false
        - name: PHOTOPRISM_DISABLE_FACES
          value: false
        - name: PHOTOPRISM_DISABLE_CLASSIFICATION
          value: false
        - name: PHOTOPRISM_DISABLE_VECTORS
          value: false
        - name: PHOTOPRISM_DISABLE_RAW
          value: false
        - name: PHOTOPRISM_RAW_PRESETS
          value: false
        - name: PHOTOPRISM_SIDECAR_YAML
          value: true
        - name: PHOTOPRISM_BACKUP_ALBUMS
          value: true
        - name: PHOTOPRISM_BACKUP_DATABASE
          value: true
        - name: PHOTOPRISM_BACKUP_SCHEDULE
          value: daily
        - name: PHOTOPRISM_INDEX_SCHEDULE
          value:
        - name: PHOTOPRISM_AUTO_INDEX
          value: 300
        - name: PHOTOPRISM_AUTO_IMPORT
          value: -1
        - name: PHOTOPRISM_DETECT_NSFW
          value: false
        - name: PHOTOPRISM_UPLOAD_NSFW
          value: true
        - name: PHOTOPRISM_DATABASE_DRIVER
          value: mysql
        - name: PHOTOPRISM_DATABASE_SERVER
          value: /var/sock/db/mysqld.sock
        - name: PHOTOPRISM_DATABASE_NAME
          value: photoprism
        - name: PHOTOPRISM_DATABASE_USER
          value: photoprism
        - name: PHOTOPRISM_DATABASE_PASSWORD
          value: <CUT>
        - name: PHOTOPRISM_SITE_CAPTION
          value: AI-Powered Photos App
        - name: PHOTOPRISM_SITE_DESCRIPTION
          value:
        - name: PHOTOPRISM_SITE_AUTHOR
          value:
        - name: PHOTOPRISM_UID
          value: 0
        - name: PHOTOPRISM_GID
          value: 0
        - name: PHOTOPRISM_HTTP_HOST
          value: unix:/var/sock/main/photoprism2.sock
      image: docker.io/photoprism/photoprism:latest
      name: photoprism
      volumeMounts:
        - mountPath: /var/sock
          name: photoprism-sock
        - mountPath: /photoprism/storage
          name: photoprism-photoprism
        - mountPath: /photoprism/originals
          name: photoprism-photo
  hostNetwork: true
  hostname: home-photoprism
  restartPolicy: Always
  TerminationGracePeriodSeconds: 10
  volumes:
    - hostPath:
        path: /testpath/db
        type: Directory
      name: photoprism-db
    - hostPath:
        path: /testpath/photoprism
        type: Directory
      name: photoprism-photoprism
    - hostPath:
        path: /testpath/sock/photoprism
        type: Directory
      name: photoprism-sock
    - hostPath:
        path: /testpath/sock/photoprism/db
        type: Directory
      name: photoprism-sock-db
    - hostPath:
        path: /testpath/Photo
        type: Directory
      name: photoprism-photo
```
