### DISCUSSION TITLE
photoprism app stuck in starting loop

### DISCUSSION THREAD

**Discussion by mattheja** [photoprism/photoprism#4732] [Q&A] [answered]
Last month, I installed PhotoPrism and mariadb using the new custom docker-compose feature on TrueNAS Scale. It was working great. I imported over 40k pictures, added some users, and created a bunch of albums. I edited my docker-compose file a few times, stopped and started my apps during initial setup. All was working. Except today after another edit to the docker-compose file to add PHOTOPRISM_AUTO_IMPORT, it is stuck in a starting loop.

I'm stuck. Any ideas?

The TrueNAS Scale custom docker-compose is referenced on [their docs page](https://www.truenas.com/docs/truenasapps/usingcustomapp/#installing-via-yaml), and it does not have anything special as far as I can see.

mariadb container looks to boot normally. Except for these errors:
```
2025-01-18 10:58:10 81 [Warning] Aborted connection 81 to db: 'photoprism' user: 'photoprism' host: '172.16.2.3' (Got an error reading communication packets)
2025-01-18 10:58:32 82 [Warning] Aborted connection 82 to db: 'photoprism' user: 'photoprism' host: '172.16.2.3' (Got an error reading communication packets)
```

Docker logs for photoprism container just loop on:
```
/opt/photoprism/bin/photoprism start
started 240915 as root (amd64-prod)
init: account with the user id 568 already exists
init: updating filesystem permissions
PHOTOPRISM_DISABLE_CHOWN="true" disables permission updates
Problems? Our Troubleshooting Checklists help you quickly diagnose and solve them:
https://docs.photoprism.app/getting-started/troubleshooting/
file umask....: "0002" (u=rwx,g=rwx,o=rx)
home directory: /photoprism
assets path...: /opt/photoprism/assets
storage path..: /photoprism/storage
config path...: default
cache path....: default
backup path...: /photoprism/storage/backups
import path...: /photoprism/import
originals path: /photoprism/originals
switching to uid 568:568
/opt/photoprism/bin/photoprism start
```

Here are the full logs after boot from mariadb and photoprism:
[mariadb_logs.txt](https://github.com/user-attachments/files/18464151/mariadb_logs.txt)
[photoprism_logs.txt](https://github.com/user-attachments/files/18464152/photoprism_logs.txt)

Also here is my docker-compose file:
[docker-compose.yml.txt](https://github.com/user-attachments/files/18463985/docker-compose.yml.txt)

Originally, the photoprism.environment had this:
```
    environment:
      GID: "568"
      GROUP_ID: "568"
      PGID: "568"
      PHOTOPRISM_ADMIN_PASSWORD: admin123
      PHOTOPRISM_ADMIN_USER: prismadmin
      PHOTOPRISM_GID: "568"
      PHOTOPRISM_HTTP_PORT: "20800"
      PHOTOPRISM_IMPORT_PATH: /photoprism/import
      PHOTOPRISM_ORIGINALS_PATH: /photoprism/originals
      PHOTOPRISM_PUBLIC: "false"
      PHOTOPRISM_STORAGE_PATH: /photoprism/storage
      PHOTOPRISM_UID: "568"
      PHOTOPRISM_HTTP_COMPRESSION: "gzip"
      PHOTOPRISM_DATABASE_DRIVER: "mysql"
      PHOTOPRISM_DATABASE_SERVER: "mariadb:3306"
      PHOTOPRISM_DATABASE_NAME: "photoprism"
      PHOTOPRISM_DATABASE_USER: "photoprism"
      PHOTOPRISM_DATABASE_PASSWORD: "insecure"
      PHOTOPRISM_SITE_CAPTION: "Family photos viewer"
      PHOTOPRISM_INIT: "ffmpeg"
      PHOTOPRISM_AUTO_IMPORT: 60
      PUID: "568"
      TZ: Etc/UTC
      UID: "568"
      UMASK: "002"
      UMASK_SET: "002"
      USER_ID: "568"
```

But I removed today:
```
      GID: "568"
      GROUP_ID: "568"
      PGID: "568"
      PUID: "568"
      UID: "568"
      UMASK: "002"
      UMASK_SET: "002"
      USER_ID: "568"
```

In favor of just (plus also added PHOTOPRISM_AUTO_IMPORT):
```
      PHOTOPRISM_GID: "568"
      PHOTOPRISM_UID: "568"
      PHOTOPRISM_UMASK: "002"
      PHOTOPRISM_AUTO_IMPORT: 60
```

I did revert back to the old docker-compose file, but this did not change anything.
