### DISCUSSION TITLE
Running Multiple Instances on the Same Server

### DISCUSSION THREAD

**Discussion by tootbrute** [photoprism/photoprism#734] [Q&A] [answered]
Is this possible? Is anybody doing it?

1. Currently Photoprism only has 1 user per Docker instance, correct?
2. I want to make my wife have her own Photoprism instance on my server. Can this be done? What settings need to be changed?
 
- In docker-compose.yml
- I've changed name of the YML file, the port number, and of course the volumes.
- Will two instances conflict? I'm not that well versed in Docker.

Thank you!

**Comment by lastzero** [comment, marked as answer]
No problem, just make sure to set different directories and database names. You can use the same MariaDB server, depending on how familiar you are with configuring Docker.

**Reply by tootbrute** [reply]
I'm thinking what I need to change to use the same MariaDB is:
- MYSQL_DATABASE: photoprism_anothernamehere
- then change the PHOTOPRISM_DATABASE_DSN: to that photoprism_anothernamehere (in front of the ?)
- use same mysql root password, and mysql photoprism user password
- also change
services:
  photoprism_anothernamehere (for the different container name I think)
- i'm hoping watchtower is fine

Am I on the right track?

Also how will I know if I'm using the same MariaDB? i.e. How will I know if I'm successful?
If I screw something up, is my first photoprism database in any danger?

Thanks in advance if you can point me in the correct direction. Hopefully this information will be useful for others too :)

**Comment by lastzero** [comment]
First of all, please use our latest Docker Compose examples from dl.photoprism.org as config variables have been improved and reduced. Then put them in different folders. This will automatically separate installations. If you are unsure, you should not try to perform optimizations.

**Reply by tootbrute** [reply]
Ah great. Yes I see this updated docker-compose file is much clearer. Thank you!

Ok great, separate folders sounds good enough for now. Thanks for the advice :D

**Reply by lastzero** [reply]
Note that you still need to set different storage paths for PhotoPrism and MariaDB as the default is `- "~/.photoprism/mariadb:/var/lib/mysql"`, so the same hidden folder in the current user's home directory. You may change this into `- "./storage/mariadb:/var/lib/mysql"` for MariaDB and `- "./storage:/photoprism/storage"` for PhotoPrism so that the folder `storage` in the current directory is used.

**Reply by lastzero** [reply]
Updated our examples accordingly

**Comment by N20Visuals** [comment]
Hey Guys, 

i'm sorry if i'm being really stupid here, but can someone explain to me step by step how to set up multiple instances of photoprism on the same host system (ubuntu vm)? 
so far i've tried to modify the docker-compose.yml file to include two instances of photoprism and so far it seems to be working, but the second photoprism instance (with a different name) just outputs an error message that the connection to the database is refused. do i have to manually add the second database to mariadb or is it automatically created when launching the second photoprism container?

**Reply by lastzero** [reply]
Since the database gets initialized only once, you need to manually create databases for additional instances (or use any tool that does so for you):

https://mariadb.com/kb/en/create-database/

**Reply by N20Visuals** [reply]
ah, okay i'll give it a try. do i need to do anything special to be able to access mariaDB via my network? i thought i could connect to the IP:Port but that doesn't seem to work with Beekeeper Studio. with another install of mariaDB it worked that way, do i need to manually expose the container via the docker-compose file?

**Reply by lastzero** [reply]
You need to expose the port like for PhotoPrism:

```yaml
ports:
  - "3306:3306"
```

**Reply by N20Visuals** [reply]
ah perfect, thank you very much! now i can access mariaDB and was able to create a second database. so far it seems like everything is working but one thing: 

the second container is starting as it should but when starting with "sudo docker-compose up" (so i can see the logs) it tells me it's exposing the same port as my original instance (2342) despite me having set port 2355 everywhere there is a port to set: 

```
      ports:
        - "2345:2345" # HTTP port (host:container)
        - 
   PHOTOPRISM_SITE_URL: "http://localhost:2345/" 
```

**Reply by lastzero** [reply]
`- "2345:2342" `

**Reply by N20Visuals** [reply]
my god. thank you.

**Reply by Jimmy2027** [reply]
Hi @lastzero, how do I need to setup the mariadb for a second instance? I have a photoprism instance running with a mariadb, so I added a new user `other_photoprism` and a new database `other_photoprism` to which I wanted to connect with another photoprism instance. But the second photoprism instance fails with: 
`level=fatal msg="dial tcp: lookup mariadb on 127.0.0.11:53: no such host`
Do I need to have two mariadb docker containers running? I was thinking that having 1 mariadb container for 2 photoprism containers would be enough.

This is the config for my primary photoprism:
``` yaml

version: '3.5'

services:
  photoprism:
    image: photoprism/photoprism:latest
    depends_on:
      - mariadb
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    ports:
      - "2342:2342" # HTTP port (host:container)
    environment:
      PHOTOPRISM_ADMIN_PASSWORD: "my_pw"
      PHOTOPRISM_SITE_URL: "http://localhost:2342/"  # Public server URL incl http:// or https:// and /path, :port is optional
      .
      .
      .
      PHOTOPRISM_DATABASE_DRIVER: "mysql"            # Use MariaDB 10.5+ or MySQL 8+ instead of SQLite for improved performance
      PHOTOPRISM_DATABASE_SERVER: "mariadb:3306"     # MariaDB or MySQL database server (hostname:port)
      PHOTOPRISM_DATABASE_NAME: "photoprism"         # MariaDB or MySQL database schema name
      PHOTOPRISM_DATABASE_USER: "photoprism"         # MariaDB or MySQL database user name
      PHOTOPRISM_DATABASE_PASSWORD: "my_pw"       # MariaDB or MySQL database user password
      PHOTOPRISM_SITE_TITLE: "PhotoPrism"
      PHOTOPRISM_SITE_CAPTION: "Browse Your Life"
      PHOTOPRISM_SITE_DESCRIPTION: "PhotoPrism"
      PHOTOPRISM_SITE_AUTHOR: "John Doe"
      HOME: "/photoprism"

    working_dir: "/photoprism"
    volumes:
      - "/path/pictures:/photoprism/originals"               # original media files (photos and videos)
      - "/path/storage:/photoprism/storage"                  # *writable* storage folder for cache, database, and sidecar files (never remove)

  mariadb:
    restart: unless-stopped
    image: mariadb:10.6
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    command: mysqld --innodb-buffer-pool-size=128M --transaction-isolation=READ-COMMITTED --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-connections=512 --innodb-rollback-on-timeout=OFF --innodb-lock-wait-timeout=120 
    volumes:
      - "/path/database:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: insecure
      MYSQL_DATABASE: photoprism
      MYSQL_USER: photoprism
      MYSQL_PASSWORD: my_pw

```

This is the config of my second photoprism instance (without mariadb):

``` yaml

version: '3.5'

services:
  photoprism:
    image: photoprism/photoprism:latest
    depends_on:
      - mariadb
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    ports:
      - "2343:2342" # HTTP port (host:container)
    environment:
      PHOTOPRISM_ADMIN_PASSWORD: "my_pw"
      PHOTOPRISM_SITE_URL: "http://localhost:2343/"  # Public server URL incl http:// or https:// and /path, :port is optional
      .
      .
      .
      PHOTOPRISM_DATABASE_DRIVER: "mysql"            # Use MariaDB 10.5+ or MySQL 8+ instead of SQLite for improved performance
      PHOTOPRISM_DATABASE_SERVER: "mariadb:3306"     # MariaDB or MySQL database server (hostname:port)
      PHOTOPRISM_DATABASE_NAME: "other_photoprism"         # MariaDB or MySQL database schema name
      PHOTOPRISM_DATABASE_USER: "other_photoprism"         # MariaDB or MySQL database user name
      PHOTOPRISM_DATABASE_PASSWORD: "my_pw"       # MariaDB or MySQL database user password
      PHOTOPRISM_SITE_TITLE: "Other PhotoPrism"
      PHOTOPRISM_SITE_CAPTION: "Browse Your Life"
      PHOTOPRISM_SITE_DESCRIPTION: "PhotoPrism"
      PHOTOPRISM_SITE_AUTHOR: "John Doe"
      HOME: "/photoprism"

    working_dir: "/photoprism"
    volumes:
      - "/other_path/pictures:/photoprism/originals"               # original media files (photos and videos)
      - "/other_path/storage:/photoprism/storage"                  # *writable* storage folder for cache, database, and sidecar files (never remove)

```

**Comment by TheTravelAddict** [comment]
Hi - I am trying to get 2 instances running and I have so far been as successful at setting this up as Wile E. Coyote has at catching birds in the desert.

First instance works great; Here is what I have done for the second:
1) Created new 4 new directories; 1 for import, one for originals 1 for storage and one for the new yaml file. They mirror in structure that of my original, working instance.
2) copied the original YAML file into the new directory and edit it as follows:
>     ports:
>       - "2343:2342".  # working instance is "2342:2342". I also tried 2343:2343 just in case I misunderstood
> PHOTOPRISM_SITE_URL: "http://localhost:2343/"  # working instance is "http://localhost:2342/"
> PHOTOPRISM_DATABASE_NAME: "photoprism2" # working instance is "photoprism"
> PHOTOPRISM_SITE_DESCRIPTION: "PhotoPrism Test" # working instance is  "PhotoPrism"

And I changed the entries for import, originals, and storage to point to the new locations.

And I can't connect; I get this in the browser:

> Firefox can’t establish a connection to the server at 127.0.0.1:2343.
> 
>     The site could be temporarily unavailable or too busy. Try again in a few moments.
>     If you are unable to load any pages, check your computer’s network connection.
>     If your computer or network is protected by a firewall or proxy, make sure that Firefox is permitted to access the Web.

The original instance still works.

**Reply by TheTravelAddict** [reply]
ok - something new.  
I changed: 
> MARIADB_DATABASE: "photoprism2". # working instance is "photoprism"

now I get this in the browser:

> The connection was reset
> The connection to the server was reset while the page was loading.
> The site could be temporarily unavailable or too busy. Try again in a few moments.
> If you are unable to load any pages, check your computer’s network connection.
> If your computer or network is protected by a firewall or proxy, make sure that Firefox is permitted to access the Web

**Reply by graciousgrey** [reply]
Seems to be solved --> https://www.reddit.com/r/photoprism/comments/w0ktk1/getting_multiple_instances_up_and_running/ ? :)

**Comment by NaXal** [comment]
Hello,

I am on this same boat. Trying to run multiple instance of PhotoPrism on a single server to serve multiple NextCloud users as their separate and private photo gallery.

I am no expert with Docker so please do correct me if I am wrong in my process of deployment !!

On a Ubuntu Server 22 (clean installation) machine, I have docker and docker compose installed. On the home directory of that installation, I have a directory called "dockers", under that I have multiple directories for each users (at present 2 for testing). Both these individual directories are having their separate .yml file of photoprism docker.

I have edited the respective yml files to change following values,

1. Port No (like one is running on default 2342 another on one 2343)
2. Add following argument `PHOTOPRISM_HTTP_PORT: "2343" ` for custom port number under environment variables !!
3. admin password -> different for both users
4. Database name and passwords are different for each of these users

Lastly, running `docker compose up -d` on individual directories works. I see, I have two different photoprism instance running separately on the mentioned ports. I am syncing the data from my NextCloud installation and that too works for both.

Problem is with reboot. If I reboot this server, I see the docker process is started but I don't see photoprism running. On every reboot, I have to manually run `docker compose up -d` for both directories to start photoprism.

How can I solve this?

Thanks.

**Reply by StanDaMan0505** [reply]
You need to add "restart: unless-stopped" to your service.

**Reply by NaXal** [reply]
Hello,

Thank you for the reply. 

I see the line is already there in the given yml file, just commented out by default so uncommenting it did the trick, its now starting up automatically at reboot. 

```
services:
  photoprism:
    ## Use photoprism/photoprism:preview for testing preview builds:
    image: photoprism/photoprism:latest
    depends_on:
      - mariadb
    ## Don't enable automatic restarts until PhotoPrism has been properly configured and tested!
    ## If the service gets stuck in a restart loop, this points to a memory, filesystem, network, or database issue:
    ## https://docs.photoprism.app/getting-started/troubleshooting/#fatal-server-errors
    # restart: unless-stopped                <---- THIS ONE
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
```

Thanks.

**Comment by jrstrunk** [comment]
I just got multiple instances running on one server (which also has NextCloud running on it) and sharing one mariadb container with the following `docker-compose.yml`:

```
version: "3.9"

services:
  caddy:
    image: caddy:latest
    restart: always
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    volumes:
      - /home/john/Caddyfile:/etc/caddy/Caddyfile
      - /home/john/certs:/certs
      - /home/john/config:/config
      - /home/john/data:/data
      - /home/john/sites:/srv
    network_mode: "host"

  nextcloud:
    image: nextcloud/all-in-one:latest
    init: true
    restart: always
    container_name: nextcloud-aio-mastercontainer
    ports:
      - "8080:8080"
    environment:
      - APACHE_PORT=11000
      - APACHE_IP_BINDING=127.0.0.1
      - NEXTCLOUD_DATADIR=/ext/data/datadir
    volumes:
      - nextcloud_aio_mastercontainer:/ext/docker-aio-config
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - caddy

  mariadb:
    image: mariadb:11
    restart: unless-stopped
    stop_grace_period: 5s
    container_name: photoprism-db
    security_opt: # see https://github.com/MariaDB/mariadb-docker/issues/434#issuecomment-1136151239
      - seccomp:unconfined
      - apparmor:unconfined
    # Creates two databases, if any more databases are needed after first time setup, then run `sudo docker exec -it photoprism-mariadb-1 mariadb -u root`, then `CREATE DATABASE IF NOT EXISTS thirdDB; GRANT ALL PRIVILEGES ON thirdDB.* TO 'photoprism'@'%'; FLUSH PRIVILEGES;`
    entrypoint: 
      - sh
      - -c
      - |
        echo "CREATE DATABASE IF NOT EXISTS photoprism_john; GRANT ALL PRIVILEGES ON photoprism_john.* TO 'photoprism'@'%'; CREATE DATABASE IF NOT EXISTS photoprism_john2; GRANT ALL PRIVILEGES ON photoprism_john2.* TO 'photoprism'@'%'; FLUSH PRIVILEGES;" > /docker-entrypoint-initdb.d/init.sql;
        /usr/local/bin/docker-entrypoint.sh --innodb-buffer-pool-size=512M --transaction-isolation=READ-COMMITTED --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-connections=512 --innodb-rollback-on-timeout=OFF --innodb-lock-wait-timeout=120
    volumes:
      - "./photoprism/database:/var/lib/mysql" # DO NOT REMOVE
    environment:
      MARIADB_AUTO_UPGRADE: "1"
      MARIADB_INITDB_SKIP_TZINFO: "1"
      MARIADB_USER: "photoprism"
      MARIADB_PASSWORD: "password"
      MARIADB_ROOT_PASSWORD: "password"
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306

  photoprism-john:
    image: photoprism/photoprism:latest
    container_name: photoprism-john
    restart: unless-stopped
    stop_grace_period: 10s
    depends_on:
      - mariadb
      - caddy
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    ports:
      - "2342:2342" # HTTP port (host:container)
    environment:
      PHOTOPRISM_ADMIN_USER: "john"                  # admin login username
      PHOTOPRISM_ADMIN_PASSWORD: "password"    # initial admin password (8-72 characters)
      PHOTOPRISM_AUTH_MODE: "password"               # authentication mode (public, password)
      PHOTOPRISM_SITE_URL: "https://photoprism.mydomain.com:443/" # server URL in the format "http(s)://domain.name(:port)/(path)"
      PHOTOPRISM_DISABLE_TLS: "true"                # disables HTTPS/TLS even if the site URL starts with https:// and a certificate is available
      PHOTOPRISM_DEFAULT_TLS: "true"                 # defaults to a self-signed HTTPS/TLS certificate if no other certificate is available
      PHOTOPRISM_ORIGINALS_LIMIT: 5000               # file size limit for originals in MB (increase for high-res video)
      PHOTOPRISM_HTTP_COMPRESSION: "gzip"            # improves transfer speed and bandwidth utilization (none or gzip)
      PHOTOPRISM_LOG_LEVEL: "info"                   # log level: trace, debug, info, warning, error, fatal, or panic
      PHOTOPRISM_READONLY: "false"                   # do not modify originals directory (reduced functionality)
      PHOTOPRISM_EXPERIMENTAL: "false"               # enables experimental features
      PHOTOPRISM_DISABLE_CHOWN: "false"              # disables updating storage permissions via chmod and chown on startup
      PHOTOPRISM_DISABLE_WEBDAV: "false"             # disables built-in WebDAV server
      PHOTOPRISM_DISABLE_SETTINGS: "false"           # disables settings UI and API
      PHOTOPRISM_DISABLE_TENSORFLOW: "false"         # disables all features depending on TensorFlow
      PHOTOPRISM_DISABLE_FACES: "false"              # disables face detection and recognition (requires TensorFlow)
      PHOTOPRISM_DISABLE_CLASSIFICATION: "false"     # disables image classification (requires TensorFlow)
      PHOTOPRISM_DISABLE_VECTORS: "false"            # disables vector graphics support
      PHOTOPRISM_DISABLE_RAW: "false"                # disables indexing and conversion of RAW images
      PHOTOPRISM_RAW_PRESETS: "false"                # enables applying user presets when converting RAW images (reduces performance)
      PHOTOPRISM_JPEG_QUALITY: 85                    # a higher value increases the quality and file size of JPEG images and thumbnails (25-100)
      PHOTOPRISM_DETECT_NSFW: "true"                 # automatically flags photos as private that MAY be offensive (requires TensorFlow)
      PHOTOPRISM_UPLOAD_NSFW: "true"                 # allows uploads that MAY be offensive (no effect without TensorFlow)
      PHOTOPRISM_DATABASE_DRIVER: "mysql"            # use MariaDB 10.5+ or MySQL 8+ instead of SQLite for improved performance
      PHOTOPRISM_DATABASE_SERVER: "mariadb:3306"     # MariaDB or MySQL database server (hostname:port)
      PHOTOPRISM_DATABASE_NAME: "photoprism_john"    # MariaDB or MySQL database schema name
      PHOTOPRISM_DATABASE_USER: "photoprism"         # MariaDB or MySQL database user name
      PHOTOPRISM_DATABASE_PASSWORD: "password"       # MariaDB or MySQL database user password
      PHOTOPRISM_SITE_CAPTION: "Photo Prism"
      PHOTOPRISM_SITE_DESCRIPTION: "A Privacy Preserving Photos App" # meta site description
      PHOTOPRISM_SITE_AUTHOR: "Me"                   # meta site author
    working_dir: "/photoprism" # do not change or remove
    ## Storage Folders: "~" is a shortcut for your home directory, "." for the current directory
    volumes:
      - "/ext/data/photoprism/john/pictures:/photoprism/originals"               # Original media files (DO NOT REMOVE)
      - "/ext/data/photoprism/john/import:/photoprism/import"                  # *Optional* base folder from which files can be imported to originals
      - "/ext/data/photoprism/john/storage:/photoprism/storage"                  # *Writable* storage folder for cache, database, and sidecar files (DO NOT REMOVE)

  photoprism-john2:
    image: photoprism/photoprism:latest
    container_name: photoprism-john2
    restart: unless-stopped
    stop_grace_period: 10s
    depends_on:
      - mariadb
      - caddy
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    ports:
      - "2343:2342" # HTTP port (host:container)
    environment:
      PHOTOPRISM_ADMIN_USER: "john2"               # admin login username
      PHOTOPRISM_ADMIN_PASSWORD: "password"    # initial admin password (8-72 characters)
      PHOTOPRISM_AUTH_MODE: "password"               # authentication mode (public, password)
      PHOTOPRISM_SITE_URL: "https://photoprism2.mydomain.com:443/"  # server URL in the format "http(s)://domain.name(:port)/(path)"
      PHOTOPRISM_DISABLE_TLS: "true"                # disables HTTPS/TLS even if the site URL starts with https:// and a certificate is available
      PHOTOPRISM_DEFAULT_TLS: "true"                 # defaults to a self-signed HTTPS/TLS certificate if no other certificate is available
      PHOTOPRISM_ORIGINALS_LIMIT: 5000               # file size limit for originals in MB (increase for high-res video)
      PHOTOPRISM_HTTP_COMPRESSION: "gzip"            # improves transfer speed and bandwidth utilization (none or gzip)
      PHOTOPRISM_LOG_LEVEL: "info"                   # log level: trace, debug, info, warning, error, fatal, or panic
      PHOTOPRISM_READONLY: "false"                   # do not modify originals directory (reduced functionality)
      PHOTOPRISM_EXPERIMENTAL: "false"               # enables experimental features
      PHOTOPRISM_DISABLE_CHOWN: "false"              # disables updating storage permissions via chmod and chown on startup
      PHOTOPRISM_DISABLE_WEBDAV: "false"             # disables built-in WebDAV server
      PHOTOPRISM_DISABLE_SETTINGS: "false"           # disables settings UI and API
      PHOTOPRISM_DISABLE_TENSORFLOW: "false"         # disables all features depending on TensorFlow
      PHOTOPRISM_DISABLE_FACES: "false"              # disables face detection and recognition (requires TensorFlow)
      PHOTOPRISM_DISABLE_CLASSIFICATION: "false"     # disables image classification (requires TensorFlow)
      PHOTOPRISM_DISABLE_VECTORS: "false"            # disables vector graphics support
      PHOTOPRISM_DISABLE_RAW: "false"                # disables indexing and conversion of RAW images
      PHOTOPRISM_RAW_PRESETS: "false"                # enables applying user presets when converting RAW images (reduces performance)
      PHOTOPRISM_JPEG_QUALITY: 85                    # a higher value increases the quality and file size of JPEG images and thumbnails (25-100)
      PHOTOPRISM_DETECT_NSFW: "true"                 # automatically flags photos as private that MAY be offensive (requires TensorFlow)
      PHOTOPRISM_UPLOAD_NSFW: "true"                 # allows uploads that MAY be offensive (no effect without TensorFlow)
      PHOTOPRISM_DATABASE_DRIVER: "mysql"            # use MariaDB 10.5+ or MySQL 8+ instead of SQLite for improved performance
      PHOTOPRISM_DATABASE_SERVER: "mariadb:3306"     # MariaDB or MySQL database server (hostname:port)
      PHOTOPRISM_DATABASE_NAME: "photoprism_john2" # MariaDB or MySQL database schema name
      PHOTOPRISM_DATABASE_USER: "photoprism"         # MariaDB or MySQL database user name
      PHOTOPRISM_DATABASE_PASSWORD: "password"       # MariaDB or MySQL database user password
      PHOTOPRISM_SITE_CAPTION: "Photo Prism"
      PHOTOPRISM_SITE_DESCRIPTION: "A Privacy Preserving Photos App"                # meta site description
      PHOTOPRISM_SITE_AUTHOR: "Me"                     # meta site author
    working_dir: "/photoprism" # do not change or remove
    ## Storage Folders: "~" is a shortcut for your home directory, "." for the current directory
    volumes:
      - "/ext/data/photoprism/john2/pictures:/photoprism/originals"               # Original media files (DO NOT REMOVE)
      - "/ext/data/photoprism/john2/import:/photoprism/import"                  # *Optional* base folder from which files can be imported to originals
      - "/ext/data/photoprism/john2/storage:/photoprism/storage"                  # *Writable* storage folder for cache, database, and sidecar files (DO NOT REMOVE)

volumes:
  nextcloud_aio_mastercontainer:
    name: nextcloud_aio_mastercontainer
```

and the following `Caddyfile` in the same dir:
```
https://cloud.mydomain.com:443 {
    reverse_proxy localhost:11000
}
https://photoprism.mydomain.com:443 {
    reverse_proxy localhost:2342
}
https://photoprism2.mydomain.com:443 {
    reverse_proxy localhost:2343
}
```

Hope this helps!
