### ISSUE TITLE
Raspberry Pi 4 crashes while indexing

### ISSUE THREAD

**Issue by fl0r1s** [photoprism/photoprism#1172]
## Installation details
I followed the official installation guide [here](https://docs.photoprism.org/getting-started/raspberry-pi/). 

Hardware: RPi 4 4gb  @ 2100 MHz with active cooling
OS: Ubuntu Server 20.10 arm64
The server has all images stored on an ssd on which the OS runs. 

Running everything as services in compose. 

## Compose file
```
  photoprism:
    # Use photoprism/photoprism-arm64:preview instead for testing preview builds:
    image: photoprism/photoprism-arm64:latest
    container_name: photoprism
    # Only enable automatic restarts once your installation is properly
    # configured as it otherwise may get stuck in a restart loop:
    # https://docs.photoprism.org/getting-started/faq/#why-is-photoprism-getting-stuck-in-a-restart-loop
    restart: unless-stopped
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    ports:
      - ${PHOTOPRISM_PORT}:2342 # [local port]:[container port]
    environment:
      PHOTOPRISM_ADMIN_PASSWORD: "REDACTED"          # PLEASE CHANGE: Your initial admin password (min 4 characters)
      PHOTOPRISM_HTTP_PORT: 2342                     # Built-in Web server port
      PHOTOPRISM_HTTP_COMPRESSION: "none"            # Improves transfer speed and bandwidth utilization (none or gzip)
      PHOTOPRISM_WORKERS: 2                          # Limits the number of indexing workers to reduce system load
      PHOTOPRISM_DEBUG: "false"                      # Run in debug mode (shows additional log messages)
      PHOTOPRISM_PUBLIC: "false"                     # No authentication required (disables password protection)
      PHOTOPRISM_READONLY: "false"                   # Don't modify originals directory (reduced functionality)
      PHOTOPRISM_EXPERIMENTAL: "false"               # Enables experimental features
      PHOTOPRISM_DISABLE_WEBDAV: "false"             # Disables built-in WebDAV server
      PHOTOPRISM_DISABLE_SETTINGS: "false"           # Disables Settings in Web UI
      PHOTOPRISM_DISABLE_TENSORFLOW: "true"         # Disables using TensorFlow for image classification
      PHOTOPRISM_DARKTABLE_PRESETS: "true"           # Enables Darktable presets and disables concurrent RAW conversion
      PHOTOPRISM_FFMPEG_ENCODER: "h264_v4l2m2m"    # FFmpeg AVC encoder for video transcoding (default: libx264)
      # PHOTOPRISM_FFMPEG_BUFFERS: "64"              # FFmpeg capture buffers (default: 32)
      PHOTOPRISM_DETECT_NSFW: "false"                # Flag photos as private that MAY be offensive
      PHOTOPRISM_UPLOAD_NSFW: "true"                 # Allow uploads that MAY be offensive
      # PHOTOPRISM_DATABASE_DRIVER: "sqlite"         # SQLite is an embedded database that doesn't require a server
      PHOTOPRISM_DATABASE_DRIVER: "mysql"            # Use MariaDB (or MySQL) instead of SQLite for improved performance
      PHOTOPRISM_DATABASE_SERVER: "photoprism_db:3306"     # MariaDB database server (hostname:port)
      PHOTOPRISM_DATABASE_NAME: "photoprism"         # MariaDB database schema name
      PHOTOPRISM_DATABASE_USER: "photoprism"         # MariaDB database user name
      PHOTOPRISM_DATABASE_PASSWORD: "${PICTURES_DB_USER_PW}"       # MariaDB database user password
      PHOTOPRISM_SITE_URL: "REDACTED"  # Public PhotoPrism URL
      #PHOTOPRISM_SITE_URL: "http://localhost:2342/"  # Public PhotoPrism URL
      PHOTOPRISM_SITE_TITLE: REDACTED"
      PHOTOPRISM_SITE_CAPTION: "REDACTED"
      PHOTOPRISM_SITE_DESCRIPTION: ""
      PHOTOPRISM_SITE_AUTHOR: "REDACTED"
      PHOTOPRISM_WORKERS: 1
      # You may optionally set a user / group id using environment variables if your Docker version or NAS does not
      # support this natively (see next example):
      #UID: ${PUID}
      #GID: ${PGID}
      # UMASK: 0000
    # Uncomment and edit the following line to set a specific user / group id (native):
    user: "${PUID}:${PGID}"
    # For hardware AVC transcoding using the h264_v4l2m2m encoder:
    devices:
      - "/dev/video11:/dev/video11"
    volumes:
      # Your photo and video files ([local path]:[container path]):
      - "${SSD_MEDIA_ROOT}/photoprism:/photoprism/originals"
      - "${SSD_MEDIA_ROOT}/photoprism_import:/photoprism/import"
      # Multiple folders can be indexed by mounting them as sub-folders of /photoprism/originals:
      # - "/mnt/Family:/photoprism/originals/Family"    # [folder_1]:/photoprism/originals/[folder_1]
      # - "/mnt/Friends:/photoprism/originals/Friends"  # [folder_2]:/photoprism/originals/[folder_2]
      # Mounting an import folder is optional (see docs):
      # - "~/Import:/photoprism/import"
      # Permanent storage for settings, index & sidecar files (DON'T REMOVE):
      - "${SSD_APPDATA_ROOT}/photoprism:/photoprism/storage"
    depends_on:
      - photoprism_db

  photoprism_db:
    image: arm64v8/mariadb:10.5
    container_name: photoprism_db
    restart: unless-stopped
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    command: mysqld --transaction-isolation=READ-COMMITTED --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-connections=512 --innodb-rollback-on-timeout=OFF --innodb-lock-wait-timeout=50
    volumes: # Don't remove permanent storage for index database files!
      - "${SSD_APPDATA_ROOT}/photoprism_db:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: ${PICTURES_DB_ROOT_PW}
      MYSQL_DATABASE: photoprism
      MYSQL_USER: photoprism
      MYSQL_PASSWORD: ${PICTURES_DB_USER_PW}
```

## The Problem
The server crashes when importing larger (e.g. > 3) amounts of files. Have tried reducing the amount but manually uploading 3 files every time is tedious. Have to physically reset the server after such a crash. 

I suspect this is related to the thumbnail creation module, but is there a way to stage the thumbnail creation so that it takes longer, but doesn't crash?

## Steps I've taken to solve this
Everything on the documentation page, including: 
- Disabling TF
- Creating a swap partition (8gb) 
- set `PHOTOPRISM_WORKERS=1`
- Disable hardware decoding by commenting out `PHOTOPRISM_FFMPEG_ENCODER`

## Extra info 
Below image shows an ssh connection on the moment the server crashes. 
- Left: info messages from photoprism `docker logs -f photoprism`. 
- Middle: `swapon -s` to see swap usage. It can be observed that swap is not entirely used. 
- Right: `vcgencmd measure_temp` - a module to measure temperatures on a raspberrypi CPU. 
![sample_2](https://user-images.githubusercontent.com/50661872/113472278-6c52be80-9462-11eb-8995-84b93cfd2a55.JPG)
