### ISSUE TITLE
Problem indexing Big Files

### ISSUE THREAD

**Issue by Fersn** [photoprism/photoprism#1232]
Hi Guys,

I’m trying to set up Photoprism for my massive Photo Library (around 120.000 Pics).
I have severe issues with big JPG Files.
My Server Configuration:
•	Linux Debian machine on Hyper-V
•	RAM Dynamic up to 4096MB (But only used around 3300MB)
•	Processor Cores: 2
•	Index Store on an external drive and Pictorestore (readonly) mounted with fstab
My Docker Composer File:
```
version: '3.5'

services:
  photoprism:
    image: photoprism/photoprism:latest
loop
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    ports:
      - 2342:2342 # [local port]:[container port]
    environment:
      PHOTOPRISM_ADMIN_PASSWORD: "MyPassword"          # PLEASE CHANGE: Your initial admin password (min 4 characters)
      PHOTOPRISM_HTTP_PORT: 2342                     # Built-in Web server port
      PHOTOPRISM_HTTP_COMPRESSION: "gzip"            # Improves transfer speed and bandwidth utilization (none or gzip)
      PHOTOPRISM_DEBUG: "false"                      # Run in debug mode (shows additional log messages)
      PHOTOPRISM_PUBLIC: "false"                     # No authentication required (disables password protection)
      PHOTOPRISM_READONLY: "false"                   # Don't modify originals directory (reduced functionality)
      PHOTOPRISM_EXPERIMENTAL: "false"               # Enables experimental features
      PHOTOPRISM_DISABLE_WEBDAV: "false"             # Disables built-in WebDAV server
      PHOTOPRISM_DISABLE_SETTINGS: "false"           # Disables Settings in Web UI
      PHOTOPRISM_DISABLE_TENSORFLOW: "false"         # Disables using TensorFlow for image classification
      PHOTOPRISM_DARKTABLE_PRESETS: "false"          # Enables Darktable presets and disables concurrent RAW conversion
      PHOTOPRISM_DETECT_NSFW: "false"                # Flag photos as private that MAY be offensive (requires TensorFlow)
      PHOTOPRISM_UPLOAD_NSFW: "true"                 # Allow uploads that MAY be offensive
require a server
      PHOTOPRISM_DATABASE_DRIVER: "mysql"            # Use MariaDB (or MySQL) instead of SQLite for improved performance
      PHOTOPRISM_DATABASE_SERVER: "mariadb:3306"     # MariaDB database server (hostname:port)
      PHOTOPRISM_DATABASE_NAME: "photoprism"         # MariaDB database schema name
      PHOTOPRISM_DATABASE_USER: "photoprism"         # MariaDB database user name
      PHOTOPRISM_DATABASE_PASSWORD: "MyDBPassword#"       # MariaDB database user password
      PHOTOPRISM_SITE_URL: "http://myURL:2342/"  # Public PhotoPrism URL
      PHOTOPRISM_SITE_TITLE: "PhotoPrism"
      PHOTOPRISM_SITE_CAPTION: "Browse Your Life"
      PHOTOPRISM_SITE_DESCRIPTION: "Photoprism"
      PHOTOPRISM_SITE_AUTHOR: "Soneone"
    volumes:
      - "/mnt/photos:/photoprism/originals/photos_OG1" # My External Store for Indexing
      - "/mnt/index:/photoprism/storage" # My External Store for Indexing

  mariadb:
    image: mariadb:10.5
    restart: unless-stopped
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    command: mysqld --transaction-isolation=READ-COMMITTED --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-connections=512 --innodb-rollback-on-timeout=OFF --innodb-lock-wait-timeout=50
    volumes: # Don't remove permanent storage for index database files!
      - "./database:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: MyDBRootPassword
      MYSQL_DATABASE: photoprism
      MYSQL_USER: photoprism
      MYSQL_PASSWORD: MyDBPassword
```
At first I could not even index a Picture with 25MB.

Error Message:
```
fatal error: runtime: out of memory

runtime stack:
runtime.throw(0x1092b56, 0x16)
        /usr/local/go/src/runtime/panic.go:1117 +0x72
runtime.sysMap(0xc05c000000, 0x38000000, 0x225b130)
        /usr/local/go/src/runtime/mem_linux.go:169 +0xc6
runtime.(*mheap).sysAlloc(0x20bcb00, 0x37800000, 0x438457, 0x20bcb08)
        /usr/local/go/src/runtime/malloc.go:729 +0x1e5
runtime.(*mheap).grow(0x20bcb00, 0x1bb9d, 0x0)
        /usr/local/go/src/runtime/mheap.go:1346 +0x85
runtime.(*mheap).allocSpan(0x20bcb00, 0x1bb9d, 0x470100, 0x20bcb00)
        /usr/local/go/src/runtime/mheap.go:1173 +0x609
runtime.(*mheap).alloc.func1()
        /usr/local/go/src/runtime/mheap.go:910 +0x59
runtime.systemstack(0x7f7f20000020)
        /usr/local/go/src/runtime/asm_amd64.s:379 +0x66
runtime.mstart()
        /usr/local/go/src/runtime/proc.go:1246

goroutine 53 [running]:
runtime.systemstack_switch()
        /usr/local/go/src/runtime/asm_amd64.s:339 fp=0xc004354da0 sp=0xc004354d98 pc=0x4780e0
runtime.(*mheap).alloc(0x20bcb00, 0x1bb9d, 0x101, 0x0)
        /usr/local/go/src/runtime/mheap.go:904 +0x85 fp=0xc004354df0 sp=0xc004354da0 pc=0x434005
runtime.(*mcache).allocLarge(0x7f7f65cc5108, 0x37739800, 0xddc0101, 0x0)
        /usr/local/go/src/runtime/mcache.go:224 +0x97 fp=0xc004354e48 sp=0xc004354df0 pc=0x424677
runtime.mallocgc(0x37739800, 0xf555c0, 0x1, 0x200000003)
        /usr/local/go/src/runtime/malloc.go:1078 +0x925 fp=0xc004354ed0 sp=0xc004354e48 pc=0x41a0c5
runtime.makeslice(0xf555c0, 0x377398, 0x377398, 0x80)
        /usr/local/go/src/runtime/slice.go:98 +0x6c fp=0xc004354f00 sp=0xc004354ed0 pc=0x45b00c
image/jpeg.(*decoder).processSOS(0xc000b7e000, 0xa, 0x2, 0x80)
        /usr/local/go/src/image/jpeg/scan.go:156 +0x5dc fp=0xc004355138 sp=0xc004354f00 pc=0x60e1dc
image/jpeg.(*decoder).decode(0xc000b7e000, 0x12750c0, 0xc0043f41e0, 0x417800, 0xf71800, 0x1024920, 0x10f3400, 0x12750c0)
        /usr/local/go/src/image/jpeg/reader.go:630 +0x312 fp=0xc004355188 sp=0xc004355138 pc=0x60c612
image/jpeg.Decode(0x12750c0, 0xc0043f41e0, 0xc0043f41e0, 0x12750c0, 0xc0043f41e0, 0x2)
        /usr/local/go/src/image/jpeg/reader.go:779 +0x54 fp=0xc0043551d8 sp=0xc004355188 pc=0x60d494
image.Decode(0x12761e0, 0xc004926658, 0x0, 0xc000000000, 0xc004926658, 0x0, 0x0, 0xc004355350)
        /usr/local/go/src/image/format.go:93 +0x102 fp=0xc0043552d0 sp=0xc0043551d8 pc=0x5f9722
github.com/disintegration/imaging.Decode(0x12761e0, 0xc004926658, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1, 0xc0043678f1)
        /go/pkg/mod/github.com/disintegration/imaging@v1.6.2/io.go:61 +0x465 fp=0xc0043553a0 sp=0xc0043552d0 pc=0x7ffe65
github.com/disintegration/imaging.Open(0xc003537490, 0x65, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /go/pkg/mod/github.com/disintegration/imaging@v1.6.2/io.go:101 +0x125 fp=0xc004355410 sp=0xc0043553a0 pc=0x7fffe5
github.com/photoprism/photoprism/internal/thumb.FromFile(0xc003537490, 0x65, 0xc0043678f0, 0x28, 0xc004366390, 0x24, 0x3, 0x3, 0x1, 0xc000038f18, ...)
        /go/src/github.com/photoprism/photoprism/internal/thumb/create.go:141 +0x2e8 fp=0xc0043554f8 sp=0xc004355410 pc=0xa316e8
github.com/photoprism/photoprism/internal/photoprism.(*MediaFile).Thumbnail(0xc004273500, 0xc004366390, 0x24, 0x1073ba3, 0x6, 0xc004273500, 0xc0035374f1, 0x4, 0x7f7f65cc5f18)
        /go/src/github.com/photoprism/photoprism/internal/photoprism/mediafile.go:898 +0x205 fp=0xc004355a78 sp=0xc0043554f8 pc=0xb7bb05
github.com/photoprism/photoprism/internal/photoprism.(*MediaFile).Resample(0xc004273500, 0xc004366390, 0x24, 0x1073ba3, 0x6, 0x24, 0x0, 0x0, 0xc004366390)
        /go/src/github.com/photoprism/photoprism/internal/photoprism/mediafile.go:911 +0x57 fp=0xc004355ad0 sp=0xc004355a78 pc=0xb7bf17
github.com/photoprism/photoprism/internal/photoprism.(*MediaFile).Colors(0xc004273500, 0xc004366390, 0x24, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/photoprism/photoprism/internal/photoprism/colors.go:19 +0xb1 fp=0xc004355c40 sp=0xc004355ad0 pc=0xb59cd1
github.com/photoprism/photoprism/internal/photoprism.(*Index).MediaFile(0xc000c17920, 0xc004273500, 0x0, 0x0, 0x2010100, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/photoprism/photoprism/internal/photoprism/index_mediafile.go:294 +0x1465 fp=0xc00435d5b0 sp=0xc004355c40 pc=0xb683c5
github.com/photoprism/photoprism/internal/photoprism.IndexMain(0xc00430de70, 0xc000c17920, 0x0, 0x0, 0x10100, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/photoprism/photoprism/internal/photoprism/index_related.go:58 +0x14e fp=0xc00435d888 sp=0xc00435d5b0 pc=0xb721ae
github.com/photoprism/photoprism/internal/photoprism.IndexRelated(0xc00426a230, 0x2, 0x2, 0xc004273500, 0xc000c17920, 0x0, 0x0, 0x10100, 0x0, 0x0, ...)
        /go/src/github.com/photoprism/photoprism/internal/photoprism/index_related.go:77 +0x12a fp=0xc00435de70 sp=0xc00435d888 pc=0xb7334a
github.com/photoprism/photoprism/internal/photoprism.IndexWorker(0xc000478b40)
        /go/src/github.com/photoprism/photoprism/internal/photoprism/index_worker.go:12 +0x127 fp=0xc00435dfb0 sp=0xc00435de70 pc=0xb74867
github.com/photoprism/photoprism/internal/photoprism.(*Index).Start.func2(0xc000478b40, 0xc000824b54)
        /go/src/github.com/photoprism/photoprism/internal/photoprism/index.go:98 +0x2b fp=0xc00435dfd0 sp=0xc00435dfb0 pc=0xb861ab
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1371 +0x1 fp=0xc00435dfd8 sp=0xc00435dfd0 pc=0x479f21
created by github.com/photoprism/photoprism/internal/photoprism.(*Index).Start
        /go/src/github.com/photoprism/photoprism/internal/photoprism/index.go:97 +0x265

goroutine 1 [chan send]:
github.com/photoprism/photoprism/internal/photoprism.(*Index).Start.func5(0xc0039070a0, 0x68, 0xc004403cb0, 0x45b00c, 0x68)
        /go/src/github.com/photoprism/photoprism/internal/photoprism/index.go:208 +0xd0f
github.com/karrick/godirwalk.walk(0xc0039070a0, 0x68, 0xc004403cb0, 0xc003987620, 0x68, 0x0)
        /go/pkg/mod/github.com/karrick/godirwalk@v1.16.1/walk.go:277 +0x69
github.com/karrick/godirwalk.walk(0xc002886840, 0x57, 0xc004282450, 0xc003987620, 0x57, 0x0)
        /go/pkg/mod/github.com/karrick/godirwalk@v1.16.1/walk.go:338 +0x4bb
github.com/karrick/godirwalk.walk(0xc004213b80, 0x4d, 0xc0040d5a70, 0xc003987620, 0x4d, 0x0)
        /go/pkg/mod/github.com/karrick/godirwalk@v1.16.1/walk.go:338 +0x4bb
github.com/karrick/godirwalk.walk(0xc0040a59a0, 0x47, 0xc0040ae7e0, 0xc003987620, 0x47, 0xc00389d6c0)
        /go/pkg/mod/github.com/karrick/godirwalk@v1.16.1/walk.go:338 +0x4bb
github.com/karrick/godirwalk.walk(0xc003e348c0, 0x42, 0xc004000300, 0xc003987620, 0x42, 0x0)
        /go/pkg/mod/github.com/karrick/godirwalk@v1.16.1/walk.go:338 +0x4bb
github.com/karrick/godirwalk.walk(0xc002ee3c80, 0x3e, 0xc001b89500, 0xc003987620, 0x3e, 0x0)
        /go/pkg/mod/github.com/karrick/godirwalk@v1.16.1/walk.go:338 +0x4bb
github.com/karrick/godirwalk.walk(0xc002ae6990, 0x25, 0xc0033986c0, 0xc003987620, 0x25, 0x0)
        /go/pkg/mod/github.com/karrick/godirwalk@v1.16.1/walk.go:338 +0x4bb
github.com/karrick/godirwalk.walk(0xc0004a6000, 0x20, 0xc003fde030, 0xc003987620, 0x20, 0xc003fe0020)
        /go/pkg/mod/github.com/karrick/godirwalk@v1.16.1/walk.go:338 +0x4bb
github.com/karrick/godirwalk.walk(0xc000c26138, 0x15, 0xc001cf9e60, 0xc003987620, 0x0, 0x0)
        /go/pkg/mod/github.com/karrick/godirwalk@v1.16.1/walk.go:338 +0x4bb
github.com/karrick/godirwalk.Walk(0xc000c26138, 0x15, 0xc003987620, 0x9, 0xc0039875a8)
        /go/pkg/mod/github.com/karrick/godirwalk@v1.16.1/walk.go:258 +0x246
github.com/photoprism/photoprism/internal/photoprism.(*Index).Start(0xc000c17920, 0x0, 0x0, 0x10100, 0x0)
        /go/src/github.com/photoprism/photoprism/internal/photoprism/index.go:120 +0x616
github.com/photoprism/photoprism/internal/commands.indexAction(0xc0004382c0, 0x0, 0x0)
        /go/src/github.com/photoprism/photoprism/internal/commands/index.go:73 +0x326
github.com/urfave/cli.HandleAction(0xf28400, 0x10f1a30, 0xc0004382c0, 0xc0004382c0, 0x0)
        /go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:524 +0x105
github.com/urfave/cli.Command.Run(0x10715e8, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0x10a5339, 0x27, 0x0, ...)
        /go/pkg/mod/github.com/urfave/cli@v1.22.5/command.go:173 +0x579
github.com/urfave/cli.(*App).Run(0xc000442000, 0xc000032060, 0x2, 0x2, 0x0, 0x0)
        /go/pkg/mod/github.com/urfave/cli@v1.22.5/app.go:277 +0x808
main.main()
        /go/src/github.com/photoprism/photoprism/cmd/photoprism/photoprism.go:75 +0x629

goroutine 6 [select]:
github.com/patrickmn/go-cache.(*janitor).Run(0xc00038d280, 0xc000394b00)
        /go/pkg/mod/github.com/patrickmn/go-cache@v2.1.0+incompatible/cache.go:1079 +0xa9
created by github.com/patrickmn/go-cache.runJanitor
        /go/pkg/mod/github.com/patrickmn/go-cache@v2.1.0+incompatible/cache.go:1099 +0xa9

goroutine 7 [select]:
github.com/melihmucuk/geocache.NewCache.func1(0xc00039e000, 0xc000394b40)
        /go/pkg/mod/github.com/melihmucuk/geocache@v0.0.0-20160621165317-521b336a001c/cache.go:82 +0x8a
created by github.com/melihmucuk/geocache.NewCache
        /go/pkg/mod/github.com/melihmucuk/geocache@v0.0.0-20160621165317-521b336a001c/cache.go:80 +0xf3

goroutine 34 [select]:
github.com/patrickmn/go-cache.(*janitor).Run(0xc00038c000, 0xc001ed95c0)
        /go/pkg/mod/github.com/patrickmn/go-cache@v2.1.0+incompatible/cache.go:1079 +0xa9
created by github.com/patrickmn/go-cache.runJanitor
        /go/pkg/mod/github.com/patrickmn/go-cache@v2.1.0+incompatible/cache.go:1099 +0xa9

goroutine 35 [select]:
github.com/patrickmn/go-cache.(*janitor).Run(0xc00038c010, 0xc001ed9600)
        /go/pkg/mod/github.com/patrickmn/go-cache@v2.1.0+incompatible/cache.go:1079 +0xa9
created by github.com/patrickmn/go-cache.runJanitor
        /go/pkg/mod/github.com/patrickmn/go-cache@v2.1.0+incompatible/cache.go:1099 +0xa9

goroutine 36 [select]:
github.com/patrickmn/go-cache.(*janitor).Run(0xc00038c030, 0xc001ed9700)
        /go/pkg/mod/github.com/patrickmn/go-cache@v2.1.0+incompatible/cache.go:1079 +0xa9
created by github.com/patrickmn/go-cache.runJanitor
        /go/pkg/mod/github.com/patrickmn/go-cache@v2.1.0+incompatible/cache.go:1099 +0xa9

goroutine 25 [chan receive]:
github.com/photoprism/photoprism/internal/config.(*Config).initHub.func1(0xc00007da40, 0xc00007d900)
        /go/src/github.com/photoprism/photoprism/internal/config/config.go:454 +0x37
created by github.com/photoprism/photoprism/internal/config.(*Config).initHub
        /go/src/github.com/photoprism/photoprism/internal/config/config.go:451 +0x1a6

goroutine 31 [select]:
database/sql.(*DB).connectionOpener(0xc00054ea90, 0x1289398, 0xc000427e80)
        /usr/local/go/src/database/sql/sql.go:1133 +0xb5
created by database/sql.OpenDB
        /usr/local/go/src/database/sql/sql.go:740 +0x12a

goroutine 66 [select]:
github.com/go-sql-driver/mysql.(*mysqlConn).startWatcher.func1(0xc00010c7e0, 0xc000468b40, 0xc0000dc060)
        /go/pkg/mod/github.com/go-sql-driver/mysql@v1.5.0/connection.go:621 +0xa5
created by github.com/go-sql-driver/mysql.(*mysqlConn).startWatcher
        /go/pkg/mod/github.com/go-sql-driver/mysql@v1.5.0/connection.go:618 +0xbe

goroutine 51 [select]:
database/sql.(*DB).connectionCleaner(0xc00054ea90, 0x8bb2c97000)
        /usr/local/go/src/database/sql/sql.go:1005 +0x114
created by database/sql.(*DB).startCleanerLocked
        /usr/local/go/src/database/sql/sql.go:992 +0xb7

goroutine 52 [chan receive]:
github.com/photoprism/photoprism/internal/entity.SaveErrorMessages()
        /go/src/github.com/photoprism/photoprism/internal/entity/error.go:28 +0x1c5
created by github.com/photoprism/photoprism/internal/config.(*Config).InitDb
        /go/src/github.com/photoprism/photoprism/internal/config/db.go:230 +0x8c

goroutine 324 [select]:
github.com/go-sql-driver/mysql.(*mysqlConn).startWatcher.func1(0xc003ac68a0, 0xc003ade360, 0xc0025125a0)
        /go/pkg/mod/github.com/go-sql-driver/mysql@v1.5.0/connection.go:621 +0xa5
created by github.com/go-sql-driver/mysql.(*mysqlConn).startWatcher
        /go/pkg/mod/github.com/go-sql-driver/mysql@v1.5.0/connection.go:618 +0xbe
```
Due to Github Posts I disabled “Tensorflow” and this particular image could be indexed.
`PHOTOPRISM_DISABLE_TENSORFLOW: "true"`
The next time it crashed, it was a quite big Panorama with 150MB, so I renamed this big one and thought everything would be OK, but the next File was not that big. It had only 25MB and I had no chance of fixing the indexproblem this time.

Can anyone help me tweak my settings, that I can index my whole library?

Thank you very much.

Yours Fersn
