### ISSUE TITLE
Photoprism fails with "illegal instruction"

### ISSUE THREAD

**Issue by vi-n** [photoprism/photoprism#128]
I try to setup Photoprism in Docker, and when running it the only output I get is:

> photoprism_1        | Illegal instruction (core dumped)

The docker-compose snippet that I use for Photoprism:
```
    photoprism:
        image: photoprism/photoprism
        volumes:
            - /mnt/nas/pictures/2019/JPG/:/home/photoprism/Pictures/Originals/:ro
        labels:
            - "traefik.enable=true"
            - "traefik.port=2342"
            - "traefik.frontend.rule=Host:pics.hostname"
            - "traefik.docker.network=my_gateway"
        networks:
            - gateway
```

This is running on a 64 bit linux install, what am I missing.

Unrelated: is there an IRC/Matrix room with users?

**Comment by scottjl** [comment]
Same issue here, using latest container. My docker-compose.yml:

```
version: '3.6'

volumes:
    photoprism_db:
        driver: local
        name: photoprism_db
    photoprism_cache:
        driver: local
        name: photoprism_cache

services:
    photoprism:
        container_name: photoprism
        restart: unless-stopped
        volumes:
            - '/media/photos:/home/photoprism/Pictures/Originals:ro'
            - 'photoprism_cache:/home/photoprism/.cache/photoprism'
            - 'photoprism_db:/home/photoprism/.local/share/photoprism/resources/database'
        ports:
            - '2342:2342'
        image: photoprism/photoprism
```
