### ISSUE TITLE
PhotoPrism Container Crashing

### ISSUE THREAD

**Issue by jackbrown1993** [photoprism/photoprism#1390]
Container been fine for past few weeks but has now started to crash at random times.

Docker logs showing

`/entrypoint.sh: line 43:    17 Killed                  gosu "${UID}:${GID}" "$@"`

Set workers to 6 on 8 core CPU. Server has 64GB RAM and SWAP configured.

**Comment by lastzero** [comment]
Seems there's an issue with the user ID. You've set it via environment variables?

**Comment by lastzero** [comment]
Is this the only log line? Maybe running out of disk space?

**Comment by jackbrown1993** [comment]
Here is my Docker-compose snippet for PhotoPrism, I have recently added the 'restart: unless-stopped' due to this issue keep crashing the container, at least this way it restarts.

```
  photoprism:
    # Use photoprism/photoprism:preview instead for testing preview builds:
    image: photoprism/photoprism:latest
    container_name: photoprism
    hostname: acorns-photoprism
    # Only enable automatic restarts once your installation is properly
    # configured as it otherwise may get stuck in a restart loop:
    # https://docs.photoprism.org/getting-started/faq/#why-is-photoprism-getting-stuck-in-a-restart-loop
    restart: unless-stopped
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    environment:
      PHOTOPRISM_ADMIN_PASSWORD: "<removed>"          # PLEASE CHANGE: Your initial admin password (min 4 characters)
      PHOTOPRISM_ORIGINALS_LIMIT: 3000               # File size limit for originals in MB (increase for high-res video)
      PHOTOPRISM_HTTP_COMPRESSION: "gzip"            # Improves transfer speed and bandwidth utilization (none or gzip)
      PHOTOPRISM_DEBUG: "true"                      # Run in debug mode (shows additional log messages)
      PHOTOPRISM_PUBLIC: "false"                     # No authentication required (disables password protection)
      PHOTOPRISM_READONLY: "false"                   # Don't modify originals directory (reduced functionality)
      PHOTOPRISM_EXPERIMENTAL: "false"               # Enables experimental features
      PHOTOPRISM_DISABLE_WEBDAV: "false"             # Disables built-in WebDAV server
      PHOTOPRISM_DISABLE_SETTINGS: "false"           # Disables Settings in Web UI
      PHOTOPRISM_DISABLE_TENSORFLOW: "false"         # Disables using TensorFlow for image classification
      PHOTOPRISM_DARKTABLE_PRESETS: "false"          # Enables Darktable presets and disables concurrent RAW conversion
      PHOTOPRISM_DETECT_NSFW: "true"                # Flag photos as private that MAY be offensive (requires TensorFlow)
      PHOTOPRISM_UPLOAD_NSFW: "true"                 # Allow uploads that MAY be offensive
      PHOTOPRISM_DATABASE_DRIVER: "mysql"            # Use MariaDB (or MySQL) instead of SQLite for improved performance
      PHOTOPRISM_DATABASE_SERVER: "photoprism_mariadb:3306"     # MariaDB database server (hostname:port)
      PHOTOPRISM_DATABASE_NAME: "photoprism"         # MariaDB database schema name
      PHOTOPRISM_DATABASE_USER: "photoprism"         # MariaDB database user name
      PHOTOPRISM_DATABASE_PASSWORD: "<removed>"       # MariaDB database user password
      PHOTOPRISM_SITE_URL: "http://localhost:2342/"  # Public PhotoPrism URL
      PHOTOPRISM_SITE_TITLE: "Brown PhotoPrism"
      PHOTOPRISM_SITE_CAPTION: "Browse Your Life"
      PHOTOPRISM_SITE_DESCRIPTION: ""
      PHOTOPRISM_SITE_AUTHOR: "Jack Brown"
      PHOTOPRISM_ORIGINALS_PATH: "/nas/photoprism/originals"
      PHOTOPRISM_IMPORT_PATH: "/nas/photoprism/import"
      PHOTOPRISM_WORKERS: 4
      # You may optionally set a user / group id using environment variables if your Docker version or NAS does not
      # support this natively (see next example):
      UID: 1000
      GID: 1000
      # UMASK: 0000
    # Uncomment and edit the following line to set a specific user / group id (native):
    #user: "1000:1000"
    volumes:
      # Your photo and video files ([local path]:[container path]):
      - /mnt/NAS/photoprism:/nas/photoprism
      # Multiple folders can be indexed by mounting them as sub-folders of /photoprism/originals:
      # - "/mnt/Family:/photoprism/originals/Family"    # [folder_1]:/photoprism/originals/[folder_1]
      # - "/mnt/Friends:/photoprism/originals/Friends"  # [folder_2]:/photoprism/originals/[folder_2]
      # Permanent storage for settings, index & sidecar files (DON'T REMOVE):
      - /home/jack/docker_data/photoprism/app:/photoprism/storage
      - /mnt/NAS/Backups/photoprism:/nas_backups
    labels:
      - traefik.enable=true
      - traefik.http.routers.photoprism.rule=Host(`<removed>`)
      - traefik.http.services.photoprism.loadbalancer.server.port=2342
      - traefik.http.routers.photoprism.entrypoints=websecure
      - traefik.http.routers.photoprism.tls.certresolver=letsEncrypt
```
Disk space looks ok:

```
jack@docker:~$ df -h
Filesystem                         Size  Used Avail Use% Mounted on
udev                                32G     0   32G   0% /dev
tmpfs                              6.3G  2.2M  6.3G   1% /run
/dev/mapper/ubuntu--vg-ubuntu--lv  245G  175G   60G  75% /
tmpfs                               32G     0   32G   0% /dev/shm
tmpfs                              5.0M     0  5.0M   0% /run/lock
tmpfs                               32G     0   32G   0% /sys/fs/cgroup
/dev/sda2                          976M  203M  707M  23% /boot
/dev/loop1                          56M   56M     0 100% /snap/core18/2066
/dev/loop3                          68M   68M     0 100% /snap/lxd/20326
/dev/loop2                          70M   70M     0 100% /snap/lxd/19188
/dev/loop4                          33M   33M     0 100% /snap/snapd/12057
/dev/loop5                          33M   33M     0 100% /snap/snapd/12159
vault.brown1993.com:/Data           55T   14T   41T  26% /mnt/NAS

```
