### ISSUE TITLE
Can't get HTTPS working

### ISSUE THREAD

**Issue by pierosavi** [photoprism/photoprism#1599]
Hi all, I can't get the correct certificate to show up, I always get TRAEFIK DEFAULT CERT.

I've tried many times restarting the machine and resetting docker compose.
I think something in my config files is broken but I can't figure out what

Secret things below are hidden + removed mariadb, ofelia ecc

docker-compose.yaml
``` yaml
version: '3.5'

services:
  photoprism:
    restart: always
    image: photoprism/photoprism:latest
    container_name: photoprism
    depends_on:
      - mariadb
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    user: "1000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.photoprism.loadbalancer.server.port=2342"
      - "traefik.http.routers.photoprism.tls=true"
      - "traefik.http.routers.photoprism.entrypoints=websecure"
      - "traefik.http.routers.photoprism.rule=Host(`redacted`)"
      - "traefik.http.routers.photoprism.tls.certresolver=myresolver"
    environment:
      PHOTOPRISM_SITE_URL: "https://redacted/"
...rest of photoprism config...

  traefik:
    restart: always
    image: traefik:v2.4
    container_name: traefik
    ports:
      - "80:80"
      - "443:443"
    expose:
      - "80"
      - "443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./traefik/:/data/"
      - "./traefik.yaml:/etc/traefik/traefik.yaml"
```

traefik.yaml

``` yaml
serversTransport:
  insecureSkipVerify: true

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"

certificatesResolvers:
  myresolver:
    acme:
      email: redacted
      storage: /data/letsencrypt.json
      httpChallenge:
        entryPoint: web

serversTransport:
  insecureSkipVerify: true

providers:
  docker:
    exposedByDefault: false
    watch: true

api:
  insecure: false
  dashboard: false
```

traefik/letsencrypt.json states `"status": "valid"` but `"Certificates": null`, I don't know if it's as expected

Thanks
