### ISSUE TITLE
Thumbnails not loading sometimes

### ISSUE THREAD

**Issue by gogo199432** [photoprism/photoprism#1647]
Hey, so I have Photoprism with a relatively big collection of around 24k images. It doesn't matter which subcollection I view, there are always thumbnails that don't load, just display a gray box. 

Firefox console has the following error msg:
```
[Vuetify] Image load failed

src: /api/v1/t/25bd25a6ceefafe28addb08cf83139c2cc2384bf/public/tile_500

found in

---> <VImg>
       <VCard>
         <PPhotoCards>
           <PPagePhotos>
             <VContent>
               <VApp>
                 <Photoprism>
                   <Root>    
```

I have the following docker compose:
```
photoprism:
    image: photoprism/photoprism
    container_name: photoprism
    restart: unless-stopped
    user: "1000:1000"
    networks:
      - proxy
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    volumes:
      - ${FAMILY}/Pictures:/photoprism/originals/oldFamilyPhotos
      - ${CONFIG}/photoprism:/photoprism/storage
    shm_size: "2gb"
    environment:
      HOME: "/photoprism"
      PHOTOPRISM_SITE_URL: "https://photo.example.com/"
      PHOTOPRISM_SITE_TITLE: "PhotoPrism"
      PHOTOPRISM_SITE_CAPTION: "Browse Your Life"
      PHOTOPRISM_SITE_DESCRIPTION: "Open-Source Photo Management"
      PHOTOPRISM_SITE_AUTHOR: "@photoprism_app"
      PHOTOPRISM_READONLY: "false"
      PHOTOPRISM_DEBUG: "false"
      PHOTOPRISM_EXPERIMENTAL: "true"
      PHOTOPRISM_PUBLIC: "true"
      PHOTOPRISM_HTTP_HOST: "0.0.0.0"
      PHOTOPRISM_HTTP_PORT: 2342
      PHOTOPRISM_HTTP_COMPRESSION: "gzip"     # Improves transfer speed and bandwidth utilization (none or gzip)
      PHOTOPRISM_DATABASE_DRIVER: "sqlite"
      PHOTOPRISM_ADMIN_PASSWORD: "somepassword" # The initial admin password (min 4 characters)
      PHOTOPRISM_DISABLE_BACKUPS: "false"     # Don't backup photo and album metadata to YAML files
      PHOTOPRISM_DISABLE_WEBDAV: "false"      # Disables built-in WebDAV server
      PHOTOPRISM_DISABLE_SETTINGS: "false"    # Disables Settings in Web UI
      PHOTOPRISM_DISABLE_PLACES: "false"      # Disables reverse geocoding and maps
      PHOTOPRISM_DISABLE_EXIFTOOL: "false"    # Don't create ExifTool JSON files for improved metadata extraction
      PHOTOPRISM_DISABLE_TENSORFLOW: "false"  # Don't use TensorFlow for image classification
      PHOTOPRISM_DETECT_NSFW: "false"         # Flag photos as private that MAY be offensive (requires TensorFlow)
      PHOTOPRISM_UPLOAD_NSFW: "false"         # Allow uploads that may be offensive
      PHOTOPRISM_DARKTABLE_PRESETS: "false"   # Enables Darktable presets and disables concurrent RAW conversion
      PHOTOPRISM_THUMB_FILTER: "lanczos"      # Resample filter, best to worst: blackman, lanczos, cubic, linear
      PHOTOPRISM_THUMB_UNCACHED: "false"       # Enables on-demand thumbnail rendering (high memory and cpu usage)
      PHOTOPRISM_THUMB_SIZE: 720              # Pre-rendered thumbnail size limit (default 2048, min 720, max 7680)
      # PHOTOPRISM_THUMB_SIZE: 4096           # Retina 4K, DCI 4K (requires more storage); 7680 for 8K Ultra HD
      PHOTOPRISM_THUMB_SIZE_UNCACHED: 7680    # On-demand rendering size limit (default 7680, min 720, max 7680)
      PHOTOPRISM_JPEG_SIZE: 720               # Size limit for converted image files in pixels (720-30000)
      PHOTOPRISM_JPEG_QUALITY: 80             # Set to 95 for high-quality thumbnails (25-100)
      TF_CPP_MIN_LOG_LEVEL: 0                 # Show TensorFlow log messages for development
```

Photoprism version: 211018-e200f322-Linux-x86_64
The storage is on VM-local SSD, the images on HDD
