### ISSUE TITLE
Photoprism does not connect to MariaDB database

### ISSUE THREAD

**Issue by Gilibenzio** [photoprism/photoprism#1650]
Hi.
I'm having major problems installing Photoprism on my server.
Server specifications:
```
system             OptiPlex 7040 (06B9)
processor          Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz
memory             8GiB DIMM DDR4 Synchronous 2133 MHz
operating system   Debian 11
kernel             5.10.0-9-amd64
```

This is my docker-compose.yaml file:

```
version: '3.5'

networks:
  frontend:
    external: true
  backend: 
    external: true

services:
  photoprism:
    # Use photoprism/photoprism:preview instead for testing preview builds:
    image: photoprism/photoprism:latest
    container_name: photoprism
    depends_on:
      - mariadb
    # Only enable automatic restarts once your installation is properly
    # configured as it otherwise may get stuck in a restart loop:
    # https://docs.photoprism.org/getting-started/faq/#why-is-photoprism-getting-stuck-in-a-restart-loop
    # restart: unless-stopped
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    # Run as a specific, non-root user (see https://docs.docker.com/engine/reference/run/#user):
    # user: "1000:1000"
    ports:
      - 500:2342 # [server]:[container]
    environment:
      PHOTOPRISM_ADMIN_PASSWORD: "mysecurepassword"      # PLEASE CHANGE: Your initial admin password (min 4 characters)
      PHOTOPRISM_ORIGINALS_LIMIT: 50000                  # File size limit for originals in MB (increase for high-res video)
      PHOTOPRISM_HTTP_COMPRESSION: "gzip"                # Improves transfer speed and bandwidth utilization (none or gzip)
      PHOTOPRISM_DEBUG: "true"                           # Run in debug mode (shows additional log messages)
      PHOTOPRISM_LOG_LEVEL: "error"
      PHOTOPRISM_PUBLIC: "false"                         # No authentication required (disables password protection)
      PHOTOPRISM_READONLY: "false"                       # Don't modify originals directory (reduced functionality)
      PHOTOPRISM_EXPERIMENTAL: "false"                   # Enables experimental features
      PHOTOPRISM_DISABLE_CHOWN: "false"                  # Disables storage permission updates on startup
      PHOTOPRISM_DISABLE_WEBDAV: "false"                 # Disables built-in WebDAV server
      PHOTOPRISM_DISABLE_SETTINGS: "false"               # Disables Settings in Web UI
      PHOTOPRISM_DISABLE_TENSORFLOW: "false"             # Disables all features depending on TensorFlow
      PHOTOPRISM_DISABLE_FACES: "false"                  # Disables facial recognition
      PHOTOPRISM_DISABLE_CLASSIFICATION: "false"         # Disables image classification
      PHOTOPRISM_DARKTABLE_PRESETS: "false"              # Enables Darktable presets and disables concurrent RAW conversion
      PHOTOPRISM_DETECT_NSFW: "false"                    # Flag photos as private that MAY be offensive (requires TensorFlow)
      PHOTOPRISM_UPLOAD_NSFW: "true"                     # Allow uploads that MAY be offensive
      # PHOTOPRISM_DATABASE_DRIVER: "sqlite"             # SQLite is an embedded database that doesn't require a server
      PHOTOPRISM_DATABASE_DRIVER: "mysql"                # Use MariaDB (or MySQL) instead of SQLite for improved performance
      PHOTOPRISM_DATABASE_SERVER: "mariadb:3306"         # MariaDB database server (hostname:port)
      PHOTOPRISM_DATABASE_NAME: "photoprism"             # MariaDB database schema name
      PHOTOPRISM_DATABASE_USER: "photoprism"             # MariaDB database user name
      PHOTOPRISM_DATABASE_PASSWORD: "samedbpassword"     # MariaDB database user password
      # PHOTOPRISM_SITE_URL: "removed"                   # Public PhotoPrism URL
      PHOTOPRISM_SITE_TITLE: "PhotoPrism"
      PHOTOPRISM_SITE_CAPTION: "Galleria della Famiglia"
      PHOTOPRISM_SITE_DESCRIPTION: ""
      PHOTOPRISM_SITE_AUTHOR: "Me"
      # Set a non-root user, group, or custom umask if your Docker environment doesn't support this natively:
      PHOTOPRISM_UID: 1000
      PHOTOPRISM_GID: 1000
      # PHOTOPRISM_UMASK: 0000
      # Enable TensorFlow AVX2 support for modern Intel CPUs (requires starting the container as root):
      PHOTOPRISM_INIT: "tensorflow-amd64-avx2"
      # Hardware video transcoding options:
      # PHOTOPRISM_FFMPEG_BUFFERS: "64"              # FFmpeg capture buffers (default: 32)
      # PHOTOPRISM_FFMPEG_BITRATE: "32"              # FFmpeg encoding bitrate limit in Mbit/s (default: 50)
      # PHOTOPRISM_FFMPEG_ENCODER: "h264_v4l2m2m"    # Use Video4Linux for AVC transcoding (default: libx264)
      PHOTOPRISM_FFMPEG_ENCODER: "h264_qsv"          # Use Intel Quick Sync Video for AVC transcoding (default: libx264)
      PHOTOPRISM_INIT: "intel-graphics tensorflow-amd64-avx2" # Enable TensorFlow AVX2 & Intel Graphics support
      HOME: "/photoprism"
    # Optional hardware devices for video transcoding and machine learning:
    devices:
    #  - "/dev/video11:/dev/video11" # Video4Linux (h264_v4l2m2m)
       - "/dev/dri/renderD128:/dev/dri/renderD128" # Intel GPU
       - "/dev/dri/card0:/dev/dri/card0"
    working_dir: "/mnt/storage/FOTO/photoprism"
    volumes:
      # The *originals* folder contains your original photo and video files (- "[host folder]:/photoprism/originals"):
      - "/mnt/storage/FOTO:/photoprism/originals"
      # Multiple folders can be made accessible by mounting them as subfolders of /photoprism/originals:
      # - "/mnt/Family:/photoprism/originals/Family"    # [folder 1]:/photoprism/originals/[folder 1]
      # - "/mnt/Friends:/photoprism/originals/Friends"  # [folder 2]:/photoprism/originals/[folder 2]
      # You may mount an *import* folder from which files can be transferred to *originals* (optional):
      # - "~/Import:/photoprism/import"
      # Cache, session, thumbnail, and sidecar files will be created in the *storage* folder (never remove):
      - "./storage:/photoprism/storage"
    networks:
      - frontend

  mariadb:
    restart: unless-stopped
    image: mariadb:10.5
    container_name: photoprism_mariadb
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    command: mysqld --transaction-isolation=READ-COMMITTED --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-connections=512 --innodb-rollback-on-timeout=OFF --innodb-lock-wait-timeout=120
    volumes:
      - "./database:/var/lib/mysql" # Never remove
    environment:
      MYSQL_ROOT_PASSWORD: "samedbpassword"
      MYSQL_DATABASE: photoprism
      MYSQL_USER: photoprism
      MYSQL_PASSWORD: "samedbpassword"
    networks:
      - backend

```

The photoprism docker container doesn't stay active: after starting both containers (photoprism and photoprism_mariadb) with `sudo docker-compose up -d`, the first one exits after about a minute. The web page located at `http://my.server.ip.address:500` isn't even up. 
I runned `sudo docker-compose up` and before exiting the container gives this message:
`time="2021-10-22T07:43:51Z" level=fatal msg="can't create /photoprism/storage/sidecar: please check configuration and permissions"`.
I created that folder manually but it returned the same error as above for the folder `/photoprism/storage/cache`: 
`time="2021-10-22T08:05:45Z" level=fatal msg="can't create /photoprism/storage/cache: please check configuration and permissions"`.
So I changed the permissions of the '/storage' folder:
`# chmod 777 storage/`.

Running the container again gave this error:
`photoprism | time="2021-10-22T08:11:35Z" level=fatal msg="dial tcp: lookup mariadb on 127.0.0.11:53: no such host"`
I saw that the database was not present, so I tried to create the database by myself following this guide: https://docs.photoprism.org/getting-started/advanced/databases/, but the container still exits after one minute, even if this time the database exists. It's like that the container doesn't see the database. 
How can I fix this problem? 

Thank you very much!
