### ISSUE TITLE
Setup: Add installation instructions for Portainer

### ISSUE THREAD

**Issue by brink668** [photoprism/photoprism#1696]
When I use the directions for the portainer/synology docker install the MariaDB gets created but the PhotoPrism app does not get created and there is no error.

Are these directions still accurate? Or maybe the docker-compose file is out of date.
https://docs.photoprism.org/getting-started/portainer/synology/

If you could provide an example of your Synology based Portainer compose files with the paths that may help as well.

**Comment by lastzero** [comment]
Maybe needs updating. Sadly, we don't have a device for testing. From what I know, Portrainer now supports Docker Compose v3 config files. So you should be able to use our regular examples and not the special version in the howto.

**Comment by brink668** [comment]
Hey thanks for responding, that actually helped me figure out my issue :) .  The directions are pretty much spot on but the confusing part was some of wording around what should be changed in the docker config file.  I will spend some more time in the app and if everything goes well I will help update your docs on github.

**Comment by lastzero** [comment]
Excellent, thank you! 🥇

**Comment by catchdave** [comment]
I had a lots of issues trying to get photoprism running on **Synology** with non-root users, the below docker-compose ended up working for me (specifically **portainer** stack):

```
version: '2'

services:
  photoprism:
    image: photoprism/photoprism:latest
    container_name: photoprism_app_1
    user: ${UID}:${GID}
    depends_on:
      - prism_mariadb
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    ports:
      - "2342:2342"
    environment:
      PHOTOPRISM_DATABASE_DRIVER: "mysql"
      PHOTOPRISM_DATABASE_SERVER: "photoprism_mariadb_1:3306"
      PHOTOPRISM_DATABASE_NAME: "photoprism"
      PHOTOPRISM_DATABASE_USER: "photoprism"
      PHOTOPRISM_DATABASE_PASSWORD: "${mysql_password}"
      PHOTOPRISM_ADMIN_PASSWORD: “${prism_password}"
      PHOTOPRISM_SITE_URL: "https://photos.example.com/“  # public server URL incl http:// or https:// and /path, :port is optional
      PHOTOPRISM_ORIGINALS_LIMIT: 5000               # file size limit for originals in MB (increase for high-res video)
      PHOTOPRISM_HTTP_COMPRESSION: "gzip"            # improves transfer speed and bandwidth utilization (none or gzip)
      PHOTOPRISM_DEBUG: "true"                      # run in debug mode (shows additional log messages)
      PHOTOPRISM_PUBLIC: "true"                      # no authentication required (disables password protection)
      PHOTOPRISM_READONLY: "true"                   # don't modify originals directory (reduced functionality)
      PHOTOPRISM_EXPERIMENTAL: "false"               # enables experimental features
      PHOTOPRISM_DISABLE_CHOWN: "true"              # disables storage permission updates on startup
      PHOTOPRISM_DISABLE_WEBDAV: "false"             # disables built-in WebDAV server
      PHOTOPRISM_DISABLE_SETTINGS: "false"           # disables Settings in Web UI
      PHOTOPRISM_DISABLE_TENSORFLOW: "false"         # disables all features depending on TensorFlow
      PHOTOPRISM_DISABLE_FACES: "false"              # disables facial recognition
      PHOTOPRISM_DISABLE_CLASSIFICATION: "false"     # disables image classification
      PHOTOPRISM_DARKTABLE_PRESETS: "false"          # enables Darktable presets and disables concurrent RAW conversion
      PHOTOPRISM_DETECT_NSFW: "false"                # flag photos as private that MAY be offensive (requires TensorFlow)
      PHOTOPRISM_UPLOAD_NSFW: "true"                 # allows uploads that MAY be offensive
      PHOTOPRISM_SITE_TITLE: "PhotoPrism"
      PHOTOPRISM_SITE_CAPTION: "AI-Powered Photos App"
      HOME: "/photoprism"
      PHOTOPRISM_SIDECAR_PATH: "/photoprism/sidecar"
      PHOTOPRISM_CACHE_PATH: "/photoprism/cache"
      PHOTOPRISM_ORIGINALS_PATH: "/photoprism/originals"
      PHOTOPRISM_BACKUP_PATH: "/photoprism/backup"
      ## Run/install on first startup (options: update, gpu, tensorflow, davfs, nano, clean):
      #PHOTOPRISM_INIT: "gpu tensorflow"
    volumes:
      - /etc/passwd:/etc/passwd:ro  # Specific prism user from host system
      - /etc/localtime:/etc/localtime:ro
      - /volume1/photos:/photoprism/originals
      - /volume1/docker/config/photoprism/storage:/photoprism/storage
      - /volume1/docker/config/photoprism/backup:/photoprism/backup
      - /volume1/data/photoprism/sidecar/:/photoprism/sidecar
      - /volume1/data/photoprism/cache:/photoprism/cache

  ofelia:
    restart: unless-stopped
    image: mcuadros/ofelia:latest
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /volume1/docker/config/ofelia/jobs.ini:/etc/ofelia/config.ini
      - /volume1/docker/config/ofelia/logs:/logs
      - /etc/passwd:/etc/passwd:ro
      - /etc/localtime:/etc/localtime:ro

  prism_mariadb:
    restart: unless-stopped
    container_name: photoprism_mariadb_1
    user: ${UID}:${GID}
    image: mariadb:10.6
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    command: mysqld --innodb-buffer-pool-size=128M --transaction-isolation=READ-COMMITTED --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-connections=512 --innodb-rollback-on-timeout=OFF --innodb-lock-wait-timeout=120
    volumes:
      - /volume1/docker/databases/photoprism/mysql:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
      - /etc/passwd:/etc/passwd:ro
    environment:
      MYSQL_ROOT_PASSWORD: ${mysql_root_password}
      MYSQL_DATABASE: photoprism
      MYSQL_USER: photoprism
      MYSQL_PASSWORD: ${mysql_password}
```
