### ISSUE TITLE
Windows: Should We Use Package Managers to Simplify Setup?

### ISSUE THREAD

**Issue by lastzero** [photoprism/photoprism#1727]
We would love to simplify the installation of PhotoPrism. I've recently noticed that the [V2Fly project](https://www.v2fly.org/en_US/guide/install.html#package-integrity) uses the following Package Managers to install their software on Windows:

- https://chocolatey.org/
- https://scoop.sh/
- https://github.com/microsoft/winget-cli

👉 &nbsp; The scope of this issue includes only research, in particular reading documentation and testing available tools. A simple proof of concept MAY be created to verify feasibility.

Questions:

- [ ] Are these popular tools like Homebrew on macOS? How many potential users could we reach with this?
- [ ] What exactly needs to be done to build a package / installation script (list of steps)? How much effort is it (in days or hours)?
- [ ] Can important dependencies such as Darktable, RawTherapee, ExifTool, and TensorFlow be installed using these package managers? Are packages available already and if yes, what versions?
- [ ] Are there other / better alternatives we should take a look at?

**Comment by AaronDewes** [comment]
There is an official Microsoft tool which does this too: https://github.com/microsoft/winget-cli
That may be another alternative

**Comment by lastzero** [comment]
Thanks! 🙃 &nbsp; It would be nice to know more about the differences, especially in terms of user base, ease of use, and security.
For example: Does Microsoft require code signing / any certificates to use their installer?

**Comment by SiJiL82** [comment]
One thing that Winget needs (but doesn't enforce) is that the version number for the application is visible/retrievable in Add/Remove programs. It uses this to determine what version you have installed, which it then compares against the version number in the package repository. If your installer doesn't include this, then when you search for upgrades with Winget it lists the current installed version as "Unknown" and will show a package as an update, even if it's actually the same version.

Alternatives like Chocolatey get around this by making the user install it initially through the package manager, as it can then log in its own internal database which version you installed, and checks against its database, not anything the application provides, for future updates.

I'm personally not a fan of how Chocolatey installs programs, as it puts them in its own install location - so you could download an application the traditional way, run its installer to install to C:\Program Files\ and then also install the same app in Chocolatey and it would be completely separate.
Winget doesn't do this - you can install an application by downloading it from the developer's website and Winget will pick it up from Add/Remove programs if it has a matching package in its repository. This feels like a much cleaner approach, although it does have the limitation that the developer needs to package the installer correctly as mentioned above.

So from what I've seen, you just need a Windows installer of some kind, which can install your application and any dependencies, and sets the version correctly in the Windows installed applications DB.
They are still in the process of adding dependencies as part of the package manifest, so they wouldn't have to be managed by your own installer, although I imagine this could cause issues if specific versions were needed as AFAIK Winget doesn't have the ability to install a specific version of a package.
https://github.com/microsoft/winget-cli/issues/163

**Comment by SiJiL82** [comment]
Applications from your list that already exist as packages:

### Winget
- Darktable v3.4.1.1
- RawTherapee v5.8

### Chocolatey
- Darktable 3.6.1
- RawTherapee 5.8
- ExifTool 12.35

### Scoop
- ExifTool 12.35

**Comment by SiJiL82** [comment]
Effort required to create a Winget package is minimal - you can use the "wingetcreate" package to prompt you through the process, which takes minutes. Once you've done it once, you can integrate a PowerShell script into your build process to auto update the package manifest with the new version details: https://github.com/microsoft/winget-create

**Comment by lastzero** [comment]
Do we need a Windows VM / Server? Or can we build packages in our existing Linux CI environment (alone)?

**Comment by SiJiL82** [comment]
> Do we need a Windows VM / Server? Or can we build packages in our existing Linux CI environment (alone)?

For Winget you can do it without a Windows machine - it's just creating a YAML file, so would probably be quite easy to automate generating it (assuming you can create the Windows installer without a Windows server?)
Sample file:
```
PackageIdentifier: Microsoft.WindowsTerminal
PackageVersion: 1.6.10571.0
PackageLocale: en-US
Publisher: Microsoft
PackageName: Windows Terminal
License: MIT
ShortDescription: The new Windows Terminal, a tabbed command line experience for Windows.
Installers: 
 - Architecture: x64
   InstallerType: msix
   InstallerUrl: https://github.com/microsoft/terminal/releases/download/v1.6.10571.0/Microsoft.WindowsTerminal_1.6.10571.0_8wekyb3d8bbwe.msixbundle
   InstallerSha256: 092aa89b1881e058d31b1a8d88f31bb298b5810afbba25c5cb341cfa4904d843
   SignatureSha256: e53f48473621390c8243ada6345826af7c713cf1f4bbbf0d030599d1e4c175ee
ManifestType: singleton
ManifestVersion: 1.0.0
```
