### ISSUE TITLE
Index: Incorrect string value xF8

### ISSUE THREAD

**Issue by Tukks** [photoprism/photoprism#1924]
**What does not work as expected?**

while indexing I have error like 
2022-01-10 22:55:26 ERRO index: Error 1366: Incorrect string value: '\xF8;' for column `photoprism`.`photos`.`photo_description` at row 1 / record not found in 'synologyphoto/2013/03/10032013-2013-03-10 19.06.52.jpg' (find or create photo)
on 30k photos I have this case on 100 hundred or less

**How can we reproduce it?**
I would want to attach a photo not woking, but I can't

**What behavior do you expect?**

an index working correctly

**What could be the cause of your problem?**

maybe the space in the filename<

**Can you provide us with example files for testing, error logs, or screenshots?**

**Which software versions do you use?**

Your app version / build number can be found in *Settings* when you scroll to the bottom.

          PhotoPrism®
          211215-93b26f19-Linux-x86_64

**Comment by lastzero** [comment]
**Can you provide us with example files for testing, error logs, or screenshots?**

Please add example files or screenshots that help to reproduce your problem.
You may also send files via email or share a download link:
https://photoprism.app/contact

Learn how to diagnose frontend issues:
https://docs.photoprism.app/getting-started/troubleshooting/browsers/

**Which software versions do you use?**

Your app version / build number can be found in *Settings* when you scroll to the bottom.

- PhotoPrism Architecture & Build Number
- Database Type & Version (MySQL or SQLite)
- Operating System Types & Versions (Linux, Windows, Android,...)

**Comment by Tukks** [comment]
![10112012-2012-11-10 23 47 05](https://user-images.githubusercontent.com/5930169/148848814-88b15b29-9aa8-4296-9583-81419073e389.jpg)

Example photo not working

Which software versions do you use?
Docker compose
Mysql
Ubuntu 20.04

**Comment by Tukks** [comment]
Sample of photo send to samples@photoprism.app
Photo can be used in the samples

**Comment by graciousgrey** [comment]
The files can be indexed without any errors when using mariadb as recommended.

When using mysql you need to set the right character set: https://dev.mysql.com/doc/refman/8.0/en/charset-unicode-utf8mb4.html
Our docker-compose example: https://dl.photoprism.org/docker/docker-compose.yml shows how to do this for mariadb:

```
## Database Server (recommended)
  ## see https://docs.photoprism.app/getting-started/faq/#should-i-use-sqlite-mariadb-or-mysql
  mariadb:
    ## If MariaDB gets stuck in a restart loop, this points to a memory or filesystem issue:
    ## https://docs.photoprism.app/getting-started/troubleshooting/#fatal-server-errors
    restart: unless-stopped
    image: mariadb:10.6
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    command: mysqld --innodb-buffer-pool-size=128M --transaction-isolation=READ-COMMITTED --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-connections=512 --innodb-rollback-on-timeout=OFF --innodb-lock-wait-timeout=120
```

**Comment by Tukks** [comment]
@graciousgrey Thank's for the response
I'm already using MariaDb with the docker-compose example with this option --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

**Comment by lastzero** [comment]
If the logs show "incorrect string value" database errors and you are running a custom MariaDB or MySQL server that is not based on our [default configuration](https://dl.photoprism.app/docker/docker-compose.yml):

- [ ] Full [Unicode](https://home.unicode.org/basic-info/faq/) support [must be enabled](https://mariadb.com/kb/en/setting-character-sets-and-collations/#example-changing-the-default-character-set-to-utf-8), e.g. using the `mysqld` command parameters `--character-set-server=utf8mb4` and `--collation-server=utf8mb4_unicode_ci`
- [ ] Note that an existing database may use a different character set if you imported it from another server
- [ ] Before reporting a bug, verify the problem still occurs with a newly created database based on our example

Run this command in a terminal to see the current values of the collation and character set variables (change the root password `insecure` and database name `photoprism` as specified in your `docker-compose.yml`):

```bash
echo "SHOW VARIABLES WHERE Variable_name LIKE 'character\_set\_%' OR Variable_name LIKE 'collation%';" | \
docker-compose exec -T mariadb mysql -uroot -pinsecure photoprism
```

**Comment by Tukks** [comment]
Here's my value :
Variables (--variable-name=value)
and boolean options {FALSE|TRUE}  Value (after reading options)
--------------------------------- ----------------------------------------
abort-source-on-error             FALSE
auto-rehash                       TRUE
auto-vertical-output              FALSE
binary-as-hex                     FALSE
character-sets-dir                (No default value)
column-type-info                  FALSE
comments                          FALSE
compress                          FALSE
debug-check                       FALSE
debug-info                        FALSE
database                          (No default value)
default-character-set             auto
delimiter                         ;
vertical                          FALSE
force                             FALSE
named-commands                    FALSE
ignore-spaces                     FALSE
init-command                      (No default value)
local-infile                      FALSE
no-beep                           FALSE
host                              (No default value)
html                              FALSE
xml                               FALSE
line-numbers                      TRUE
unbuffered                        FALSE
column-names                      TRUE
sigint-ignore                     FALSE
port                              0
progress-reports                  FALSE
prompt                            \N [\d]> 
protocol                          
quick                             FALSE
raw                               FALSE
reconnect                         FALSE
socket                            /run/mysqld/mysqld.sock
ssl                               FALSE
ssl-ca                            (No default value)
ssl-capath                        (No default value)
ssl-cert                          (No default value)
ssl-cipher                        (No default value)
ssl-key                           (No default value)
ssl-crl                           (No default value)
ssl-crlpath                       (No default value)
tls-version                       (No default value)
ssl-verify-server-cert            FALSE
table                             FALSE
user                              root
safe-updates                      FALSE
i-am-a-dummy                      FALSE
connect-timeout                   0
max-allowed-packet                16777216
net-buffer-length                 16384
select-limit                      1000
max-join-size                     1000000
secure-auth                       FALSE
show-warnings                     FALSE
plugin-dir                        (No default value)
default-auth                      (No default value)
binary-mode                       FALSE
connect-expired-password          FALSE

**Comment by lastzero** [comment]
Are you using a MariaDB image for ARMv7 / 32-bit?

This is the expected command output with the latest MariaDB 10.6 (AMD64 version):

```
Variable_name	Value
character_set_database	utf8mb4
character_set_filesystem	binary
character_set_results	latin1
character_set_server	utf8mb4
character_set_system	utf8mb3
collation_connection	latin1_swedish_ci
collation_database	utf8mb4_unicode_ci
collation_server	utf8mb4_unicode_ci
```

**Comment by Tukks** [comment]
this is my docker compose  for maria: 
```yaml
mariadb:
    ## If MariaDB gets stuck in a restart loop, this points to a memory or filesystem issue:
    ## https://docs.photoprism.app/getting-started/troubleshooting/#fatal-server-errors
    restart: unless-stopped
    image: mariadb:10.6
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    command: mysqld --innodb-buffer-pool-size=1G --transaction-isolation=READ-COMMITTED --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-connections=512 --innodb-rollback-on-timeo>
    ## Never store database files on an unreliable device such as a USB flash drive, an SD card, or a shared network folder:
    volumes:
      - "./database:/var/lib/mysql" # Important, don't remove
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: photoprism
      MYSQL_USER: photoprism
      MYSQL_PASSWORD: 
```
Like in the doc
