### ISSUE TITLE
No Photos Found

### ISSUE THREAD

**Issue by UnPossible-Me** [photoprism/photoprism#1943]
Hello!
Pretty much what the title says, indexing happens quite quickly, & subsequently, no photos are found. 
After going though previous issues,  [#777](https://github.com/photoprism/photoprism/issues/777), & posts online, I'd hazard a guess as to say it's likely permission issues.
The thing is, how do I make it work?

I'm running PP from docker, on a Raspberry Pi alongside Nextcloud using guides given in the docs. Everything seems to startup just fine.
My `docker-compose.yml` looks like this:
```
      HOME: "/mnt/HDD1/photoprism"
    ## Hardware devices for video transcoding and machine learning (optional):
    # devices:
    #  - "/dev/video11:/dev/video11" # Video4Linux (h264_v4l2m2m)
    working_dir: "/mnt/HDD1/photoprism"
    volumes:
      ## The *originals* folder contains your original photo and video files (- "[host folder]:/photoprism/originals"):
      - "/mnt/HDD1/nextcloud/data/UnPossible/files/Photos:/photoprism/orginals"
      ## Multiple folders can be made accessible by mounting them as subfolders of /photoprism/originals:
      # - "/mnt/Family:/photoprism/originals/Family"    # [folder 1]:/photoprism/originals/[folder 1]
      # - "/mnt/Friends:/photoprism/originals/Friends"  # [folder 2]:/photoprism/originals/[folder 2]
      ## You may mount an *import* folder from which files can be transferred to *originals* (optional):
      # - "~/Import:/photoprism/import"
      ## Cache, session, thumbnail, and sidecar files will be created in the *storage* folder (never remove):
      - "./storage:/mnt/HDD1/photoprism/storage"
```

Now, all my `nextcloud` files are owned by `www-data` with `755` permissions.
I'm running `docker-compose up -d` as `root`, so I was hoping photoprism would be able to access these files as well.

A trick I read was to launch a console as root in the PP container & check if it can find the photos. 
Well, I can't the photoprism directory is all that's available. 

I'm aware of mounting Nextcloud folders from `sync` settings, but that just copies them over to the originals folder AFAIK, nice for backups, but useless since they're both running on the same machine & I don't have the luxury of hosting 2 copies. 

Any ideas? Or am I just missing something obvious?
