### ISSUE TITLE
Docker: Upgrade base image to Debian 11 "Bullseye" incl. Darktable 3.8

### ISSUE THREAD

**Issue by lastzero** [photoprism/photoprism#2076]
**The new Docker image for our upcoming release is based on Debian 11 "Bullseye" instead of Ubuntu Server:**

- It is smaller and comes with many updated dependencies like [Darktable 3.8.1](https://www.darktable.org/2022/02/darktable-3.8.1-released/)
- The new build process also makes it easier to provide standalone packages in the future

**Hardware Video Transcoding**

Improvements include [automatic detection of compatible CPU and GPU drivers at first startup](https://github.com/photoprism/photoprism/issues/1337), depending on what has been configured via `PHOTOPRISM_INIT`:

```yaml
services:
  photoprism:
    image: photoprism/photoprism:latest
    ...
    environment:      
      ## Run/install on first startup (options: update, gpu, tensorflow, davfs, clean):
      PHOTOPRISM_INIT: "update gpu tensorflow clean"
```

**Related Commits**

This issue was created after the upgrade for documentation purposes. The corresponding changes can be found in the following commits:

- https://github.com/photoprism/photoprism/search?q=Bullseye&type=commits
