### ISSUE TITLE
Docker Swarm, Traefik and FQDN

### ISSUE THREAD

**Issue by gpulido** [photoprism/photoprism#208]
Hello,
I'm trying to run photoprism in its own stack on a docker swarm (1 node) using traefik as reverse proxy to access it.
I used the provided docker_compose.yml as a base and added the traefik tags:
```yaml
version: '3.3'

services:
  app:
    image: photoprism/photoprism:latest
    env_file: /var/data/config/photoprism/photoprism.env
    ports:
      - 2342:2342
    volumes:
     - /etc/localtime:/etc/localtime:ro
     - /var/data/photoprism:/home/photoprism/Pictures

    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.photoprism.entrypoints=https"
        - "traefik.http.routers.photoprism.rule=Host(`photoprism.midomain.com`)"
        - "traefik.http.routers.photoprism.tls.certresolver=namecheap"
        - "traefik.http.services.photoprism.loadbalancer.server.port=2342"

networks:
  traefik_public:
    external: true
```
The environment file is the following:
```
PHOTOPRISM_URL=https://photoprism.midomain.com
PHOTOPRISM_TITLE=PhotoPrism
PHOTOPRISM_SUBTITLE=Browse your life
PHOTOPRISM_DESCRIPTION=Personal Photo Management powered by Go and Google TensorFlow. Free and open-source.
HOTOPRISM_AUTHOR=Anonymous
PHOTOPRISM_TWITTER=@rowseyourlife"
PHOTOPRISM_IMPORT_PATH=/home/photoprism/Pictures/Import
PHOTOPRISM_EXPORT_PATH=/home/photoprism/Pictures/Export
PHOTOPRISM_ORIGINALS_PATH=/home/photoprism/Pictures/Originals
PHOTOPRISM_UPLOAD_NSFW=true
PHOTOPRISM_HIDE_NSFW=false
PHOTOPRISM_EXPERIMENTAL=false
PHOTOPRISM_DEBUG=true
PHOTOPRISM_READONLY=false
PHOTOPRISM_PUBLIC=true
PHOTOPRISM_ADMIN_PASSWORD=photoprism
```
The server seems to be up and running (this is the docker log):
```
time="2020-01-20T07:11:32+01:00" level=info msg="starting database server at localhost:4000\n"
time="2020-01-20T07:11:37+01:00" level=info msg="init database"
time="2020-01-20T07:11:37+01:00" level=debug msg="set database password"
time="2020-01-20T07:11:37+01:00" level=debug msg="flush database privileges"
time="2020-01-20T07:11:37+01:00" level=debug msg="create database if not exists"
time="2020-01-20T07:11:37+01:00" level=info msg="database created"
time="2020-01-20T07:11:45+01:00" level=info msg="starting web server at 0.0.0.0:2342"
```
Then inside my server network y can access to http://my_server_ip:2342 and I reach the photoprism instance.
The problem is when I try to reach from outside using the FQDN that I provided to Traefik: 
https://photoprism.midomain.com that is returning a 504 with a gateway timeout.

The traefik configuration is the same for others services that I'm hosting and is pretty straightforward, I don't receive any hit on the photoprism log I don't know if I'm missing something on the photoprism configuration.
Thanks in advance for the amazing software and the help.
