### ISSUE TITLE
Monitoring: Add a Prometheus-compatible API endpoint

### ISSUE THREAD

**Issue by lastzero** [photoprism/photoprism#213]
**As an admin, I want to monitor the health and performance of PhotoPrism using a common tool like Prometheus.**

This PR by @brandon1024 added a Prometheus-compatible `GET /api/v1/metrics` endpoint to our API:

- https://github.com/photoprism/photoprism/pull/3730

See [comments below](https://github.com/photoprism/photoprism/issues/213#issuecomment-1854116006) for further details.

**Comment by RichiH** [comment]
You might call me biased, but I would prefer Prometheus.

Influx can understand Prometheus data format and by using client_golang, you would get the upgrade path to OpenMetrics for free.

**Comment by lastzero** [comment]
What could be advantages / disadvantages for our specific application? What metrics would you collect?

**Comment by RichiH** [comment]
It is very unlikely that you would be unhappy with using Prometheus client
libraries.

You get baseline process metrics automagically, so I would suggest starting
with vanity/boundary metrics (amount of pictures, storage size), usage (how
often are certain endpoints hit, how long do they take to load, etc), and
"put a counter everywhere you would be tempted to put a debug statement".

That should immediately be useful and also allow you to get a feeling of
what you find useful, or fun.

Sent by mobile; please excuse my brevity.

**Comment by lastzero** [comment]
Compared both recently and found that InfluxDB was developed after Prometheus to fix shortcomings for certain use cases. AFAIK InfluxDB needs less storage and can have higher performance, but that really doesn't matter for a private user. Question was meant to learn, not to suggest users would be unhappy with Prometheus.

**Comment by RichiH** [comment]
Ah, OK.

InfluxDB predates Prometheus by quite a bit. Using Prometheus client allows
you to use both Prometheus and InfluxDB, and others, as they added support
for Prometheus.

Performance is roughly the same, but I think we are slightly ahead of
Influx in storage and performance.

Anything else you want to know about metrics etc, just ask :)


Sent by mobile; please excuse my brevity.

**Comment by haozhou** [comment]
Just curious which KPI you'd like to take for health monitoring? 
Disk usage or CPU usage is application-independent

**Comment by mmontes11** [comment]
Any update about this? It would be a huge plus! 📈🚀

**Comment by lastzero** [comment]
Nope. Working on face detection right now. You can do monitoring via Traefik already if you just want to see requests.

**Comment by mmontes11** [comment]
Wow, that's sweet. 👍🏻

**Comment by centralhardware** [comment]
> Just curious which KPI you'd like to take for health monitoring? Disk usage or CPU usage is application-independent

hm, looks like all we need it's node exporter for node monitoring and mysql_exporter for database Monitoring. 
Maybe we can monitor count of recognized faces or count of photos but i don't think it's useful enough

**Comment by RichiH** [comment]
For direct instrumentation, it would be more common to expose e.g.
latency buckets for processing time of photos or requests.

For data that's in MySQL, or on the local machine, mysql_exporter &
node_exporter are better, agreed.

**Comment by MostFrabjous** [comment]
I'd vote for some API endpoints that expose statistics about the photoprism instance. Like
- number of originals|hidden|error|photos|places|albums|people|[new] faces|etc.
- sync status? (I'm not using sync)

**Comment by lastzero** [comment]
If you would like to test this without building from source, you can now use the `photoprism/photoprism:test` image available on Docker Hub:
- https://hub.docker.com/r/photoprism/photoprism/tags?page=1&name=test

Then run the `photoprism clients` CLI subcommands to [add client authentication credentials](https://github.com/photoprism/photoprism/issues/3943) and finally test the credentials with the new `GET /api/v1/metrics` endpoint. The required scope for this is "metrics", but the "*" setting should also work.

A working config example for Prometheus can be found here (change `client_id` and `client_secret` as needed):

- https://github.com/photoprism/photoprism/blob/develop/prometheus.yml
- https://github.com/photoprism/photoprism/blob/cf93437b1c4f0a20cd51cf964e0455bf6a66e8e3/docker-compose.yml#L194-L198

**Comment by lastzero** [comment]
A big thank you to Brandon Richardson (@brandon1024) for implementing the metrics endpoint and for being so patient with our team to get it merged! :heart:

**Comment by KiraPC** [comment]
Has this feature released?

Thanks

**Comment by graciousgrey** [comment]
It will be included in our next release. 

If you would like to test this you can use the photoprism/photoprism:test image available on Docker Hub.

**Comment by SchoolGuy** [comment]
I leave this here so future people have it easier. In the following you will find an example config for the kube-prom-stack to monitor a single Photoprism instance (this expects a service called `photoprism-web` and the app being installed in the namespace `photoprism`):

```yml
apiVersion: v1
kind: Secret
metadata:
  name: photoprism-monitoring-client-secret
  namespace: monitoring
type: Opaque
stringData:
  clientId: <Client ID>
  clientSecret: <Client Secret>
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: photoprism
  namespace: monitoring
  labels:
    release: kube-prom-stack
spec:
  selector:
    matchLabels:
      app: photoprism
  endpoints:
  - port: http
    path: /api/v1/metrics
    oauth2:
      clientId:
        secret:
          name: photoprism-monitoring-client-secret
          key: clientId
      clientSecret:
        name: photoprism-monitoring-client-secret
        key: clientSecret
      tokenUrl: http://photoprism-web.photoprism.svc.cluster.local:2342/api/v1/oauth/token
      scopes:
        - 'metrics'
      endpointParams:
        grant_type: "client_credentials"
  namespaceSelector:
    any: true
```
