### ISSUE TITLE
darktable searches the config folder in the wrong directory

### ISSUE THREAD

**Issue by zanna-37** [photoprism/photoprism#2225]
**What does not work as described in the documentation?**
When converting `.CR2` files I get:
`[index: failed converting IMG_2551.CR2 to jpeg (path lookup '/photoprism/.config/darktable' fails with: 'No such file or directory' )]()`

**What could be the cause of your problem?**
Inside the container, the darktable folder seems to be in `/photoprism/storage/config/darktable`. Note the extra `/storage/`.

**Which software versions do you use?**
`Build 220302-0059f429-Linux-AMD64`

**Other info**
I'm using this parameters in the docker-compose.yml, as suggested in the [documentation](https://dl.photoprism.app/docker/docker-compose.yml).
```yaml
# ...
    environment:
      # ...
      HOME: "/photoprism"
    user: "1234:100"
    working_dir: "/photoprism"
    volumes:
      # ...
      - "./storage:/photoprism/storage"  
# ...
```
