### ISSUE TITLE
WebDAV: Add Bearer authentication support e.g. for ownCloud 10

### ISSUE THREAD

**Issue by dorianim** [photoprism/photoprism#2267]
**What does not work as described in the documentation?**

I tried setting up syncing with Owncloud as described here: https://docs.photoprism.app/user-guide/settings/sync/

However, when I try to set up the sync, I always get the error `Could not connect, please try again` and in the logs: `level=error msg="account-folder: Authorize https://owncloud.example.com/remote.php/dav/files/photoprism-binduser/: 401`

I tried the same parameters in Nautilus, and it works fine, so I assume that the problem is not with Owncloud.

**How can we reproduce it?**

1. Go to 'Settings > Sync'
2. Click on 'ADD SERVER'
3. Enter valid parameters for an Owncloud WebDAV endpoint
4. Click on the sync icon to configure syncing
5. The error from above appears and the Folder dropdown is empty

**What behavior do you expect?**

No error and a list of available folders in the Folder dropdown.

**What could be the cause of your problem?**

Maybe an issue with the WebDAV lib in Photoprism or a wrong URL.

**Can you provide us with example files for testing, error logs, or screenshots?**

- Log in Photoprism: `level=error msg="account-folder: Authorize https://cloud.itsblue.de/remote.php/dav/files/photoprism-binduser/: 401`
- Log in Owncloud: `"PROPFIND /remote.php/dav/files/photoprism-binduser/
HTTP/1.1" 401 1668 "-" "Go-http-client/2.0"`

**Which software versions do you use?**

- PhotoPrism Build 220302-0059f429-Linux-AMD64
- MariaDB 10.5
- OwnCloud 10.9.1 (stable) 

**Do you use a Reverse Proxy, Firewall, VPN, or CDN?**

- Yes Traefik for both, Owncloud and Photoprism

**Comment by lastzero** [comment]
- Does it work when you enter the protocol and hostname only, without path?
 - Does the server have a valid HTTPS certificate? 
 - Any specific auth requirements / settings in ownCloud? Should basic auth work? 
 - Does it work with our preview build?

**Comment by dorianim** [comment]
Thanks for the reply!

> Does it work when you enter the protocol and hostname only, without path?

Nope, the error changes: `account-folder: ReadDir /: 405 Method Not Allowed - PROPFIND /`

> Does the server have a valid HTTPS certificate?

Yes

> Any specific auth requirements / settings in ownCloud? Should basic auth work?

I don't think so. It's basically a vanilla Owncloud with a normal account. Auth works in Nautilus.

> Does it work with our preview build?

Nope, same error as above

**Comment by faquad** [comment]
The error with http `PROFIND` comes either from the owncloud itself or from the owncloud's reverse-proxy (nginx or apache) - the server seems to block this http method. 
Nautilus seems to be able to handle the case where `PROFIND` is not supported.

**Comment by dorianim** [comment]
The error appears, because the path `/` is not valid for PROFIND. Only `/remote.php/dav/files/photoprism-binduser/` allows it.

I think, this is to be expected and not related to the issue.

**Comment by faquad** [comment]
ah, agree, i guess it must be fixed on the go-http-client side to use  `/remote.php/dav/files/photoprism-binduser/` instead of `/`

**Comment by lastzero** [comment]
Definitely an authentication / http configuration issue. Found many similar reports related to WebDAV and Owncloud via Google:

- https://github.com/owncloud/core/issues/12146
- https://github.com/owncloud/core/issues/21461

The auto detected WebDAV resource URL is OK (no such thing and "-binduser" etc, this is the exact same URL that Owncloud provides in their UI for connecting with the admin user):

```
https://owncloud.photoprism.dev/remote.php/dav/files/admin/
```

However, authentication fails with code 401. So it COULD be related to:
- MOD_X_ACCEL_REDIRECT_ENABLED
- mod_rewrite
- Sabre_DAV
- fastcgi
- ...

If I had a second to test more, I would, but that is not possible. A good opportunity to contribute and find out what's wrong!

As it looks to me, WebDAV will probably work with Owncloud OCIS and/or other Ownload 10 settings :+1:

**Comment by tarun-menta** [comment]
I'd like to try working on this, could this be assigned to me?

**Comment by lastzero** [comment]
I'm working on WebDAV right now anyway, so if you could figure out what is causing this and needs to be changed so we can take care of it, that would be a big help already!

**Comment by tarun-menta** [comment]
Is there a HTTPS OwnCloud dev server setup that I can use to test?

**Comment by lastzero** [comment]
This is the docker-compose.yml that we use for testing. Of course, you need Traefik with Let's Encrypt (DNS challenge for wildcard certificates), MariaDB and Redis to make it work as shown here. You also need to adjust the network configuration and domains to your environment (see our [development environment](https://github.com/photoprism/photoprism/blob/develop/docker-compose.yml) for how to use this together):

```yaml
version: '3.5'

networks:
  default:
    name: backend
    external: true

services:
  owncloud:
    container_name: "owncloud-10"
    image: owncloud/server:10
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.owncloud.entrypoints=websecure"
      - "traefik.http.middlewares.secure.headers.stsSeconds=15552000"
      - "traefik.http.routers.owncloud.middlewares=secure"
      - "traefik.http.routers.owncloud.tls.domains[0].main=yourdomain.dev"
      - "traefik.http.routers.owncloud.tls.domains[0].sans=*.yourdomain.dev"
      - "traefik.http.routers.owncloud.tls.certresolver=myresolver"
      - "traefik.http.routers.owncloud.rule=Host(`owncloud.yourdomain.dev`)"
      - "traefik.http.routers.owncloud.tls=true"
    environment:
      OWNCLOUD_DOMAIN: "owncloud.yourdomain.dev"
      OWNCLOUD_DB_TYPE: "mysql"
      OWNCLOUD_DB_NAME: "owncloud_10"
      OWNCLOUD_DB_USERNAME: "owncloud_10"
      OWNCLOUD_DB_PASSWORD: "owncloud_10"
      OWNCLOUD_DB_HOST: "mariadb"
      OWNCLOUD_ADMIN_USERNAME: "admin"
      OWNCLOUD_ADMIN_PASSWORD: "photoprism"
      OWNCLOUD_MYSQL_UTF8MB4: "true"
      OWNCLOUD_REDIS_ENABLED: "true"
      OWNCLOUD_REDIS_HOST: "redis"
    volumes:
      - "./data:/mnt/data/"
```
