### ISSUE TITLE
Tenserflow fails on ubuntu 18.04 with docker-compose and a nginx reverse proxy

### ISSUE THREAD

**Issue by mithek** [photoprism/photoprism#282]
Hey, first of all awesome project!

I'm now trying to install photoprism on my ubuntu 18.04 server with docker-compose but i run into 2 issues.

1. The api returns a 401, it's not consistent and sometimes it does work.
- my guess it's happening because of my nginx reverse proxy.

2. When i upload a image it will fail properly because of Tensorflow. 
- I haven't been able to solve this issue or get it working once. 

My guess is that i have something configured incorrectly or that something is not able to work with my setup.
Below you can see the docker compose logs and my settings.

**Docker-compose logs:**
`photoprism_1  | time="2020-04-09T18:55:33Z" level=info msg="starting database server at localhost:4000\n"
photoprism_1  | time="2020-04-09T18:55:41Z" level=info msg="webdav: enabled, username: photoprism"
photoprism_1  | time="2020-04-09T18:55:41Z" level=info msg="webdav: /originals available"
photoprism_1  | time="2020-04-09T18:55:41Z" level=info msg="webdav: /import available"
photoprism_1  | time="2020-04-09T18:55:41Z" level=info msg="starting web server at 0.0.0.0:2342"
photoprism_1  | time="2020-04-09T18:56:05Z" level=error msg="GET /api/v1/photos?count=60&offset=0&country=&camera=0&lens=0&label=&year=0&color=&order=newest&q= (401) [109.536µs]"
photoprism_1  | time="2020-04-09T18:57:19Z" level=info msg="1 files uploaded in 19.305472ms"
photoprism_1  | time="2020-04-09T18:57:19Z" level=info msg="moving files from \"1586458639631\""
photoprism_1  | time="2020-04-09T18:57:19Z" level=info msg="tensorflow: loading image classification model from \"nasnet\""
photoprism_1  | Killed`

**My nginx vhost:**
```
server {
	server_name subdomain.domain.ltd;

	location / {
		proxy_pass http://127.0.0.1:2342;	
		proxy_set_header Upgrade $http_upgrade;
    	proxy_set_header Connection "Upgrade";
		proxy_set_header Host $host;
    	proxy_set_header X-Real-IP $remote_addr;
	}

    listen 443 ssl http2; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/subdomain.domain.ltd/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/subdomain.domain.ltd/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot
}
server {
    if ($host = subdomain.domain.ltd) {
        return 301 https://$host$request_uri;
    } # managed by Certbot

	listen 80;
	server_name subdomain.domain.ltd;
    return 404; # managed by Certbot
}
```

**My docker-compose file:**
```
version: '3.3'

# Example docker-compose config file for production use
# Container image on Docker Hub: https://hub.docker.com/r/photoprism/photoprism/
# To keep photoprism running, add "restart: always"
#
# Usage: docker-compose up

services:
  photoprism:
    image: photoprism/photoprism
    #image: photoprism/photoprism:latest
    restart: always
    ports:
      - 2342:2342 # [local port]:[container port]
    environment: # Run "photoprism help" and "photoprism config" too see all config options and current values
      PHOTOPRISM_URL: "https://subdomain.domain.ltd/"
      PHOTOPRISM_TITLE: "PhotoPrism"
      PHOTOPRISM_SUBTITLE: "Browse your life"
      PHOTOPRISM_DESCRIPTION: "Personal Photo Management powered by Go and Google TensorFlow. Free and open-source."
      PHOTOPRISM_AUTHOR: "Anonymous"
      PHOTOPRISM_TWITTER: ""
      PHOTOPRISM_UPLOAD_NSFW: "true"
      PHOTOPRISM_HIDE_NSFW: "false"
      PHOTOPRISM_EXPERIMENTAL: "false"
      PHOTOPRISM_DEBUG: "false"
      PHOTOPRISM_READONLY: "false"
      PHOTOPRISM_PUBLIC: "false"
      PHOTOPRISM_ADMIN_PASSWORD: "replaced-password" # Plain text or bcrypt hash (escape "$" with "$$")
      PHOTOPRISM_WEBDAV_PASSWORD: "replaced-password # Plain text only (username "photoprism")
    volumes:
      - "/mnt/volume_ams3_01/photoprism/Originals:/photoprism/originals" # [local path]:[container path]
      - "/mnt/volume_ams3_01/photoprism/Import:/photoprism/import" # [local path]:[container path] (optional)
      - "photoprism-cache:/photoprism/cache" # keep thumbnail cache
      - "photoprism-database:/photoprism/database" # keep database files

volumes: # keep this
  photoprism-cache:
    driver: local
  photoprism-database:
    driver: local
```

**Server:**
I have a droplet at digitalocean with 1 cpu, 2GB of memory and 25GB of disk space with a mounted volume.
