### ISSUE TITLE
docker-compose: Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by totti4ever** [photoprism/photoprism#289]
I did find #128, but I do have the exact same problem now with the latest image
```
version: '3.3'

services:
  photoprism:
    image: photoprism/photoprism:latest
    restart: unless-stopped
```

I also did try the fulle dc.yml from https://raw.githubusercontent.com/photoprism/photoprism/master/docker/photoprism/docker-compose.yml

Anything I could have done wrong? Have running a lot of other containers, so it shouldn't be some local docker issue.
