### ISSUE TITLE
Using Docker mapped volumes to allow seamless migrations, backups of Photoprism, 

### ISSUE THREAD

**Issue by nodecentral** [photoprism/photoprism#3120]
#### 1. What is not working as documented?

The issue is perhaps not specific to what’s not working as documented, as it does not seem to be specifically called out, but as i can’t get what I’m trying to do to work, this post is more to confirm if my approach is even possible.

My goal : To be able to map all key Photoprism volumes to locally mapped directories to allow for seamless migrations of the anpp and also to back up of my entire Photoprism instance. Previous attempts just to update the mapping from one local folder to another resulted in Photoprism starting up and not seeing any of the previous indexing / face mapping that I’d done before.. (I’ve lost hours of work in the process)

#### 2. How can we reproduce it?

Deleted the active containers, and tried to move from this local mapping..  
````
 volumes:
      - /share/Container/photoprism/import:/photoprism/import
      - /share/Container/photoprism/storage:/photoprism/storage
      - /share/Container/photoprism/backup:/photoprism/backup
      - /share/Multimedia/Pictures:/photoprism/originals
 ````
To
````
 volumes:
      - /share/VM/photoprism/import:/photoprism/import
      - /share/VM/photoprism/storage:/photoprism/storage
      - /share/VM/photoprism/backup:/photoprism/backup
      - /share/Multimedia/Pictures:/photoprism/originals
 ````
But when i loaded the updated docker_compose.yml it started from scratch again ..

#### 3. What behavior do you expect?

I expected to be able to use my mapped folders as my backup and migration facility without the need to re-do, re-index all the data again 

#### 4. What could be the cause of your problem?

I can only assume something that’s needed to achieve this is not stored / mapped to one of the local folders ? Maybe config, or cache ?

#### 5. Can you provide us with example files for testing, error logs, or screenshots?

My full docker_compose is as follows..

````
version: '3.5'
# https://docs.photoprism.app/getting-started/config-options/
services:
  photoprism:
    image: photoprism/photoprism:latest
    depends_on:
      - mariadb
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    ports:
      - "2342:2342" # HTTP port (host:container)
    environment:
      PHOTOPRISM_ADMIN_PASSWORD: "insecure"
      PHOTOPRISM_SITE_URL: "http://localhost:2342/"
      PHOTOPRISM_ORIGINALS_LIMIT: 5000
      PHOTOPRISM_HTTP_COMPRESSION: "gzip"
      PHOTOPRISM_LOG_LEVEL: "info"
      PHOTOPRISM_PUBLIC: "false"  
      PHOTOPRISM_READONLY: "false"
      PHOTOPRISM_EXPERIMENTAL: "false"               # enables experimental features
      PHOTOPRISM_DISABLE_CHOWN: "false"              # disables storage permission updates on startup
      PHOTOPRISM_DISABLE_WEBDAV: "false"             # disables built-in WebDAV server
      PHOTOPRISM_DISABLE_SETTINGS: "false"           # disables settings UI and API
      PHOTOPRISM_DISABLE_TENSORFLOW: "false"         # disables all features depending on TensorFlow
      PHOTOPRISM_DISABLE_FACES: "false"              # disables facial recognition
      PHOTOPRISM_DISABLE_CLASSIFICATION: "false"     # disables image classification
      PHOTOPRISM_DISABLE_RAW: "false"                # disables indexing and conversion of RAW files
      PHOTOPRISM_RAW_PRESETS: "false"
      PHOTOPRISM_JPEG_QUALITY: 85    
      PHOTOPRISM_DETECT_NSFW: "false"
      PHOTOPRISM_UPLOAD_NSFW: "true" 
      PHOTOPRISM_DATABASE_DRIVER: "mysql" 
      PHOTOPRISM_DATABASE_SERVER: "mariadb:3306"     # MariaDB or MySQL dB server (hostname:port)
      PHOTOPRISM_DATABASE_NAME: "photoprism"         # MariaDB or MySQL dB schema name
      PHOTOPRISM_DATABASE_USER: "photoprism"         # MariaDB or MySQL dB user name
      PHOTOPRISM_DATABASE_PASSWORD: "insecure"       # MariaDB or MySQL dB user password
      PHOTOPRISM_SITE_CAPTION: "AI-Powered Photos App"
      PHOTOPRISM_SITE_DESCRIPTION: ""                # meta site description
      PHOTOPRISM_SITE_AUTHOR: ""                     # meta site author
      PHOTOPRISM_BACKUP_PATH: "/photoprism/backup"
   
    working_dir: "/photoprism" # do not change or remove
    volumes:
      - /share/Container/photoprism/import:/photoprism/import
      #- /share/Container/photoprism/export:/photoprism/export
      - /share/Container/photoprism/storage:/photoprism/storage
      - /share/Container/photoprism/backup:/photoprism/backup
      #- /share/Container/photoprism/config:/photoprism/config
      #- /share/Container/photoprism/cache:/photoprism/cache
      - /share/Multimedia/Pictures:/photoprism/originals
      
  mariadb:
    restart: unless-stopped
    image: mariadb:10.8
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    command: mysqld --innodb-buffer-pool-size=512M --transaction-isolation=READ-COMMITTED --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-connections=512 --innodb-rollback-on-timeout=OFF --innodb-lock-wait-timeout=120
    volumes:
      - "/share/Container/photoprism/database:/var/lib/mysql" # DO NOT REMOVE
    environment:
      MARIADB_AUTO_UPGRADE: "1"
      MARIADB_INITDB_SKIP_TZINFO: "1"
      MARIADB_DATABASE: "photoprism"
      MARIADB_USER: "photoprism"
      MARIADB_PASSWORD: "insecure"
      MARIADB_ROOT_PASSWORD: "insecure"
````

#### 6. Which software versions do you use?

Details in docker_compose above..
All browsers.

#### 7. On what kind of device is PhotoPrism installed?

QNAP NAS TD453D , 4 Core, 16Gb Memory

#### 8. Do you use a Reverse Proxy, Firewall, VPN, or CDN?

No.
