### ISSUE TITLE
PHOTOPRISM_HTTPS_PROXY doesn't seem to take effect

### ISSUE THREAD

**Issue by zarko-a** [photoprism/photoprism#3881]
I'm pretty sure this is a bug related to env variables setting the proxy configuration. Definitely not trying to seek technical support. 

---------------------------------------------------------------------------

#### 1. What is not working as documented?

I try to run all my containers in an isolated network mode (known as `internal` networks in docker). This means that by default egress network traffic is not allowed. So when I saw that PhotoPrism supports outbound proxy (aka forward proxy) I was thrilled. 

I already had photoprism fully working before trying to use a forward proxy via `PHOTOPRISM_HTTPS_PROXY`. 

But when I added the following to my docker compose and tried to index the files containing GPS coordinates I started seeing timeouts and no attempts to connect in my squid proxy log (which I normally see whenever a connection is made).
```
      PHOTOPRISM_HTTPS_PROXY: https://squid-exp:3129
      PHOTOPRISM_HTTPS_PROXY_INSECURE: true
```

Errors from photoprism:
```
time="2023-11-12T18:40:09Z" level=info msg="indexing originals..."
time="2023-11-12T18:40:09Z" level=info msg="classify: loading nasnet"
time="2023-11-12T18:40:14Z" level=info msg="classify: loading labels from labels.txt"
time="2023-11-12T18:40:14Z" level=info msg="index: found no .ppignore file"
time="2023-11-12T18:40:14Z" level=info msg="media: IMG_20160227_112206.jpg was taken at 2016-02-27 17:22:08 +0000 UTC (meta)"
time="2023-11-12T18:41:19Z" level=error msg="places: Get \"https://places.photoprism.app/v1/location/<random looking string>\": dial tcp 5.9.32.79:443: i/o timeout (http request failed)"
time="2023-11-12T18:41:19Z" level=error msg="photo: Get \"https://places.photoprism.app/v1/location/<random looking string>\": dial tcp 5.9.32.79:443: i/o timeout (find location)"
time="2023-11-12T18:41:19Z" level=info msg="index: added main jpg file '<file path>//IMG_20160227_112206.jpg'"
time="2023-11-12T18:41:21Z" level=info msg="media: created 11 thumbnails for '<file path>/IMG_20160227_112214.jpg' [1.903432897s]"
```
Obviously traffic is not going out. I started investigating why. 

First I tested with `curl` from within photoprism container.
this worked. 
`docker exec -it photoprism bash`

```
# Testing the HTTPS port of the proxy, since it's using self-signed cert, we are using insecure option
curl --proxy-insecure -x https://squid-exp:3129 "https://www.amazon.com"
<output ommited but connected successfully and shows up in squid log >

# Testing via HTTP where HTTPS connections are handled via `CONNECT` tunnel
curl -x http://squid-exp:3128 "https://www.amazon.com"
<output ommited but connected successfully and shows up in squid log >
```

Then I started digging deeper why doesn't photoprism use the proxy even though env variables should be set correctly and proxy is definitely working. 

Finally I attempted to set commonly used env variables for the equivalent functionality. And it worked with those.
```
      HTTPS_PROXY: https://squid-exp:3129
      HTTPS_PROXY_INSECURE: true
``` 

This implies that `PHOTOPRISM` prefixed proxy vars are somehow not picked up properly. I'd assume that `HTTPS_PROXY` is picked up by the client library used for proxying and that's why it's working.

#### 2. How can we reproduce it?

1. Have Squid proxy configured and listening on [https_port](http://www.squid-cache.org/Doc/config/https_port/)
2. Make sure PhotoPrism network doesn't normally allow outbound internet access. If running in docker this can be easily achieved by setting the network `internal` attribute to `true` 
3. Set `PHOTOPRISM_HTTPS_PROXY`  and `PHOTOPRISM_HTTPS_PROXY_INSECURE`.
4. Index photos that have GPS coordinates.
5. See timeouts in log

Pasting the config samples below.

#### 3. What behavior do you expect?

Based on the [official docs](https://docs.photoprism.app/getting-started/config-options/#proxy-servers), forward/outbound proxy config should be pretty straightforward and work with just the two specified env variables.
 
#### 4. What could be the cause of your problem?

It would appear that PhotoPrism is not picking up `PHOTOPRISM` prefix proxy vars properly.

#### 5. Can you provide us with example files for testing, error logs, or screenshots?

Generate self-signed cert for squid proxy.
`openssl req -x509 -newkey rsa:4096 -keyout key.pem -out cert.pem -nodes -sha256 -days 3650`

Docker compose excerpt for photoprism
```
version: '3.8'
services:
  photoprism:
    container_name: photoprism
    restart: unless-stopped
    image: photoprism/photoprism:latest
    user: 1000:1000
    stop_grace_period: 10s
    working_dir: /photoprism
    volumes:
      - /opt/docker/photoprism/originals:/photoprism/originals
      - /opt/docker/photoprism/import:/photoprism/import
      - /opt/docker/photoprism/storage:/photoprism/storage
    depends_on:
      - mariadb
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    environment:
      PHOTOPRISM_TRUSTED_PROXY: 172.17.0.2/32
      PHOTOPRISM_PROXY_PROTO_HEADER: X-Forwarded-Proto
      PHOTOPRISM_PROXY_PROTO_HTTPS: https
      # HTTPS_PROXY: https://squid-exp:3129
      # HTTPS_PROXY_INSECURE: true
      PHOTOPRISM_HTTPS_PROXY: https://squid-exp:3129
      PHOTOPRISM_HTTPS_PROXY_INSECURE: true
      PHOTOPRISM_ADMIN_USER: admin
      PHOTOPRISM_ADMIN_PASSWORD: ${PHOTOPRISM_ADMIN_PASSWORD}
      PHOTOPRISM_AUTH_MODE: public
      PHOTOPRISM_SITE_URL: https://photos.<domain>.<TLD>/
      PHOTOPRISM_DISABLE_TLS: true
      PHOTOPRISM_DEFAULT_TLS: true
      PHOTOPRISM_ORIGINALS_LIMIT: 5000
      PHOTOPRISM_HTTP_COMPRESSION: gzip
      PHOTOPRISM_LOG_LEVEL: info
      PHOTOPRISM_READONLY: false
      PHOTOPRISM_EXPERIMENTAL: false
      PHOTOPRISM_DISABLE_CHOWN: false
      PHOTOPRISM_DISABLE_WEBDAV: false
      PHOTOPRISM_DISABLE_SETTINGS: false
      PHOTOPRISM_DISABLE_TENSORFLOW: false
      PHOTOPRISM_DISABLE_FACES: false
      PHOTOPRISM_DISABLE_CLASSIFICATION: false
      PHOTOPRISM_DISABLE_VECTORS: false
      PHOTOPRISM_DISABLE_RAW: false
      PHOTOPRISM_RAW_PRESETS: false
      PHOTOPRISM_JPEG_QUALITY: 85
      PHOTOPRISM_DETECT_NSFW: false
      PHOTOPRISM_UPLOAD_NSFW: true
      PHOTOPRISM_DATABASE_DRIVER: mysql
      PHOTOPRISM_DATABASE_SERVER: mariadb:3306
      PHOTOPRISM_DATABASE_NAME: photoprism
      PHOTOPRISM_DATABASE_USER: photoprism
      PHOTOPRISM_DATABASE_PASSWORD: ${PHOTOPRISM_DB_USER_PASSWORD}
      PHOTOPRISM_SITE_CAPTION: Family Photos
      PHOTOPRISM_SITE_DESCRIPTION: Family Photos
      PHOTOPRISM_SITE_AUTHOR: Family
      PHOTOPRISM_UID: 1000
      PHOTOPRISM_GID: 1000
      PHOTOPRISM_UMASK: 0
    networks:
      mariadb_internal_network:
      squid-exp_internal_network:
      photoprism_internal_network:
  mariadb:
    container_name: mariadb
    restart: unless-stopped
    image: mariadb:10.11
    command: mariadbd --innodb-buffer-pool-size=512M --transaction-isolation=READ-COMMITTED --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-connections=512 --innodb-rollback-on-timeout=OFF --innodb-lock-wait-timeout=120
    stop_grace_period: 5s
    volumes:
      - /opt/docker/mariadb/:/var/lib/mysql
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    environment:
      MARIADB_AUTO_UPGRADE: 1
      MARIADB_INITDB_SKIP_TZINFO: 1
      MARIADB_DATABASE: photoprism
      MARIADB_USER: photoprism
      MARIADB_PASSWORD: ${PHOTOPRISM_DB_USER_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
    networks:
      mariadb_internal_network:
  squid-exp:
    container_name: squid-exp
    restart: unless-stopped
    image: ubuntu/squid:5.2-22.04_beta
    volumes:
      - /opt/docker/squid-exp/logs:/var/log/squid
      - /opt/docker/squid-exp/cache:/var/spool/squid
      - /opt/docker/squid-exp/config/explicit.conf:/etc/squid/conf.d/custom.conf
      - /opt/docker/squid-exp/config/cert.pem:/etc/squid/cert.pem
      - /opt/docker/squid-exp/config/key.pem:/etc/squid/key.pem
    ports:
      - 3128:3128
      - 3129:3129
    environment:
      TZ: America/Chicago
    networks:
      external_network:
      squid-exp_internal_network:
networks:
  external_network:
    internal: false
  photoprism_internal_network:
    internal: true
  mariadb_internal_network:
    internal: true
  squid-exp_internal_network:
    internal: true
```

Squid config
```
cat /opt/docker/squid-exp/config/explicit.conf
https_port 3129 tls-cert=/etc/squid/cert.pem tls-key=/etc/squid/key.pem
# ACLs
acl allowed dstdomain .amazon.com
acl allowed dstdomain .media-amazon.com
# PhotoPrism
# https://docs.photoprism.app/getting-started/troubleshooting/firewall/
acl allowed dstdomain dl.photoprism.app
acl allowed dstdomain my.photoprism.app
acl allowed dstdomain cdn.photoprism.app
acl allowed dstdomain maps.photoprism.app
acl allowed dstdomain places.photoprism.app
acl allowed dstdomain places.photoprism.xyz
# 
http_access allow allowed
http_access deny all
```

#### 6. Which software versions do you use?

(a) PhotoPrism Architecture & Build Number: AMD64, ARM64, ARMv7,...
AMD64 - Docker image, latest

[PhotoPrism® CE]
Build 231021-9abea5b55

(b) Database Type & Version: MariaDB, MySQL, SQLite,...
MariaDB 10.11

(c) Operating System Types & Versions: Linux, Windows, Android,...
Linux - Ubuntu - 22.04.3 LTS (Jammy Jellyfish)

(d) Browser Types & Versions: Firefox, Chrome, Safari on iPhone,...
N/A.

(e) Ad Blockers, Browser Plugins, and/or Firewall Software?
N/A

#### 7. On what kind of device is PhotoPrism installed?
Shouldn't be relevant to this issue, but can provide info if needed. 

#### 8. Do you use a Reverse Proxy, Firewall, VPN, or CDN?

Yes, but shouldn't be relevant to this issue. I can provide more info if needed.
