### ISSUE TITLE
docker-compose.yaml does not work out of the box

### ISSUE THREAD

**Issue by kendalharland** [photoprism/photoprism#3944]
#### 1. What is not working as documented?

The example docker-compose.yaml file at [this link] does not work out of the box.  I ran into the following errors and had to make the following non-obvious changes to get this server running with docker compose:

1. Photoprism can't connect to mariadb - connection is refused

To fix this you have to log into mariadb and create the `photoprism` user, since that is the user that appears in `docker-compose.yaml`

```
# When prompted for a password, just press enter without entering anything/
docker compose exec mariadb mariadb -u root -p

CREATE USER 'photoprism'@'%' IDENTIFIED BY 'insecure;
GRANT ALL PRIVILEGES ON *.* TO 'photoprism'@'%';
FLUSH PRIVILEGES;
```

2. Photoprism fails to startup with error: "unknown database 'photoprism'".

If you log into mariadb and run `SHOW DATABASES;` you'll notice there's no `photoprism` database. This is probably a bug in mariadb
as photoprism's `mariadb` configuration in `docker-compose.yaml` file does contain the environment variable: `MARIADB_DATABASE=photoprism` but it seems this is completely ignored by mariadb.  I am not sure if this is the correct solution, but I got this to work by changing this line, so that photoprism uses the existing `mysql` database:

```yaml
# OLD
PHOTOPRISM_DATABASE_NAME: "photoprism"         # MariaDB or MySQL database schema name

# NEW
PHOTOPRISM_DATABASE_NAME: "mysql"         # MariaDB or MySQL database schema name
```

After these steps I'm able to navigate to localhost:2342 and see photoprism's landing page.

[this link]: https://dl.photoprism.app/docker/docker-compose.yml
