### ISSUE TITLE
Can't connect to webdav (docker+traefik)

### ISSUE THREAD

**Issue by qroac** [photoprism/photoprism#4023]
I just started a fresh stack to try the features of photoprism and wanted to connect to webdav to access the first images in the library.

Adding `\\my.internal.domain.com\originals\` as windows network ressource reports: 
```
Der eingegebene Ordner ist ungültig. Wählen Sie einen anderen Ordner.
```

Because this is quite generic as I expect from a microsoft error message, I tried accessing the https webdav url with CarotDAV, I got this error:

```
Error occurred during retrieving properties.
Target: https://my.internal.domain.com/originals/
Rei.Fs.SimpleWebException: Die Anfrage wurde abgebrochen: Es konnte kein geschützter SSL/TLS-Kanal erstellt werden..
   bei Rei.Fs.Webdav.WebdavFs.GetResponse(HttpWebRequest request, Boolean notreqstream)
   bei Rei.Fs.Webdav.WebdavFs.InnerGetInfo(Uri target, DepthType depth)
   bei Rei.Fs.Webdav.WebdavFs.GetInfoAndEntries(Uri targeturi)
   bei CarotDAV.CacheManager.GetInfoAndEntries(FsBase fs, Uri targeturi, Boolean enablecache)
   bei CarotDAV.MainForm.Fs_GetInfoAndInnerEntries(Uri uri, ResourceId id, ResourceId parentid, Boolean enablecache)
```

My setup is as follows:

- Raspberry Pi 4, 4GB Ram, 4GB Swap
- letsencrypt wildcard certificates obtained with DNS challenge and acme.sh
- traefik2 using these certificates for websites on :443, works for photoprism and some other services with SNI in the browser
- photoprism app

Photoprism Compose:
```yaml
version: "3.8"
# Example Docker Compose config file for PhotoPrism (Raspberry Pi 3/4 and other ARM64-based devices)
#
# Note:
# - You have to boot your Raspberry Pi 3/4 with the parameter "arm_64bit=1" in config.txt to use our ARM64 (64-bit) image.
#   An "exec format" error will occur otherwise.
# - Try explicitly pulling the ARM64 version if you've booted your device with the "arm_64bit=1" flag and you see
#   the "no matching manifest" error on Raspberry Pi OS (Raspbian). See documentation for details.
# - Use https://dl.photoprism.app/docker/armv7/docker-compose.yml to run PhotoPrism and MariaDB on ARMv7-based devices
#   as well as Raspberry Pi OS (Raspbian) installations without 64-bit support.
# - Running PhotoPrism on a server with less than 4 GB of swap space or setting a memory/swap limit can cause unexpected
#   restarts ("crashes"), for example, when the indexer temporarily needs more memory to process large files.
# - In case you see Docker errors related to "cgroups", try adding the following parameters to /boot/firmware/cmdline.txt
#   or /boot/cmdline.txt (file location depends on the OS in use): cgroup_enable=cpuset cgroup_enable=memory cgroup_memory=1
# - If you install PhotoPrism on a public server outside your home network, please always run it behind a secure
#   HTTPS reverse proxy such as Traefik or Caddy. Your files and passwords will otherwise be transmitted
#   in clear text and can be intercepted by anyone, including your provider, hackers, and governments:
#   https://docs.photoprism.app/getting-started/proxies/traefik/
#
# Setup Guides:
# - https://docs.photoprism.app/getting-started/docker-compose/
# - https://docs.photoprism.app/getting-started/raspberry-pi/
# - https://www.photoprism.app/kb/activation
#
# Troubleshooting Checklists:
# - https://docs.photoprism.app/getting-started/troubleshooting/
# - https://docs.photoprism.app/getting-started/troubleshooting/docker/
# - https://docs.photoprism.app/getting-started/troubleshooting/mariadb/
#
# CLI Commands:
# - https://docs.photoprism.app/getting-started/docker-compose/#command-line-interface
#
# All commands may have to be prefixed with "sudo" when not running as root.
# This will point the home directory shortcut ~ to /root in volume mounts.

services:
  photoprism:
    ## Use photoprism/photoprism:preview-arm64 for testing preview builds:
    image: photoprism/photoprism:arm64
    ## Don't enable automatic restarts until PhotoPrism has been properly configured and tested!
    ## If the service gets stuck in a restart loop, this points to a memory, filesystem, network, or database issue:
    ## https://docs.photoprism.app/getting-started/troubleshooting/#fatal-server-errors
    # restart: unless-stopped
    stop_grace_period: 10s
    depends_on:
      - mariadb
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    ports:
      ## Web server port mapping in the format "Host:Container". To use a different port, change the host port
      ## on the left-hand side and keep the container port, e.g. "80:2342" (for HTTP) or "443:2342 (for HTTPS):
      - 2342:2342
    environment:
      PHOTOPRISM_ADMIN_USER: admin # admin login username
      PHOTOPRISM_ADMIN_PASSWORD: n^t7iUteazZz%Rq # initial admin password (8-72 characters)
      PHOTOPRISM_AUTH_MODE: password # authentication mode (public, password)
      PHOTOPRISM_SITE_URL: https://my.internal.domain.com/ # server URL in the format "http(s)://domain.name(:port)/(path)"
      PHOTOPRISM_DISABLE_TLS: "true" # disables HTTPS/TLS even if the site URL starts with https:// and a certificate is available
      PHOTOPRISM_DEFAULT_TLS: "true" # defaults to a self-signed HTTPS/TLS certificate if no other certificate is available
      PHOTOPRISM_ORIGINALS_LIMIT: 5000 # file size limit for originals in MB (increase for high-res video)
      PHOTOPRISM_HTTP_COMPRESSION: none # improves transfer speed and bandwidth utilization (none or gzip)
      PHOTOPRISM_WORKERS: 2 # limits the number of indexing workers to reduce system load
      PHOTOPRISM_LOG_LEVEL: info # log level: trace, debug, info, warning, error, fatal, or panic
      PHOTOPRISM_READONLY: "false" # do not modify originals directory (reduced functionality)
      PHOTOPRISM_EXPERIMENTAL: "false" # enables experimental features
      PHOTOPRISM_DISABLE_CHOWN: "false" # disables updating storage permissions via chmod and chown on startup
      PHOTOPRISM_DISABLE_WEBDAV: "false" # disables built-in WebDAV server
      PHOTOPRISM_DISABLE_SETTINGS: "false" # disables Settings in Web UI
      PHOTOPRISM_DISABLE_TENSORFLOW: "false" # disables all features depending on TensorFlow
      PHOTOPRISM_DISABLE_FACES: "false" # disables face detection and recognition (requires TensorFlow)
      PHOTOPRISM_DISABLE_CLASSIFICATION: "false" # disables image classification (requires TensorFlow)
      PHOTOPRISM_DISABLE_VECTORS: "false" # disables vector graphics support
      PHOTOPRISM_DISABLE_RAW: "false" # disables indexing and conversion of RAW images
      PHOTOPRISM_RAW_PRESETS: "false" # enables applying user presets when converting RAW images (reduces performance)
      PHOTOPRISM_JPEG_QUALITY: 85 # a higher value increases the quality and file size of JPEG images and thumbnails (25-100)
      PHOTOPRISM_DETECT_NSFW: "true" # automatically flags photos as private that MAY be offensive (requires TensorFlow)
      PHOTOPRISM_UPLOAD_NSFW: "true" # allow uploads that MAY be offensive
      # PHOTOPRISM_DATABASE_DRIVER: "sqlite"         # SQLite is an embedded database that doesn't require a server
      PHOTOPRISM_DATABASE_DRIVER: mysql # use MariaDB 10.5+ or MySQL 8+ instead of SQLite for improved performance
      PHOTOPRISM_DATABASE_SERVER: mariadb:3306 # MariaDB or MySQL database server (hostname:port)
      PHOTOPRISM_DATABASE_NAME: photoprism # MariaDB or MySQL database schema name
      PHOTOPRISM_DATABASE_USER: photoprism # MariaDB or MySQL database user name
      PHOTOPRISM_DATABASE_PASSWORD: ***# MariaDB or MySQL database user password
      PHOTOPRISM_SITE_CAPTION: "Fotospace"
      PHOTOPRISM_SITE_DESCRIPTION: "" # meta site description
      PHOTOPRISM_SITE_AUTHOR: "" # meta site author
      ## Video Transcoding (https://docs.photoprism.app/getting-started/advanced/transcoding/):
      # PHOTOPRISM_FFMPEG_ENCODER: "software"        # H.264/AVC encoder (software, intel, nvidia, apple, raspberry, or vaapi)
      # PHOTOPRISM_FFMPEG_SIZE: "1920"               # video size limit in pixels (720-7680) (default: 3840)
      # PHOTOPRISM_FFMPEG_BITRATE: "32"              # video bitrate limit in Mbit/s (default: 50)
      ## Run/install on first startup (options: update, gpu, tensorflow, davfs, clean):
      # PHOTOPRISM_INIT: "update clean"
      ## Run as a non-root user after initialization (supported: 0, 33, 50-99, 500-600, and 900-1200):
      # PHOTOPRISM_UID: 1000
      # PHOTOPRISM_GID: 1000
      # PHOTOPRISM_UMASK: 0000
      ## Share hardware devices with FFmpeg and TensorFlow (optional):
      ## See: https://www.raspberrypi.com/documentation/accessories/camera.html#driver-differences-when-using-libcamera-or-the-legacy-stack
      # devices:
      #  - "/dev/video11:/dev/video11" # Video4Linux Video Encode Device (h264_v4l2m2m)
    working_dir: /photoprism # do not change or remove
    ## Storage Folders: "~" is a shortcut for your home directory, "." for the current directory
    volumes:
      # "/host/folder:/photoprism/folder"                # Example
      - ./v/originals:/photoprism/originals # Original media files (DO NOT REMOVE)
      - ./v/import:/photoprism/import # *Optional* base folder from which files can be imported to originals
      - ./v/storage:/photoprism/storage # *Writable* storage folder for cache, database, and sidecar files (DO NOT REMOVE)
    labels:
      - com.centurylinklabs.watchtower.enable=true
      - traefik.enable=true
      - traefik.http.services.photoprism.loadbalancer.server.port=2342
      - traefik.http.routers.photoprism.entrypoints=http
      - traefik.http.routers.photoprism.rule=Host(`my.internal.domain.com`) #URL anpassen
      - traefik.http.middlewares.photoprism-https-redirect.redirectscheme.scheme=https
      - traefik.http.routers.photoprism.middlewares=grocy-https-redirect
      - traefik.http.routers.photoprism-secure.entrypoints=https
      - traefik.http.routers.photoprism-secure.rule=Host(`my.internal.domain.com`) #URL anpassen
      - traefik.http.routers.photoprism-secure.tls=true
      #- traefik.http.routers.photoprism-secure.middlewares=secHeaders@file
    networks:
      - internal
      - proxy
  ## Database Server (recommended)
  ## see https://docs.photoprism.app/getting-started/faq/#should-i-use-sqlite-mariadb-or-mysql
  mariadb:
    image: arm64v8/mariadb:10.11 # ARM64 IMAGE ONLY, DOES NOT WORK ON ARMv7, AMD or Intel
    ## If MariaDB gets stuck in a restart loop, this points to a memory or filesystem issue:
    ## https://docs.photoprism.app/getting-started/troubleshooting/#fatal-server-errors
    restart: unless-stopped
    stop_grace_period: 5s
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    command: --innodb-buffer-pool-size=256M --transaction-isolation=READ-COMMITTED
      --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
      --max-connections=512 --innodb-rollback-on-timeout=OFF
      --innodb-lock-wait-timeout=120
    ## Never store database files on an unreliable device such as a USB flash drive, an SD card, or a shared network folder:
    volumes:
      - ./v/db:/var/lib/mysql # DO NOT REMOVE
    environment:
      MARIADB_AUTO_UPGRADE: "1"
      MARIADB_INITDB_SKIP_TZINFO: "1"
      MARIADB_DATABASE: photoprism
      MARIADB_USER: photoprism
      MARIADB_PASSWORD: ***
      MARIADB_ROOT_PASSWORD: ***
    networks:
      - internal
networks:
  internal: {}
  proxy:
    external: true
```

Traefik compose: 
```yaml
version: '3'
services:
  main:
    image: traefik:latest
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /mnt/local/traefik/data/traefik.yml:/traefik.yml:ro
      - /mnt/local/traefik/data/dynamic_conf.yml:/dynamic_conf.yml
      - /mnt/local/traefik/data/acme.json:/acme.json
      - /home/pi/.acme.sh:/acme.sh:ro
    labels:
    - "traefik.enable=true"
    - "traefik.http.routers.traefik.entrypoints=http"
    - "traefik.http.routers.traefik.rule=Host(`dockpi.internal.domain.com`)"
    - "traefik.http.middlewares.traefik-auth.basicauth.users=admin:***/"
    - "traefik.http.middlewares.traefik-https-redirect.redirectscheme.scheme=https"
    - "traefik.http.routers.traefik.middlewares=traefik-https-redirect"
    - "traefik.http.routers.traefik-secure.entrypoints=https"
    - "traefik.http.routers.traefik-secure.rule=Host(`dockpi.internal.domain.com`)"
    - "traefik.http.routers.traefik-secure.middlewares=traefik-auth"
    - "traefik.http.routers.traefik-secure.service=api@internal"
    - "traefik.http.services.traefik-secure.loadbalancer.server.port=8080"
    - "providers.file.filename=/dynamic_conf.yml"

networks:
  proxy:
    external: true
```

traefik.yml
```yaml
api:
  dashboard: true
pilot:
  token: "ea75ec42-1eec-4bf3-987e-a8a0a4bd9f8a"
accessLog: {}

entryPoints:
  http:
    address: ":80"
  https:
    address: ":443"
    http:
      tls:
        certResolver: le-tls

log:
  level: DEBUG

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    #endpoint: "tcp://127.0.0.1:2375"
    swarmMode: false
    exposedByDefault: false
    network: proxy
  file:
    filename: "/dynamic_conf.yml"

certificatesResolvers:
  le-tls:
    acme:
      #caServer: https://acme-staging-v02.api.letsencrypt.org/directory
      caServer: https://acme-v02.api.letsencrypt.org/directory
      email: hostmaster@domain.com   #### hier eure E-Mail angeben ####
      storage: acme.json
      tlsChallenge: {}
      #httpChallenge:
      #  entryPoint: http
```

dynamic_conf.yml
```yaml
tls:
  options:
    default:
      minVersion: VersionTLS12

      cipherSuites:
        - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
        - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305
        - TLS_AES_128_GCM_SHA256
        - TLS_AES_256_GCM_SHA384
        - TLS_CHACHA20_POLY1305_SHA256

      curvePreferences:
        - CurveP521
        - CurveP384

      sniStrict: true
  certificates:
    - certFile: /acme.sh/internal.domain.com_ecc/internal.domain.com.cer
      keyFile: /acme.sh/internal.domain.com_ecc/internal.domain.com.key

http:
  middlewares:
    redirect-https:
      redirectscheme:
        scheme: https

    secHeadersMedium:
      headers:
        browserXssFilter: true
        frameDeny: true
        sslRedirect: true
        sslProxyHeaders:
          X-Forwarded-Proto: https
        #HSTS Configuration
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 31536000
        customFrameOptionsValue: "SAMEORIGIN"
    secHeaders:
      headers:
        browserXssFilter: true
        contentTypeNosniff: true
        frameDeny: true
        sslRedirect: true
        #HSTS Configuration
        stsIncludeSubdomains: true
        stsPreload: true
        stsSeconds: 31536000
        customFrameOptionsValue: "SAMEORIGIN"

```
