### ISSUE TITLE
Synology: Fatal glibc error "cannot get entropy for arc4random"

### ISSUE THREAD

**Issue by update-freak** [photoprism/photoprism#4339]
#### 1. What is not working as documented?
After updating [240420] to the latest docker version [240531] I tried to index a specific folder which I recently added.
Then after it finished I recognised that I can not see these newly added pictures.
In the log I saw that it was skipped due to the problem: Fatal glibc error: cannot get entropy for arc4random.

I think it's related to an to old kernel version of my Synology NAS (Linux NAS 3.10.108 #64570).

#### 2. How can we reproduce it?

0. Be sure to use a system with a kernel version of "Linux NAS 3.10.108 #64570" (or maybe even older)
1. Install the 240420 version on docker
2. Click on settings and try to index the pictures of a new added folder 
3. See error "Fatal glibc error: cannot get entropy for arc4random" in the logs

#### 3. What behavior do you expect?
No error

#### 4. What could be the cause of your problem?
I think the root cause is a too old kernel version.
This has also been reported on other software: https://github.com/jlesage/docker-freefilesync/issues/8#issuecomment-1696377382, https://github.com/MatthewVance/unbound-docker/issues/147)

#### 5. Can you provide us with example files for testing, error logs, or screenshots?
If needed I can add logs.

#### 6. Which software versions do you use?

(a) PhotoPrism version: 240531
(b) Database Type & Version: ?
(c) Operating System Types & Versions: Linux -> DSM 7.2 from Synology NAS
(d) Browser Types & Versions: Chrome (current version)
(e) Ad Blockers, Browser Plugins, and/or Firewall Software: uBlockOrigin

#### 7. On what kind of device is PhotoPrism installed?
Synology NAS DS716+

#### 8. Do you use a Reverse Proxy, Firewall, VPN, or CDN?
Yes, reverse proxy

#### 9. Docker-compose for installation
[docker-compose.txt](https://github.com/user-attachments/files/15890344/docker-compose.txt)

**Comment by lastzero** [comment]
Thanks for reporting this! Unfortunately, there's probably not much we can do about it if your kernel is very old. Is 3.10 the kernel version you are using? If it's a different version, please let us know which one.

**Comment by update-freak** [comment]
yes, exactly. I checked with uname -a my version and got Linux NAS 3.10.108 #64570
Here (https://github.com/jlesage/docker-freefilesync/issues/8#issuecomment-1696377382) for example getentropy() was removed as solution (maybe helps)

**Comment by rkmfl** [comment]
Like the OP, I'm also on Kernel 3.10.108, because I'm **limited by Synology**. This is the kernel being used with Synology's most recent DSM 7.2.xxx releases, there is no method to upgrade.

PhotoPrism continually crashes on my Synology system with the same error:
```Fatal glibc error: cannot get entropy for arc4random```

On PhotoPrism latest release: 240531-60b3a4628

**Docker Compose:**
(I have it limited to a single worker thread and dedicate 10 GB of RAM explicitly for PhotoPrism)
```
services:
  photoprism:
    deploy:
      resources:
        limits:
          memory: 10G

    image: photoprism/photoprism:latest

    restart: unless-stopped
    stop_grace_period: 10s

    depends_on:
      - mariadb
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    ports:
      - "2342:2342"

    working_dir: "/volume1/docker/photo-prism"

    volumes:
      - "/volume2/Media/Photos:/photoprism/originals"
      - "/volume1/docker/photo-prism:/photoprism/storage"

    environment:
      PHOTOPRISM_ADMIN_USER: "<<obfuscated>>"
      PHOTOPRISM_ADMIN_PASSWORD: "<<obfuscated>>"
      PHOTOPRISM_AUTH_MODE: "public"

      PHOTOPRISM_SITE_URL: "http://10.10.10.11:2342/"

      PHOTOPRISM_DISABLE_TLS: "false"
      PHOTOPRISM_DEFAULT_TLS: "true"

      PHOTOPRISM_ORIGINALS_LIMIT: 20
      PHOTOPRISM_WORKERS: 1
      PHOTOPRISM_RESAMPLE_UNCACHED: "false"
      PHOTOPRISM_THUMB_UNCACHED: "false"
      PHOTOPRISM_THUMB_SIZE: 1600
      PHOTOPRISM_THUMB_SIZE_UNCACHED: 1600
      PHOTOPRISM_JPEG_SIZE: 7680
      PHOTOPRISM_JPEG_QUALITY: 70
      PHOTOPRISM_DARKTABLE_PRESETS: "false"

      PHOTOPRISM_HTTP_COMPRESSION: "gzip"
      PHOTOPRISM_LOG_LEVEL: "info"
      PHOTOPRISM_READONLY: "false"
      PHOTOPRISM_EXPERIMENTAL: "false"
      PHOTOPRISM_DISABLE_CHOWN: "false"
      PHOTOPRISM_DISABLE_WEBDAV: "false"
      PHOTOPRISM_DISABLE_SETTINGS: "false"
      PHOTOPRISM_DISABLE_TENSORFLOW: "false"
      PHOTOPRISM_DISABLE_FACES: "false"
      PHOTOPRISM_DISABLE_CLASSIFICATION: "false"
      PHOTOPRISM_DISABLE_VECTORS: "false"
      PHOTOPRISM_DISABLE_RAW: "false"
      PHOTOPRISM_RAW_PRESETS: "false"
      PHOTOPRISM_SIDECAR_YAML: "true"
      PHOTOPRISM_SIDECAR_JSON: "false"
      PHOTOPRISM_THUMB_FILTER: "lanczos"

      PHOTOPRISM_BACKUP_ALBUMS: "true"
      PHOTOPRISM_BACKUP_DATABASE: "true"
      PHOTOPRISM_BACKUP_SCHEDULE: "0 8 * * 1"
      PHOTOPRISM_INDEX_SCHEDULE: "0 9 * * *"

      PHOTOPRISM_AUTO_INDEX: 300
      PHOTOPRISM_AUTO_IMPORT: -1
      PHOTOPRISM_DETECT_NSFW: "false"
      PHOTOPRISM_UPLOAD_NSFW: "true"

      PHOTOPRISM_DATABASE_DRIVER: "mysql"
      PHOTOPRISM_DATABASE_SERVER: "mariadb:3306"
      PHOTOPRISM_DATABASE_NAME: "<<obfuscated>>"
      PHOTOPRISM_DATABASE_USER: "<<obfuscated>>"
      PHOTOPRISM_DATABASE_PASSWORD: "<<obfuscated>>"
      PHOTOPRISM_SITE_CAPTION: "AI-Powered Photos App"
      PHOTOPRISM_SITE_DESCRIPTION: ""
      PHOTOPRISM_SITE_AUTHOR: ""

  mariadb:
    image: mariadb:11
    restart: unless-stopped
    stop_grace_period: 5s
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    command: --innodb-buffer-pool-size=512M --transaction-isolation=READ-COMMITTED --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-connections=32 --innodb-rollback-on-timeout=OFF --innodb-lock-wait-timeout=120
    volumes:
      - "/volume1/docker/photo-prism/mysql"
    environment:
      MARIADB_AUTO_UPGRADE: "1"
      MARIADB_INITDB_SKIP_TZINFO: "1"
      MARIADB_DATABASE: "<<obfuscated>>"
      MARIADB_USER: "<<obfuscated>>"
      MARIADB_PASSWORD: "<<obfuscated>>"
      MARIADB_ROOT_PASSWORD: "<<obfuscated>>"
```

**Comment by trampas75** [comment]
I have just installed PhotoPrism on my Synology 716+ NAS with Portainer and Docker and have exactly the same error:
Fatal glibc error: cannot get entropy for arc4random

This is after successfully loading 479 of about 900 folders of mainly photos with some video.
I am on the same kernel 3.10.108 and have 8GB of memory and plenty of free disk space.
Any help appreciated, thanks.

**Comment by rkmfl** [comment]
> glibc error: cannot get entropy for arc4random

In my post above, I was not able to find a solution. Instead I watched for an image where it continually crashed on the same image and deleted that specific image.

I did this for about a dozen images with problems (having to re-run and locate the image where it crashed **every time**).

After doing this, I was able to continue without the ```Fatal glibc error: cannot get entropy for arc4random``` error.

**Comment by trampas75** [comment]
Thanks for the fast reply.  I think that I can wait for a new version of PhotoPrism to appear and then try again.
Regards.

**Comment by lastzero** [comment]
It might be caused by some software / tool written in C that we use as dependency. It would help a lot to know which files or file types are causing this (e.g. RAW images). If it's file format independent, then maybe disabling TensorFlow helps (see Feature Flags in our Getting Started guide when you navigate to Config Options). As a workaround you can downgrade to the version released in April 2024, which is based on an older Linux distribution (and glibc).

**Comment by lastzero** [comment]
If the new Ubuntu Linux release we now use as base image is causing this, then I would not expect this issue to go away with an update which might require an even newer kernel. While it's also not an option to ship outdated software to everyone for the sake of compatibility, we could provide a special image for Synology users or replace / disable the dependency that's causing this (unless it's a general issue with Ubuntu 24.04 or later).

**Comment by rkmfl** [comment]
> It would help a lot to know which files or file types are causing this

I'll attach a sample image here that causes the problem.

> If it's file format independent

I believe it is file format independent. I can't be 100 certain now, but I believe it occurred with both .PNG and .JPG's in my case.

> maybe disabling TensorFlow helps 

Yes, I considered this using docker compose yaml:
```PHOTOPRISM_DISABLE_TENSORFLOW: "true"```

However, I wondered whether disabling Tensorflow might eliminate some of the ML features of PhotoPrism, which to me are the most important features.

Thank you.
![BirdPainting](https://github.com/photoprism/photoprism/assets/3689892/4584ef3c-1661-47ed-a04d-f05c7b5f1307)

**Comment by trampas75** [comment]
Looking at the log I tried deleting images and restarting indexing a few times all from the same folder.  In the end I deleted the whole folder which was from my old OnePlus Nord mobile phone, mainly jpgs.  So far PhotoPrism is still indexing!!!
So thanks for the deleting image suggestions but I will have to continue tomorrow.

**Comment by lastzero** [comment]
Temporarily disabling TensorFlow won't remove existing Labels and People. However, it might help us find what exactly is causing this. Another thing you can try is to use the "imaging" image library instead of the newly added libvips:
https://docs.photoprism.app/getting-started/config-options/#preview-images

**Comment by Bananas-Are-Yellow** [comment]
I have the exact same problem with my Synology DS1517+ (DSM version: DSM 7.2-64570 Update 3) and docker (what Synology calls the Container Manager). I installed PhotoPrism last night, so it's the latest version. It ran for many hours before I got the error:

`Fatal glibc error: cannot get entropy for arc4random`

My NAS is also using the same kernel as the OP:
```
$ uname -a
Linux diskstation 3.10.108 #64570 SMP Fri Jul 14 01:07:53 CST 2023 x86_64 GNU/Linux synology_avoton_1517+
```
I hope you guys can fix this.

**Comment by lastzero** [comment]
After googling for the error message, I found out that `getrandom()` was first available in Linux 3.17, which was released in October 2014:

- https://github.com/golang/go/issues/66821

However, Synology is still shipping Linux 3.10. It might thus be that our crypto/math libraries (or one of our dependencies) are trying to use an alternative instead? From what I know, `arc4random()` is mainly used on BSD, including macOS and iOS, so I wouldn't expect Linux 3.10 to support it?

- https://github.com/golang/go/issues/47812

If `arc4random()` is called directly by our app, it is possible that the problem can be resolved by adding a fix directly to Go, or the `math/rand/v2` and `crypto/rand` libraries we use:

- https://pkg.go.dev/math/rand/v2
- https://pkg.go.dev/crypto/rand

**Would someone with a bit of technical knowledge be able to do further research (on Google / GitHub) and try to report the issue to the go/package maintainers if needed?** It seems that other developers/users are having similar issues, so that could be a good starting point to find out more.

In addition, please make sure that your `docker-compose.yml` (or Portainer stack configuration) contains the following options, as [shown in the examples](https://dl.photoprism.app/docker/docker-compose.yml) we provide, just in case a kernel module is blocking access to the function:

```yaml
services:
  photoprism:
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
```

You should also check if there is a `libbsd` package that you can install, as it might add the missing `arc4random()` function:

- https://wiki.debian.org/arc4random
- https://tracker.debian.org/pkg/libbsd

Based on this conversation, could `arc4random()` have been added to `glibc` as well, so that this change might have broken something?

- https://lore.kernel.org/all/6bf352e9-1312-40de-4733-3219721b343c@linaro.org/t/

On a side note, am I surprised that such an old kernel is still maintained? If it is no longer actively maintained, it could also contain a long list of other issues.

**Comment by lastzero** [comment]
An updated development preview build is now available on Docker Hub, so you can test if using the latest Go version and/or adding `libbsd` makes a difference (it doesn't contain any breaking changes and should be safe to use):
- https://docs.photoprism.app/getting-started/updates/#development-preview

**Comment by trampas75** [comment]
I have had a few more "cannot get entropy for arc4random" crashes.  This may be too late to help, but each time the image causing the issue was a larger than usual jpg, for example 7063x5297 and 8.6MB.

**Comment by trampas75** [comment]
Just tried the new preview version.  Updated via Portainer, changing latest to preview.  Got the photoprism has been updated message. Still fails in the same way:
Fatal glibc error: cannot get entropy for arc4random

**Comment by update-freak** [comment]
Thanks a lot for checking and providing a test version that fast!
I tried to re-index an existing folder with jpg-files in it (komplete reinitialisation & cleaing => so both settings are ticked).
In the logs I could confirm that the re-index process was sucessfull.

 `time="2024-06-26T18:19:29Z" level=info msg="photo: updated sidecar file '2024-06-15 Hochzeit X&Y/2024-06-15 Hochzeit X&Y (9).yml'"
time="2024-06-26T18:19:29Z" level=info msg="index: updated main jpg file '2024-06-15 Hochzeit X&Y/2024-06-15 Hochzeit X&Y (9).jpg'"
time="2024-06-26T18:19:30Z" level=info msg="index: updated 45 files [3m33.351538149s]"
time="2024-06-26T18:19:33Z" level=info msg="cleanup: removed 0 index entries and deleted 0 sidecar files [1.542659ms]"
time="2024-06-26T18:19:34Z" level=info msg="cleanup: searching for orphaned cache files"
time="2024-06-26T18:21:19Z" level=info msg="cleanup: deleted 0 files from cache [1m45.763422018s]"
time="2024-06-26T18:21:22Z" level=info msg="indexierung in 325 s abgeschlossen"`

So for me it solved the problem :)

**Comment by Bananas-Are-Yellow** [comment]
The preview version didn’t work for me. It ran from 2:57 pm until 8:43 pm (similar time as yesterday) and then I got the same error about arc4random.

**Comment by trampas75** [comment]
I just managed to complete indexing on all of my photo/videos but I had to reduce the size of some more overlarge photos down to say 4000x3000 to get it through.  This with the preview version of course.

**Comment by lastzero** [comment]
**Would someone be able to do further research (on Google / GitHub) regarding this issue?**

It seems that other developers/users are having similar issues, so that could be a good starting point to find out more, e.g.:

- https://github.com/MatthewVance/unbound-docker/issues/147
- https://www.synology-forum.de/threads/unbound-probleme.131170/
- https://community.synology.com/enu/forum/1/post/187869
- https://stackoverflow.com/questions/26021181/not-enough-entropy-to-support-dev-random-in-docker-containers-running-in-boot2d

Also note that your `docker-compose.yml` (or portainer stack configuration) should include the following options as shown in [the examples we provide](https://dl.photoprism.app/docker/docker-compose.yml), e.g. in case a kernel module is blocking access to a function (some of these issues are resolved with Docker updates, so it would be good to have the [**latest Docker version installed**](https://www.reddit.com/r/synology/comments/189hgqt/docker_eol_on_synology/) as well):

```yaml
services:
  photoprism:
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
```

@update-freak I found the following additional Docker Compose options in your config file, which might cause indexing issues, e.g. if the **configured memory limit is exceeded for a short period of time** or if a dependency we use is not compatible with the `no-new-privileges` setting for some reason (e.g. in combination with the Linux kernel and Docker version you use):

```yaml
    mem_limit: 6g
    cpu_shares: 1024
    security_opt:
      - no-new-privileges=true
```

For more information on memory limits and the system requirements, see https://docs.photoprism.app/getting-started/faq/#why-is-my-configured-memory-limit-exceeded-when-indexing-even-though-photoprism-doesnt-actually-seem-to-use-that-much-memory and https://docs.photoprism.app/getting-started/#system-requirements.

**We appreciate your help as we have very limited resources and no suitable device for testing. Thank you very much!**

**Comment by trampas75** [comment]
Following on from my comments above:
Synology 716+, 8GB memory, photoprism set up via Portainer (thanks to Marius Hosting) and then updated to the preview version.  The setup includes the mem_limit 6g etc. lines mentioned above.
I have just loaded about 50,000 photos in about 900 folders and have had the arc4random issue with less than 10 photos each of which was oversized in pixel width and height.  For me the issue was definitely caused by higher than usual definition photos.

**Comment by lastzero** [comment]
If it was caused by large images, did you try without the mem_limit option to see if it makes a difference?

**Comment by rkmfl** [comment]
> If it was caused by large images, did you try without the mem_limit option to see if it makes a difference?

I think you've just stumbled upon a brilliant solution to this problem **without the technical hassle** when it's merely to support old kernels or low-memory systems.

Although the "mem_limit" option doesn't help, create a new parameter that will cause no issue in backward compatibility and it will eliminate future issues for Synology/Pi/etc or just general low-power setups.

Currently you have a maximum size for videos. Add a maximum size for images as well. Leave it zero (none) by default and recommend Synology/etc users to set it to 40 MB. I believe 40 MB is about the threshold where it becomes an issue.

Again, you're already using this for videos, it could be adjacent to that option. It's a win-win!

**Comment by trampas75** [comment]
Just to be clear.  It is not the file size that causes the issue but it is the image dimensions.
I did a test with a jpg 4000x3000 file size 5572KB which worked fine.
I then created a second jpg by doubling the dimensions to 8000x6000 file size 7983KB which caused the arc4random issue.

**Comment by lastzero** [comment]
You can limit the resolution of images that are indexed with the `PHOTOPRISM_RESOLUTION_LIMIT` config option:

- https://docs.photoprism.app/getting-started/config-options/#storage

You should also limit the number of indexing workers to 1 with the `PHOTOPRISM_INDEX_WORKERS` option, if your device has limited CPU or memory resources:

- https://docs.photoprism.app/getting-started/config-options/#indexing

Please note that the `mem_limit` option in your `docker-compose.yml` does not limit the size or resolution of media files that can be opened / indexed. All it may do is kill your PhotoPrism instance when there are memory usage spikes, e.g. due to high-resolution images or too many indexing workers.

As mentioned above, I additionally recommend to test setting the `PHOTOPRISM_THUMB_LIBRARY` option to `"imaging"` if you are using our latest release, which otherwise defaults to `"vips"` (libvips), a C image processing library that could theoretically also perform the problematic `arc4random()` call (e.g. in combination with large images):

- https://docs.photoprism.app/getting-started/config-options/#preview-images
- https://github.com/photoprism/photoprism/issues/1474

In general, `libvips` should use less memory than Imaging, since it can - from what I know - split the processing of large images into smaller parts. I would not be surprised if it uses low-level C calls for this, which could then lead to compatibility issues on older systems. We have already found out that 32-bit systems are not compatible:

- https://github.com/photoprism/photoprism/issues/4299

**Comment by trampas75** [comment]
Thanks for that info.  The resolution limit I did not test as the default is way larger than any of the failed jpgs.
However I changed the thumb library option to 'imaging', set up some 8000x6000 test images and tested indexing.
All worked perfectly!!
So the issue seems to be with using libvips as you suggested, and the solution to change to 'imaging'.
Again, many thanks.

**Comment by lastzero** [comment]
@trampas75 @update-freak Could you please inform the maintainers of the Synology configuration templates/examples that they should add `PHOTOPRISM_THUMB_LIBRARY: "imaging"`? Ideally with a note/comment that this is not required on devices with a newer kernel. Thank you very much!

If we receive no further feedback indicating that more changes (especially in any of our own code) are needed, we will  consider the issue to be resolved with this.

**Comment by Bananas-Are-Yellow** [comment]
I am testing out the `PHOTOPRISM_THUMB_LIBRARY: "imaging"` fix on my Synology DS1517+ right now, but this will take several hours to complete before I can report back.

I think some other people have followed the instructions from this article:

[Synology: Install PhotoPrism With Portainer – Marius Hosting](https://mariushosting.com/synology-install-photoprism-with-portainer/)

This is where some of the settings (like `mem_limit` and `cpu_shares`) have come from. I did not follow that article, I simply followed the documentation here:

[Docker Compose - PhotoPrism](https://docs.photoprism.app/getting-started/docker-compose/)

I started from the sample [docker-compose.yml](https://dl.photoprism.app/docker/docker-compose.yml) provided.

I suggest you add the fix to this template, with a comment, something like this:

```
  environment:
    # For hosting on a Synology NAS with kernel version 3.10, uncomment the following line:
    # PHOTOPRISM_THUMB_LIBRARY: "imaging"
    PHOTOPRISM_ADMIN_USER: "admin"                 # admin login username
    PHOTOPRISM_ADMIN_PASSWORD: "insecure"          # initial admin password (8-72 characters)
    ...
```
Maybe you could also add a red box in the docker compose installation web page, like the one you have for `PHOTOPRISM_ADMIN_PASSWORD`.

As for the Marius Lixandru article, it says at the end:

> This post was updated on Tuesday / June 11th, 2024 at 10:10 AM

This is very recent, so maybe he'll update the article. If my rescan completes successfully, I will email him with a reference to this issue.
