### ISSUE TITLE
Mysql Db does not work

### ISSUE THREAD

**Issue by gerroon** [photoprism/photoprism#446]
Hi

I uncommented the mariadb and disabled sqlite in the docker-compose file. I am getting bunch of errors see below.

```
version: '3.3'

# Example docker-compose config file for production use
# Container image on Docker Hub: https://hub.docker.com/r/photoprism/photoprism/
# To keep photoprism running, add "restart: always"
#
# Usage: docker-compose up

services:
  photoprism:
    image: photoprism/photoprism:latest
    restart: unless-stopped
    ports:
      - 2342:2342 # [local port]:[container port]
    healthcheck: # Optional
      test: "photoprism status"
      interval: 60s
      timeout: 15s
      retries: 5
    environment: # Run "photoprism help" and "photoprism config" too see all config options and current values
      PHOTOPRISM_DEBUG: "false"                      # Run in debug mode (shows additional log messages)
      PHOTOPRISM_PUBLIC: "false"                     # No authentication required (disables password protection)
      PHOTOPRISM_READONLY: "false"                   # Don't modify originals directory (reduced functionality)
      PHOTOPRISM_UPLOAD_NSFW: "true"                 # Allow uploads that MAY be offensive
      PHOTOPRISM_DETECT_NSFW: "false"                # Flag photos as private that MAY be offensive
      PHOTOPRISM_EXPERIMENTAL: "false"               # Enable experimental features
      PHOTOPRISM_SITE_URL: "http://localhost:2342/"  # Canonical / public site URL
      PHOTOPRISM_SITE_TITLE: "PhotoPrism"
      PHOTOPRISM_SITE_CAPTION: "Browse Your Life"
      PHOTOPRISM_SITE_DESCRIPTION: ""
      PHOTOPRISM_SITE_AUTHOR: ""
      PHOTOPRISM_HTTP_HOST: "0.0.0.0"
      PHOTOPRISM_HTTP_PORT: 2342
      PHOTOPRISM_SETTINGS_HIDDEN: "false"            # Users can not view or change settings
      PHOTOPRISM_ADMIN_PASSWORD: "photoprism"        # Initial admin password (can be changed in settings)
      PHOTOPRISM_DATABASE_DRIVER: "mysql"          # Using MariaDB or MySQL instead of SQLite is optional
      # PHOTOPRISM_DATABASE_DSN: "photoprism:photoprism@tcp(photoprism-db:3306)/photoprism?charset=utf8mb4,utf8&parseTime=true"
      # PHOTOPRISM_SIDECAR_JSON: "true"              # Read metadata from JSON sidecar files created by exiftool
      # PHOTOPRISM_SIDECAR_YAML: "true"              # Backup photo metadata to YAML sidecar files
      PHOTOPRISM_THUMB_FILTER: "lanczos"             # Resample filter, best to worst: blackman, lanczos, cubic, linear
      PHOTOPRISM_THUMB_UNCACHED: "false"             # Enable on-demand thumbnail rendering (high memory and cpu usage)
      PHOTOPRISM_THUMB_SIZE: 2048                    # Pre-rendered thumbnail size limit (default 2048, min 720, max 7680)
      # PHOTOPRISM_THUMB_SIZE: 4096                  # Retina 4K, DCI 4K (requires more storage); 7680 for 8K Ultra HD
      PHOTOPRISM_THUMB_SIZE_UNCACHED: 7680           # On-demand rendering size limit (default 7680, min 720, max 7680)
      PHOTOPRISM_JPEG_SIZE: 7680                     # Size limit for converted image files in pixels (720-30000)
      PHOTOPRISM_JPEG_QUALITY: 90                    # Set to 95 for high-quality thumbnails (requires more storage)
      PHOTOPRISM_DARKTABLE_PRESETS: "false"          # Use darktable presets (disables concurrent raw to jpeg conversion)
      PHOTOPRISM_STORAGE_PATH: "/photoprism/storage" # Storage PATH for generated files like cache and index
    volumes:
      - "PHOTOS:/photoprism/originals" # [local path]:[container path]
      - "~/Pictures/Import:/photoprism/import"       # [local path]:[container path] (optional)
      - "photoprism:/photoprism/storage"     # Keep cache, settings and database

  photoprism-db: # Uncomment, if you want to use MariaDB instead of SQLite
    image: mariadb:10.5 # Alternatively mysql:8.0
    restart: unless-stopped
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-connections=1024 --innodb-rollback-on-timeout=OFF --innodb-lock-wait-timeout=50
    volumes:
      - "photoprism-database:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: iUbzYZ8
      MYSQL_USER: photoprism
      MYSQL_PASSWORD: iUbzYZ8
      MYSQL_DATABASE: photoprism

volumes: # keep this
  photoprism-storage:
    driver: local
  photoprism-database:
    driver: local


```

Errors

```
photoprism-db_1  | 2020-08-05 18:19:22 0 [Note] Server socket created on IP: '::'.                                                                                                                                 
photoprism-db_1  | 2020-08-05 18:19:22 0 [Warning] 'user' entry 'root@37caa0fb5f0f' ignored in --skip-name-resolve mode.                                                                                           
photoprism-db_1  | 2020-08-05 18:19:22 0 [Warning] 'user' entry '@37caa0fb5f0f' ignored in --skip-name-resolve mode.                                                                                               
photoprism-db_1  | 2020-08-05 18:19:22 0 [Warning] 'proxies_priv' entry '@% root@37caa0fb5f0f' ignored in --skip-name-resolve mode.                                                                                
photoprism-db_1  | 2020-08-05 18:19:22 0 [Note] Reading of all Master_info entries succeeded                                                                                                                       
photoprism-db_1  | 2020-08-05 18:19:22 0 [Note] Added new Master_info '' to hash table                                                                                                                             
photoprism-db_1  | 2020-08-05 18:19:22 0 [Note] mysqld: ready for connections.                                                                                                                                     
photoprism-db_1  | Version: '10.5.4-MariaDB-1:10.5.4+maria~focal'  socket: '/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution                                                                  
photoprism_1     | time="2020-08-05T18:19:22Z" level=info msg="settings file not found: /photoprism/storage/settings/settings.yml"                                                                                 
photoprism-db_1  | 2020-08-05 18:19:22 3 [Warning] Aborted connection 3 to db: 'unconnected' user: 'unauthenticated' host: '192.168.192.3' (This connection closed normally without authentication)                
photoprism-db_1  | 2020-08-05 18:19:22 4 [Warning] Aborted connection 4 to db: 'unconnected' user: 'unauthenticated' host: '192.168.192.3' (This connection closed normally without authentication)                
photoprism-db_1  | 2020-08-05 18:19:27 5 [Warning] Aborted connection 5 to db: 'unconnected' user: 'unauthenticated' host: '192.168.192.3' (This connection closed normally without authentication)                
photoprism-db_1  | 2020-08-05 18:19:32 6 [Warning] Aborted connection 6 to db: 'unconnected' user: 'unauthenticated' host: '192.168.192.3' (This connection closed normally without authentication)                
photoprism-db_1  | 2020-08-05 18:19:37 7 [Warning] Aborted connection 7 to db: 'unconnected' user: 'unauthenticated' host: '192.168.192.3' (This connection closed normally without authentication)                
photoprism-db_1  | 2020-08-05 18:19:42 8 [Warning] Aborted connection 8 to db: 'unconnected' user: 'unauthenticated' host: '192.168.192.3' (This connection closed normally without authentication)                
photoprism-db_1  | 2020-08-05 18:19:47 9 [Warning] Aborted connection 9 to db: 'unconnected' user: 'unauthenticated' host: '192.168.192.3' (This connection closed normally without authentication)   


hotoprism-db_1  | 2020-08-05 18:21:21 27 [Warning] Aborted connection 27 to db: 'unconnected' user: 'unauthenticated' host: '192.168.192.3' (This connection closed normally without authentication)      
photoprism-db_1  | 2020-08-05 18:21:26 28 [Warning] Aborted connection 28 to db: 'unconnected' user: 'unauthenticated' host: '192.168.192.3' (This connection closed normally without authentication)
photoprism_photoprism_1 exited with code 1
photoprism_1     | time="2020-08-05T18:16:10Z" level=info msg="settings file not found: /photoprism/storage/settings/settings.yml"
photoprism_1     | time="2020-08-05T18:17:10Z" level=fatal msg="dial tcp 192.168.192.2:3306: connect: connection refused"
photoprism_1     | time="2020-08-05T18:17:22Z" level=info msg="settings file not found: /photoprism/storage/settings/settings.yml"
photoprism_1     | time="2020-08-05T18:19:22Z" level=info msg="settings file not found: /photoprism/storage/settings/settings.yml"
photoprism_1     | time="2020-08-05T18:20:22Z" level=fatal msg="commands out of sync. Did you run multiple statements at once?"
photoprism_1     | time="2020-08-05T18:20:31Z" level=info msg="settings file not found: /photoprism/storage/settings/settings.yml"
photoprism_1     | time="2020-08-05T18:21:31Z" level=fatal msg="commands out of sync. Did you run multiple statements at once?"
photoprism_1     | time="2020-08-05T18:21:40Z" level=info msg="settings file not found: /photoprism/storage/settings/settings.yml"
photoprism-db_1  | 2020-08-05 18:21:40 29 [Warning] Aborted connection 29 to db: 'unconnected' user: 'unauthenticated' host: '192.168.192.3' (This connection closed normally without authentication)
photoprism-db_1  | 2020-08-05 18:21:40 30 [Warning] Aborted connection 30 to db: 'unconnected' user: 'unauthenticated' host: '192.168.192.3' (This connection closed normally without authentication)
photoprism-db_1  | 2020-08-05 18:21:45 31 [Warning] Aborted connection 31 to db: 'unconnected' user: 'unauthenticated' host: '192.168.192.3' (This connection closed normally without authentication)
photoprism-db_1  | 2020-08-05 18:21:50 32 [Warning] Aborted connection 32 to db: 'unconnected' user: 'unauthenticated' host: '192.168.192.3' (This connection closed normally without authentication)
photoprism-db_1  | 2020-08-05 18:21:55 33 [Warning] Aborted connection 33 to db: 'unconnected' user: 'unauthenticated' host: '192.168.192.3' (This connection closed normally without authentication)
photoprism-db_1  | 2020-08-05 18:22:00 34 [Warning] Aborted connection 34 to db: 'unconnected' user: 'unauthenticated' host: '192.168.192.3' (This connection closed normally without authentication)
photoprism-db_1  | 2020-08-05 18:22:05 35 [Warning] Aborted connection 35 to db: 'unconnected' user: 'unauthenticated' host: '192.168.192.3' (This connection closed normally without authentication)
photoprism-db_1  | 2020-08-05 18:22:10 36 [Warning] Aborted connection 36 to db: 'unconnected' user: 'unauthenticated' host: '192.168.192.3' (This connection closed normally without authentication)
hotoprism-db_1  | 2020-08-05 18:21:21 27 [Warning] Aborted connection 27 to db: 'unconnected' user: 'unauthenticated' host: '192.168.192.3' (This connection closed normally without authentication)      
photoprism-db_1  | 2020-08-05 18:21:26 28 [Warning] Aborted connection 28 to db: 'unconnected' user: 'unauthenticated' host: '192.168.192.3' (This connection closed normally without authentication)
photoprism_photoprism_1 exited with code 1
photoprism_1     | time="2020-08-05T18:16:10Z" level=info msg="settings file not found: /photoprism/storage/settings/settings.yml"
photoprism_1     | time="2020-08-05T18:17:10Z" level=fatal msg="dial tcp 192.168.192.2:3306: connect: connection refused"
photoprism_1     | time="2020-08-05T18:17:22Z" level=info msg="settings file not found: /photoprism/storage/settings/settings.yml"
photoprism_1     | time="2020-08-05T18:19:22Z" level=info msg="settings file not found: /photoprism/storage/settings/settings.yml"
photoprism_1     | time="2020-08-05T18:20:22Z" level=fatal msg="commands out of sync. Did you run multiple statements at once?"
photoprism_1     | time="2020-08-05T18:20:31Z" level=info msg="settings file not found: /photoprism/storage/settings/settings.yml"
photoprism_1     | time="2020-08-05T18:21:31Z" level=fatal msg="commands out of sync. Did you run multiple statements at once?"
photoprism_1     | time="2020-08-05T18:21:40Z" level=info msg="settings file not found: /photoprism/storage/settings/settings.yml"
photoprism-db_1  | 2020-08-05 18:21:40 29 [Warning] Aborted connection 29 to db: 'unconnected' user: 'unauthenticated' host: '192.168.192.3' (This connection closed normally without authentication)
photoprism-db_1  | 2020-08-05 18:21:40 30 [Warning] Aborted connection 30 to db: 'unconnected' user: 'unauthenticated' host: '192.168.192.3' (This connection closed normally without authentication)
photoprism-db_1  | 2020-08-05 18:21:45 31 [Warning] Aborted connection 31 to db: 'unconnected' user: 'unauthenticated' host: '192.168.192.3' (This connection closed normally without authentication)
photoprism-db_1  | 2020-08-05 18:21:50 32 [Warning] Aborted connection 32 to db: 'unconnected' user: 'unauthenticated' host: '192.168.192.3' (This connection closed normally without authentication)
photoprism-db_1  | 2020-08-05 18:21:55 33 [Warning] Aborted connection 33 to db: 'unconnected' user: 'unauthenticated' host: '192.168.192.3' (This connection closed normally without authentication)
photoprism-db_1  | 2020-08-05 18:22:00 34 [Warning] Aborted connection 34 to db: 'unconnected' user: 'unauthenticated' host: '192.168.192.3' (This connection closed normally without authentication)
photoprism-db_1  | 2020-08-05 18:22:05 35 [Warning] Aborted connection 35 to db: 'unconnected' user: 'unauthenticated' host: '192.168.192.3' (This connection closed normally without authentication)
photoprism-db_1  | 2020-08-05 18:22:10 36 [Warning] Aborted connection 36 to db: 'unconnected' user: 'unauthenticated' host: '192.168.192.3' (This connection closed normally without authentication)


```
