### ISSUE TITLE
When issuing a scan getting ERRO index: database is locked in image.jpg (purge duplicate)

### ISSUE THREAD

**Issue by guysoft** [photoprism/photoprism#4485]
#### 1. What is not working as documented?

When I start the server and run a complete re-index:

I get in the logs messages such as this:
```
 2024-08-27 15:56:20 ERRO index: database is locked in sda1/snapshot/android/39AC-633A/DCIM/Camera/20200825_190100.jpg (purge duplicate)

2024-08-27 15:56:20 ERRO duplicate: database is locked in sda1/snapshot/android/39AC-633A/DCIM/Camera/20200825_190100.jpg (purge)
 ```

- ...

*Please never report [known issues](https://docs.photoprism.app/known-issues/) or [missing features](https://github.com/photoprism/photoprism/issues) as bugs, and do not submit bug reports for the purpose of getting [technical support](https://www.photoprism.app/kb/getting-support) or because you have not received a response in our [public community forums](https://github.com/photoprism/photoprism/discussions). Thank you very much!*

#### 2. How can we reproduce it?

1. Start photoprisim using docker compose (using nginx-proxy here):
```yaml
version: '3.3'

# Example docker-compose config file for production use
# Container image on Docker Hub: https://hub.docker.com/r/photoprism/photoprism/
# To keep photoprism running, add "restart: always"
#
# Usage: docker-compose up

services:
  photoprism:
    restart: always
    security_opt:
      - seccomp:unconfined
      
    image: photoprism/photoprism:latest
    platform: linux/arm64
    environment: # Run "photoprism help" and "photoprism config" too see all config options and current values
      PHOTOPRISM_URL: "https://yourhost.com/"
      PHOTOPRISM_TITLE: "PhotoPrism"
      PHOTOPRISM_SUBTITLE: "Browse your life"
      PHOTOPRISM_DESCRIPTION: "Personal Photo Management powered by Go and Google TensorFlow. Free and open-source."
      PHOTOPRISM_AUTHOR: "Anonymous"
      PHOTOPRISM_TWITTER: "@browseyourlife"
      PHOTOPRISM_IMPORT_PATH: "/home/photoprism/Pictures/Import"
      PHOTOPRISM_EXPORT_PATH: "/home/photoprism/Pictures/Export"
      PHOTOPRISM_ORIGINALS_PATH: "/home/photoprism/Pictures/Originals"
      PHOTOPRISM_UPLOAD_NSFW: "true"
      PHOTOPRISM_HIDE_NSFW: "false"
      PHOTOPRISM_EXPERIMENTAL: "false"
      PHOTOPRISM_DEBUG: "false"
      PHOTOPRISM_READONLY: "false"
      PHOTOPRISM_PUBLIC: "false"
      PHOTOPRISM_ADMIN_PASSWORD: "SECRET_PASSWORD"

      VIRTUAL_HOST: yourhost.com
      LETSENCRYPT_HOST: yourhost.com
      LETSENCRYPT_EMAIL: your@email.com
      VIRTUAL_PORT: 2342
      #- VIRTUAL_PATH=/

    volumes:
      - "/path/to/pictures:/home/photoprism/Pictures/Originals/path/to/pictures:ro"
      - "photoprism-cache:/home/photoprism/.cache/photoprism" # keep thumbnail cache
      - "photoprism-database:/home/photoprism/.local/share/photoprism/resources/database" # keep database files

volumes: # keep this
  photoprism-cache:
    driver: local
  photoprism-database:
    driver: local

networks:
  default:
    external:
      name: nginx-proxy
```
2. make sure ``/path/to/pictures`` has lots of images
3. Go to:  ``https://yourhost.com/library/index`` select "complete rescan" and start indexing

#### 3. What behavior do you expect?

Log should not have errors

#### 4. What could be the cause of your problem?

I am not sure - I tried cleaning the database and also had several upgrades, not sure how complete rescan would cause this

#### 6. Which software versions do you use?
```
PhotoPrism® CE Build [240711-2197af848](https://docs.photoprism.app/release-notes/)
```

(a) PhotoPrism Architecture & Build Number: AMD64, ARM64, ARMv7,...
arm64 docker container
(b) Database Type & Version: MariaDB, MySQL, SQLite,...
local I guess sqlite?
(c) Operating System Types & Versions: Linux, Windows, Android,...
Linux container running on top rpi os
(d) Browser Types & Versions: Firefox, Chrome, Safari on iPhone,...
n/a
(e) Ad Blockers, Browser Plugins, and/or Firewall Software?
n/a
You can find the version/build number of the app in *Settings* by scrolling to the bottom. Note that MySQL 8 support has been discontinued, see system requirements at <https://docs.photoprism.app/getting-started/#system-requirements>.

*Always provide database and operating system details if it is a backend, import, or indexing issue. Should it be a frontend issue, at a minimum we require you to provide web browser and operating system details. When reporting a performance problem, we ask that you provide us with complete information about your environment, as there may be more than one cause.*

#### 7. On what kind of device is PhotoPrism installed?

This is especially important if you are reporting a performance, import, or indexing issue. You can skip this if you're reporting a problem you found in our public demo, or if it's a completely unrelated issue, such as incorrect page layout.

(a) Device / Processor Type: Raspberry Pi 4, Intel Core i7-3770, AMD Ryzen 7 3800X,...

(b) Physical Memory & Swap Space in GB

(c) Storage Type: HDD, SSD, RAID, USB, Network Storage,...

(d) Anything else that might be helpful to know?

*Always provide device, memory, and storage details if you have a backend, performance, import, or indexing issue.*

#### 8. Do you use a Reverse Proxy, Firewall, VPN, or CDN?
Using Nginx-proxy for docker https://hub.docker.com/r/nginxproxy/nginx-proxy

If yes, please specify type and version. You can skip this if you are reporting a completely unrelated issue.

*Always provide this information when you have a reliability, performance, or frontend problem, such as failed uploads, connection errors, broken thumbnails, or video playback issues.*

**Using NGINX?** Please also provide the configuration and/or consider asking the NGINX community for advice as we do not specialize in supporting their product. Docs can be found at <https://docs.photoprism.app/getting-started/proxies/nginx/>.
