### ISSUE TITLE
Infrastructure: Sqlite to MariaDB upgrade path and vice versa

### ISSUE THREAD

**Issue by SchoolGuy** [photoprism/photoprism#495]
As an administrator I'd like to be able to upgrade a small instance to a bigger one and vice versa so that I have the optimum resource usage of my infra structure.

I have set up my personal instance now and noticed that when I am browsing while importing pictures are re-indexing my library I often hit the toast "Database locked". I am currently having 22,5k Images of which approx a fifth are CR3 and CR2 RAWs.

Since I initially was not expecting that my library is getting this big I am now in the need of an upgrade path. Since the metadata I am editing is not written back (which is fine in my eyes), I don't want to lose all my data when switching to a "full" MariaDB instance.

The same goes in my eyes vice versa. If I am a user how sets up a MariaDB instance and there is not that much going on then I think it would be good if there would be a way to "downgrade" to an SQLite based instance.

In scenarios with little resources I think this could be especially beneficial.

**Comment by lastzero** [comment]
Research regarding standard tools / best practices should be performed as a first step. 

Basically, you have to translate SQL dialects, which I expect to be solved; ideally there are existing open-source tools that just need to be explained in our docs.

**Comment by SchoolGuy** [comment]
@lastzero So the theory is that one can just convert this automatically and then exchange the dsn and you are good to go?

**Comment by SchoolGuy** [comment]
If that is really the case then I will create a PR for that once I do that on my instance. If it is more then docs then I would prefer to not do it as I have no experience with Go and Vue.js so far.

**Comment by lastzero** [comment]
> @lastzero So the theory is that one can just convert this automatically and then exchange the dsn and you are good to go?

Yes, that should be it. Of course we can as well write code that copies schemas & rows, but why reinvent the wheel?

Commands can be put in a little shell script though, so that users don't need to copy & paste every line from the docs.

**Comment by SchoolGuy** [comment]
@lastzero Then assign me to this one. I will probably do it in the next month if that is enough...

**Comment by lastzero** [comment]
Thank you for taking a look at this 🌈

**Comment by SchoolGuy** [comment]
Okay I found a small python project which seems promising: https://github.com/techouse/sqlite3-to-mysql

Once I am at home and I can try it, I will report back.

**Comment by SchoolGuy** [comment]
To make this actually usable I will package both tools at:

- https://build.opensuse.org/package/show/home:SchoolGuy/mysql-to-sqlite3
-https://build.opensuse.org/package/show/home:SchoolGuy/sqlite3-to-mysql

Over time I will need to do that cross distro so the Debian and Redhatish people are also getting this.  Because when we use that in production we don't want to depend on dev dependencies as we currently do in many cases.

**Comment by SchoolGuy** [comment]
Also I will try to get photoprism into our distro but that is another thing...

**Comment by SchoolGuy** [comment]
So both packages are now in a openSUSE OBS Devel Project. Thus I will try to hand them to Factory/Tumbleweed and then Advanced Users may use them to convert the database. I will write some docs on how to do that exactly when I am done with packaging.

**Comment by SchoolGuy** [comment]
Okay so I have a littlebit more time now to work on this. Since the tool is in Python, I can't just call it directly in Go. Thus I would appreciate the way you desire this to go forward. The tools themselves expect the MySQL DB to be running.

I see the following options:

- I can just call it in the Go code as an external program and take care of everything (complex solution).
- I can just add Docs to Photoprism and document how example commands with the two tools would look like (easy solution).

@lastzero @graciousgrey Opinions?

In any case I will try to convert my old sqlite database into a MariaDB to see how easy the process in any case is.

**Comment by lastzero** [comment]
Docs are fine! We can later automate this in code if needed.

**Comment by SchoolGuy** [comment]
Okay process is as follows for sqlite --> MariaDB:

- Install <https://github.com/techouse/sqlite3-to-mysql> on your Host.
- Do a `docker-compose down` on your current stack.
- Add the current snippet of the MariaDB to your Sqlite Photoprism Compose with the addition of the extra `ports` section where you expose Port 3306 to the Host. In my case this looked like Attachment 1.
- Stop Photoprism via `docker-compose stop photoprism`.
- On the Host now run `sudo sqlite3mysql -f <PATH_TO_STORAGE_MOUNT>/storage/index.db -d photoprism -u root --mysql-password 'please_change'`
- Stop the whole Container Stack with `docker-compose down`
- Edit your `docker-compose.yml` so it uses the MariaDB database you added before. Don't forget to remove the `ports` section of the MariaDB Container.
- Start your stack again with `docker-compose up -d`

Attachment 1:

```yml
mariadb:
    image: mariadb:10.5
    container_name: mariadb
    restart: unless-stopped
    ports:
      - 3306:3306
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    command: mysqld --transaction-isolation=READ-COMMITTED --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-connections=512 --innodb-rollback-on-timeout=OFF --innodb-lock-wait-timeout=50
    volumes: # Don't remove permanent storage for index database files!
      - "./database:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: please_change
      MYSQL_DATABASE: photoprism
      MYSQL_USER: photoprism
      MYSQL_PASSWORD: insecure
```

---

I tried this with a test container with 10 images and it went flawlessly. No warnings, no errors. Just a normal startup.
