### ISSUE TITLE
docker: can't create /photoprism/storage/sidecar: please check configuration and permissions

### ISSUE THREAD

**Issue by dekiesel** [photoprism/photoprism#556]
Hi,

I am trying to install pp using docker-compose but I ran into this strange issue:

```
photoprism_1  | time="2020-10-20T12:31:05+02:00" level=debug msg="mkdir /photoprism/storage/sidecar: required key not available"
photoprism_1  | time="2020-10-20T12:31:05+02:00" level=fatal msg="can't create /photoprism/storage/sidecar: please check configuration and permissions"
photoprism_1  | time="2020-10-20T12:31:08+02:00" level=debug msg="mkdir /photoprism/storage/sidecar: required key not available"
photoprism_1  | time="2020-10-20T12:31:08+02:00" level=fatal msg="can't create /photoprism/storage/sidecar: please check configuration and permissions"
photoprism_photoprism_1 exited with code 0
photoprism_1  | time="2020-10-20T12:31:10+02:00" level=debug msg="mkdir /photoprism/storage/sidecar: required key not available"
photoprism_1  | time="2020-10-20T12:31:10+02:00" level=fatal msg="can't create /photoprism/storage/sidecar: please check configuration and permissions"
```

Here is my compose file (mariadb part omitted for brevity):

```
services:
  photoprism:
    image: photoprism/photoprism:latest
    restart: unless-stopped
    # Uncomment and edit the following line to set a specific user / group id:
    user: "${UID}:${GID}"
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    ports:
      - 2342:2342 # [local port]:[container port]

    # Run "photoprism help" and "photoprism config" too see all config options and current values:
    environment: # Run "photoprism help" and "photoprism config" too see all config options and current values
      PHOTOPRISM_ADMIN_PASSWORD: "myr00tpw"     # Initial admin password: PLEASE CHANGE!
      PHOTOPRISM_DEBUG: "true"                      # Run in debug mode (shows additional log messages)
      PHOTOPRISM_PUBLIC: "false"                     # No authentication required (disables password protection)
      PHOTOPRISM_READONLY: "false"                   # Don't modify originals directory (reduced functionality)
      PHOTOPRISM_UPLOAD_NSFW: "true"                 # Allow uploads that MAY be offensive
      PHOTOPRISM_DETECT_NSFW: "true"                # Flag photos as private that MAY be offensive
      PHOTOPRISM_EXPERIMENTAL: "false"               # Enable experimental features
      PHOTOPRISM_SITE_URL: "http://localhost:2342/"  # Canonical / public site URL
      PHOTOPRISM_SITE_TITLE: "PhotoPrism"
      PHOTOPRISM_SITE_CAPTION: "Browse Your Life"
      PHOTOPRISM_SITE_DESCRIPTION: ""
      PHOTOPRISM_SITE_AUTHOR: ""
      PHOTOPRISM_HTTP_HOST: "0.0.0.0"
      PHOTOPRISM_HTTP_PORT: 2342
      PHOTOPRISM_SETTINGS_HIDDEN: "false"            # Users can not view or change settings
      #PHOTOPRISM_DATABASE_DRIVER: "sqlite"           # SQLite is an embedded database that doesn't require a server
      PHOTOPRISM_DATABASE_DRIVER: "mysql"          # Use MariaDB (or MySQL) instead of SQLite for improved performance
      PHOTOPRISM_DATABASE_DSN: "photoprism:insecure@tcp(mariadb:3306)/photoprism?charset=utf8mb4,utf8&parseTime=true"
      PHOTOPRISM_SIDECAR_JSON: "true"                # Automatically create JSON sidecar files using Exiftool
      PHOTOPRISM_SIDECAR_YAML: "true"                # Automatically backup metadata to YAML sidecar files
      PHOTOPRISM_THUMB_FILTER: "lanczos"             # Resample filter, best to worst: blackman, lanczos, cubic, linear
      PHOTOPRISM_THUMB_UNCACHED: "false"             # Enable on-demand thumbnail rendering (high memory and cpu usage)
      PHOTOPRISM_THUMB_SIZE: 2048                    # Pre-rendered thumbnail size limit (default 2048, min 720, max 7680)
      # PHOTOPRISM_THUMB_SIZE: 4096                  # Retina 4K, DCI 4K (requires more storage); 7680 for 8K Ultra HD
      PHOTOPRISM_THUMB_SIZE_UNCACHED: 7680           # On-demand rendering size limit (default 7680, min 720, max 7680)
      PHOTOPRISM_JPEG_SIZE: 7680                     # Size limit for converted image files in pixels (720-30000)
      PHOTOPRISM_JPEG_QUALITY: 92                    # Set to 95 for high-quality thumbnails (25-100)
      PHOTOPRISM_DARKTABLE_PRESETS: "false"          # Use darktable presets (disables concurrent raw to jpeg conversion)
      # You may optionally set user, group and/or file permissions using environment variables:
      #UID: 1000
      #GID: 1000
      #UMASK: 0000
    volumes:
      # Storage folder for settings, index & sidecar files (DON'T REMOVE):
      - "${storage}:/photoprism/storage"
      # Your personal photo and video collection ([local path]:[container path]):
      - "${photos}:/photoprism/originals"
      - /etc/localtime:/etc/localtime:ro
```

I can see that the "storage folder is being created on the host filesystem with 777-permissions by root so I don't know why creating the sidecar folders isn't possible.
