### ISSUE TITLE
Videos: Some avc1 files can't be played in Safari

### ISSUE THREAD

**Issue by robflate** [photoprism/photoprism#603]
When clicking a video in Safari (mobile and desktop), the lightbox video player pops up but is black with the error;

`Media error: Format(s) not supported or source(s) not found`

Below the error is a Download File link which correctly downloads the video.

Doing the same thing on Chrome or Firefox successfully plays the video in the popup player.

The popup player in Safari correctly shows the popup in portrait or landscape depending on the video.

This happens on all videos such as .mp4 files from an iPhone (MPEG-4 AVC).

**Comment by lastzero** [comment]
What versions of Safari and macOS?

**Comment by robflate** [comment]
Tested on;

macOS 10.15.7 with Safari 14.0
macOS 1.0.1 with Safari 14.0.1
iOS 12.4.8

**Comment by lastzero** [comment]
We need to debug this further. Video files are more complex than images, especially in that there are multiple container & codec formats that can be combined. Not all combinations supported on all devices / browsers.

**Comment by lastzero** [comment]
For further debugging, it will be helpful to get the video file metadata as JSON, grouped by type:

```
exiftool -g -j FILENAME
```

**Comment by robflate** [comment]
```
[{
  "SourceFile": "IMG_2534.MOV",
  "ExifTool": {
    "ExifToolVersion": 10.80,
    "Warning": "[minor] The ExtractEmbedded option may find more tags in the movie data"
  },
  "File": {
    "FileName": "IMG_2534.MOV",
    "Directory": ".",
    "FileSize": "66 MB",
    "FileModifyDate": "2020:10:31 11:50:39+00:00",
    "FileAccessDate": "2020:11:14 14:26:29+00:00",
    "FileInodeChangeDate": "2020:11:01 22:14:53+00:00",
    "FilePermissions": "rw-r-----",
    "FileType": "MOV",
    "FileTypeExtension": "mov",
    "MIMEType": "video/quicktime"
  },
  "QuickTime": {
    "MajorBrand": "Apple QuickTime (.MOV/QT)",
    "MinorVersion": "0.0.0",
    "CompatibleBrands": ["qt  "],
    "MovieDataSize": 69412416,
    "MovieDataOffset": 36,
    "MovieHeaderVersion": 0,
    "CreateDate": "2020:10:31 11:50:39",
    "ModifyDate": "2020:10:31 11:51:14",
    "TimeScale": 600,
    "Duration": "0:00:34",
    "PreferredRate": 1,
    "PreferredVolume": "100.00%",
    "PreviewTime": "0 s",
    "PreviewDuration": "0 s",
    "PosterTime": "0 s",
    "SelectionTime": "0 s",
    "SelectionDuration": "0 s",
    "CurrentTime": "0 s",
    "NextTrackID": 5,
    "TrackHeaderVersion": 0,
    "TrackCreateDate": "2020:10:31 11:50:39",
    "TrackModifyDate": "2020:10:31 11:51:14",
    "TrackID": 1,
    "TrackDuration": "0:00:34",
    "TrackLayer": 0,
    "TrackVolume": "100.00%",
    "ImageWidth": 1920,
    "ImageHeight": 1080,
    "CleanApertureDimensions": "1920x1080",
    "ProductionApertureDimensions": "1920x1080",
    "EncodedPixelsDimensions": "1920x1080",
    "GraphicsMode": "ditherCopy",
    "OpColor": "32768 32768 32768",
    "CompressorID": "avc1",
    "SourceImageWidth": 1920,
    "SourceImageHeight": 1080,
    "XResolution": 72,
    "YResolution": 72,
    "CompressorName": "H.264",
    "BitDepth": 24,
    "VideoFrameRate": 29.983,
    "Balance": 0,
    "AudioFormat": "mp4a",
    "AudioBitsPerSample": 16,
    "AudioSampleRate": 44100,
    "LayoutFlags": "Mono",
    "AudioChannels": 1,
    "PurchaseFileFormat": "mp4a",
    "MatrixStructure": "1 0 0 0 1 0 0 0 1",
    "ContentDescribes": "Track 1",
    "MediaHeaderVersion": 0,
    "MediaCreateDate": "2020:10:31 11:50:39",
    "MediaModifyDate": "2020:10:31 11:51:14",
    "MediaTimeScale": 600,
    "MediaDuration": "0:00:34",
    "MediaLanguageCode": "und",
    "GenMediaVersion": 0,
    "GenFlags": "0 0 0",
    "GenGraphicsMode": "ditherCopy",
    "GenOpColor": "32768 32768 32768",
    "GenBalance": 0,
    "HandlerClass": "Data Handler",
    "HandlerVendorID": "Apple",
    "HandlerDescription": "Core Media Data Handler",
    "MetaFormat": "mebx",
    "HandlerType": "Metadata Tags",
    "GPSCoordinates": "51 deg 52' 58.44\" N, 2 deg 25' 30.36\" W, 151.575 m Above Sea Level",
    "Make": "Apple",
    "Model": "iPhone 6",
    "Software": "12.4.8",
    "CreationDate": "2020:10:31 11:50:39+00:00"
  },
  "Composite": {
    "AvgBitrate": "15.9 Mbps",
    "GPSAltitude": "151.575 m",
    "GPSAltitudeRef": "Above Sea Level",
    "GPSLatitude": "51 deg 52' 58.44\" N",
    "GPSLongitude": "2 deg 25' 30.36\" W",
    "ImageSize": "1920x1080",
    "Megapixels": 2.1,
    "Rotation": 0,
    "GPSPosition": "51 deg 52' 58.44\" N, 2 deg 25' 30.36\" W"
  }
}]

```
Notes:
- I tested the same file in [PhotoStructure](https://photostructure.com) and [FileRun](https://www.filerun.com) using Safari and it plays.
- I've left the GPS info in because it's a public place and non identifying.

**Comment by lastzero** [comment]
That's strange, avc1 files should work. Just tested it with Safari. Can you also provide up with a test file? If you like via email to hello@photoprism.org or post a link where we can download it :)

**Comment by lastzero** [comment]
I've just spent a lot of time improving video transcoding. Let us know if you still have issues after upgrading. Also try re-indexing your videos.

Fresh Docker images available very soon: https://docs.photoprism.app/getting-started/updates/#development-preview

**Comment by robflate** [comment]
Thanks. I pulled the new image and reindexed but still have the issue. I've emailed an example video to hello@photoprism.org with the subject `Video file Photoprism github issue 603`.

Normally I'd assume it was an issue with my setup but the fact it plays on Photoprism in Chrome suggests otherwise. Anyway, hopefully I'm not being dumb and wasting your time!

**Comment by lastzero** [comment]
Works for me... latest build uses a more explicit content type header... if you just pulled, you should already have it... maybe a system or browser setting, that gets in your way? I know mov avc1 files don't play in every browser, but Safari and Chrome work for me on a Mac:

![video](https://user-images.githubusercontent.com/301686/101999465-9dee2100-3cdd-11eb-953f-8a96a3b4da73.jpg)

**Comment by robflate** [comment]
Thanks for testing. I just tried a different mac with macOS 10.15.2 and Safari 13.0.4 to see if I had a system/browser setting getting in the way. I also tried a different ISP. I've tried accessing Photoprism through my reverse proxy and locally. The video just never plays in Safari. When I click the play button I get the following logs;

```
time="2020-12-13T00:45:07Z" level=debug msg="GET /api/v1/videos/d87ff8054ad2a419e286693c71a78deb0d1c96a9/public/avc (206) [2.339848ms]"
time="2020-12-13T00:45:07Z" level=debug msg="GET /api/v1/videos/d87ff8054ad2a419e286693c71a78deb0d1c96a9/public/avc (206) [89.038591ms]"
time="2020-12-13T00:45:07Z" level=debug msg="GET /api/v1/videos/d87ff8054ad2a419e286693c71a78deb0d1c96a9/public/avc (206) [2.102472ms]"
```
I will try setting up PhotoPrism from scratch and testing with this single video but other than that I just can't think what could be the problem.

Just in case there's some obvious issue you can see, here's my compose;

```
  photoprism_db:
    container_name: photoprism_db
    image: ghcr.io/linuxserver/mariadb:latest
    restart: always
    networks:
      - t2_proxy
    command: mysqld --transaction-isolation=READ-COMMITTED --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-connections=512 --innodb-rollback-on-timeout=OFF --innodb-lock-wait-timeout=50
    security_opt:
      - no-new-privileges:true
    ports:
      - "3306:3306"
    volumes:
      - ./config/photoprism_db:/config
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      PUID: 1000
      PGID: 1000
      TZ: Europe/London
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: photoprism
      MYSQL_USER: photoprism
      MYSQL_PASSWORD: photoprism

  photoprism:
    image: photoprism/photoprism:latest
    container_name: photoprism
    restart: unless-stopped
    networks:
      - t2_proxy
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    ports:
      - "2342:2342"
    volumes:
      - /media/user/htpc09/Media/Photos/iCloud:/photoprism/originals
      - ./config/photoprism:/photoprism/storage
    environment:
      PHOTOPRISM_DEBUG: "true"
      PHOTOPRISM_PUBLIC: "false"
      PHOTOPRISM_READONLY: "false"
      PHOTOPRISM_UPLOAD_NSFW: "true"
      PHOTOPRISM_DETECT_NSFW: "false"
      PHOTOPRISM_EXPERIMENTAL: "false"
      PHOTOPRISM_SITE_URL: "https://photoprism.example.com"
      PHOTOPRISM_SITE_TITLE: "PhotoPrism"
      PHOTOPRISM_SITE_CAPTION: "Browse Your Life"
      PHOTOPRISM_SITE_DESCRIPTION: ""
      PHOTOPRISM_SITE_AUTHOR: ""
      PHOTOPRISM_HTTP_HOST: "0.0.0.0"
      PHOTOPRISM_HTTP_PORT: 2342
      PHOTOPRISM_SETTINGS_HIDDEN: "false"
      PHOTOPRISM_DATABASE_DRIVER: "mysql"
      PHOTOPRISM_DATABASE_DSN: "photoprism: photoprism@tcp(photoprism_db:3306)/photoprism?charset=utf8mb4,utf8&parseTime=true"
      PHOTOPRISM_SIDECAR_JSON: "true"
      PHOTOPRISM_SIDECAR_YAML: "true"
      PHOTOPRISM_THUMB_FILTER: "lanczos"
      PHOTOPRISM_THUMB_UNCACHED: "false"
      PHOTOPRISM_THUMB_SIZE: 2048
      PHOTOPRISM_THUMB_SIZE_UNCACHED: 7680
      PHOTOPRISM_JPEG_SIZE: 7680
      PHOTOPRISM_JPEG_QUALITY: 95
      PHOTOPRISM_DARKTABLE_PRESETS: "false"
      PHOTOPRISM_STORAGE_PATH: "/photoprism/storage"
      PHOTOPRISM_ORIGINALS_LIMIT: 5000
      UID: 1000
      GID: 1000
    labels:
      - "traefik.enable=true"
      ## HTTP Routers
      - "traefik.http.routers.photoprism-rtr.entrypoints=https"
      - "traefik.http.routers.photoprism-rtr.rule=Host(`photoprism.example.com`)"
      ## Middlewares
      - "traefik.http.routers.photoprism-rtr.middlewares=chain-oauth@file"
      ## HTTP Services
      - "traefik.http.routers.photoprism-rtr.service=photoprism-svc"
      - "traefik.http.services.photoprism-svc.loadbalancer.server.port=2342"
      ## HTTP Routers Auth Bypass
      - "traefik.http.routers.photoprism-rtr-bypass.entrypoints=https"
      - "traefik.http.routers.photoprism-rtr-bypass.rule=Host(`photoprism.example.com`) && PathPrefix(`/s`,`/api`)"
      - "traefik.http.routers.photoprism-rtr-bypass.priority=100"
      - "traefik.http.routers.photoprism-rtr-bypass.service=photoprism-svc"
      - "traefik.http.routers.photoprism-rtr-bypass.middlewares=chain-no-auth@file"

```
Thanks again.
