### ISSUE TITLE
Albums are lost on re-install

### ISSUE THREAD

**Issue by CyanBC** [photoprism/photoprism#721]
If I remove and reinstall the docker instance of photoprism I lose all album information. I do not modify anything between removal and reinstall.
![image](https://user-images.githubusercontent.com/16420413/102642779-86ada880-41a1-11eb-8884-f3fc722a3e4b.png)

If I check mariadb I can see the photos_albums, and album tables are properly filled out before remove/reinstall.
![image](https://user-images.githubusercontent.com/16420413/102642478-169f2280-41a1-11eb-99d5-598fadb0a684.png)

![image](https://user-images.githubusercontent.com/16420413/102642541-333b5a80-41a1-11eb-97ec-bc22e326cf60.png)

After removal and reinstall I log into photoprism from my browser and re-scan (Complete Rescan NOT selected) then I can see some previous albums (not all), the the photos_albums is empty.
![image](https://user-images.githubusercontent.com/16420413/102643372-8530b000-41a2-11eb-9f21-31e2c1336650.png)
but also no albums show up in the albums page.
![image](https://user-images.githubusercontent.com/16420413/102643465-abeee680-41a2-11eb-8e30-da78a2d585bb.png)

I'm concerned that upgrading to newer versions would also cause a loss of album information.

I use the ARM64 (odroid N2+) image with mariadb.

My docker-compose.yaml:

```
version: '3.5'

services:
  photoprism:
    image: photoprism/photoprism-arm64
    container_name: photoprism
    restart: unless-stopped

    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    ports:
      - 8097:8097 # [local port]:[container port]

    # Run "photoprism help" and "photoprism config" too see all config options and current values:
    environment:
      PHOTOPRISM_ADMIN_PASSWORD: "photoprism"     # Initial admin password: PLEASE CHANGE!
      PHOTOPRISM_DEBUG: "false"                      # Run in debug mode (shows additional log messages)
      PHOTOPRISM_PUBLIC: "true"                     # No authentication required (disables password protection)
      PHOTOPRISM_READONLY: "false"                   # Don't modify originals directory (reduced functionality)
      PHOTOPRISM_UPLOAD_NSFW: "true"                 # Allow uploads that MAY be offensive
      PHOTOPRISM_DETECT_NSFW: "true"                 # Flag photos as private that MAY be offensive
      PHOTOPRISM_EXPERIMENTAL: "false"               # Enable experimental features
      PHOTOPRISM_SITE_URL: "http://localhost:8097/"  # Canonical / public site URL
      PHOTOPRISM_SITE_TITLE: "PhotoPrism"
      PHOTOPRISM_SITE_CAPTION: ""
      PHOTOPRISM_SITE_DESCRIPTION: ""
      PHOTOPRISM_SITE_AUTHOR: ""
      PHOTOPRISM_HTTP_HOST: "0.0.0.0"
      PHOTOPRISM_HTTP_PORT: 8097
      PHOTOPRISM_SETTINGS_HIDDEN: "false"            # Users can not view or change settings
      PHOTOPRISM_DATABASE_DRIVER: "mysql"          # Use MariaDB instead of SQLite for improved performance
      PHOTOPRISM_DATABASE_SERVER: "mariadb-photo:3306"
      PHOTOPRISM_DATABASE_NAME: "photoprism"
      PHOTOPRISM_DATABASE_USER: "photoprism"
      PHOTOPRISM_DATABASE_PASSWORD: "photoprism"
      PHOTOPRISM_SIDECAR_JSON: "true"                # Automatically create JSON sidecar files using Exiftool
      PHOTOPRISM_SIDECAR_YAML: "true"                # Automatically backup metadata to YAML sidecar files
      PHOTOPRISM_THUMB_FILTER: "lanczos"             # Resample filter, best to worst: blackman, lanczos, cubic, linear
      PHOTOPRISM_THUMB_UNCACHED: "false"             # Enable on-demand thumbnail rendering (high memory and cpu usage)
      PHOTOPRISM_THUMB_SIZE: 2048                    # Pre-rendered thumbnail size limit (default 2048, min 720, max 7680)
      PHOTOPRISM_THUMB_SIZE_UNCACHED: 7680           # On-demand rendering size limit (default 7680, min 720, max 7680)
      PHOTOPRISM_JPEG_SIZE: 7680                     # Size limit for converted image files in pixels (720-30000)
      PHOTOPRISM_JPEG_QUALITY: 92                    # Set to 95 for high-quality thumbnails (25-100)
      PHOTOPRISM_DARKTABLE_PRESETS: "false"          # Use darktable presets (disables concurrent raw to jpeg conversion)

    volumes:
      # Storage folder for settings, index & sidecar files (DON'T REMOVE):
      - "/usbdrives/OldSSD/photoprism/config:/photoprism/storage"
      # Your personal photo and video collection ([local path]:[container path]):
      - "/usbdrives/OldSSD/photoprism/originals:/photoprism/originals"
      # Mounting the import folder is optional (see docs):
      - "/usbdrives/OldSSD/photoprism/Import:/photoprism/import"
      
# Uncomment the following lines to use MariaDB instead of SQLite for improved performance & scalability:
  mariadb:
    image: mariadb
    container_name: mariadb-photo
    restart: unless-stopped
    command: mysqld --transaction-isolation=READ-COMMITTED --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-connections=512 --innodb-rollback-on-timeout=OFF --innodb-lock-wait-timeout=50
    volumes:
      - "/usbdrives/OldSSD/photoprism/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: photoprism
      MYSQL_USER: photoprism
      MYSQL_PASSWORD: photoprism
      MYSQL_DATABASE: photoprism
```
