### ISSUE TITLE
mariadb docker won't start due to inability to check config

### ISSUE THREAD

**Issue by jmburges** [photoprism/photoprism#748]
Hi all! I'm on an ARM64 System on a chip computer (Odroid C2) and downloaded the arm64 `docker-compose.yml` from the docs. I then modified my volumes to point to the photos and did a `docker-compose up`. The mariadb container is unable to start though. Here is the full log output

```
Starting photoprism_photoprism_1 ... done
Starting photoprism_mariadb_1    ... done
Attaching to photoprism_mariadb_1, photoprism_photoprism_1
mariadb_1     | 2020-12-27 13:32:36+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 1:10.5.8+maria~focal started.
mariadb_1     | 2020-12-27 13:32:37+00:00 [ERROR] [Entrypoint]: mysqld failed while attempting to check config
mariadb_1     |         command was: mysqld --transaction-isolation=READ-COMMITTED --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-connections=512 --innodb-rollback-on-timeout=OFF --innodb-lock-wait-timeout=50 --verbose --help --log-bin-index=/tmp/tmp.AI8ZIs8qWo
mariadb_1     | 
mariadb_1     | 2020-12-27 13:32:40+00:00 [ERROR] [Entrypoint]: mysqld failed while attempting to check config
mariadb_1     |         command was: mysqld --transaction-isolation=READ-COMMITTED --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-connections=512 --innodb-rollback-on-timeout=OFF --innodb-lock-wait-timeout=50 --verbose --help --log-bin-index=/tmp/tmp.VVFiTb9wGK
mariadb_1     | 
photoprism_mariadb_1 exited with code 1
mariadb_1     | 2020-12-27 13:32:44+00:00 [ERROR] [Entrypoint]: mysqld failed while attempting to check config
mariadb_1     |         command was: mysqld --transaction-isolation=READ-COMMITTED --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-connections=512 --innodb-rollback-on-timeout=OFF --innodb-lock-wait-timeout=50 --verbose --help --log-bin-index=/tmp/tmp.h6Gsw0aFu1
mariadb_1     | 
^CGracefully stopping... (press Ctrl+C again to force)
Stopping photoprism_photoprism_1 ... done
Stopping photoprism_mariadb_1    ... done
```

and here is my `docker-compose.yml`

```
version: '3.5'

# Example Docker Compose config file for PhotoPrism (Raspberry Pi / ARM64)
#
# Documentation : https://docs.photoprism.org/getting-started/raspberry-pi/
# Docker Hub URL: https://hub.docker.com/r/photoprism/photoprism-arm64/
#
# Please run behind a reverse proxy like Caddy, Traefik or Nginx if you need HTTPS / SSL support
# e.g. when running PhotoPrism on a public server outside your home network.
#
# Usage: docker-compose up

services:
  photoprism:
    image: photoprism/photoprism-arm64:latest
    # Only enable restart and healthcheck once your installation is properly
    # configured as it otherwise gets stuck in a restart loop:
    # restart: unless-stopped
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    ports:
      - 2342:2342 # [local port]:[container port]
    # Uncomment the following lines to enable regular health checks (causes automatic restarts, be careful):
    # healthcheck:
    #   test: ["CMD", "photoprism", "status"]
    #   interval: 60s
    #   timeout: 15s
    #   retries: 5
    # Run "photoprism help" and "photoprism config" in a terminal too see all config options and current values:
    environment:
      PHOTOPRISM_HTTP_PORT: 2342
      PHOTOPRISM_ADMIN_PASSWORD: "insecure"          # PLEASE CHANGE: This is your initial admin password
      PHOTOPRISM_DEBUG: "false"                      # Run in debug mode (shows additional log messages)
      PHOTOPRISM_PUBLIC: "false"                     # No authentication required (disables password protection)
      PHOTOPRISM_READONLY: "false"                   # Don't modify originals directory (reduced functionality)
      PHOTOPRISM_DISABLE_WEBDAV: "false"             # Disable built-in WebDAV server
      PHOTOPRISM_DISABLE_SETTINGS: "false"           # Users can not view or change settings
      PHOTOPRISM_DISABLE_TENSORFLOW: "false"         # Don't use TensorFlow for image classification
      PHOTOPRISM_DETECT_NSFW: "false"                # Flag photos as private that MAY be offensive
      PHOTOPRISM_UPLOAD_NSFW: "true"                 # Allow uploads that MAY be offensive
      # PHOTOPRISM_DATABASE_DRIVER: "sqlite"         # SQLite is an embedded database that doesn't require a server
      PHOTOPRISM_DATABASE_DRIVER: "mariadb"            # Use MariaDB (or MySQL) instead of SQLite for improved performance
      PHOTOPRISM_DATABASE_SERVER: "mariadb:3306"     # MariaDB database server (hostname:port)
      PHOTOPRISM_DATABASE_NAME: "photoprism"         # MariaDB database schema name
      PHOTOPRISM_DATABASE_USER: "photoprism"         # MariaDB database user name
      PHOTOPRISM_DATABASE_PASSWORD: "insecure"       # MariaDB database user password
      PHOTOPRISM_SITE_URL: "http://localhost:2342/"  # Public PhotoPrism URL
      PHOTOPRISM_SITE_TITLE: "PhotoPrism"
      PHOTOPRISM_SITE_CAPTION: "Browse Your Life"
      PHOTOPRISM_SITE_DESCRIPTION: ""
      PHOTOPRISM_SITE_AUTHOR: ""
      # You may optionally set a user / group id using environment variables if your Docker version or NAS does not
      # support this natively (see next example):
      # UID: 1000
      # GID: 1000
      # UMASK: 0000
    # Uncomment and edit the following line to set a specific user / group id (native):
    # user: "1000:1000"
    volumes:
      # Your photo and video files ([local path]:[container path]):
      - "/media/e33f7af5-eb55-478e-ab75-6040bddac379/Photos:/photoprism/originals"
      # Multiple folders can be indexed by mounting them as sub-folders of /photoprism/originals:
      # - "/mnt/Family:/photoprism/originals/Family"    # [folder_1]:/photoprism/originals/[folder_1]
      # - "/mnt/Friends:/photoprism/originals/Friends"  # [folder_2]:/photoprism/originals/[folder_2]
      # Mounting an import folder is optional (see docs):
      # - "~/Import:/photoprism/import"
      # Permanent storage for settings, index & sidecar files (DON'T REMOVE):
      - "./storage:/photoprism/storage"

  mariadb:
    image: mariadb:10.5
    restart: unless-stopped
    command: mysqld --transaction-isolation=READ-COMMITTED --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-connections=512 --innodb-rollback-on-timeout=OFF --innodb-lock-wait-timeout=50
    volumes:
      # Permanent storage for index database files (DON'T REMOVE):
      - "./storage/mariadb:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: insecure
      MYSQL_DATABASE: photoprism
      MYSQL_USER: photoprism
      MYSQL_PASSWORD: insecure

# Uncomment the following lines to upgrade automatically, whenever there is a new Docker image available:
#
#  watchtower:
#    image: containrrr/watchtower
#    restart: unless-stopped
#    volumes:
#      - "/var/run/docker.sock:/var/run/docker.sock"
```

Any ideas? I'm on ubuntu 20.04
