### ISSUE TITLE
Docker - indexing causes container to be killed

### ISSUE THREAD

**Issue by voarsh2** [photoprism/photoprism#762]
After mounting my mountpoint for my photo collecting and running index, I get full CPU usage, I check the logs and the last thing it does is index a video file and the container seems to die.

![image](https://user-images.githubusercontent.com/60437695/103233794-dd4f7b00-4935-11eb-8a8c-2bdd55ed5377.png)

**Comment by lastzero** [comment]
Do you have 4 GB of RAM and some swap configured?

**Comment by voarsh2** [comment]
> Do you have 4 GB of RAM and some swap configured?

Yes.
Just a quick question, my docker-compose file doesn't mention any database, and when I look on the file system I don't see anything:
![image](https://user-images.githubusercontent.com/60437695/103234568-eb060000-4937-11eb-9184-7d66a0a0e200.png)

I will try a separate Docker installation of this again and see how it goes - uploading (manually) ANY file seems to not work.

**Comment by lastzero** [comment]
We modified our examples over time. Unclear what docker-compose.yml you're using. Please download and adapt the latest version from dl.photoprism.org.

**Comment by lastzero** [comment]
Reducing the original size limit or the number of workers (as documented) might help as well.

**Comment by lastzero** [comment]
If you have 8 logical CPU cores, you might need more than 4 GB of RAM. This is a minimal requirement for 2 cores.

**Comment by voarsh2** [comment]
> If you have 8 logical CPU cores, you might need more than 4 GB of RAM. This is a minimal requirement for 2 cores.

Thanks for your help. I have 16 CPU cores and 16 GB's RAM - I checked the docker image in a separate VM.
I was able to modify compare the official compose and mine, and somehow the database part was missing!
I uploaded a file and it was saved properly.

I will test my NAS/indexing again and update/close this issue.

**Comment by lastzero** [comment]
What RAM and CPU cores does that VM have configured?

**Comment by voarsh2** [comment]
> What RAM and CPU cores does that VM have configured?

I allocated this:
![image](https://user-images.githubusercontent.com/60437695/103235952-471e5380-493b-11eb-982a-d99682eb6bf4.png)

**Comment by lastzero** [comment]
I suggest reducing the number of cores to match the RAM.

**Comment by voarsh2** [comment]
> I suggest reducing the number of cores to match the RAM.

I will look to do this.
My issue was resolved.

I'll contact HomeLabOS to fix their docker-compose file - since this is why I had issues with photoprism.

**Comment by voarsh2** [comment]
Just dropping this here: https://github.com/photoprism/photoprism/issues/766

It seems when I restart the docker container the DB gets wiped, seemingly.


```
---
version: '3'


services:
  app:
    # REQUIRED
    image: photoprism/photoprism:latest
    restart: unless-stopped
    ports:
      - 2342:2342
    environment: # Run "photoprism help" and "photoprism config" too see all config options and current values
      PHOTOPRISM_URL: "192.168.100.101"
      PHOTOPRISM_TITLE: "PhotoPrism"
      PHOTOPRISM_SUBTITLE: "Browse your life"
      PHOTOPRISM_DESCRIPTION: "Personal Photo Management powered by Go and Google TensorFlow. Free and open-source."
      #PHOTOPRISM_AUTHOR: "Anonymous"
      #PHOTOPRISM_TWITTER: "@browseyourlife"
      #PHOTOPRISM_UPLOAD_NSFW: "true"
      #PHOTOPRISM_HIDE_NSFW: "false"
      #PHOTOPRISM_EXPERIMENTAL: "false"
      #PHOTOPRISM_DEBUG: "false"
      #PHOTOPRISM_READONLY: "false"
      #PHOTOPRISM_PUBLIC: "false"
      # Plain text or bcrypt hash (escape "$" with "$$")
      PHOTOPRISM_ADMIN_PASSWORD: "*****"
      # Plain text only (username "photoprism")
      PHOTOPRISM_WEBDAV_PASSWORD: "*****"
      PHOTOPRISM_THUMB_UNCACHED: "true"
      PHOTOPRISM_CACHE_PATH: "/photoprism/cache"
    volumes:
      - "/shared/odrive/Photos:/photoprism/originals" # :
      - "/shared/odrive/Photos/PhotoPrismImport:/photoprism/import" # : (optional)
      - "/shared/photoprismcache/thumbnails/:/photoprism/cache" # keep thumbnail cache
      - "/var/homelabos/ownphotos/db/:/photoprism/database" # keep database files


  mariadb:
    image: mariadb:10.5
    restart: unless-stopped
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    command: mysqld --transaction-isolation=READ-COMMITTED --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-connections=512 --innodb-rollback-on-timeout=OFF --innodb-lock-wait-timeout=50
    volumes: # Don't remove permanent storage for index database files!
      - "/var/homelabos/photoprism/database:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: *****
      MYSQL_DATABASE: photoprism
      MYSQL_USER: photoprism
      MYSQL_PASSWORD: *****
```

I cannot see why restarting the container is making the database refresh.

**Comment by lastzero** [comment]
/photoprism/storage is not mounted and the database server, schema and user name don't seem set. Compare this with our original Docker Compose examples.

**Comment by voarsh2** [comment]
> /photoprism/storage is not mounted

volumes 
     - "/shared/photoprismstorage:/photoprism/storage"

 > and the database server
      - "/var/homelabos/photoprism/database/:/photoprism/database" # keep database files


> schema and user name don't seem set. 
```
  mariadb:
    image: mariadb:10.5
    restart: unless-stopped
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    command: mysqld --transaction-isolation=READ-COMMITTED --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-connections=512 --innodb-rollback-on-timeout=OFF --innodb-lock-wait-timeout=50
    volumes: # Don't remove permanent storage for index database files!
      - "/var/homelabos/photoprism/database:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: ***
      MYSQL_DATABASE: photoprism
      MYSQL_USER: photoprism
      MYSQL_PASSWORD:  ***
```

They seem pretty much the same?

https://github.com/photoprism/photoprism/blob/develop/docker/examples/docker-compose.yml

But still, after adding files, and restarting the container the changes aren't written to the DB. They get lost.

**Comment by voarsh2** [comment]
That's embarrassing.
It was a permissions problem!

Sorry about that

**Comment by voarsh2** [comment]
So, I was checking my indexing, and found that I got a lot of database locks, and I thought it was impossible to happen on MYSQL/MariaDB.
So I looked inside the container: 
![image](https://user-images.githubusercontent.com/60437695/103300680-59f65e00-49f7-11eb-9398-b48acb3edb29.png)
Is it what I think it is? SQLLite?

/photoprism/database is empty:
![image](https://user-images.githubusercontent.com/60437695/103300725-76929600-49f7-11eb-9448-deb42744d14e.png)

Outside my container, on the disk:
![image](https://user-images.githubusercontent.com/60437695/103300752-88743900-49f7-11eb-8ff9-7fae6c787d7a.png)

![image](https://user-images.githubusercontent.com/60437695/103300761-945ffb00-49f7-11eb-9150-58955c428b4b.png)

Am I correct in assuming, that although the MariaDB container is running, that it is not actually using MYSQL/MariaDB?

**Comment by lastzero** [comment]
As mentioned earlier, your database server, schema and user name are NOT configured in your docker-compose.yml - compare it with our example on https://dl.photoprism.org/docker please :)

**Comment by voarsh2** [comment]
> As mentioned earlier, your database server, schema and user name are NOT configured in your docker-compose.yml - compare it with our example on https://dl.photoprism.org/docker please :)

I have compared the files.


docker-compose[15679]: app_1      | time="2020-12-29T17:23:29Z" level=fatal msg="dial tcp: lookup photoprism-db on 127.0.0.11:53: no such host"

I added:
```

      PHOTOPRISM_DATABASE_NAME: "photoprism"         # MariaDB database schema name
      PHOTOPRISM_DATABASE_DRIVER: "mariadb"            # Use MariaDB (or MySQL) instead of SQLite for improved performance
      PHOTOPRISM_DATABASE_SERVER: "127.0.0.1:3306"     # MariaDB database server (hostname:port)

  mariadb:
    image: mariadb:10.5
    network_mode: host
```

**Comment by lastzero** [comment]
Please use the exact same values as in our example, except of course the passwords - which you should change. `PHOTOPRISM_DATABASE_DSN` must be removed as it is deprecated for configuring databases other than SQLite.

```yaml
services:
  photoprism:
    # ...other config values...
    environment: 
      PHOTOPRISM_DATABASE_SERVER: "mariadb:3306"     # MariaDB database server (hostname:port)
      PHOTOPRISM_DATABASE_NAME: "photoprism"         # MariaDB database schema name
      PHOTOPRISM_DATABASE_USER: "photoprism"         # MariaDB database user name
      PHOTOPRISM_DATABASE_PASSWORD: "insecure"       # MariaDB database user password

mariadb:
    image: mariadb:10.5
    restart: unless-stopped
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    command: mysqld --transaction-isolation=READ-COMMITTED --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-connections=512 --innodb-rollback-on-timeout=OFF --innodb-lock-wait-timeout=50
    volumes: # Don't remove permanent storage for index database files!
      - "./database:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: please_change
      MYSQL_DATABASE: photoprism
      MYSQL_USER: photoprism
      MYSQL_PASSWORD: insecure
```

**Comment by voarsh2** [comment]
> Please use the exact same values as in our example, except of course the passwords - which you should change. `PHOTOPRISM_DATABASE_DSN` must be removed as it is deprecated for configuring databases other than SQLite.

I have replaced it entirely.

Seems photoprism image is not compatible with my OS. I'll need to use my previous one:

photoprism_1  | standard_init_linux.go:211: exec user process caused "exec format error"

**Comment by voarsh2** [comment]
After replacing the image, replacing using the exact docker-compose.yml you specified:

```
Attaching to photoprism_photoprism_1, photoprism_mariadb_1
mariadb_1     | 2020-12-29 18:10:50 0 [Note] mysqld: O_TMPFILE is not supported on /tmp (disabling future attempts)
mariadb_1     | 2020-12-29 18:10:50 0 [Note] InnoDB: Initializing buffer pool, total size = 256M, instances = 1, chunk size = 128M
mariadb_1     | 2020-12-29 18:10:50 0 [Note] InnoDB: Completed initialization of buffer pool
mariadb_1     | 2020-12-29 18:10:50 0 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
mariadb_1     | 201229 18:10:51 mysqld_safe Logging to syslog.
mariadb_1     | 2020-12-29 18:10:51 0 [Note] InnoDB: 128 out of 128 rollback segments are active.
mariadb_1     | 2020-12-29 18:10:51 0 [Note] InnoDB: Creating shared tablespace for temporary tables
mariadb_1     | 2020-12-29 18:10:51 0 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
mariadb_1     | 2020-12-29 18:10:51 0 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
mariadb_1     | 2020-12-29 18:10:51 0 [Note] InnoDB: Waiting for purge to start
mariadb_1     | 201229 18:10:51 mysqld_safe Starting mysqld daemon with databases from /config/databases
mariadb_1     | 2020-12-29 18:10:51 0 [Note] InnoDB: 10.4.17 started; log sequence number 60976; transaction id 20
mariadb_1     | 2020-12-29 18:10:51 0 [Note] InnoDB: Loading buffer pool(s) from /config/databases/ib_buffer_pool
mariadb_1     | 2020-12-29 18:10:51 0 [Note] Plugin 'FEEDBACK' is disabled.
mariadb_1     | 2020-12-29 18:10:51 0 [Note] InnoDB: Buffer pool(s) load completed at 201229 18:10:51
mariadb_1     | 2020-12-29 18:10:51 0 [Note] Server socket created on IP: '::'.
mariadb_1     | 2020-12-29 18:10:51 0 [Note] Reading of all Master_info entries succeeded
mariadb_1     | 2020-12-29 18:10:51 0 [Note] Added new Master_info '' to hash table
mariadb_1     | 2020-12-29 18:10:51 0 [Note] mysqld: ready for connections.
mariadb_1     | Version: '10.4.17-MariaDB-1:10.4.17+maria~bionic-log'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution
photoprism_1  | time="2020-12-29T18:11:46Z" level=fatal msg="dial tcp: lookup photoprism-db on 127.0.0.11:53: no such host"
```

(I am using     image: photoprism/photoprism:latest)


```
version: '3.5'

# Example Docker Compose config file for PhotoPrism (Raspberry Pi / ARM64)
#
# Documentation : https://docs.photoprism.org/getting-started/raspberry-pi/
# Docker Hub URL: https://hub.docker.com/r/photoprism/photoprism-arm64/
#
# Please run behind a reverse proxy like Caddy, Traefik or Nginx if you need HTTPS / SSL support
# e.g. when running PhotoPrism on a public server outside your home network.
#
# DOCKER COMPOSE COMMAND REFERENCE
# ---------------------------------------------------------------
# Update:   sudo docker-compose pull photoprism
# Stop:     sudo docker-compose stop photoprism
# Start:    sudo docker-compose up -d photoprism
# Logs:     sudo docker-compose logs --tail=20
# Terminal: sudo docker-compose exec photoprism bash
# Help:     sudo docker-compose exec photoprism photoprism help
# Config:   sudo docker-compose exec photoprism photoprism config

services:
  photoprism:
    image: photoprism/photoprism:latest
    # Only enable automatic restarts once your installation is properly
    # configured as it otherwise may get stuck in a restart loop:
    # https://docs.photoprism.org/getting-started/faq/#why-is-photoprism-getting-stuck-in-a-restart-loop
    # restart: unless-stopped
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    ports:
      - 2342:2342 # [local port]:[container port]
    environment:
      PHOTOPRISM_HTTP_PORT: 2342
      PHOTOPRISM_ADMIN_PASSWORD: "***"          # PLEASE CHANGE: This is your initial admin password
      PHOTOPRISM_WORKERS: 2                          # Limit the number of indexing workers to reduce system load
      PHOTOPRISM_DEBUG: "false"                      # Run in debug mode (shows additional log messages)
      PHOTOPRISM_PUBLIC: "false"                     # No authentication required (disables password protection)
      PHOTOPRISM_READONLY: "false"                   # Don't modify originals directory (reduced functionality)
      PHOTOPRISM_DISABLE_WEBDAV: "false"             # Disable built-in WebDAV server
      PHOTOPRISM_DISABLE_SETTINGS: "false"           # Users can not view or change settings
      PHOTOPRISM_DISABLE_TENSORFLOW: "false"         # Don't use TensorFlow for image classification
      PHOTOPRISM_DETECT_NSFW: "false"                # Flag photos as private that MAY be offensive
      PHOTOPRISM_UPLOAD_NSFW: "true"                 # Allow uploads that MAY be offensive
      # PHOTOPRISM_DATABASE_DRIVER: "sqlite"         # SQLite is an embedded database that doesn't require a server
      PHOTOPRISM_DATABASE_DRIVER: "mysql"            # Use MariaDB (or MySQL) instead of SQLite for improved performance
      PHOTOPRISM_DATABASE_SERVER: "mariadb:3306"     # MariaDB database server (hostname:port)
      PHOTOPRISM_DATABASE_NAME: "photoprism"         # MariaDB database schema name
      PHOTOPRISM_DATABASE_USER: "photoprism"         # MariaDB database user name
      PHOTOPRISM_DATABASE_PASSWORD: "***"       # MariaDB database user password
      PHOTOPRISM_SITE_URL: "http://192.168.100.101:2342/"  # Public PhotoPrism URL
      PHOTOPRISM_SITE_TITLE: "PhotoPrism"
      PHOTOPRISM_SITE_CAPTION: "Browse Your Life"
      PHOTOPRISM_SITE_DESCRIPTION: ""
      PHOTOPRISM_SITE_AUTHOR: ""
      # You may optionally set a user / group id using environment variables if your Docker version or NAS does not
      # support this natively (see next example):
      # UID: 1000
      # GID: 1000
      # UMASK: 0000
    # Uncomment and edit the following line to set a specific user / group id (native):
    # user: "1000:1000"

      PHOTOPRISM_THUMB_UNCACHED: "true"
      PHOTOPRISM_CACHE_PATH: "/photoprism/cache"
    volumes:
      - "/shared/odrive/Photos:/photoprism/originals" # [local path]:[container path]
      - "/shared/odrive/Photos/PhotoPrismImport:/photoprism/import" # [local path]:[container path] (optional)
      - "/shared/photoprismcache/thumbnails/:/photoprism/cache" # keep thumbnail cache
      - "/var/homelabos/photoprism/database/:/photoprism/database" # keep database files
      - "/shared/photoprismstorage:/photoprism/storage"

  mariadb:
    image: linuxserver/mariadb:latest
    restart: unless-stopped
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    command: mysqld --transaction-isolation=READ-COMMITTED --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-connections=512 --innodb-rollback-on-timeout=OFF --innodb-lock-wait-timeout=50
    volumes: # Don't remove permanent storage for index database files!
      - "/var/homelabos/photoprism/database:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: ***
      MYSQL_DATABASE: photoprism
      MYSQL_USER: photoprism
      MYSQL_PASSWORD: ***

# Uncomment the following lines to upgrade automatically, whenever there is a new Docker image available:
#
#  watchtower:
#    image: containrrr/watchtower
#    restart: unless-stopped
#    volumes:
#      - "/var/run/docker.sock:/var/run/docker.sock"
```

**Comment by lastzero** [comment]
Thought this is an Intel compatible processor? The database part now seems to use the MariaDB image we recommend for ARM64, not AMD64...

**Comment by voarsh2** [comment]
> Thought this is an Intel compatible processor? 

To be honest, I am not sure what that means.
The LXC is 
![image](https://user-images.githubusercontent.com/60437695/103305471-215c8180-4a03-11eb-814b-7cb89c37b5b4.png)

Recommend/not recommend, it's not connecting, and I've no idea why....

**Comment by voarsh2** [comment]
Perhaps it would be better if I just installed MariaDB separately?

**Comment by lastzero** [comment]
Why aren't you using `mariadb:10.5` as shown in my example, which I asked you to copy exactly? 🙃

**Comment by voarsh2** [comment]
|

> Why aren't you using `mariadb:10.5` as shown in my example, which I asked you to copy exactly? 🙃

If you look at what I posted, I am using mariadb:10.5

```
  mariadb:
    image: mariadb:10.5
    restart: unless-stopped
    security_opt:
      - seccomp:unconfined
      - apparmor:unconfined
    command: mysqld --transaction-isolation=READ-COMMITTED --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --max-connections=512 --innodb-rollback-on-timeout=OFF --innodb-lock-wait-timeout=50
    volumes: # Don't remove permanent storage for index database files!
      - "/var/homelabos/photoprism/database:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: ***
      MYSQL_DATABASE: photoprism
      MYSQL_USER: photoprism
      MYSQL_PASSWORD: ***
```
