### ISSUE TITLE
(Docker) Disabling cache or moving it inside my NAS

### ISSUE THREAD

**Issue by voarsh2** [photoprism/photoprism#766]
My docker-compose contains:

```
      PHOTOPRISM_THUMB_UNCACHED: "true"
      PHOTOPRISM_CACHE_PATH: "/photoprism/cache"
    volumes:
      - "/shared/odrive/Photos:/photoprism/originals" # [local path]:[container path]
      - "/shared/odrive/Photos/PhotoPrismImport:/photoprism/import" # [local path]:[container path] (optional)
      - "/shared/odrive/Photos/thumbnails/:/photoprism/cache" # keep thumbnail cache
      - "/var/homelabos/ownphotos/db/:/photoprism/database" # keep database files
```

I was hoping to put the cache/thumbnails inside the photos folder (where the photos are). My computer drive is full and I can't be having photoprism generating thumbnails on the system drive.
Before this change my docker-compose file was like this:

```
    volumes:
      - "/shared/odrive/Photos:/photoprism/originals" # [local path]:[container path]
      - "/shared/odrive/Photos/PhotoPrismImport:/photoprism/import" # [local path]:[container path] (optional)
      - "/var/homelabos/ownphotos/thumbnails/:/photoprism/cache" # keep thumbnail cache
      - "/var/homelabos/ownphotos/db/:/photoprism/database" # keep database files
```
![image](https://user-images.githubusercontent.com/60437695/103259878-2550bb00-4993-11eb-8beb-033d0703a6df.png)
It seems the /photoprism/storage/cache was empty, but it must be generating thumbnails, and I can't seem to find where they are.
