### ISSUE TITLE
Operating Photoprism behind authentication proxy with PHOTOPRISM_PUBLIC=true

### ISSUE THREAD

**Issue by voigt** [photoprism/photoprism#811]
Hi Photoprism Team,

first of all I'd like to thank you for all of your efforts resulting into such a great product!

I'm currently evaluating Photoprism for personal use and intend to run it behind [Pomerium](https://github.com/pomerium/pomerium) as an authentication proxy (simply as I secure most of my personal services with it). The entire setup roughly depends on: Traefik -> Pomerium -> Photoprism.

This works just fine - I set `PHOTOPRISM_PUBLIC=true`, so Photoprism doesn't need to handle any auth.

Now I discovered, that Photoprism provides a sharing functionality which exposes Albums via `<host>/s/<id>`. Therefore I excluded the path `/s` from authentication - the Pomerium [policy](https://www.pomerium.io/reference/#policy) looks something like this:

```
policy:
  - from: https://traefik.christophvoigt.com
    to: http://0.0.0.0:8080
    allowed_users:
      - <...>
  - from: https://photo.christophvoigt.com
    to: http://0.0.0.0:2342
    prefix: /s
    allow_websockets: true
    allow_public_unauthenticated_access: true
  - from: https://photo.christophvoigt.com
    to: http://0.0.0.0:2342
    allow_websockets: true
    allowed_users:
      - <...>
```

The rule works as expected, unfortunately the shared album does not load properly:

<img width="964" alt="grafik" src="https://user-images.githubusercontent.com/2982698/103529412-e97f8f00-4e85-11eb-8187-2dd9da4923e9.png">

As the reason I identified a request to `/api/v1/session`.

<img width="1392" alt="grafik" src="https://user-images.githubusercontent.com/2982698/103529746-82160f00-4e86-11eb-9f0c-7bdbb74520d2.png">

Allowing `/api/v1/session` will lead to an additional request to `/api/v1/albums`. Allowing this path obviously exposes more than I want :)

I'm totally aware, that Photoprism actually relies on its own auth for sharing (so this is not even an edge case). Though I'd kindly ask for answers to the following questions:

1. Is there any option I might have overseen? I thought about running an additional read-only instance of Photoprism, working with the same database - is there anything obvious why this would not work?
3. Are there any plans to deliver prerendered albums that do not rely on additional authenticated api-requests from the client?

Otherwise, I simply need to wait for #782 and thank you for your time :)
