### ISSUE TITLE
Download: Add UI for album download settings

### ISSUE THREAD

**Issue by graciousgrey** [photoprism/photoprism#848]
**As an Admin, I want to be able to configure the file names and types of downloads for single files and album archives through the UI under Settings > Content.**

The new UI toggles allow users to adjust the same settings that can already be changed through `settings.yml`:
- https://docs.photoprism.app/getting-started/config-files/settings/#download
- https://docs.photoprism.app/getting-started/config-files/settings/#albums

These settings allow you to change the default sort order for newly created albums, as well as configure or disallow downloads of entire albums:

```yaml
Albums:
  Download:
    Name: share
    Disabled: false
    Originals: true
    MediaRaw: false
    MediaSidecar: false
  Order:
    Album: oldest
    Folder: added
    Moment: oldest
    State: newest
    Month: oldest
```

**Acceptance Criteria:**

- [ ] Add settings to UI
- [x] Update documentation
- [x] Write unit tests
