### ISSUE TITLE
Segmentation fault on start of Docker container

### ISSUE THREAD

**Issue by rcdailey** [photoprism/photoprism#89]
Using latest on `develop` (SHA1: 6cf39ebd677aecf3a6af42f5dacccc5df0d897ce), I have my own `docker-compose.yml` as shown:

```yml
version: '3.7'

services:
  photoprism:
    build:
      context: source
      dockerfile: docker/photoprism/Dockerfile
    image: photoprism/photoprism
    #restart: always
    network_mode: bridge
    user: $UID:$GID
    ports:
    - 50180:80
    volumes:
    - /media/photo/photoprism:/srv/photoprism/photos
    - ./cache:/srv/photoprism/cache # thumbnail cache
    - ./database:/srv/photoprism/database # database files
    environment:
    - PHOTOPRISM_DEBUG=true
    - PHOTOPRISM_SERVER_MODE=debug
    - PHOTOPRISM_IMPORT_PATH=/srv/photoprism/photos/import
    - PHOTOPRISM_EXPORT_PATH=/srv/photoprism/photos/export
    - PHOTOPRISM_ORIGINALS_PATH=/srv/photoprism/photos/originals
```

I have the repository cloned at directory `source` next to my YML file. I get this segmentation fault when I do `docker-compose up` after doing a `docker-compose build`:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x7c3eb7]

goroutine 1 [running]:
github.com/photoprism/photoprism/internal/fsutil.ExpandedFilename(0x191acb6, 0x1e, 0xb, 0x191acb6)
    /go/src/github.com/photoprism/photoprism/internal/fsutil/file.go:25 +0x37
github.com/photoprism/photoprism/internal/context.NewConfig(0xc000430420, 0xc00043c7b8)
    /go/src/github.com/photoprism/photoprism/internal/context/config.go:68 +0xda
github.com/photoprism/photoprism/internal/commands.startAction(0xc000430420, 0x0, 0xc000430420)
    /go/src/github.com/photoprism/photoprism/internal/commands/start.go:42 +0x40
github.com/urfave/cli.HandleAction(0x1655600, 0x19902a8, 0xc000430420, 0xc000240400, 0x0)
    /go/pkg/mod/github.com/urfave/cli@v1.20.0/app.go:490 +0xc8
github.com/urfave/cli.Command.Run(0x18f1a51, 0x5, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1905092, 0x11, 0x0, ...)
    /go/pkg/mod/github.com/urfave/cli@v1.20.0/command.go:210 +0x9a2
github.com/urfave/cli.(*App).Run(0xc0000d8820, 0xc0000ce000, 0x2, 0x2, 0x0, 0x0)
    /go/pkg/mod/github.com/urfave/cli@v1.20.0/app.go:255 +0x687
main.main()
    /go/src/github.com/photoprism/photoprism/cmd/photoprism/photoprism.go:33 +0x309
```

**Comment by lastzero** [comment]
Ok, so if your source is up-to-date it looks like the current user can't be found for any reason. We need to implement error handling in file.go line 24 for that case. Do you want to send a pull request?

**Comment by lastzero** [comment]
Added error handling. Let me know if this fixed it.

**Comment by lastzero** [comment]
At least I didn't try so far... would it be possible to fix the permissions somethow and try again?

**Comment by rcdailey** [comment]
Permissions are already correct on the host, specifically where the volumes
are concerned.

**Comment by lastzero** [comment]
Just noticed that you mount the db and cache volumes from your host:

```
- ./cache:/srv/photoprism/cache # thumbnail cache
- ./database:/srv/photoprism/database # database files
```
Why? In that case, permissions & case sensitivity can be an issue. Also performance might suffer (at least on a Mac).

**Comment by rcdailey** [comment]
I do it this way so I can directly access the files if needed, and also so
I can control permissions manually. I cannot do either of these without
trickery if they are true docker volumes. Not to mention that it's too easy
to remove docker volumes, IMHO. And important data should not go into
docker volumes for this reason (only data that is easily reproduced or
redownloaded, such as cache but not database).

Anyway, I'm not asking you to agree with how I'm doing it, just know that I
do this with 10 other distinct docker containers and it works fine. The
issue is likely that your entrypoint script is running commands that only
work when you're root. However, now they are running as a non-privileged
user inside the container. So your container logic and processes will need
to handle both root and non-root users.

**Comment by rcdailey** [comment]
I think there's 2 principles that most containers usually follow:

1. Do not support changes between UID/GID between multiple sessions using the same volume.
2. Allow root and non-root users to be specified for running services.

What number 1 means is that if I start my container with UID 1000, you assume that UID will never change. So if I start as UID 2000 after files have been created in volumes and I get permission errors, that's something I need to fix myself. Some containers do things like `sudo chown -R` but this is situational.

For number 2, I've seen two approaches:

1. Use `--user` with `docker run` or `user:` with Docker Compose. This runs your entrypoint as that UID/GID.
1. Do not use `--user`, and instead provide environment variables (e.g. `PHOTOPRISM_UID` and `PHOTOPRISM_GID`, which the user specifies when they start the container.

In the second case, it works a bit like this:

1. Container is started
1. Container entrypoint is executed as **root** user
1. Perform root-level setup as-needed (initialize volumes, download/install stuff, `chmod`, etc)
1. Execute your service (photoprism in this case) using an explicit UID/GID (pulling these values from the aforementioned environment variables the user provided to the container).

This approach is generally required if you still need root for certain tasks required to initialize the container, but don't affect the host machine in any significant way (e.g. writes files to volumes as root that the user in turn can't access on the host).

Both of these solutions address file permissions problems in volumes, which is generally the biggest issue you see. Imagine someone mapping an NFS mounted-volume on the host to the container. NFS is pretty permission sensitive, so if it's creating files with the root UID, that might cause failures or other problems.

If you need a real world example, look at the LinuxServer.io containers. They have a pretty neat framework set up to run init services under specific UID/GID.

**Comment by lastzero** [comment]
Thank you very much for the overview! 👍 

I'll have a closer look when I find the time... A pull request would be really amazing. I'm slowly running out of food as I spent the last 6 months working for free on various open-source projects.

**Comment by lastzero** [comment]
> I saw your previous question

Haha, yes, I thought I can figure this out myself. Thanks for the clarification. I'll leave this issue open so that someone can pick it up.

**Comment by scottjl** [comment]
Just heard about Photoprism and wanted to check it out, crashes with a segfault immediately on launch, can't even get any logging information out of it. Any assistance would be appreciated, including my compose file, environment is running Ubuntu 18.04, Docker 19.03.1 build 74b1e89.

```
version: '3.6'

volumes:
    photoprism_db:
        driver: local
        name: photoprism_db
    photoprism_cache:
        driver: local
        name: photoprism_cache

services:
    photoprism:
        container_name: photoprism
        restart: unless-stopped
        volumes:
            - '/media/photos:/home/photoprism/Pictures/Originals:ro'
            - 'photoprism_cache:/home/photoprism/.cache/photoprism'
            - 'photoprism_db:/home/photoprism/.local/share/photoprism/resources/database'
        ports:
            - '2342:2342'
        image: photoprism/photoprism
```
